### ISSUE TITLE
Ability to see designated timestamp column and indexed columns

### ISSUE THREAD

**Issue by snenkov** [questdb/questdb#1009]
**Is your feature request related to a problem? Please describe.**
When I have a table now, I don't know how to verify that the table:
- has a designated timestamp
- which column is the designated timestamp
- which column(s) are symbols which are indexed

**Describe the solution you'd like**
Ideally, there would be a SQL like function like the `build()` which can tell the user the table's meta-data (there may be more to this which I am missing here)

**Describe alternatives you've considered**
None exist right now to my knowledge

**Additional context**
None.

**Comment by ideoma** [comment]
In 6.0 you can do 
```
select * from tables()
```
