### ISSUE TITLE
Crash: EXCEPTION_ILLEGAL_INSTRUCTION

### ISSUE THREAD

**Issue by Yussef77** [questdb/questdb#1012]
**Describe the bug**
When I run the following query, QuestDB crashes:

`SELECT sensorID, max(reading) from temperatures;`

Log:

2021-05-13T07:32:47.790498Z I http-server connected [ip=127.0.0.1, fd=1580]
2021-05-13T07:32:53.766413Z I i.q.c.h.p.JsonQueryProcessorState [1532] exec [q='SELECT sensorID, max(reading) from temperatures']
2021-05-13T07:32:53.766472Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-3, sql=SELECT sensorID, max(reading) from temperatures]
2021-05-13T07:32:53.767357Z I i.q.g.SqlCompiler plan [q=`select-group-by sensorID, max(reading) max from (select [sensorID, reading] from temperatures timestamp (ts))`, fd=1532]
2021-05-13T07:32:53.776687Z I i.q.c.h.p.JsonQueryProcessorState [1532] execute-new [skip: 0, stop: 1000]

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=0x0000000066a9c192, pid=25432, tid=11796

 JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.8+10) (build 11.0.8+10-LTS)
 Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.8+10-LTS, mixed mode, tiered, compressed oops, parallel gc, windows-amd64)
 Problematic frame:
 C  [libquestdb17581070583141605799.dll+0x1c192]

 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:

**Environment (please complete the following information):**
 - Windows 10
 - questdb 6.0.0

**Comment by ideoma** [comment]
Can you please add your CPU model and if you run it under a VM please?

**Comment by Yussef77** [comment]
I run it without virtual machine.

Today in the morning I wanted to test questdb, I downloaded it. I did 5 INSERT, a simple SELECT and then the SELECT that gives the error.

Then I restart the server and every time I do a simple SELECT the software works, but when asking for a MAX it crashes.

I think there are 2 problems in the matter, the first is the error itself, and the second and more serious is that the software crashes before the error.

**Comment by bluestreak01** [comment]
CPU model is important, we could have mis-detected hardware and using wrong instruction set for the max(). If you let us know OS you're using we would help you find out CPU model

**Comment by Yussef77** [comment]
Sorry, I thought I put it.

The CPU is:
AMD Phenom (tm) II X6 1090T Processor, 6 cores, 7G, Windows 10, 64 bit Build 17763 (10.0.17763.475)

**Comment by bluestreak01** [comment]
thanks!

This is quite old CPU, which we did not test with :( Could you check log output similar to:

```
2021-05-13T23:23:46.492281Z I server-main platform [bit=64]
2021-05-13T23:23:46.492292Z I server-main OS: apple-silicon [xxx,x]
```

this reports CPU instruction set as questdb detected it

**Comment by Yussef77** [comment]
This is the best CPU ever !! (... 12 years ago when I bought it)

This is the closest thing I found
2021-05-14T00:02:11.074868Z I server-main os scheduled [name=questdb-ilpwriter-2]
2021-05-14T00:02:11.075062Z I server-main os scheduled [name=questdb-worker-3]


I attach the logs
[stdout-2021-05-13T20-02-08.txt](https://github.com/questdb/questdb/files/6475669/stdout-2021-05-13T20-02-08.txt)
[hs_err_pid1796.log](https://github.com/questdb/questdb/files/6475670/hs_err_pid1796.log)

I am looking for alternatives to Influxdb to migrate.

I understand that my CPU is old, when I run in production it will run on a newer one, so I am also concerned that the software will crash instead of throwing an error in the query.

**Comment by bluestreak01** [comment]
It is a beautiful CPU! We just need to find a way to help you :)

I was actually looking for this:
```
2021-05-14T00:02:10.202236Z I server-main OS: windows-amd64 [SSE2,3]
```

it is in your logs, thanks!

**Comment by bluestreak01** [comment]
it looks like we erroneously generate AVX instruction set for SSE2/SSE4 functions. We found one site but we need to find hardware where this can be tested. We will keep you updated!

**Comment by bluestreak01** [comment]
thank you @mharmer !  This is very useful, I can confirm I'm able to reproduce this issue with "Nahalem CPU" setup, which is pretty much just below AVX. Its perfect!
