### ISSUE TITLE
Allow drop partitions when injecting in ILP

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#1030]
**Is your feature request related to a problem? Please describe.**
When table is constantly injecting ILP there is no way to drop a partition.

**Describe the solution you'd like**
A way to do quick writer operations when ILP runs, especially partition drop / detach

**Describe alternatives you've considered**
Stopping QuestDB to remove partitions

**Comment by bsmth** [comment]
Duplicate of https://github.com/questdb/questdb/issues/1489

**Comment by bsmth** [comment]
Fixed in https://github.com/questdb/questdb/pull/1504
