### ISSUE TITLE
Unexpected results when INTEGER compared with NULL TIMESTAMP in WHERE

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#1031]
**Describe the bug**
When integer column compared with function which returns NULL timestamp results are no filtering

**To Reproduce**
```
create table l as
( select x from long_sequence(100) )

select * from l
where x >  cast('12' as timestamp) 
```

this returns all 100 rows

**Expected behavior**
No rows should be returned 

**Environment (please complete the following information):**
 - Version: 6.0.1

**Comment by marregui** [comment]
This has been fixed with this merge https://github.com/questdb/questdb/pull/1179
