### ISSUE TITLE
Inserting invalid ILP results in a writer being in infinite null pointer exception loop.

### ISSUE THREAD

**Issue by danbulant** [questdb/questdb#1037]
**Describe the bug**
Writing invalid ILP (like trying to write string value in `fields` to symbol) results in the writer in infinite null pointer loop, which also corrupts the table (querying the table then results in error `1970-1.0` is not a bucket, but bucket cannot be deleted as the format is invalid).

**To Reproduce**
1. Write invalid ILP (i.e. `table symbol="test"` to table with `symbol` set to `SYMBOL` type)
2. Query the table in any way (`table`)
3. See error

**Expected behavior**
Invalid ILP should be just logged and ignored or close the connection with a message without affecting the database at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/30036876/118656774-215ef180-b7eb-11eb-824e-a2742f602778.png)

**Environment (please complete the following information):**
 - OS: Linux 5.10.34 Manjaro
 - Version: 6.0.1

**Related**
The documentation should state that `SYMBOL`s need to be in the `meta` section in ILP and not in `field` (as it looks other types can be in field type).

**Comment by bluestreak01** [comment]
fixed on master, will release with 6.0.3
