### ISSUE TITLE
When insterting via ILP and there is an issue on database side the error is not propagated back to client

### ISSUE THREAD

**Issue by postol** [questdb/questdb#1042]
**Describe the bug**
When insterting via ILP and there is an issue on database side the error is not propagated back to client.

**To Reproduce**
1. Start inserting some invalid data, for example send field with value with space
2. QuestDB will start throwing errors that the format of ILP is wrong
3. Client continuous to insert data without knowing that the writes are actually failing

**Expected behavior**
Errors should be propagated back to client so the application that is inserting data can react.

**Environment (please complete the following information):**
 - version 6.0.1
 - 
**Additional context**
The same is happening for any error I believe as we saw the same behavior when the writes were failing on out of disk space

**Comment by patrickSpaceSurfer** [comment]
ILP as a protocol, does not have any mechanism to propagate errors back to the client. If ILP is the ingestion choice then some other mecahnism needs to be used to monitor the status of questdb

**Comment by postol** [comment]
ok, makes sense ... feel tree to close if not relevant

**Comment by guywilsonjr** [comment]
where do you go to view the errors? the logs just say connected to[ip]. disconnected from [ip]

**Comment by puzpuzpuz** [comment]
Note: 6.2.1 added `line.tcp.disconnect.on.error` config option to forcefully close ILP TCP connection on any error.
