### ISSUE TITLE
IN operator doesn't work with postgres variables.

### ISSUE THREAD

**Issue by danbulant** [questdb/questdb#1052]
**Describe the bug**
Using postgres variables (`$1`) with the `IN` operator doesn't work (results in 0 results), but hardcoding the variable does.

**To Reproduce**
Try to use postgres variables (`$1` and others) in a query involving `IN`.

**Expected behavior**
It should work the same as if the value was hard coded.

**Screenshots**
![image](https://user-images.githubusercontent.com/30036876/119261780-2cde5e00-bbd9-11eb-9405-9894308460a7.png)
![image](https://user-images.githubusercontent.com/30036876/119261783-310a7b80-bbd9-11eb-9ca7-9ec848d717ae.png)
![image](https://user-images.githubusercontent.com/30036876/119261787-34056c00-bbd9-11eb-9690-e11e5d2f786a.png)

**Environment:**
 - OS: Linux 
 - Browser: Chrome (not required for the bug)
 - Version: 6.0.1

**Additional context**
Using the `BETWEEN` operator works as expected.

**Comment by ideoma** [comment]
Fixed in master, will be in 6.0.3
