### ISSUE TITLE
Support for timezone conversions

### ISSUE THREAD

**Issue by postol** [questdb/questdb#1057]
**Is your feature request related to a problem? Please describe.**
Usually you store all your data with same timezone, let's say UTC. But then when you query the data you often need to work with datetimes / timestamps in a specific timezone. Currently it is not possible to convert such data easily between timezones especially because of daylight saving times.

**Describe the solution you'd like**
It would be great to support timezone conversions as other databases do where you can specify the target timezone as a string and database will convert the give datetime/timestamp to target timezone. For example postgresql has its at timezone keyword. Details how it works here: https://www.enterprisedb.com/postgres-tutorials/postgres-time-zone-explained

**Describe alternatives you've considered**
No real alternative unfortunately :(

**Additional context**

**Comment by postol** [comment]
Can be implemented in any way ... the only important requirement is to convert given datetime/timestamp to target timezone. For example `source_datetime at timezone "Europe/Prague"` or `to_timezone(source_datetime, "Europe/Prague")`

**Comment by bluestreak01** [comment]
Implemented in master. Will be released with 6.0.3
