### ISSUE TITLE
PHP/PDO reads corrupt values

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1059]
```php
// QDB
$dbName = 'qdb';
$hostname = '127.0.0.1';
$password = 'quest';
$port = 8812;
$username = 'admin';

$pdo = new PDO("pgsql:host=$hostname;dbname=$dbName;port=$port", $username, $password);
echo '<pre>';
$stmt = $pdo->prepare("SELECT * FROM test_table");
try {
    $stmt->execute(array());
    while ($row = $stmt->fetch()) {
        print_r($row);
    }
} catch(PDOException $e) {
    echo $e;
}
```

Produces corrupt output:

```php
Array
(
    [personnel_id] => 0 // this is bugged, it should be returning a value of 1...
    [0] => 0
    [ts] => IXO�` // timestamp is bugged
    [1] => IXO�` 
    [date] => ������X // date is bugged
    [2] => ������X 
    [name] => test_string // this string works fine...
    [3] => test_string
    [value] => 0
    [4] => 0
)
```

https://stackoverflow.com/questions/67678674/questdb-select-returning-special-chars-but-postgres-does-not

**Comment by andyfleming** [comment]
Copying over some relevant info from the SO question: 

QuestDB 6.0.2
PHP 8.0.2

> If I change from `SELECT * to SELECT <single_column> like SELECT date FROM test_table`, it works fine... But if I add more columns to the query, then the character encoding bugs return.
> 
> This bug also happens with the pre-installed telemetry table, so I don't think it's related to the way I'm creating tables.
