### ISSUE TITLE
Add Javadoc

### ISSUE THREAD

**Issue by bratseth** [questdb/questdb#1060]
It would be very helpful if your interfaces defined their behavior in Javadoc.
As it is we need to guess, or try to deduce it from the code ... but there are many implementations.

For example, I'm facing an issue where myRecord.getStr(0) returns null. What does that mean? Or is it a bug? Very hard to tell.

**Comment by bluestreak01** [comment]
there is some here:

https://javadoc.questdb.io/io.questdb/module-summary.html

We are going to document `Record` Interface better.

Generally `Record.getStr(0)` depends on the type of column `0`. If the type is `String` then `null` means that value is `null`, if type is not string and something else - the behaviour is undefined. 

Happy to help if there more context of `Record.getStr(0)` issue! :)

**Comment by bratseth** [comment]
Thanks! Apart from PageFrame - which is as I would expect apart from not having a class level header explaining what it is - there is no Javadoc whatsoever in the sql package.

Regarding getStr in particular, in this case column 0 is a string but the code will not ever write null. 
I suppose it could be the same underlying issue as the core I reported, so I'll upgrade and see if that solves it - thanks again!

**Comment by bluestreak01** [comment]
we're on javadoc!

**Comment by bluestreak01** [comment]
you are very clear, thank you Jon! what I meant to say is that we are going to work on javadoc to get it in shape!

"to be on something" = "to get to work on something right away" :)

**Comment by bsmth** [comment]
Hi @bratseth, there's some additions which landed in https://github.com/questdb/questdb/pull/1067 with some additional corrections now on master. Looking forward to your feedback!

**Comment by bratseth** [comment]
Great, I think thiat completely solves this issue. Thanks!
