### ISSUE TITLE
Unsafe memory access

### ISSUE THREAD

**Issue by bratseth** [questdb/questdb#1061]
**Describe the bug**

We occasionally see our servers embedding QuestDb core with

`java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code\n\tat io.questdb.cairo.IntervalFwdDataFrameCursor.next(IntervalFwdDataFrameCursor.java:68)\n\tat io.questdb.griffin.engine.table.DataFrameRecordCursor.nextFrame(DataFrameRecordCursor.java:102)\n\tat io.questdb.griffin.engine.table.DataFrameRecordCursor.nextRow(DataFrameRecordCursor.java:80)\n\tat io.questdb.griffin.engine.table.DataFrameRecordCursor.hasNext(DataFrameRecordCursor.java:60)\n\tat 
`

**Environment (please complete the following information):**

 - OS: Linux - 4.18.0-240.15.1.el8_3.x86_64
 - Jdk: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.10+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
 - QuestDb version: 5.0.6

**Comment by bluestreak01** [comment]
hi Jon, would you mind upgrading to

```
<dependency>
    <groupId>org.questdb</groupId>
    <artifactId>questdb</artifactId>
    <version>6.0.2</version>
</dependency>
```

I think this is fixed in the new version

**Comment by bratseth** [comment]
After upgrading to 6.0.2 we get these cores instead:

```
Stack: [0x00007f784694b000,0x00007f7846a4c000],  sp=0x00007f7846a45b20,  free space=1002k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libquestdb14221187480876967236.so+0xf360]  void radix_sort_long_index_asc_in_place<index_t>(index_t*, unsigned long, index_t*)+0x90
j  io.questdb.cairo.TableWriter.o3Commit(J)Z+183
j  io.questdb.cairo.TableWriter.commit(IJ)V+47
j  io.questdb.cairo.TableWriter.commit(I)V+3
j  io.questdb.cairo.TableWriter.commit()V+5
j  com.yahoo.vespa.hosted.provision.autoscale.QuestMetricsDb.addClusterMetrics(Lcom/yahoo/config/provision/ApplicationId;Ljava/util/Map;Lio/questdb/cairo/TableWriter;)V+170
j  
```

**Comment by bratseth** [comment]
Some time after the comment above we stopped seeing any cores. Since we expire data after a few days, I guess the reason for the second variant above could be reading 5.x data on 6.x.

Anyway, I think this is fixed.

**Comment by bratseth** [comment]
I spoke too soon. Here's a new one:

```
Current thread (0x0000010014b8f000):  JavaThread "httpclient-dispatch-1" daemon [_thread_in_Java, id=1208, stack(0x00007f1d9b3a9000,0x00007f1d9b4aa000)]

Stack: [0x00007f1d9b3a9000,0x00007f1d9b4aa000],  sp=0x00007f1d9b4a6920,  free space=1014k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
v  ~StubRoutines::jint_disjoint_arraycopy
J 15126 c2 sun.misc.Unsafe.copyMemory(JJJ)V jdk.unsupported@11.0.11 (11 bytes) @ 0x00007f1df210fd9b [0x00007f1df210fd20+0x000000000000007b]
j  io.questdb.std.Vect.memcpy(JJJ)V+16
j  io.questdb.cairo.O3CopyJob.copyFixedSizeCol(JJJJI)V+17
j  io.questdb.cairo.O3CopyJob.copyO3(IJJJJJJJJJJ)V+160
j  io.questdb.cairo.O3CopyJob.copy(Ljava/util/concurrent/atomic/AtomicInteger;Ljava/util/concurrent/atomic/AtomicInteger;IIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJZJJJZLio/questdb/cairo/TableWriter;Lio/questdb/cairo/BitmapIndexWriter;)V+95
j  io.questdb.cairo.O3CopyJob.copy(Lio/questdb/tasks/O3CopyTask;JLio/questdb/mp/Sequence;)V+399
j  io.questdb.cairo.TableWriter.o3CopySafe(J)V+28
j  io.questdb.cairo.TableWriter.o3ConsumePartitionUpdates(JJJ)V+530
j  io.questdb.cairo.TableWriter.o3Commit(J)Z+1719
j  io.questdb.cairo.TableWriter.commit(IJ)V+47
j  io.questdb.cairo.TableWriter.commit(I)V+3
j  io.questdb.cairo.TableWriter.commit()V+5
j  com.yahoo.vespa.hosted.provision.autoscale.QuestMetricsDb.addNodeMetrics(Ljava/util/Collection;Lio/questdb/cairo/TableWriter;)V+240
...

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

Register to memory mapping:

RAX=0x000000007fc00000 is an unknown value
RBX={method} {0x00007f1dcf146590} 'copyMemory' '(JJJ)V' in 'sun/misc/Unsafe'
RCX=0x0000000000000001 is an unknown value
RDX=0x0 is NULL
RSP=0x00007f1d9b4a6920 is pointing into the stack for thread: 0x0000010014b8f000
RBP=0x00007f1d9b4a6920 is pointing into the stack for thread: 0x0000010014b8f000
RSI=0xfffffffffffffff8 is an unknown value
RDI=0x000001002bfffffc points into unknown readable memory: 00 00 00 00
R8 =0x0000000000000004 is an unknown value
R9 =0x0000000000000018 is an unknown value
R10=0x00007f1de9cff2c0 is at begin+0 in a stub
StubRoutines::unsafe_arraycopy [0x00007f1de9cff2c0, 0x00007f1de9cff2fb[ (59 bytes)
R11=0x0000000000000001 is an unknown value
R12=0x0 is NULL
R13=0x00007f1d9b4a69e0 is pointing into the stack for thread: 0x0000010014b8f000
R14=0x00007f1d9b4a6a98 is pointing into the stack for thread: 0x0000010014b8f000
R15=0x0000010014b8f000 is a thread


Registers:
RAX=0x000000007fc00000, RBX=0x00007f1dcf146590, RCX=0x0000000000000001, RDX=0x0000000000000000
RSP=0x00007f1d9b4a6920, RBP=0x00007f1d9b4a6920, RSI=0xfffffffffffffff8, RDI=0x000001002bfffffc
R8 =0x0000000000000004, R9 =0x0000000000000018, R10=0x00007f1de9cff2c0, R11=0x0000000000000001
R12=0x0000000000000000, R13=0x00007f1d9b4a69e0, R14=0x00007f1d9b4a6a98, R15=0x0000010014b8f000
RIP=0x00007f1de9cfe4b7, EFLAGS=0x0000000000010202, CSGSFS=0x002b000000000033, ERR=0x0000000000000006
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f1d9b4a6920)
0x00007f1d9b4a6920:   00007f1d9b4a69c0 00007f1df210fd9b
0x00007f1d9b4a6930:   0000000000000000 0000000000000000
0x00007f1d9b4a6940:   00007f1d00000001 00007f1de9cbb099
0x00007f1d9b4a6950:   0000000000000000 0000000000000000 

```

**Comment by bluestreak01** [comment]
sorry, we somehow didn't pick this up on time - is this 6.0.2 or 6.0.3 ?

**Comment by bluestreak01** [comment]
do you have `boolean` fields in the table ?

**Comment by bratseth** [comment]
This is 6.0.2.

> Do you have boolean fields in the table ?

Yes:

`create table metrics hostname string, at timestamp, cpu_util float, mem_total_util float, disk_util float, application_generation long, inService boolean, stable boolean, queries_rate float) timestamp(at) PARTITION BY DAY;`

> Is there possibility of tableWriter instance being used concurrently by more than one thread?

No.

> Would you be able to describe workflow that lead to this?

I have several threads writing to this table, and several others reading. Rarely, a write cores like this.
I'm not sure what else could be relevant, but here's the code:
https://github.com/vespa-engine/vespa/blob/master/node-repository/src/main/java/com/yahoo/vespa/hosted/provision/autoscale/QuestMetricsDb.java#L100

**Comment by bluestreak01** [comment]
Thank you for the information! Am I correct to assume that `addNodeMetrics` can be called concurrently? I'm going o investigate if `CairoEngine` can give same `TableWriter` instance to multiple threads by mistake (it isn't supposed to).

It is interesting that you got SEGSEV in O3 code even though you do actively avoid O3 from happening: 

https://github.com/vespa-engine/vespa/blob/8588e7ccf1f2b747bf3b5ac12a786dba3c330dde/node-repository/src/main/java/com/yahoo/vespa/hosted/provision/autoscale/QuestMetricsDb.java#L118

In the mean time, there is `6.0.3` on maven central.  In this release we prevent negative timestamps from going in. They can cause crashes and table corruption.

**Comment by bratseth** [comment]
> Am I correct to assume that addNodeMetrics can be called concurrently?

Yes.

> It is interesting that you got SEGSEV in O3 code even though you do actively avoid O3 from happening

There's a mistake on my side here - the check and assignment to highestTimestampAdded isn't atomic (I used to have only one writer). Do you think it could matter here?

I'll upgrade to 6.0.3 now. Thanks!

**Comment by bratseth** [comment]
Another variant:

```
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libquestdb10406546446386172603.so+0x2fff2]  merge_copy_var_column_int32_SSE41(index_t*, long, long*, char*, long*, char*, long*, char*, long)+0x92

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  io.questdb.std.Vect.oooMergeCopyStrColumn(JJJJJJJJJ)V+0
j  io.questdb.cairo.O3CopyJob.mergeCopy(IJJJJJJJJJJJJ)V+160
j  io.questdb.cairo.O3CopyJob.copy(Ljava/util/concurrent/atomic/AtomicInteger;Ljava/util/concurrent/atomic/AtomicInteger;IIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJZJJJZLio/questdb/cairo/TableWriter;Lio/questdb/cairo/BitmapIndexWriter;)V+65
j  io.questdb.cairo.O3CopyJob.copy(Lio/questdb/tasks/O3CopyTask;JLio/questdb/mp/Sequence;)V+399
j  io.questdb.cairo.TableWriter.o3CopySafe(J)V+28
j  io.questdb.cairo.TableWriter.o3ConsumePartitionUpdates(JJJ)V+530
j  io.questdb.cairo.TableWriter.o3Commit(J)Z+1804
j  io.questdb.cairo.TableWriter.commit(IJ)V+47
j  io.questdb.cairo.TableWriter.commit(I)V+3
j  io.questdb.cairo.TableWriter.commit()V+5
j  com.yahoo.vespa.hosted.provision.autoscale.QuestMetricsDb.addNodeMetrics(Ljava/util/Collection;Lio/questdb/cairo/TableWriter;)V+240

```

**Comment by bluestreak01** [comment]
Hi Jon, although I could not reproduce this I strongly feel that code writing to 0 pointers means that TableWriter instance is being handed to more than one thread at a time.

We have similar usecase where multiple threads write to the same table (ILP) and this is implemented via a multi-publisher and single-consumer queue.

I would be very happy to elaborate how to set it up if you think this is a viable option for you?

**Comment by bratseth** [comment]
The addNodeMetrics method you see in the trace above is only invoked from [this code](https://github.com/vespa-engine/vespa/blob/8588e7ccf1f2b747bf3b5ac12a786dba3c330dde/node-repository/src/main/java/com/yahoo/vespa/hosted/provision/autoscale/QuestMetricsDb.java#L102):

```
        try (TableWriter writer = engine.getWriter(newContext().getCairoSecurityContext(), nodeTable)) {
            addNodeMetrics(snapshots, writer);
        }
```

**Comment by bluestreak01** [comment]
I was suggesting concurrency issue on the basis that the fault is in out of order code despite checks to prevent this. Does this make sense?

**Comment by bratseth** [comment]
Depends on what you mean by concurrency issue. 

_Could there be concurrent writes with the same TableWriter instance?_

No.

_Could there be concurrent writes towards the same table, from different TableWriter instances, having timestamps not strictly ordered?_

Yes. (I'll change that on our side, that will be fine for us, but as far as I understand QuestDb is supposed to handle it.)

**Comment by bluestreak01** [comment]
I suspect engine.getWriter() can give the same instance of table writer to more than one thread. It is of course a bug but so far I’m failing to reproduce it. I suggested perhaps using queues as a workaround to remove concurrent pressure from CairoEngine. This coincidentally will also solve max timestamp update issue

**Comment by bratseth** [comment]
Ok, I see. 

Yes, I'll serialize these calls. I should take care to get the writer inside the serialized block, that's good to know.

**Comment by bratseth** [comment]
I'm now serializing all writes (except occasional removal of old data - I'll try that as well), and see cores with:

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  io.questdb.std.Vect.oooMergeCopyStrColumn(JJJJJJJJJ)V+0
j  io.questdb.cairo.O3CopyJob.mergeCopy(IJJJJJJJJJJJJ)V+160
j  io.questdb.cairo.O3CopyJob.copy(Ljava/util/concurrent/atomic/AtomicInteger;Ljava/util/concurrent/atomic/AtomicInteger;IIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJZJJJZLio/questdb/cairo/TableWriter;Lio/questdb/cairo/BitmapIndexWriter;)V+65
j  io.questdb.cairo.O3CopyJob.copy(Lio/questdb/tasks/O3CopyTask;JLio/questdb/mp/Sequence;)V+399
j  io.questdb.cairo.TableWriter.o3CopySafe(J)V+28
j  io.questdb.cairo.TableWriter.o3ConsumePartitionUpdates(JJJ)V+530
j  io.questdb.cairo.TableWriter.o3Commit(J)Z+1804
j  io.questdb.cairo.TableWriter.commit(IJ)V+47
j  io.questdb.cairo.TableWriter.commit(I)V+3
j  io.questdb.cairo.TableWriter.commit()V+5
j  com.yahoo.vespa.hosted.provision.autoscale.QuestMetricsDb.addNodeMetricsBody(Ljava/util/Collection;)V+258

```
