### ISSUE TITLE
Unable to start QuestDB service on Windows 10 (no JVM version)

### ISSUE THREAD

**Issue by RiccardoGiro** [questdb/questdb#1073]
I have managed to successfully install QuestDB 6.0.2 (no JVM version) from the binaries on my local machine, which is running Windows 10. However, I am unable to start the service (as it can be inferred from the screenshot below), even though I am running the command line as an administrator:
![Immagine 2021-05-31 123401](https://user-images.githubusercontent.com/60734967/120180848-929b9d00-c20c-11eb-9746-34e56b0b4919.png)
The contents of the destination folder `"C:\QuestDB\"` are the following:
![Immagine 2021-05-31 123846](https://user-images.githubusercontent.com/60734967/120181448-5e74ac00-c20d-11eb-89f7-b512b2d373ae.png)

**Comment by duggar** [comment]
I have the same issue

**Comment by ideoma** [comment]
Do you have JAVA_HOME environment variable set on the system level?

**Comment by bluestreak01** [comment]
Could you check registry settings for questdb service:
![image](https://user-images.githubusercontent.com/7276403/120629585-dfc27d80-c45d-11eb-995b-12ff8d346d56.png)

If java path contains spaces, could you enclosed `-j` option in double quotes, e.g.

```
c:\questdb\questdb.exe service -d qdbroot -j "C:\Program Files\Java\jdk-11.0.10\bin\java.exe"
```

**Comment by RiccardoGiro** [comment]
> Do you have JAVA_HOME environment variable set on the system level?

Yes
<img width="441" alt="Immagine 2021-06-03 133831" src="https://user-images.githubusercontent.com/60734967/120639473-a98ef900-c471-11eb-82fc-9e96f908783e.png">

**Comment by RiccardoGiro** [comment]
> Could you check registry settings for questdb service:
> ![image](https://user-images.githubusercontent.com/7276403/120629585-dfc27d80-c45d-11eb-995b-12ff8d346d56.png)
> 
> If java path contains spaces, could you enclosed `-j` option in double quotes, e.g.
> 
> ```
> c:\questdb\questdb.exe service -d qdbroot -j "C:\Program Files\Java\jdk-11.0.10\bin\java.exe"
> ```

It turns out to be like so:
<img width="1068" alt="Immagine 2021-06-03 134257" src="https://user-images.githubusercontent.com/60734967/120639589-ce836c00-c471-11eb-8b28-641de566e154.png">

**Comment by bluestreak01** [comment]
there is strange double quote on the path

**Comment by RiccardoGiro** [comment]
> there is strange double quote on the path

I have noticed it. It is strange that the ImagePath entry of QuestDB service is automatically written using this erroneous syntax since I have never touched the system registry. Anyways, after having performed the modification you have suggested, everything now works fine. Thank you very much!

<img width="674" alt="Immagine 2021-06-03 135718" src="https://user-images.githubusercontent.com/60734967/120641244-aa288f00-c473-11eb-8a55-1aa24280f530.png">

**Comment by bluestreak01** [comment]
glad all is worked out! thank you for your patience!
