### ISSUE TITLE
Add all contribs 🎉 

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb#1083]
Adding latest contributors 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @rrjanbiah for bug reports

Thanks for your contribution!

**Comment by bsmth** [comment]
@all-contributors bot, please add @rrjanbiah for bug reports

Thanks from the QuestDB team!

**Comment by bsmth** [comment]
@all-contributors bot, please add @sarunas-stasaitis for bug reports

Thanks from the QuestDB team!

**Comment by bsmth** [comment]
@all-contributors bot, please add @RiccardoGiro for bug reports

Thanks for your contribution!

**Comment by bsmth** [comment]
@all-contributors bot, please add @duggar for bug reports

Thanks from the QuestDB team!

**Comment by bsmth** [comment]
@all-contributors bot, please add @postol for bug reports

Thanks from the QuestDB team!

**Comment by bsmth** [comment]
@all-contributors bot, please add @nikochiko for feature request and feedback

Thanks for your contribution!

**Comment by bsmth** [comment]
@all-contributors bot, please add @nikochiko for feature request and feedback

Thanks for your contribution!

**Comment by bsmth** [comment]
@all-contributors bot, please add @petrjahoda for bug reports

Thanks from the QuestDB team!

**Comment by bsmth** [comment]
@all-contributors bot, please add @t00 for bug report

Thanks from the QuestDB team!

**Comment by bsmth** [comment]
@all-contributors bot, please add @snenkov for user testing, feature requests and bug reports

Thanks for your continued feedback and ideas!

**Comment by bsmth** [comment]
Thanks everyone for your awesome feedback 🙌🏻

**Comment by snenkov** [comment]
Wow that's cool! Thank you 🙏

**Comment by rrjanbiah** [comment]
@bsmth Honestly, it is too much for my single ticket #1077 :-) Thank you!

**Comment by bsmth** [comment]
> @bsmth Honestly, it is too much for my single ticket #1077 :-) Thank you!

Not at all, all contributions are helpful for getting feedback from the community!
