### ISSUE TITLE
curl `overwrite=true` is not respected, corrupting data if types are changed in the second curl import

### ISSUE THREAD

**Issue by fuzzthink** [questdb/questdb#1159]
@eugenels  Submitting finding of bug per chat in Slack.

**Describe the bug**
When a csv table is created via curl, setting the field types by setting `schema=...`, and later another curl command modifies the types via `schema=...`, the data imported is corrupted.

**To Reproduce**
1. Create NYSE.csv:
```csv
ticker,ts,open,high,low,close,vol
A,20190102,66.5,66.57,65.3,65.69,2113300
```
2. Import, setting prices fields as DOUBLE via:
```bash
curl -F schema='[{"name":"ts", "type": "TIMESTAMP", "pattern": "yyyyMMdd"}, {"name":"ticker", "type": "SYMBOL"}, {"name":"open", "type": "DOUBLE"}, {"name":"high", "type": "DOUBLE"}, {"name":"low", "type": "DOUBLE"}, {"name":"close", "type": "DOUBLE"},{"name":"vol", "type": "INT"}]' -F data=@NYSE.csv 'http://localhost:9000/imp?overwrite=true&timestamp=ts&partitionBy=MONTH'
```
3. Verify data is imported correctly by running the SQL:
'NYSE.csv';
4. Re-import price fields as FLOAT:
```bash
curl -F schema='[{"name":"ts", "type": "TIMESTAMP", "pattern": "yyyyMMdd"}, {"name":"ticker", "type": "SYMBOL"}, {"name":"open", "type": "FLOAT"}, {"name":"high", "type": "FLOAT"}, {"name":"low", "type": "FLOAT"}, {"name":"close", "type": "FLOAT"},{"name":"vol", "type": "INT"}]' -F data=@NYSE.csv 'http://localhost:9000/imp?overwrite=true&timestamp=ts&partitionBy=MONTH'
```
5. Verify data is NOT imported correctly by running the SQL:
'NYSE.csv';
6. Drop the table, and reverse the curl orders, data is imported correctly as FLOAT, but corrupted when imported as DOUBLE the 2nd time.

**Expected behavior**
data should not be corrupted, `overwrite=true` is expected to truly overwrite the table

**Environment (please complete the following information):**
 - macOS 10.15.4
 - Browser: Chrome
 - QuestDB brew installed, 6.0.3, JDK 11.0.8, Commit Hash 2ea876e279b51a202f2853649785f111d9b0cdde 
 - curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2

**Comment by fuzzthink** [comment]
For knowledge sake, can someone please summaries what the bug is and how the fix fixes it?

**Comment by bluestreak01** [comment]
To the best of my knowledge on second attempt data was imported correctly. The issue was in caching the execution plan for `'NYSE.csv';` SQL. The import code did overwrite the table and changed the metadata, hover on repeated run of the verification SQL the plan had old metadata snapshot, which forced SQL to read `FLOAT` as `DOUBLE`, e.g. 8 bytes vs 4
