### ISSUE TITLE
Can't access web console via localhost:9000 

### ISSUE THREAD

**Issue by idclevxx** [questdb/questdb#1163]
**Describe the bug**
Web console fails to launch after errorless homebrew installation and run.

**To Reproduce**
After having installed questDB via Homebrew on MacOS terminal and running it with either `questdb start` or `brew services start questdb` the web console is unreachable through any browser.

Edge error: "This page isn't working right now. localhost sent an invalid response. ERR_INVALID_HTTP_RESPONSE"
Firefox: blank page
Safari error: "Cancelled load from 'http://localhost:9000' because it is using HTTP/0.9. (:0)"

Please observe these are errors that occur when address is active; if the address wasn't active the error would be "can't connect/can't reach" etc.

**Expected behavior**
Expected to reach web console.

**Environment (please complete the following information):**
 - OS: MacOS 11.4
 - Browser: Edge, Firefox, Safari; private and non-private modes
 - Version: 6.0.3

**Additional context**
Suspect this could be a system configuration error but a solution posted here will help future users. Have not found any solutions to this error in general.

**Comment by bsmth** [comment]
Hi @idclevxx, thanks for raising the issue!

I cannot reproduce it on my system, however:

* installation type: homebrew (6.0.3)
* OS: MacOS 11.4
* URLs: http://localhost:9000/ / http://127.0.0.1:9000/
* Browsers: Firefox ✅  / Safari ✅ 

Are there any other services running on port 9000 causing a conflict somehow?

try `lsof -i tcp:9000` and check the PID:

```bash
lsof -i tcp:9000
COMMAND   PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
java    49448 user   28u  IPv4 0x6b01f7a654ade5ff      0t0  TCP *:cslistener (LISTEN)
<ctl+c>
questdb stop
...QuestDB is down
Stopped 49448
```

**Comment by idclevxx** [comment]
Thank you @bsmth, you are indeed correct, had an instance of python running on 9000 for some reason (ports aren't my strong suit). Sorry for taking up your time—but at least it helps future users who run into the same issue. Cheers!

/Clev
