### ISSUE TITLE
return value for csv /imp incorrectly describes designated TS

### ISSUE THREAD

**Issue by ospqsp** [questdb/questdb#1166]
**Describe the bug**
return value for csv /imp incorrectly describes designated TS.
says "NONE" rather than actually the designated index

**To Reproduce**
https://questdb.slack.com/archives/C1NFJEER0/p1624941440139000

**Expected behavior**
in return response Timestamp != NONE

**Screenshots**
see thread

**Environment (please complete the following information):**
 - OS: 11.2.3 / M1 mac
 - Browser: safari
 - Version: 14.0.3

**Comment by ideoma** [comment]
closed in #1204
