### ISSUE TITLE
QuestDB does not create column types on the fly via ILP on Windows when table created with partition

### ISSUE THREAD

**Issue by spxie85** [questdb/questdb#1178]
I'm running QuestDB on Windows using the version [here ](https://github.com/questdb/questdb/releases/download/6.0.3/questdb-6.0.3-rt-windows-amd64.tar.gz) and it's not able to create new columns on the fly via ILP when a table has been pre-created. What's worse is that QuestDB generates CairoException continuously thereafter and the QuestDB backend stops responding to anything else. After some trial and error, I managed to find a workaround by creating the table with "partition by NONE". 

Steps to replicate the issue:
1) Create table before hand
```sql
CREATE TABLE IF NOT EXISTS 
table_a(ReceiveTime timestamp, SequenceNumber symbol index, MessageType symbol index, Length int)
timestamp(ReceiveTime) 
partition by DAY;
```

2) Insert dummy data via Python
```python
import socket

class QuestDBClient():
    
    def __init__(self, host='192.168.137.1', port=9009):

        self.host = host
        self.port = port
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)     

    def sendall(self, lines):
        self.sock.connect((self.host, self.port))                  
        self.sock.sendall(''.join(lines).encode())       
        self.sock.close()  

if __name__ == '__main__':
    sample_string = ['table_a,MessageType=B,SequenceNumber=1 Length=92i,test=1.5 1465839830100400000\n']

    client = QuestDBClient()
    client.sendall(sample_string)
```

3) Sample errors generated
```log
2021-07-02T05:55:57.968605Z E i.q.c.l.t.LineTcpMeasurementScheduler could not write line protocol measurement [tableName=table_a, ex=Cannot remove directory: D:\Work\Code\questdb-6.0.3-rt-windows-amd64\bin\qdbroot\db\table_a\2016-06-13\MessageType.k, errno=5]
2021-07-02T05:55:57.968859Z E server-main unhandled error [job=io.questdb.cutlass.line.tcp.LineTcpMeasurementScheduler$WriterJob@73a2e526, ex=
io.questdb.cairo.CairoException: [5] Cannot remove directory: D:\Work\Code\questdb-6.0.3-rt-windows-amd64\bin\qdbroot\db\table_a\2016-06-13\MessageType.k
]
2021-07-02T05:55:57.981765Z E i.q.c.l.t.LineTcpMeasurementScheduler could not write line protocol measurement [tableName=table_a, ex=Cannot remove directory: D:\Work\Code\questdb-6.0.3-rt-windows-amd64\bin\qdbroot\db\table_a\2016-06-13\MessageType.k, errno=5]
```
Wait 30seconds and these errors keep repeating, and QuestDB basically becomes unresponsive
```log
2021-07-02T05:56:28.903594Z I i.q.c.l.t.LineTcpMeasurementScheduler releasing writer, its been idle since 2021-07-02T05:55:57.923000Z[tableName=table_a]
2021-07-02T05:56:28.904106Z E server-main unhandled error [job=io.questdb.cutlass.line.tcp.LineTcpMeasurementScheduler$WriterJob@73a2e526, ex=
io.questdb.cairo.CairoException: [5] Cannot remove directory: D:\Work\Code\questdb-6.0.3-rt-windows-amd64\bin\qdbroot\db\table_a\2016-06-13\MessageType.k
]
```
4) You'll have to restart QuestDB to stop the errors 

5) Drop table_a, recreate it with statement (1) using "partition by NONE" then run the same data insert in (3) and the same errors do not appear

**Comment by bluestreak01** [comment]
CairoException usually contains OS error code that caused this exception to be thrown. In your case error is 5 = access denied. Could you check if you don’t have any other windows applications that could have “db” directory or it’s subdirectories as current due? Perhaps another instance of questdb is running?

**Comment by spxie85** [comment]
that is right, there is no other instance of questdb running. I managed to replicate this on 2 different physical desktops

**Comment by ideoma** [comment]
I can reproduce on Windows, thanks

On positive side the scenario works on Linux fine. We will fix it for Windows too

**Comment by bluestreak01** [comment]
Fixed
