### ISSUE TITLE
keyword 'ORDBY' will affect the field value is NULL in sql query result

### ISSUE THREAD

**Issue by Mouriya-Emma** [questdb/questdb#1185]
**Describe the bug**
I have several tables with the same structure, when use `UNION` combine their and sorting timestamp, the query result always be NULL in some field.

**To Reproduce**
the create table sql like this:

```sql
CREATE TABLE table_name
( ts timestamp
, tag symbol capacity 4096 nocache index capacity 1024
, value string
, type int)
timestamp(ts)
PARTITION BY DAY;
```

the query sql like this:

```sql
WITH all_by_tag AS( select * from table_name1 where tag  = '1' UNION table_name2 where tag = '1' UNION table_name3 where tag = '1')
select ts as t, tag, value, type from all_by_tag ORDER BY t;
```

**Expected behavior**
when remove ordby, everything is normal, those fields that are null will no longer be null.

**Screenshots**
the result I got looks like this.
![1.png](https://i.loli.net/2021/07/07/wlJXM1GkrnhEBbF.png)

remove ordby in query
![2.png](https://i.loli.net/2021/07/07/MRFEnLgUVecK7jN.png)

**Environment (please complete the following information):**
 - OS: Windows 10 docker desktop with WSL2
 - Browser: chrome
 - Version: 6.0.3

**Comment by marregui** [comment]
Hi @Mouriya-Emma,

Thank you for the report!

I have tried to reproduce it using a fresh clone from master. In particular these are the statements I use to create/insert/query:

```
CREATE TABLE table_name1( 
    ts timestamp, 
    tag symbol capacity 4096 nocache index capacity 1024, 
    value string, 
    type int) timestamp(ts) PARTITION BY DAY ;

CREATE TABLE table_name2( 
    ts timestamp, 
    tag symbol capacity 4096 nocache index capacity 1024, 
    value string, 
    type int) timestamp(ts) PARTITION BY DAY ;


CREATE TABLE table_name3( 
    ts timestamp, 
    tag symbol capacity 4096 nocache index capacity 1024, 
    value string, 
    type int) timestamp(ts) PARTITION BY DAY ;


insert into table_name1 values(0, '1', null, 0);
insert into table_name1 values(1, '1', 'BANANA', 0);
insert into table_name1 values(2, null, 'COCONUT', 0);
insert into table_name1 values(3, null, 'SUGAR', 0);
insert into table_name1 values(4, '2', 'SPOON', 1);
insert into table_name1 values(4, '2', 'SPOON-AGAIN', 1);

insert into table_name2 values(0, '1', null, 0);
insert into table_name2 values(1, '1', 'BANANA', 0);
insert into table_name2 values(2, null, 'COCONUT', 0);
insert into table_name2 values(3, null, 'SUGAR', 0);
insert into table_name2 values(4, '2', 'SPOON', 11);
insert into table_name2 values(4, '2', 'SPOON-AGAIN', 11);

insert into table_name3 values(0, '1', null, 0);
insert into table_name3 values(1, '1', 'BANANA', 0);
insert into table_name3 values(2, null, 'COCONUT', 0);
insert into table_name3 values(3, null, 'SUGAR', 0);
insert into table_name3 values(4, '2', 'SPOON', 111);
insert into table_name3 values(4, '2', 'SPOON-AGAIN', 111);
insert into table_name3 values(5, '2', 'THREEK' , 111);
insert into table_name3 values(6, '2', 'FORK' , 111);

WITH all_by_tag AS( select * from table_name1 where tag  = '1' UNION table_name2 where tag = '1' UNION table_name3 where tag = '1')
select ts as t, tag, value, type from all_by_tag;

WITH all_by_tag AS( select * from table_name1 where tag  = '1' UNION table_name2 where tag = '1' UNION table_name3 where tag = '1')
select ts as t, tag, value, type from all_by_tag ORDER BY t;

WITH all_by_tag AS( select * from table_name1 where tag  = '2' UNION table_name2 where tag = '2' UNION table_name3 where tag = '2')
select ts as t, tag, value, type from all_by_tag;

WITH all_by_tag AS( select * from table_name1 where tag  = '2' UNION table_name2 where tag = '2' UNION table_name3 where tag = '2')
select ts as t, tag, value, type from all_by_tag ORDER BY t;
```

The first two queries return the same.
The last two queries return the same.

Might you have `NULLs` in the tables for those values?. Would you be able to paste here a few insert statements for the 3x tables to back the report?

Thank you in advance.

Kind regards

**Comment by Mouriya-Emma** [comment]
@marregui 

At the insertion stage never have NULL value in table.

Like the picture from screenshots, the tag with `type` = `70` in the previous screenshot is always `null`, but in the 
next screenshot, the same row data has correct value `tag` = `88888888`, their `timestamps` are identical too, just removed the `ORDER BY t` from the statement.

**Comment by marregui** [comment]
Hi @Mouriya-Emma ,

Oh, could you please paste the result of these three separate queries:

```sql
table_name1 where tag  = '1'; 
table_name2 where tag = '1'; 
table_name3 where tag = '1';
```

That way I can have a closer look. A symbol resolving to null may mean a null is inserted somehow.
It would be amazing if I could have the java code, narrowed down version, to have a look at how the connection is open and general use of the driver, so that I can reproduce as close as possible to this scenario.

Thank you in advance for this :)

**Comment by Mouriya-Emma** [comment]
@marregui 

I'm sorry that I deleted my test table when I tried to get around the problem. Just now I try to reproduce this BUG but I realized that I can't, they worked as expected. what a strange. 

![1.png](https://i.loli.net/2021/07/17/MoDCjSg9i25t7R1.png)

**Comment by marregui** [comment]
Hey @Mouriya-Emma 

Happy days!!
