### ISSUE TITLE
Timestamp always shows as 1970-X-X when importing via Line Protocol in QuestDB UI

### ISSUE THREAD

**Issue by voycey** [questdb/questdb#1202]
**Describe the bug**
When importing a microsecond timestamp, in the QuestDB UI this always shows as 1970-x-x

**To Reproduce**
Import the following 
`daily,meter_id=NEM1206106 export_interval_total=3.0,import_interval_total=0.0,week_of_year=10,day_of_month=2,month=3,year=2004,hour=17,minute=30,reading_date_time="2004-03-02T17:30:00.000000",date_str="20040302" 1078248600000000`

**Expected behavior**
Epoch converters show 1078248600000000 correctly as:

```
Assuming that this timestamp is in microseconds (1/1,000,000 second):
GMT: Tuesday, 2 March 2004 17:30:00
Your time zone: Wednesday, 3 March 2004 03:30:00 GMT+10:00
Relative: 17 years ago
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1065098/125900008-eb501976-eaeb-46b2-a1c1-eea2e6ff7230.png)

**Environment (please complete the following information):**
- Docker in WSL on Windows
- Python with very basic import script

**Comment by voycey** [comment]
I have also checked this in a different client via a postgres connection and it has inserted as that. Where am I going wrong with this?

**Comment by marregui** [comment]
Hi @voycey 

By default questdb is expecting precision in nanos, so the timestamp in the line is 3x zeroes short.
The precision can be changed through configuration.

```
The TCP receiver configuration can be completely customized using configuration keys. You can use this to configure the tread pool, buffer and queue sizes, receiver IP address and port, load balancing etc.
```
https://questdb.io/docs/reference/configuration/#influxdb-line-protocol-tcp

The property is `line.tcp.timestamp`, set it to `u`.

**Comment by voycey** [comment]
Thanks, documentation still shows "Microseconds" as the requirements, you might want to update that (I used the getting started pages)
