### ISSUE TITLE
Display web console query status and history as drop down instead of pop-ups

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#1210]
**Is your feature request related to a problem? Please describe.**
At the moment console displays query status (execution timing, count or error) in a pop-ups which are source of annoyance since they overlay query editor. 

**Describe the solution you'd like**
It would be good to display them as status panel at the bottom of query editor. The status panel should be expandable (as drop down or drop up and show recent history)

**Additional context**
![Screenshot 2021-07-20 at 18 09 24](https://user-images.githubusercontent.com/2159629/126367914-42cfe85e-5526-41a4-8222-772054599fd5.png)

Alternatively status can be displayed at top / bottom of the data grid

**Comment by insmac** [comment]
Addressed in https://github.com/questdb/questdb/pull/1334.
