### ISSUE TITLE
strange problem abount timestamp

### ISSUE THREAD

**Issue by nileblack** [questdb/questdb#1212]
I use LineTCPProtoSender  to send metric to questdb.
```
        try (LineTCPProtoSender sender = new LineTCPProtoSender(Net.parseIPv4("127.0.0.1"), 9009, 4096)) {
            for (int i = 0; i < 1; i++) {
                final long ts = System.currentTimeMillis() + i * 1000L;
                sender.metric("biz_metrics3")
                        ...                        
                        .field("time_bucket", ts)
                        .field("value", 106D)
                        .$(ts);
            }
            sender.flush();
        } catch (Throwable t) {
            t.printStackTrace();
        }
```
time_bucket is timestamp

![image](https://user-images.githubusercontent.com/154701/126469738-3b066df3-3545-4094-a10e-3370a8a902d7.png)

result , half of records are write, other is 1970... what's the problem? 
![image](https://user-images.githubusercontent.com/154701/126469591-c25523f2-7980-41d3-96f6-c9dbf5c4119c.png)

**Comment by ideoma** [comment]
If time_bucket is designated timestamp, please do not include it as a field, e.g. remove line `.field("time_bucket", ts)`.
Designated timestamp is in nanoseconds for Influx compatibility, so multiply by `1_000_000L`

**Comment by ideoma** [comment]
I opened a bug to fix the underlying issue
