### ISSUE TITLE
Add index creation to Influx Line Protocol

### ISSUE THREAD

**Issue by mugendi** [questdb/questdb#1235]
**Is your feature request related to a problem? Please describe.**
So I'm working on a product that should allow schema-less ingestion out of the box. So my default ingestion method is via the influx line protocol.

But my challenge is that I also need to add indexes to some of the tags (symbols) after table creation.  The problem is that the Influx Line protocol holds a lock to the table making the prospect of running an ALTER command impossible.

**Describe the solution you'd like**
I propose a feature that allows one to denote tags to be indexed via the line protocol. Having read the documentation, I think we can borrow a leaf from the way integers are denoted using an "i" at [the end of the tag](https://questdb.io/docs/guides/influxdb-line-protocol/#how-questdb-parses-influxdb-line-protocol-messages). 

The solution I propose involves adding an escape sequence/character to denote tag indexes as shown below:

`_sensor_data,_sensor="berlin\ 2\#" _value=12.4,string="sensor data, rev 1"`

In this case **\#** indicates that **_sensor** is to be indexed. That still gives users the liberty to still use "#" in other strings and "\\#" for "\#| string sequences.

**Describe alternatives you've considered**
I have tried the following solutions and here is why they didn't work well form me:

- Pre-creating a table. This works but requires one to know the structure of the data beforehand. In my case, I need totally schemaless data ingestion so this won't cut it.
- Using the alter command. This is the closest I have come to a solution but there is one main problem. The table lock that influx line protocol establishes on the new table means that you cannot run an alter command immediately after writing data. If data ingestion is a continuous process, which is the case in my situation, then the table never becomes available for an ALTER SQL query to be run!

**Additional context**
None

**Comment by ideoma** [comment]
We are working on strategic fix which will allow to do ALTER TABLE while table is used by ILP.

Meanwhile the area which adds column in ILP is here

https://github.com/questdb/questdb/blob/c6319785786a3ab7bc4f500aecab421d24197545/core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java#L610

it can potentially take server configuration setting to add index on symbols automatically as a strategic fix. The change looks to be straightforward, test examples are in `LineTcpServerTest`.

**Comment by mugendi** [comment]
Altering table while in use by ILP would be an interesting fix not just for this issue.

Yes, it looks like an easy fix. I could tell so even without looking at the code since it's the same way the interger "I" flag is passed via ILP. 

However, Java is not my strong point so I will wait for the Java gurus to do the PRs.
