### ISSUE TITLE
Support timestamp fieldsets in ILP

### ISSUE THREAD

**Issue by devenjarvis** [questdb/questdb#1257]
**Is your feature request related to a problem? Please describe.**
I have a time series forecasting usecase where I need to store two timestamp columns in a table (one is designated). Unfortunately ILP does not seem to support timestamp columns (I tried several formats and just get conversion errors), so I am forced to resort to the Postgres client for inserting new data which works fine, but based on everything I've seen is not as fast for QuestDB.

**Describe the solution you'd like**
It would be great if the ILP could be extended to include timestamp data types for fieldsets.

**Describe alternatives you've considered**
For now I am using a Postgres client for all writes and it works acceptably, but has noticeable lag when I'm trying to write anything of decent volume.

**Comment by bsmth** [comment]
Hi @devenjarvis thanks a lot for opening the issue. Quick update; we're currently looking at ways to support this, and we should have more details soon 👍🏻

**Comment by devenjarvis** [comment]
I appreciate the update, thank you!

**Comment by puzpuzpuz** [comment]
Hello,

I'm going to give a try with this issue.

It seems to me that the most obvious way to extend ILP with timestamp field value types is to support `t` suffix similar to how it's done with `i` suffix in `long`s.

With this approach the row
```
tab atimestamp=1465839830100399000t\n
```
will be interpreted as a table with `atimestamp` column of timestamp type.

ATM the column is interpreted to be of symbol type, but it seems to be non-documented behavior. So, such ILP extension shouldn't be considered as a breaking change. WDYT?

**Comment by ideoma** [comment]
Hey @devenjarvis,

You can use `i` suffix to insert epoch microsecond long values into timestamp fields at the moment. This should work as of v.6.0.1 at least

```
tab atimestamp=1465839830100399000i\n
```

Did you mean you want the support to insert ISO timestamp values, like `2020-01-01T02:03:04.123456` into timestamp type column pre-created from SQL?

**Comment by devenjarvis** [comment]
@puzpuzpuz thanks for jumping on this!

@ideoma let me try that, I don't think my usecases are picky about the format of the data, I just could not find a way to insert data into a timestamp column other than the designated one (I have 2 timestamp columns in my tables).

**Comment by devenjarvis** [comment]
So I tried this and adding the `i` suffix on an epoch microsecond allows me to insert values to a non-designated timestamp column successfully! Thank you so much for pointing me towards this @ideoma! ILP is notably faster than the Postgres wire protocol so I'm glad to be able to start using it.

@puzpuzpuz I don't know if there is other value in the 't' suffix you started, but I believe my original issue is solved with the 'i' suffix and I am happy to close this issue

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz I don't know if there is other value in the 't' suffix you started, but I believe my original issue is solved with the 'i' suffix and I am happy to close this issue

The direct value is in dynamic table creation. Indirectly, it's probably also more obvious to have a dedicated suffix for timestamps.

Sure, please feel free to close the issue since my PR isn't supposed to close it anyway.

**Comment by devenjarvis** [comment]
That makes sense! Thanks again for the help from you both!
