### ISSUE TITLE
REST API response status_code

### ISSUE THREAD

**Issue by Ziink** [questdb/questdb#1259]
Even on error `/imp` returns a status_code of 200. The response.text did contain the message `not a timestamp ''`. The returned status code should be an error code and the returned message should be more descriptive. At a minimum it should be something like `ERROR: not a timestamp` but it would be nice to have more detail such which column.

Haven't checked the other endpoints `/exec` and `/exp`

**Comment by bluestreak01** [comment]
We had been debating this subject internally and conclusion is that status code 200 is the correct behaviour. Additionally if you were to put questdb behind reverse proxy, such as nginx, response that are not 200 will have their context hidden by nginx and response code will be 500.


I agree though text error message should contain word “error” in it and should be more detailed. We will fix that

**Comment by ideoma** [comment]
I think nginx reverse proxy not delivering error codes is a configuration issue

https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_intercept_errors
