### ISSUE TITLE
Adding a LAG equivalent function

### ISSUE THREAD

**Issue by toomuchio** [questdb/questdb#1268]
Hi,

This has already been discussed in the community Slack but a function equivalent to the Postgres LAG function.
Other DB's support this function as well Influx have it as DIFFERENCE, Graphite as derivative().

Why is this important? Just to quote the Graphite documentation as it's a clear cut example:
> Each time you run ifconfig, the RX and TXPackets are higher (assuming there is network traffic.) By applying the derivative function, you can get an idea of the packets per minute sent or received, even though you’re only recording the total.

**Comment by kzk2000** [comment]
+1

this would allow computation of delta time between rows and then allow for computing things like the time-weighted averages of price (TWAP), bid-ask spread, or mid-quotes on server side.

**Comment by marregui** [comment]
I have updated discussion https://github.com/questdb/questdb/discussions/1162 with a preliminary spec for window functions. 

Query _numero 1_ is an approximation to what needs to be achieved, _numero 2_:

```
create table tank(id integer, count bigint, ts timestamp);

insert into tank values(0, 10, '2021-08-23T11:14:40.000000Z');
insert into tank values(0, 3, '2021-08-23T11:14:41.000000Z');
insert into tank values(0, 2, '2021-08-23T11:14:42.000000Z');
insert into tank values(0, 6, '2021-08-23T11:14:43.000000Z');
insert into tank values(0, 12, '2021-08-23T11:14:44.000000Z');
insert into tank values(1, 20, '2021-08-23T11:14:50.000000Z');
insert into tank values(1, 19, '2021-08-23T11:14:51.000000Z');
insert into tank values(1, 18, '2021-08-23T11:14:51.300000Z');
insert into tank values(1, 20, '2021-08-23T11:14:52.000000Z');

-- numero 1
SELECT a.id, b.count - a.count AS count, a.ts as time
FROM tank a
INNER JOIN (SELECT b.id, b.count, b.ts - interval '1 seconds' AS hackstamp FROM tank b) b
ON a.ts = b.hackstamp AND a.id = b.id
WHERE a.ts BETWEEN '2021-08-23T11:14:42.000000Z' AND '2021-08-23T11:14:51.300000Z'


-- numero 2
SELECT id, count - LAG(count) OVER (ORDER BY ts) FROM tank
WHERE ts BETWEEN '2021-08-23T11:14:42.000000Z' AND '2021-08-23T11:14:51.300000Z'
```

**Comment by kzk2000** [comment]
One extra note here for clarification: this operator should ideally behave like

pandas[“column_name”].shift(i)

where 
i < 0 gets you data from future rows
i > 0 gets you data from past rows

(assuming your table is sorted by time)

**Comment by marregui** [comment]
Hi @toomuchio 

why would these queries not be suitable?

1. samples tank in buckets of 1 minute, calculates de difference between the last and first values in the group:
```sql
SELECT ts, last(count) - first(count) FROM tank timestamp(ts) sample by 1m
```
2. samples tank in buckets of 1 minute, partitions each bucket by id, calculates de difference between the last and first values in each partition:
```sql
SELECT ts, id, last(count) - first(count) FROM tank timestamp(ts) sample by 1m
```

Best

**Comment by ErichHeinemann** [comment]
I am searching for this function too. I need to get the delta of RX/TX packets based on Unsigned Integer 64 Bit ( SNMP Counter64 )Values - as deltaA. I have to get the delta between the 2 timestamps too as deltaB! After getting the deltaA and deltaB I would like to devide the deltaA by deltaB and get Packets per Second or with other values I would get Bytes per Second etc. I have done it long time ago with Oracle 9i ... with Lag/Lead. To get it in QuestDB would be cool.

**Comment by marregui** [comment]
Hi @ErichHeinemann and @toomuchio ,

In QuestDB, to get the delta of a column between two timestamps at intervals of 1 sec, you need a table that has a designated timestamp: 
```sql
create table tank(id int, value long, ts timestamp) timestamp(ts)
```

and then you can query in this way:
```sql
select ts, last(value) - first(value) from tank sample by 1s
```

this query will take your data, will create tumbling windows of 1 second, and for each window you are computing the delta as `last(value) - first(value)`. When the window only has one value, the delta is 0.


Example:

Lets assume these data in the table:

```
ts                             id       value
2021-09-09T12:43:45.000000Z    0        10
2021-09-09T12:43:45.200000Z    0        11
2021-09-09T12:43:45.300000Z    0        12
2021-09-09T12:43:45.400000Z    0        16
2021-09-09T12:43:46.040000Z    0        17
2021-09-09T12:43:46.050000Z    1        20
2021-09-09T12:43:46.100000Z    1        21
2021-09-09T12:43:47.000000Z    1        21
2021-09-09T12:43:47.000300Z    1        22
2021-09-09T12:43:48.000000Z    1        24
```

the above query will result in: 

```
ts                             column
2021-09-09T12:43:45.000000Z    6
2021-09-09T12:43:46.000000Z    4
2021-09-09T12:43:47.000000Z    1
2021-09-09T12:43:48.000000Z    0
```

as far as I understand, this is what you want to achieve. If not, could you please explain?

Best

**Comment by dm13450** [comment]
My input on this: 
I would like a function that takes in a column and returns the Nth shifted value. 

For context, I have a database of trades and want to calculate the price difference between different lags. 

So for the price difference between consecutive trades would be `price - lag(price, 1)`. 
The price difference between the Nth trade would be `price - lag(price, N)`.

Or in terms of pricing data, the difference in the log values would give the return.

Thanks.

**Comment by 362115815** [comment]
Use row_number to make a compromise,  eg:

```
with B as 
(
    select 
    A.ts, A.gross_asset, row_number() over (partition by A.accountid order by A.ts) as rank
    from 
    (
           select accountid , ts, last(gross_asset) as gross_asset from '4_sim_account' SAMPLE by 1d ALIGN TO CALENDAR
    )A
)
select B.gross_asset - C.gross_asset from B join B C on B.rank-C.rank=1
```

**Comment by shimondoodkin** [comment]
duplicate #2007

**Comment by Zahlii** [comment]
If thats fine, I'll have a look into it.  My idea for now would be to keep syntax in line with the approach used by row_number, i.e. lag(column, N), or lag(column, N) over (partition by a order by b)

**Comment by itsanshulkushwaha** [comment]
Use row
with B as 
(
    select 
    A.ts, A.gross_asset, row_number() over (partition by A.accountid order by A.ts) as rank
    from 
    (
           select accountid , ts, last(gross_asset) as gross_asset from '4_sim_account' SAMPLE by 1d ALIGN TO CALENDAR
    )A
)
select *, B.gross_asset - C.gross_asset from B join B C on B.rank-C.rank=1

**Comment by newskooler** [comment]
For a table with the following schema:
```
CREATE TABLE 'my_table' (
  markets SYMBOL capacity 256 CACHE,
  values
    DOUBLE,
    ts_saved_on TIMESTAMP,
    timestamp TIMESTAMP
) timestamp (timestamp) PARTITION BY DAY WAL;
```
Where markets are 20 different ones and there are a total of 700,000 rows, I use the following query:
```
WITH RankedValues AS (
    SELECT 
        markets,
        "values",
        timestamp,
        row_number() OVER (PARTITION BY markets ORDER BY timestamp) AS rn
    FROM my_table
) 

SELECT 
    a.markets,
    a.timestamp,
    "a.values" AS current_value,
    "b.values" AS shifted_value
FROM RankedValues a
LEFT JOIN RankedValues b ON a.markets = b.markets AND a.rn = b.rn + 2;
```

It works if I limit it to 1 market and 100 rows, but if I run it for the whole table it's extremely slow and times out. I hope the `LEAD` and `LAG` get added to the DB in a performant way. Until then, if anyone has any suggestions, I will be very grateful.

**Comment by javier** [comment]
This is already possible by using the `first_value` window function. In your example it would work as:

```
 SELECT 
        markets,
        "values",
        timestamp,
        first_value("values") OVER (PARTITION BY markets ORDER BY timestamp ROWS BETWEEN 2 PRECEDING AND 2 PRECEDING) AS values_2_before, 
 first_value("values") OVER (PARTITION BY markets ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS  values_1_before 
FROM my_table
```

It should be quite performant as well. On the demo machine this query returns in ~235ms for a dataset with more than 750 million rows

```
 SELECT 
        symbol,
        price,
        timestamp,
        first_value(price) OVER (PARTITION BY symbol ORDER BY timestamp ROWS BETWEEN 2 PRECEDING AND 2 PRECEDING) AS price_2_before, 
       first_value(price) OVER (PARTITION BY symbol ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS  price_1_before 
FROM trades;
```

**Comment by ideoma** [comment]
This is now covered with WINDOW functions, closing the issue
