### ISSUE TITLE
Inconsistent filtering on indexed SYMBOL columns when ILP modifies table schema

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb#1278]
**Describe the bug**
When an indexed symbol column exists in a table, adding new columns via ILP produces inconsistent results

**To Reproduce**

1. Create table with indexed `symbol` column:
```sql
create table tbl (ReceiveTime timestamp, messageType symbol index)
timestamp(ReceiveTime) 
partition by DAY;
```
2. Add records with additional column, e.g.:
```python
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
  sock.connect(('localhost', 9009))
  sock.send(('tbl,messageType=1801 description="test1"\n').encode())
  sock.send(('tbl,messageType=1802 description="test2"\n').encode()) 
except socket.error as e:
  print("Got error: %s" % (e))
sock.close()
```
3. Run this query:
```sql
select * from tbl where messageType = '1802'
```

**Expected behavior**
Filtering of table results based on indexed column, instead, no results are returned.

**Environment (please complete the following information):**
 - OS: MacOS (reported on Windows, also)
 - Version: Docker 6.0.4 (2d16df8f0846707f34f76f96864e93f0cafe85f3)

**Comment by spxie85** [comment]
I found a workaround which is to use either 
`select * from tbl where cast(messageType as string) = '1802'`
or
`select * from tbl where cast(messageType as int) = 1802`
