### ISSUE TITLE
LATEST BY Including results filtered out by Where condition when SYMBOL is indexed

### ISSUE THREAD

**Issue by jeevavenkataraman** [questdb/questdb#1299]
**Describe the bug**
When LATEST BY keyword is used with Where filter, it looks like the LATEST BY could re-adding the records already removed by the where filter.

**To Reproduce**
1. Create table

```sql
create table balances(
cust_id SYMBOL,
balance_ccy SYMBOL,
balance DOUBLE,
timestamp TIMESTAMP
)
timestamp(timestamp)
```

2. Insert data points
```sql
insert into balances values ('c1', 'USD', 1500, now())
insert into balances values ('c1', 'USD', 900.75, now())
insert into balances values ('c1', 'EUR', 880.2, now())
insert into balances values ('c1', 'EUR', 782, now())
insert into balances values ('c2', 'USD', 900, now())
insert into balances values ('c2', 'USD', 190.75, now())
insert into balances values ('c2', 'EUR', 890.2, now())
insert into balances values ('c2', 'EUR', 1000, now())
```

3. Run this SQL 
```sql
SELECT * FROM balances LATEST BY cust_id, balance_ccy 
WHERE cust_id = 'c1' and balance_ccy='EUR'
```

4. Add index
```sql
alter table balances alter column cust_id add  index 
```

5. Re-run SQL
```sql
SELECT * FROM balances LATEST BY cust_id, balance_ccy 
WHERE cust_id = 'c1' and balance_ccy='EUR'
```

**Expected behavior**
The execution is order is expected by WHERE first, so with the above data, we are not expecting the result having balance_ccy = 'USD'. At step 5 results are wrong

**Screenshots**
But the result includes balance_ccy = 'USD' which should have been filtered out.
![image](https://user-images.githubusercontent.com/62668984/132434767-38d24ec4-c1f0-46ee-9970-7024baa5fe08.png)

Whereas if the query was to do LATEST BY first, then the result matches the expectation:
![image](https://user-images.githubusercontent.com/62668984/132434947-c7e97794-0aa9-4fb9-ba13-19d393a6e3b3.png)

**Environment (please complete the following information):**
  - Version: QuestDB 6.0.4b docker container

**Comment by ideoma** [comment]
@jeevavenkataraman thanks, very good issue description. I have added add index statement, it works correctly without index and incorrectly with index

**Comment by jeevavenkataraman** [comment]
@ideoma, Yes - Re. Index, Yes, after adding Index is when I noticed this. But then I tried recreating the table with out index and the problem was still seen and that's why I did not include index in the description of the issue.
