### ISSUE TITLE
when upgrading questdb predefined queries are overwritten with default content

### ISSUE THREAD

**Issue by rstreics** [questdb/questdb#1328]
**Describe the bug**
when upgrading questdb predefined queries are overwritten with default content  

**To Reproduce**
1. Predefine queries
2. Update questdb to new version
3. File `console-configuration.json` replaced with default content

**Expected behavior**
Predefined queries to be persisted during upgrade 

**Environment (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: 6.0.4

**Comment by marregui** [comment]
Thank you for reporting this, I hope you are well.
The issue has now been solved.

Best regards
