### ISSUE TITLE
SQL NOT - case sensitive?

### ISSUE THREAD

**Issue by robocoder** [questdb/questdb#1329]
**Describe the bug**
Get `unknown function name: NOT(BOOLEAN)` when using `NOT` (instead of `not`) in query

**To Reproduce**
```
CREATE TABLE foo (ts TIMESTAMP, metric INT);
INSERT INTO foo VALUES (now(), 0);
SELECT count() FROM foo WHERE metric NOT IN (0);
```
**Expected behavior**
```
 count 
-------
     0
(1 row)
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04 LTS
 - Browser: Chrome 93.0.4577.63 (Official Build) (x86_64)
 - Version: 6.0.4\

**Additional context**
- psql (12.8 (Ubuntu 12.8-0ubuntu0.20.04.1), server 11.3)

**Comment by bluestreak01** [comment]
this is fixed in 6.0.5
