### ISSUE TITLE
JDK core dump when doing o3 sort.

### ISSUE THREAD

**Issue by jfarjona** [questdb/questdb#1338]
I have a case in which (I don't know why) it goes for "o3" sort:

```
2021-09-19T16:59:21.132415Z I i.q.c.p.WriterPool >> [table=`effr_rates`, thread=56]
2021-09-19T16:59:21.132678Z I i.q.c.TableWriter switched to o3 [table=effr_rates]
2021-09-19T16:59:21.133946Z I i.q.c.TableWriter sorting o3 [table=effr_rates]
```

When that happens, there is a core dump from the JDK:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000066aacdc3, pid=32636, tid=32648
#
# JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.12+8) (build 11.0.12+8-LTS-237)
# Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.12+8-LTS-237, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [libquestdb11394819330336213871.dll+0x2cdc3]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\...\hs_err_pid32636.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Here are the contents of the log file:

[gh-1338.log](https://github.com/questdb/questdb/files/7195561/1338.log)

**Comment by jfarjona** [comment]
Additional info:  it seems to happen on an existing table, when I try to append more rows, and the dates are duplicated.

**Comment by bluestreak01** [comment]
Thanks for raising the issue! We recently fixed a crash case, where new column addition didn't fully update internal state. If in your case there were no column added, do you mind sharing ILP rows that cause this crash ?

**Comment by bsmth** [comment]
I've edited the original issue description to include the logs as an attachment to improve readability / discussion on this issue

**Comment by ideoma** [comment]
Hey @jfarjona,
Is it possible to get a reproducible example of this crash? If it's not easy to simulate, perhaps you can share piece  of your data with me and code which results to the crash?

**Comment by jfarjona** [comment]
Here you go:


https://github.com/jfarjona/questdb-crasher


Juan

**Comment by ideoma** [comment]
Hey @jfarjona ,

Thanks for the code example, really necessary to see the code to understand what is going on.
There is a problem in API usage. When you create new row using `row = writer.newRow(ts)` you should not call `row.putTimestamp(tsIndex, ts)` on the Designated Timestamp. This results to double pushing a value for the same column and then pointer arithmetic miscalculation.

Here is a patch to fix the code in your repo
[fix-timestamp-set.txt](https://github.com/questdb/questdb/files/7224905/fix-timestamp-set.txt)

essentially it adds this check

```
// Do not put designated timestamp column, it's set in newRow(ts)
if (dbIdx!= writer.getMetadata().getTimestampIndex()) {

```

Double putting values on any column type results to similar problems, e.g. crashes, data corrupt.

I had to clear data from invalid runs after applying the fix and everything worked without crashes.

**Comment by jfarjona** [comment]
Thanks!

I think then that this should be pointed out on the documentation and the javadoc.  Perhaps the API should throw an exception when that double setting is done.
The javadocs need a lot of work, takes a lot of time to find out what to do, as they are almost empty.  

Thanks a lot for looking into this.

Juan
