### ISSUE TITLE
Feature request: text hashing function

### ISSUE THREAD

**Issue by giovannibonetti** [questdb/questdb#1341]
**Is your feature request related to a problem? Please describe.**
I'm working on using QuestDB to power my company's internal dashboards, and one thing we couldn't find in the documentation was an efficient way to count the number of distinct IP addresses (e.g. IP addresses that accessed this page today). Currently, we are using [Postgres extension HLL](https://github.com/citusdata/postgresql-hll#usage) (HyperLogLog). It works like this:
```sql
INSERT INTO analytics_table VALUES ... hll_hash_text(ip_address::text) ...
```

**Describe the solution you'd like**
Instead of storing the IP address as a string, I think it would be way more efficient to use a hashing function to convert the remote IP string representation to a 16, 32 or 64 bit integer.

**Describe alternatives you've considered**
Relying on an application level implementation of said function (instead of relying in the database). It's not that bad, now that I've stopped to think about it 🤔. Anyway, it might be a nice-to-have in the database itself, or you can just close this issue if you think it doesn't make sense.

**Comment by bsmth** [comment]
Hi @giovannibonetti thanks a lot for raising the issue, we have a related issue to track support for adding a native `ip` type at https://github.com/questdb/questdb/issues/903 would something like this cover what you are thinking of?

In the meantime, maybe a workaround would be to use the [symbol type](https://questdb.io/docs/concept/symbol/) which is more performant than using strings.

**Comment by giovannibonetti** [comment]
Great, I wasn't aware of that. I'll close this issue, then.
Thanks for the quick response!
