### ISSUE TITLE
Support for window functions / moving averages

### ISSUE THREAD

**Issue by tris0laris** [questdb/questdb#1351]
### Discussed in https://github.com/questdb/questdb/discussions/1162

<div type='discussions-op-text'>

<sup>Originally posted by **fuzzthink** June 28, 2021</sup>
A Sliding window or Moving average is pretty important in many use cases. It would be nice if questdb has this built in.

**Comment by pswu11** [comment]
Related to https://github.com/questdb/questdb/issues/258

**Comment by javier** [comment]
related to https://github.com/questdb/questdb/issues/2995

**Comment by KIC** [comment]
Do you have any updates or timelines for this?

**Comment by mighty-phoenix** [comment]
Any updates on this?

**Comment by puzpuzpuz** [comment]
avg function is already available among window functions.
