### ISSUE TITLE
CSV import unreliable in some scenerios

### ISSUE THREAD

**Issue by null-dev** [questdb/questdb#1357]
**Describe the bug**
QuestDB fails to import CSV files (using `/imp`) that it has exported previously (using `/exp`). It either:

- Fails to import the CSV, throwing an exception in console and also not returning an HTTP response (eventually the request times out)
- Fails to import the CSV, returning: `min deviation is too high`

**To Reproduce**
1. Create a fresh QuestDB instance
2. Try to import the attached `deviation-redacted.csv` file using the following command: `curl -F data=@deviation-redacted.csv 'http://127.0.0.1:9000/imp?atomicity=0&durable=false&forceHeader=true&overwrite=true'`
3. Observe that you get the following error response: `min deviation is too high [delimiterStdDev=0.17141982574219336, delimiterMaxStdDev=0.1222, lineLengthStdDev=60.95420377346737, lineLengthMaxStdDev=0.8, lineCountLimit=1000, lineCount=99]`
4. Try to import the attached `import-fail-redacted.csv` file using the following command: `curl -F data=@import-fail-redacted.csv 'http://127.0.0.1:9000/imp?atomicity=0&durable=false&forceHeader=true&overwrite=true'`
5. Observe that the request never completes and errors appear in the console.

**Expected behavior**
The import completes without error.

**Environment (please complete the following information):**
 - OS: Arch Linux 5.14.7-zen1-1-zen x86_64
 - Browser: Firefox Developer 93.0b9 (64-bit)
 - QuestDB Version: 6.0.6 (docker). I've also tested 6.0.5 and the issue is present there as well.

**Additional context**
The import also fails even if I create the tables in advance and set `overwrite=false`. If you want to try anyways, here is the DDL for the attached CSVs:

```
CREATE TABLE historian (
host_id SYMBOL,
profile_id SYMBOL,
visit_time TIMESTAMP,
browser_id string,
title STRING,
url STRING,
browser_typed_count LONG,
browser_visited_count LONG
) TIMESTAMP(visit_time)
  PARTITION BY MONTH;
```

Also, as mentioned before, the attached CSVs were exported from a live QuestDB database containing webpage titles and URLs for one of my scraping projects. The CSVs were then redacted for privacy. For example, the redaction process for `import-fail-redacted.csv` consists of:

1. Replacing each alphanumeric character in the string fields with another random alphanumeric character.
2. The same has been done to the Japanese lettering as well, replacing each existing Japanese letter with another random Japanese letter.

The above errors also happen when importing the original unredacted files.

**Attachments:**
[import-fail-redacted.csv](https://github.com/questdb/questdb/files/7229349/import-fail-redacted.csv)
[deviation-redacted.csv](https://github.com/questdb/questdb/files/7229350/deviation-redacted.csv)

**Comment by null-dev** [comment]
Also, I see according to the documentation that CSV import is not guaranteed to succeed if the data is not uniform so I guess I don't really have issue with the `min deviation is too high` error when importing `deviation-redacted.csv`.

I do think that importing `import-fail-redacted.csv` should at least return a response though instead of timing out.

**Comment by bluestreak01** [comment]
This problem should be fixed with https://github.com/questdb/questdb/pull/1655

The reported StdDev issue is against the logic trying to establish column delimiter. The heuristics is not always reliable. We have added a feature to specify delimiter manually.
