### ISSUE TITLE
Java error when starting QuestDB

### ISSUE THREAD

**Issue by RiccardoGiro** [questdb/questdb#1362]
How do I solve this issue? My current version of Java is 17 (jdk Oracle distribution).
Thank you in advance

![Screenshot 2021-09-27 102125](https://user-images.githubusercontent.com/60734967/134871349-be25ad09-96bf-4146-8a56-e8e11e3fdd84.png)

**Comment by ideoma** [comment]
JDK 17 is not supported, please use JDK 11
