### ISSUE TITLE
Influx ILP is not always inserting

### ISSUE THREAD

**Issue by zanek** [questdb/questdb#1375]
**Describe the bug**
CREATE TABLE test (id symbol, name string);
I send data to the Influx port like this (using C#) :  socket.send("test,id=\"f1\" name=\"h1\"\ntest,id=io");
The rows that show up for id,name are:  "f1", h1
The quotes are being added in the column for f1, so thats one problem. Also, many rows dont  show up

I've spent hours just trying to insert data into QuestDB and its way to difficult. I'm probably going to move to another database

If I add a space, nothing shows up
send("test,id=f2\\ gel name=\"h2\"\ntest,id=io");
 
**Environment (please complete the following information):**
 - OS:  Windows
 - Browser: Firefox
 - Version: 6.0

**Comment by bsmth** [comment]
Hi @zanek thanks for raising the issue. Sorry to hear that you're having trouble. It looks like you're sending malformed input, we don't have C# examples, but you can find a Python example here for reference: https://questdb.io/docs/develop/insert-data

i.e.:

```python
import time
import socket

HOST = 'localhost'
PORT = 9009
# For UDP, change socket.SOCK_STREAM to socket.SOCK_DGRAM
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

try:
  sock.connect((HOST, PORT))
  # Single record insert
  sock.sendall(('trades,name=client_timestamp value=12.4 %d\n' %(time.time_ns())).encode())
  # Omitting the timestamp allows the server to assign one
  sock.sendall(('trades,name=server_timestamp value=12.4\n').encode())
  # Streams of readings must be newline-delimited
  sock.sendall(('trades,name=ilp_stream_1 value=12.4\ntrades,name=ilp_stream_2 value=11.4\n').encode())

except socket.error as e:
  print("Got error: %s" % (e))

sock.close()
```

**Comment by zanek** [comment]
Thanks, I saw that Python snippet (I've read every page of the documentation). The problem is I'm loading alot of content into Quest over 90 columns (all using symbol type), so I've crashed QuestDB dozens of times, or just had it mistakenly create 50 tables from text in a string it thinks is a table name

I think this import format is really bad, and should be in JSON or something that isnt as brittle. I can easily insert in Postgres or other databases without all this trouble

**Comment by bluestreak01** [comment]
You are right about ILP being brittle, we're going to provide C# client library to escape values. We have a class for Java that does it, for reference: https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/tcp/LineTCPProtoSender.java


I'm guessing we'd have the same or worse problems if you assemble json or PostgreSQL wire commands by hand.

**Comment by bsmth** [comment]
Hi @zanek, I'm closing this as issue the moment. If you would like to add some feedback for improvements, feel free to [add your thoughts on GitHub discussions](https://github.com/questdb/questdb/discussions). :)

Thank you!
