### ISSUE TITLE
questdb-ilp-python - Python port of LineProtoSender

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1381]
The goal is to create thin, easy to use Python client for sending ILP messages. We already have a Java client:

* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/AbstractLineSender.java
* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/LineTcpSender.java
* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/LineUdpSender.java

Perhaps port this one maintaining the same API

**Comment by askalik** [comment]
Could I give this a try?

**Comment by ngnic** [comment]
Hiya, 

I've worked on this abit and would like to get some eyes/comments on this. The API is slightly different. Let me know what you guys think.

https://github.com/ngnic/python-questdb-client

here's an example:
https://github.com/ngnic/python-questdb-client/blob/main/example.py

**Comment by bluestreak01** [comment]
thank you for picking the issue up 👍 

Our existing API maintain order of items on ILP line, e.g. 

```
table,tagset fieldset timestamp
```

In that timestamp is at the end to avoid API double-buffering. ILP server is a fast ingestion API, client should not be a bottleneck.

I would also not have "raw" option. Our other clients (Java, C# https://github.com/questdb/net-questdb-client) do not have it  to reduce opportunities for formatting and encoding issues.

Additionally Python should use https://docs.python.org/3/library/asyncio.html for performance reasons.

**Comment by ngnic** [comment]
Thanks for the feedback!

> Our existing API maintain order of items on ILP line

The current implementation maintains ordering as well, there's a [test](https://github.com/ngnic/python-questdb-client/blob/main/tests/test_row.py#L50-L63) that captures this. 

Have also removed the raw option that's exposed through Row, it's retained in KeyValuePair for convenience. While it isn't hidden from the user, there's no avenue for a user to use it directly.

Regarding Async support, i'll clone the existing implementation as AsyncClient while maintaining the same interface as Client. So from the end user's perspective, they have a choice of picking sync or async. What do you think?

**Comment by pswu11** [comment]
The official python client for ilp is released: 

https://github.com/questdb/py-questdb-client
