### ISSUE TITLE
questdb-ilp-rust - Rust port of LineProtoSender

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1382]
The goal is to create thin, easy to use Rust client for sending ILP messages. We already have a Java client:

* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/AbstractLineSender.java
* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/LineTcpSender.java
* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/LineUdpSender.java

Perhaps port this one maintaining the same API

**Comment by puzpuzpuz** [comment]
fd stands for file descriptor, while lo stands for the start address of the buffer holding the data to be written to socket. I checked the code really quickly, so there is a small chance that I'm missing something.

**Comment by vss96** [comment]
@puzpuzpuz Thanks for clearing that up :)

**Comment by vss96** [comment]
@bluestreak01 I have created a barebones [rust client](https://github.com/vss96/questdb_ilp_rust) (as a start) which sends a buffer message either over TcpStream or UdpSocket. If you can explain more about how an ILP message looks like that would be great. From what I understand the only information being passed is the buffer address and the length of the buffer. Reading memory address directly is an unsafe operation in Rust, so i would need some more help as to how this message looks like in the first place.

**Comment by bluestreak01** [comment]
thanks Vikas, the goal behind having ILP client is to decouple user from knowing the protocol, helping them validate data before they send it and encode data as needed. Protocol description can be found here:

https://questdb.io/docs/guides/influxdb-line-protocol/

and 

https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/

I would encourage you to look at helper methods this class https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/AbstractLineSender.java provides

**Comment by pswu11** [comment]
client for Rust has been supported here: 
https://github.com/questdb/c-questdb-client/blob/main/questdb-rs/README.md
