### ISSUE TITLE
questdb-ilp-js - JavaScript port of LineProtoSender

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1383]
The goal is to create thin, easy to use JavaScript client for sending ILP messages. We already have a Java client:

* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/AbstractLineSender.java
* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/LineTcpSender.java
* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/LineUdpSender.java

Perhaps port this one maintaining the same API

**Comment by vascoalramos** [comment]
Hi! Can I work on this?

**Comment by bluestreak01** [comment]
absolutely

**Comment by vascoalramos** [comment]
Hi, I have been going through the code, and I have one question: where, in the repo structure, should stay the client?

**Comment by puzpuzpuz** [comment]
I'd say it should stay in a separate repo, so that we can maintain it separately and easily publish it as an npm package.

**Comment by puzpuzpuz** [comment]
The client is released and available here: https://github.com/questdb/nodejs-questdb-client
