### ISSUE TITLE
questdb-ilp-go - GoLang port of LineProtoSender

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1384]
The goal is to create thin, easy to use GoLang client for sending ILP messages. We already have Java client:

https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/LineProtoSender.java

Perhaps port this one maintaining the same API

**Comment by yaash45** [comment]
I would love to give this a try! Please let me know if I can do that. Thanks!

**Comment by yaash45** [comment]
So I took some time to study the Java client code, and I was wondering if the task is to just create a UDP-based client using Go. I was planning to do so using Go's net library. Should I create a separate directory in the root of this repo that holds the Go client?

**Comment by zikani03** [comment]
Just wanted to note that I've had success with using https://github.com/influxdata/line-protocol/ and `net` package like so:

```go
package main

import (
	"net"

	lineprotocol "github.com/influxdata/line-protocol"
)

type EventItem struct {
	Time	time.Time
}

func (e *EventItem) Tags() map[string]string {
	tags := make(map[string]string)
	// add tags here
	return tags
}

func (e *EventItem) Fields() map[string]interface{} {
	fields := make(map[string]interface{})
	// add fields
	return fields
}

func main() {
	conn, err := net.Dial("tcp", "localhost:9009")
	if err != nil {
		panic(err)
	}
	serializer := lineprotocol.NewEncoder(conn)
	serializer.SetMaxLineBytes(1024)
	serializer.SetFieldTypeSupport(lineprotocol.UintSupport)
	
	event, err := lineprotocol.New("my_events_table", eventItem.Tags(), eventItem.Fields(), eventItem.Time)
	if err != nil {
		panic(err)
	}
	serializer.Encode(event)	
}
```

**Comment by puzpuzpuz** [comment]
Implemented and available on https://github.com/questdb/go-questdb-client
