### ISSUE TITLE
questdb-ilp-cpp - C++ port of LineProtoSender

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1385]
The goal is to create thin, easy to use C++ client for sending ILP messages. We already have a Java client:

* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/AbstractLineSender.java
* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/LineTcpSender.java
* https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cutlass/line/LineUdpSender.java

Perhaps port this one maintaining the same API

**Comment by amunra** [comment]
Implemented: https://github.com/questdb/c-questdb-client
