### ISSUE TITLE
Logging on Windows not working

### ISSUE THREAD

**Issue by maximinus** [questdb/questdb#1416]
**Describe the bug**
If the instructions on the questdb website are followed, logging does not work on Windows 10 using the binary (no JVM) install

**To Reproduce**
On Windows 10, unpack the binary file, place the fies on your path, run questbd.exe install and restart the machine.
Now add a conf file for logging as described here: https://questdb.io/docs/reference/configuration/#logging
Ensure the service is running, set up a small db with a table and data.
No logging is to be seen

**Expected behavior**
I expect at least a /log folder to exist in C:\Windows\System32\qdbroot
I would expect this folder to hold 1 or more log files
The docs give the "default" path as C:\Windows\System32\questdb, but this folder does not exist for me

**Environment (please complete the following information):**
  Windows 10 Version 10.0.19042 Build 19042

**Additional context**
The docs also state "QuestDB will look for /log-stdout.conf on the classpath" but do not define the classpath (this sounds like a java thing).

**Comment by puzpuzpuz** [comment]
When QDB is ran with `questdb.exe install` and then started in service manager it doesn't create log dir with stdout-* file. On the other hand, when it's run with `questdb.exe` it does create a log dir.

**Comment by bugfoot** [comment]
@puzpuzpuz I started QuestDB `questdb.exe start` but the log directory is still not created under _C:\Windows\System32\qdbroot_.

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz I started QuestDB `questdb.exe start` but the log directory is still not created under _C:\Windows\System32\qdbroot_.

Hi @bugfoot,

Did you try specifying the root dir when starting the database? E.g.:
```
questdb.exe start -d "C:\my_root_dir"
```

**Comment by bugfoot** [comment]
@puzpuzpuz Yes, even with the (default Windows) root directory specified:
`questdb.exe start -d "C:\Windows\System32\qdbroot"`
and some `CREATE TABLE`, `INSERT` and `SELECT` operations performed there is no _log_ folder in sight under _qdbroot_.

**Comment by bziobrowski** [comment]
When running as : 
- regular process, stdout is redirected to log/stdout-$date dir . 
- service - stdout is discarded .

Since questdb.exe doesn't allow passing aribtrary CLI params (e.g. -Dout=log.conf) to java the only way to enable logging on windows is to set the following system parameters :
```
QDB_LOG_W_FILE_CLASS=io.questdb.log.LogFileWriter
QDB_LOG_W_FILE_LEVEL=INFO,ERROR
QDB_LOG_W_FILE_LOCATION=C:\Windows\System32\qdbroot\questdb-debug-test.log
```
and (re)start service .
If you use non-absolute path for QDB_LOG_W_FILE_LOCATION then log file is going to be created relative to C:\Windows\System32\qdbroot\ as that's the process work dir .
