### ISSUE TITLE
Latest by returns incorrect results when applied with filters

### ISSUE THREAD

**Issue by arina-ielchiieva** [questdb/questdb#1419]
**To Reproduce**
Data set:
```
create table numeric_column_value_1(device_id symbol index, column_name symbol index, value double, timestamp timestamp) timestamp(timestamp) partition by day;

insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c1', 101.1, '2021-10-05T11:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c1', 101.2, '2021-10-05T12:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c1', 101.3, '2021-10-05T13:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c1', 101.4, '2021-10-05T14:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.1, '2021-10-05T11:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.2, '2021-10-05T12:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.3, '2021-10-05T13:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.4, '2021-10-05T14:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d1', 'c2', 102.5, '2021-10-05T15:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d2', 'c1', 201.1, '2021-10-05T11:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d2', 'c1', 201.2, '2021-10-05T12:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d2', 'c1', 201.3, '2021-10-05T13:31:35.878Z');
insert into numeric_column_value_1 (device_id, column_name, value, timestamp) values ('d2', 'c1', 201.4, '2021-10-05T14:31:35.878Z');
```

Query: ` select * from numeric_column_value_1 latest by device_id, column_name`
Result: 
![image](https://user-images.githubusercontent.com/15086720/136762406-9255e26f-79ed-4d38-ad03-6453b8c32913.png)
Status: Correct

Query: `select * from numeric_column_value_1 latest by device_id, column_name where device_id = 'd1'`
Result: 
![image](https://user-images.githubusercontent.com/15086720/136762623-86dd143f-1185-4cf3-95cc-8feda4d68005.png)
Status: Incorrect

Query: `select * from numeric_column_value_1 latest by device_id, column_name where device_id = 'd1' and column_name in ('c1', 'c2')`
Result:  No data
![image](https://user-images.githubusercontent.com/15086720/136762830-169843c5-8f44-4a52-a9c5-2edfa3d7278c.png)
Status: Incorrect

Query: `select * from numeric_column_value_1 latest by device_id, column_name where timestamp >= '2021-10-05T14:31:35.878Z'`
Result: 
![image](https://user-images.githubusercontent.com/15086720/136763409-0aa1d40c-e13b-4e34-bcab-a31920db35f9.png)
Status: Incorrect

**Environment**:
Version: 6.0.7.1

**Comment by arina-ielchiieva** [comment]
```
Perhaps this is not clear from docs, but latest by supports only one column. We probably should error out SQL to make this clearer
```
but why then `select * from numeric_column_value_1 latest by device_id, column_name` returns correct results?

**Comment by bluestreak01** [comment]
the documentation is incorrect, we will update that. Only single column support is implemented
