### ISSUE TITLE
Column identifier qoute is not working in SqlCompiler. Parser should drop quotes from identifier in model parsing

### ISSUE THREAD

**Issue by igor-suhorukov** [questdb/questdb#143]
**Describe the bug**
Column by name reference without quoting is not work when table created by "create table" DDL with column quoiting.

**To Reproduce**
```
git clone https://github.com/igor-suhorukov/questdb-issue.git
cd questdb-issue
mvn test -Dtest=io.questdb.sql.QuoteIdentifierTest
```

**Expected behavior**
Column name should by without quoting symbols after parsing in model.
model.getColumnSet() should return values without quotes as model.getTableName() does

**Screenshots**

**Desktop (please complete the following information):**
```
desktop:~$ uname -a
Linux desktop 5.4.0-21-generic #25-Ubuntu SMP Sat Mar 28 13:10:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

desktop:~$ java -version
openjdk version "1.8.0_252-ea"
OpenJDK Runtime Environment (build 1.8.0_252-ea-8u252-b07-1-b07)
OpenJDK 64-Bit Server VM (build 25.252-b07, mixed mode)
```

**Smartphone (please complete the following information):**
NA

**Additional context**
Please be careful and test and fix this quoting issue among all QuestDB code base as it looks like common issue.

**Comment by bluestreak01** [comment]
fixed, all literals - table and column names, can we used with double quotes
