### ISSUE TITLE
Time range with negative multiplier as modifier

### ISSUE THREAD

**Issue by robocoder** [questdb/questdb#1430]
**Describe the bug**
Time range with negative multiplier as the modifier does not work.
```
ERROR: Invalid date
```

**To Reproduce**
```
SELECT count() FROM sometable WHERE ts IN '2021-10-12T14:00:00;-60m';
```

**Expected behavior**
Should work like:
```
SELECT count() FROM sometable WHERE ts IN '2021-10-12T13:00:00;60m';
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Version: 6.0.7.1
 - JRE: openjdk-11-jre-headless:amd64 (11.0.11+9-0ubuntu2~20.04)

**Additional context**
* postgresql-client-12 (12.8-0ubuntu0.20.04.1)

**Comment by robocoder** [comment]
It's in the documentation.
* https://questdb.io/docs/reference/sql/where/#time-range-with-modifier

> multiplier is a signed integer.
>
> * A positive value extends the interval.
> * A negative value reduces the interval.

**Comment by eugenels** [comment]
The negative multiplier is valid as long as the interval it describes is positive (lo < hi)

`2021-10-12T14;15m` - means 1 hour and 15 mins interval started from 14h

 `2021-10-12T14;-15m`  - means 45 mins interval started from 14h

**Comment by bluestreak01** [comment]
@bsmth we should perhaps be very explicit in the documentation that we expect point in time in queries such as:

```sql
where ts  in '2021-10-12T13:00:00.000000;60m'
```

e.g.

```
2021-10-12T13:00:00.000000 <- valid
2021-10-12T13:00:00 <- invalid
```

@eugenels is that correct ?
