### ISSUE TITLE
Table becomes corrupt after power loss

### ISSUE THREAD

**Issue by jgroenveld-jasa** [questdb/questdb#1448]
**Describe the bug**
The data is send to QuestDB using the InfluxDB line protocol through TCP.
The machines sometimes get turned off by switching off the power, which results in an instant shutdown by power loss.

When the power is suddenly lost the table becomes corrupt and gives the following error:
`[0]: Invalid metadata at fd=1352. Metadata version does not match runtime version [expected=422, actual=0]`

**Environment (please complete the following information)**
 - Windows 10
 - QuestDB 6.0.7.1

**Log before power cycle**
I have attached 2 logs files: one before the power loss and one after.
[log-after-power-cycle.txt](https://github.com/questdb/questdb/files/7382118/log-after-power-cycle.txt)
[log-before-power-cycle.txt](https://github.com/questdb/questdb/files/7382119/log-before-power-cycle.txt)

**Comment by bluestreak01** [comment]
this is fixed in 6.1.2

**Comment by mehdibouzit** [comment]
Hi,
I don't think this is fixed: just had the same issue in version 6.1.2 installed 2 days ago, after a power outage.

**Comment by Va1** [comment]
same happens upon disk snapshot restoration, on Linux in k8s
