### ISSUE TITLE
unknown function name: pg_catalog.version()

### ISSUE THREAD

**Issue by ilmoi** [questdb/questdb#1450]
Trying to connect to QuestDB from Python (using either `db8000` or `psycopg2`) and getting this error:

```
sqlalchemy.exc.ProgrammingError: (pg8000.dbapi.ProgrammingError) {'C': '00000', 'M': 'unknown function name: pg_catalog.version()', 'S': 'ERROR', 'P': '8'}
[SQL: select pg_catalog.version()]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

According to sqlalchemy docs the error is caused by the database itself rather than by sqlalchemy. I couldn't find anything on google, and couldn't debug by poking around.

Could someone advice on what the issue might be?

**Comment by rahilbhansali** [comment]
any update or timeframe on when there maybe support for sqlalchemy?

**Comment by jerrinot** [comment]
SQLAchemy is now partially supported. See: https://questdb.io/docs/third-party-tools/sqlalchemy/
`select pg_catalog.version();` works too. 

I'm now closing this issue, feel free to re-open it if it does not work for you.
