### ISSUE TITLE
UI better error message when server is not running

### ISSUE THREAD

**Issue by marregui** [questdb/questdb#1455]
### Current behaviour

1. With a QuestDB node running in localhost, go to localhost:9000 in a browser and run a valid query -> all good.
2. Now kill the server -> No feedback is given to the user.
3. Still in the web ui, run the query again -> you get the error message "X An error occurred, please try again".

### Assumed behaviour

Would be nice to have a better error message when the server is down, something along the lines: `QuestDB node not found at localhost:9000`.
Would also be nice to update the "connection" status with some visual clue.

<img width="1676" alt="Screenshot 2021-10-21 at 16 22 03" src="https://user-images.githubusercontent.com/255796/138300068-25991d32-eab8-4538-843f-7e66b0a6b2fe.png">

**Comment by bsmth** [comment]
Resolved by changes in https://github.com/questdb/questdb/pull/1451

**Comment by Mehdish1414** [comment]
Okay
