### ISSUE TITLE
Insert multiple values c'est kaput

### ISSUE THREAD

**Issue by marregui** [questdb/questdb#1462]
Postgres supports multiple values being inserted in an insert statement (https://www.postgresql.org/docs/9.4/dml-insert.html), for example:

```
create table x (id symbol index,
                        name symbol index, 
                        val double,
                        ts timestamp) timestamp(ts) partition by DAY;
insert into x values('d1', 'c1', 101.1, '2021-10-05T11:31:35.878Z'),
                        ('d1', 'c1', 101.2, '2021-10-05T12:31:35.878Z'), 
                        ('d1', 'c1', 101.3, '2021-10-05T13:31:35.878Z'),
                        ('d1', 'c1', 101.4, '2021-10-05T14:31:35.878Z'), 
                        ('d1', 'c2', 102.1, '2021-10-05T11:31:35.878Z'), 
                        ('d1', 'c2', 102.2, '2021-10-05T12:31:35.878Z'), 
                        ('d1', 'c2', 102.3, '2021-10-05T13:31:35.878Z'), 
                        ('d1', 'c2', 102.4, '2021-10-05T14:31:35.878Z'), 
                        ('d1', 'c2', 102.5, '2021-10-05T15:31:35.878Z'), 
                        ('d2', 'c1', 201.1, '2021-10-05T11:31:35.878Z'), 
                        ('d2', 'c1', 201.2, '2021-10-05T12:31:35.878Z'), 
                        ('d2', 'c1', 201.3, '2021-10-05T13:31:35.878Z'), 
                        ('d2', 'c1', 201.4, '2021-10-05T14:31:35.878Z');
```
Expectation is to have all 13 rows inserted, instead only the first row is and the rest are politely ignored with no error message.

**Comment by bluestreak01** [comment]
fixed in 6.1.3

**Comment by OmgImAlexis** [comment]
@bluestreak01 is there a limit it'll take?

**Comment by OmgImAlexis** [comment]
Also when you close an issue can you please link to the associated release or commits instead of just writing the version number?

**Comment by bluestreak01** [comment]
> @bluestreak01 is there a limit it'll take?

This insert is not parsed as a stream and is limited by receive buffer size depending on the medium:

- HTTP: `http.receive.buffer.size` - 1MB
- PostgreSQL:  `pg.recv.buffer.size` - 1MB

It is not recommended to use this method to insert large data volumes

**Comment by bluestreak01** [comment]
> Also when you close an issue can you please link to the associated release or commits instead of just writing the version number?

We have a lot of broken processes and instead of complaining please help us by linking correct release. What I had provided is not ambiguous. 

https://github.com/questdb/questdb/releases/tag/6.1.3
