### ISSUE TITLE
Sample by fill(null) cannot work with a list

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1480]
When computing multiple aggregates, such as 

```sql
SELECT ts, min(price) min, avg(price) average
FROM prices
SAMPLE BY 1h
FILL(null, 10);
```

I should be able to fill each one independently. However, I get this error:

![image](https://user-images.githubusercontent.com/7276403/138903882-55719d0d-9e69-484f-b845-35967815dffd.png)

The fix is to fill both aggregates with `null` using:

```sql
SELECT ts, min(price) min, avg(price) average
FROM prices
SAMPLE BY 1h
FILL(null);
```

My expectation that the first example should also work, e.g. `fill(null)` works, `fill(null, <value>)` does not, but should

**Comment by glasstiger** [comment]
Separate fill value per aggregate field is supported.
Problem seems to be that null is not supported when a list of fill values are provided, null can stand only on its own and used for all aggregates.

Supported:
fill(null) - null is used as fill value for both aggregate fields
fill(5.0, 10.0) - 5.0 and 10.0 are used as fill values for the two aggregate fields respectively

Not supported:
fill(null, 10.0) - null and number type cannot mix, server tries to interpret null as a number, hence the "invalid number: null" error message

Solution is to add support for null in the list of fill values.
