### ISSUE TITLE
Refresh button in the grid does not execute a correct query

### ISSUE THREAD

**Issue by insmac** [questdb/questdb#1482]
<img width="306" alt="CleanShot 2021-10-27 at 12 18 52@2x" src="https://user-images.githubusercontent.com/1871646/139047417-be365eb0-8046-4a34-be5a-ee06820a8a44.png">

The `Refresh` button does not refresh the query that resulted in the current data set visible in the grid, it takes the last cursor position in the editor instead.

Additionally, `Refresh` should be disabled if no query has been executed (i.e. on page load).

**Comment by OmgImAlexis** [comment]
@insmac is there an open issue for the same thing with the "run" not executing the correct query?

**Comment by insmac** [comment]
Fixed in #1524
