### ISSUE TITLE
Collapsible table list

### ISSUE THREAD

**Issue by insmac** [questdb/questdb#1486]
### Is your feature request related to a problem?

Add an ability to collapse the table list on the top left so that more spaces is given to the SQL editor.

### Describe the solution you'd like.

1. Allow the vertical divider to go all the way to the left (in a similar fashion to left sidebar behaviour in Slack app) so that it would collapse the Table panel and display a relevant icon (keep the "storage" icon in place so that when clicked it'll expand to a default (fallback) width. 
2. Save the state of the pane in local storage.

**Comment by enolal826** [comment]
I'm working on this one
