### ISSUE TITLE
Results grid: migrate to React

### ISSUE THREAD

**Issue by insmac** [questdb/questdb#1487]
### Is your feature request related to a problem?

The current grid is a in-house custom system developed with the help of jQuery. To unify the application codebase it needs to be ported to React keeping the current look and feel and ideally extending its feature set.

It should be a solution that can handle variable row height optionally, so that it can be reused in other parts of the application (i.e. table listing) if needed.

- [ ] Implement a well-maintained and stable, modern React virtual list/grid library. Ideally it should be a solution that supports horizontal virtualization as well.
- [ ] Implement edit-in-place (disabled for now) that will allow `UPDATE` in the future.

### Describe the solution you'd like.

Maintain the current look and behaviour, but use React only.

**Comment by bluestreak01** [comment]
Superseded by 

https://github.com/questdb/questdb/issues/1698
and
https://github.com/questdb/questdb/issues/1699
