### ISSUE TITLE
Unable to delete partition when table is in use

### ISSUE THREAD

**Issue by Zandut** [questdb/questdb#1489]
### Describe the bug

I have a service to insert realtime data. I am using InfluxDB Line Protocol. When I want to drop old partition, I got an error "Table could not be altered, table busy". Can you explain, what's going on ? and should I do ?

### Environment

```markdown
- **QuestDB version**: 6.0.7.1
- **OS**: Ubuntu 20.04
- **Browser**: Firefox 92.0 (64-Bit)
```

### Additional context

This is my error
![image](https://user-images.githubusercontent.com/5546437/139189594-7f6d5a48-6154-4d75-be94-5d4a2a5e5359.png)

This is my list partition folder
![image](https://user-images.githubusercontent.com/5546437/139189682-34e3cbdd-cb50-4b7a-b4ea-4aaf5594350c.png)

**Comment by bluestreak01** [comment]
fixed here https://github.com/questdb/questdb/pull/1504
