### ISSUE TITLE
"Invalid metadata" error message when running queries after upgrading 6.1

### ISSUE THREAD

**Issue by Elpatii** [questdb/questdb#1493]
### Describe the bug

Hello,

After upgrading QuestDB to the latest version (`6.1`), my 2 databases are unusable.
I can't even make a `SELECT` inside it: If I go the webpage, and just type the database name (or `SELECT * FROM`) and run the query, I get this error message:
`[0]: Invalid metadata at fd=17. Invalid column type 0 at [7]`

Or even this message on another database:
`[0]: Invalid metadata at fd=18. NULL column name at [1]`

I have also one old database I have not modified since few months and I get also:
`[0]: Invalid metadata at fd=17. NULL column name at [1]`

I have tried to reverse my Docker image to 6.0.9, but I get en error when running a query on databases that the version doesn't match (of course).
I have tried to insert datas inside databases, but I get same error message.

### To reproduce

1. Upgrade from 6.0.9 to 6.1
2. Run a query on database
3. Get the error message `[0]: Invalid metadata at fd=`

### Expected Behavior

Query run normally.

### Environment

```markdown
- **QuestDB version**:6.1
- **OS**: Ubuntu 20.04.2 (docker)
- **Browser**: Google Chrome 95.0.4638.54 (64 bits)
```

### Additional context

Logs of a query:
```
2021-10-29T07:54:09.549722Z I i.q.c.h.p.JsonQueryProcessorState [16] exec [q='SELECT * FROM crypto_market']
2021-10-29T07:54:09.549750Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-3, sql=SELECT * FROM crypto_market]
2021-10-29T07:54:09.549957Z I i.q.c.p.ReaderPool open 'crypto_market' [at=0:0]
2021-10-29T07:54:09.550235Z I i.q.c.h.p.JsonQueryProcessorState [16] syntax-error [q=`SELECT * FROM crypto_market`, at=14, message=`[0]: Invalid metadata at fd=17. Invalid column type 0 at [7]`]
2021-10-29T07:54:09.551893Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=16, lastRequestBytesSent=322, nCompletedRequests=45, totalBytesSent=119043]
```

**Comment by bluestreak01** [comment]
It is all good, thank you very much! We found and fixed problem with the upgrade process. Other than upgrade 6.1 is good to go.

**Comment by Elpatii** [comment]
Nice!
How do I resolve my databases? 
Do you will upgrade the Docker image and I just need to update to this one?

**Comment by bluestreak01** [comment]
If your tables are in working order now I would suggest you remove `_upgrade` file and just update to 6.1.1. All should be fixed

**Comment by Elpatii** [comment]
I'm not sure to understand.
I have removed `_upgrade.d` file and starting my container with the new `6.1.1` Docker image, but the issue is the same when I try to manipulate my databases.
`[0]: Invalid metadata at fd=17. NULL column name at [1]` for example.
