### ISSUE TITLE
Support jdk17

### ISSUE THREAD

**Issue by bratseth** [questdb/questdb#1503]
### Describe the solution you'd like.

jdk11 is getting really old and we need to move on.

**Comment by bjorncs** [comment]
Parts of the code base is incompatible with JDK17. The `io.questdb.std.BytecodeAssembler` class in `core` uses `Unsafe.defineAnonymousClass` that was deprecated in JDK15 and removed in JDK17. Its replacement, [JEP 371 Hidden Classes](https://openjdk.java.net/jeps/371), was introduced in JDK15.

**Comment by bluestreak01** [comment]
thank you guys! What is your timeline for moving to JDK17. The issue I see is that we would have maintain compatibility with JDK8, JDK11 and JDK17

**Comment by mpolden** [comment]
Our goal is this quarter.

**Comment by bluestreak01** [comment]
we should be able to release JDK17 support next week

**Comment by bluestreak01** [comment]
Guys, although support is there, but we find JDK17 very unstable, for example:

```
2022-01-06T16:11:37.7744970Z V  [libjvm.dylib+0xa54895]  _ZN19ConcurrentHashTableI17SymbolTableConfigL8MEMFLAGS10EE25do_bulk_delete_locked_forI22SymbolTableDeleteCheck19SymbolTableDoDeleteEEvP6ThreadmmRT_RT0_b+0x125
```

Just random crashes, also it drags vulnerabilities we don't want to see:

![image](https://user-images.githubusercontent.com/7276403/148424400-ef2dbc8d-8d78-4710-ab4c-f9a640fd3d81.png)
