### ISSUE TITLE
Additional syntax for SYMBOL-type column declarations

### ISSUE THREAD

**Issue by marregui** [questdb/questdb#1514]
### Is your feature request related to a problem?

Following https://questdb.io/docs/reference/sql/create-table, this statement:

```sql
CREATE TABLE tab (
    id SYMBOL capacity 100 cache index capacity 4,
    ts timestamp
)
```

### Describe the solution you'd like.

This would be more readable:

```sql
CREATE TABLE tab (
    id SYMBOL(100, 4, true, true),
    ts timestamp
)
```

Geohash columns already have parens syntax for column definitions:

```sql
CREATE TABLE teb (
    short_geohash GEOHASH(15b),
    ts timestamp
)
```

It would be nice if all these syntax alternatives were available for SYMBOL:

```sql
CREATE TABLE tib (
    s0 SYMBOL capacity 100 cache index capacity 4,
    s1 SYMBOL(100, 4, true, true),
    s3 SYMBOL(100, 4, true),
    s4 SYMBOL(100, 4),
    s5 SYMBOL(),
    s6 SYMBOL,
    ts TIMESTAMP  
)

-- arg0: sym.capacity
-- arg1: idx.capacity
-- arg2: cached
-- arg3: indexed
```
(**assuming**:
- cairo.default.symbol.cache.flag=true
- cairo.default.symbol.capacity=100
- cairo.index.value.block.size=4)

**Comment by Twilight-Shuxin** [comment]
Hi, I'm not so sure whether I'm able to apply for these issues already in the TO-DO list? I have read the code of questDB, and I think I'm able to acheive this feature by modifying the parser of CREAT TABLE statements. If help is welcomed, I'd love to give it a try.

**Comment by marregui** [comment]
hi @Twilight-Shuxin I hope all is well with you, happy new year of the rabbit!.

I wanted to thank you for contributing to this feature, your pull request was great!!, I hope that you keep contributting. 
I will confess, now that I have the power of retrospective, and 18 months on the role, that I was naive in asking for this feature, as it indeed makes the SQL more confusing. With your permision I will close this issue, and will store the PR https://github.com/questdb/questdb/pull/2057 .

AND!! please do claim swag here https://docs.google.com/forms/d/e/1FAIpQLSfI3VUwXpHT1TbZYjUkYFQpuyfhWicWu2zA0NBGP0pO3ImITA/viewform 

Kind regards

**Comment by Twilight-Shuxin** [comment]
> hi @Twilight-Shuxin I hope all is well with you, happy new year of the rabbit!.
> 
> I wanted to thank you for contributing to this feature, your pull request was great!!, I hope that you keep contributting. I will confess, now that I have the power of retrospective, and 18 months on the role, that I was naive in asking for this feature, as it indeed makes the SQL more confusing. With your permision I will close this issue, and will store the PR #2057 .
> 
> AND!! please do claim swag here https://docs.google.com/forms/d/e/1FAIpQLSfI3VUwXpHT1TbZYjUkYFQpuyfhWicWu2zA0NBGP0pO3ImITA/viewform
> 
> Kind regards

No problem, all best wishes for this project~ Happy New Year to you as well!
