### ISSUE TITLE
Can't connect to QuestDB using Python and psycopg2 on Windows 10

### ISSUE THREAD

**Issue by bugfoot** [questdb/questdb#1517]
### Describe the bug

Trying to connect to an up and running QuestDB local instance on Windows 10 using the Python code found in the [official documentation](https://questdb.io/docs/develop/connect#postgres-compatibility) results in:

```
Error while connecting to QuestDB using PostgreSQL protocol server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

I tried increasing the timeout (`http.keep-alive.timeout`) in _server.conf_ to no avail.

### To reproduce

1. Download _questdb-6.0.9-rt-windows-amd64.tar_ from the [official download page](https://questdb.io/get-questdb/)
2. Extract .tar file downloaded in step 1. using elevated ("Run as Administrator") command prompt via `tar -xvzf C:\Users\<username>\Downloads\questdb-6.0.9-rt-windows-amd64.tar -C C:\Windows\System32\questdb`. A prerequisite is to create a folder named _questdb_ under _C:\Windows\System32_. I tried other locations too, and got the same result.
3. Navigate to _C:\Windows\System32\questdb\bin_ in an elevated command prompt and run `questdb.exe install`, then `questdb.exe start`.
4. Verify that QuestDB is running by typing `questdb.exe status` in command prompt, which results in in "Service QuestDB is RUNNING". The running service can also be seen in services app and the web console at http://localhost:9000/ is working as expected.
5. Using `netstat -ab` in command prompt check that TCP communication for JAVA.EXE at 127.0.0.1:8812 is ESTABLISHED.
6. Run the Python code which tries to connect to QuestDB via its Postgres endpoint as found in the [official documentation](https://questdb.io/docs/develop/connect#postgres-compatibility).

### Expected Behavior

Python connection using psycopg2 to QuestDB via its Postgres protocol is successful, with details of its DSN parameters printed, and the server version retrieved.

### Environment

```markdown
- **QuestDB version**: questdb-6.0.9-rt-windows-amd64
- **OS**: Windows 10 Home Version 21H1, OS build 19043.1288
- **Browser**: Microsoft Edge Version 95.0.1020.40 (Official build) (64-bit)
- **Python**: 3.8.5
- **psycopg2**: 2.8.6
```

**Comment by bluestreak01** [comment]
I just tried with 6.0.9 and `master`, cannot reproduce this issue unfortunately. My python is `3.8.10` but i doubt it makes a difference. Windows version is Pro:

![image](https://user-images.githubusercontent.com/7276403/140394160-6b55e5e1-e38d-4e50-8120-d329f610f9ff.png)

Can we perhaps grab QuestDB's log ? I'm sure there lies the reason.

**Comment by bugfoot** [comment]
@bluestreak01 I would love to, but could not locate where the log file. I did not find any file with name containing _log_ either in _questdb_ nor in _qdbroot_ folders. Where should it be by default in Windows? Maybe I need to explicity activate it in the conf file?

**Comment by bugfoot** [comment]
@bluestreak01 Could you or anybody please help me find the log files? I just can't find them either in my Windows 10 nor in my Ubuntu setup.

**Comment by Joe-TheBro** [comment]
These are the logs, I believe I'm experiencing a similar issue.

2022-01-29T19:09:36.843160Z I server-main os scheduled [name=questdb-worker-6]
2022-01-29T19:09:36.898575Z A server-main enjoy
2022-01-29T19:09:57.975787Z D pg-server epoll [n=1]
2022-01-29T19:09:57.975934Z I pg-server connected [ip=___.___.___.___, fd=67]
2022-01-29T19:09:57.975984Z D pg-server pending [row=0, fd=67]
2022-01-29T19:09:57.976041Z D i.q.c.p.PGConnectionContext prepare for new query
2022-01-29T19:09:57.986178Z D pg-server epoll [n=1]
2022-01-29T19:09:57.986271Z D pg-server fired [fd=67, op=1, pos=0]
2022-01-29T19:09:57.986428Z D i.q.c.p.PGConnectionContext recv [n=8]
2022-01-29T19:09:57.986473Z E i.q.c.p.PGConnectionContext unknown init message [protocol=80877104]
2022-01-29T19:09:57.986582Z I pg-server scheduling disconnect [fd=67, reason=7]
2022-01-29T19:09:57.986672Z I pg-server disconnected [ip=___.___.___.___, fd=67, src=queue]
2022-01-29T19:09:57.986745Z D i.q.c.p.PGConnectionContext prepare for new query
2022-01-29T19:09:57.986788Z D i.q.c.p.PGWireServer pushed

Hope this helps!

**Comment by ideoma** [comment]
This looks like GSS encryption request which QuestDB does not support.

Try to disable encryptions in connection 

```
    connection = pg.connect(user="admin",
                            password="quest",
                            host="127.0.0.1",
                            port="8812",
                            database="qdb",
                           gssencmode="disable",  sslmode="disable")
```

**Comment by Joe-TheBro** [comment]
Maybe, I'll try it later as I'm working right now and will leave a comment as to the results.

**Comment by Joe-TheBro** [comment]
Hello! Here to update this thread, I can confirm that after editing code to remove GSS encryption requests, requests do succeed. 

 ```
connection = psy.connect(user="admin",
                                  password="quest",
                                  hostaddr="___.___.___.___",
                                  port="8812",
                                  dbname="qdb",
                                  gssencmode="disable",  
                                  sslmode="disable")
```
I would suggest that going forward that the reference code on the [questdb.io](https://questdb.io/docs/develop/connect/) be updated to work out-of-box so people don't have anymore issues, thanks @ideoma for the help!

**Comment by bugfoot** [comment]
I can also confirm that disabling `gssencmode` and `sslmode` works on Windows. Thanks @ideoma! 

I'm happy to update the documentation. Should I create a spearate issue for that?
