### ISSUE TITLE
QuestDB demo does not work at all.

### ISSUE THREAD

**Issue by alexey-milovidov** [questdb/questdb#1525]
### Describe the bug

I'm trying to run Q4 from https://tech.marksblogg.com/benchmarks.html

```
SELECT passenger_count, year(pickup_datetime) AS year, round(trip_distance) AS distance, count(*) AS c
FROM trips
GROUP BY passenger_count, year, distance
ORDER BY year, c DESC
```

It is running for about ten seconds and then gives
```
QuestDB is not reachable [503]
```

### To reproduce

See above.

### Expected Behavior

The claim

> Query our demo dataset with 1.6 billion rows in milliseconds

from the QuestDB front page should be more real.

### Environment

```markdown
- **QuestDB 6.0.9**:
```

**Comment by bluestreak01** [comment]
Thank you for reporting the issue Alexey 👍 we will fix that asap

**Comment by vaisov** [comment]
how soon asap looks like? It's middle of March now :)

**Comment by alexey-milovidov** [comment]
It is still relevant. The same error.

**Comment by alexey-milovidov** [comment]
I checked today, and it gives the same error.

**Comment by marregui** [comment]
The trips table has `1634599313` rows as of today (1.6 thousand million rows).

The query:

```sql
EXPLAIN SELECT passenger_count, year(pickup_datetime) AS year, round(trip_distance) AS distance, count(*) AS c
FROM trips
GROUP BY passenger_count, year, distance
ORDER BY year, c DESC
```

would be executed according to this plan:

```bash
Sort light
  keys: [year, c desc]
    GroupBy vectorized: false
      keys: [passenger_count,year,distance]
      values: [count(*)]
        VirtualRecord
          functions: [passenger_count,year(pickup_datetime),round(trip_distance)]
            DataFrame
                Row forward scan
                Frame forward scan on: trips
```

full scan, and it timesout. I am afraid the size of the table, and the nature of the query, result in QuestDB choking.

Would it be unreasonable to adapt the query so that you dig the information for a particular year instead:

```sql
SELECT passenger_count, year(pickup_datetime) AS year, round(trip_distance) AS distance, count(*) AS c
FROM trips
WHERE year(pickup_datetime) = '2009'
GROUP BY passenger_count, year, distance
ORDER BY year, c DESC
```

**Comment by puzpuzpuz** [comment]
> I checked again, but it does not work with the same error

Thanks for the update! We're going to extend our parallel query execution framework to more GROUP BY cases. So, the query should become faster in one of the next releases. I'll post an update here once this happens.

**Comment by puzpuzpuz** [comment]
@alexey-milovidov thanks for your patience. The query works on the latest release, so I'm closing this issue. Please feel free to reopen it if something is still wrong.

![Screenshot from 2024-01-05 20-54-40](https://github.com/questdb/questdb/assets/37772591/be131290-d341-49e5-aad8-b80441c61be4)
