### ISSUE TITLE
Java SE 11 Support

### ISSUE THREAD

**Issue by l2dy** [questdb/questdb#154]
**Is your feature request related to a problem? Please describe.**
> Java versions above 8 are not yet supported.

**Describe the solution you'd like**
Support at least Java SE 11 (LTS).

**Comment by bluestreak01** [comment]
Our release jar can be used with Java11 if this solves your immediate problem?

**Comment by igor-suhorukov** [comment]
Hi @l2dy thank you for issue.
I am not a core member of this project. But from my point of view this project should migrate from Unsafe class usage to JEP 370 and future release of Project Panama to be comparable with future version of java. In long term support migration to Java SE 11 is not a right choose

**Comment by l2dy** [comment]
> Our release jar can be used with Java11 if this solves your immediate problem?

Thanks for the clarification, you may want to update the [docs](https://www.questdb.io/docs/installFromBinary) to reflect that.

This is supposed to be a tracking issue for Java 11 support. If there is no intention to support it, feel free to close the issue instead.

**Comment by bluestreak01** [comment]
That’s ok to keep the issue. We do have few obstacles we need to overcome buts let’s track progress here.

We will update the docs!
