### ISSUE TITLE
Table listing: implement grouping via Tree structure

### ISSUE THREAD

**Issue by insmac** [questdb/questdb#1541]
### Is your feature request related to a problem?

Currently the list of columns for each table (visible when table name is clicked upon) is a flat list that does not provide ability to show other data (i.e. [symbols](https://questdb.io/docs/concept/symbol/), [indexes](https://questdb.io/docs/concept/indexes/) etc). It would be great to have an ability to show additional information when the particular table is expanded.

### Describe the solution you'd like.

- Implement a [Tree](https://ant.design/components/tree/#header)-like component that has the ability to load data on demand (this is currently done in columns list). It doesn't have to be a multi-purpose library, it might be enough to augment the current behaviour to allow for multiple groups (two levels of nesting instead of one as it is now).

This is a sample implementation in [PopSQL](https://popsql.com) online editor as a visual reference:
<img width="178" alt="CleanShot 2021-11-08 at 16 22 58@2x" src="https://user-images.githubusercontent.com/1871646/140878150-862ee720-d71e-4c01-898e-2fe392f5121f.png">

- Make `Columns` group expanded by default. Additional groups are unnecessary for the initial implementation.

**Comment by argshook** [comment]
Hello! The implementation in #1549 seems great but is getting stale, so i'd like to take it 
 over. However, i'm not sure what is the expected UI, this issue mentions symbols, indexes and etc, and i wonder what is the etc, where the data can be taken from?

@insmac maybe you're in the loop and can provide more details or hints?
