### ISSUE TITLE
Update UI part

### ISSUE THREAD

**Issue by djKooks** [questdb/questdb#156]
**Is your feature request related to a problem? Please describe.**
Hello
This is not a problem, just question.
Seems ui part has been a long time(not SPA, using `bower` for package manager...) from first implementation, do you have plan of refactoring?

**Describe the solution you'd like**
Using modern framework(React, Vue, Angular...no limitation)

How do you think?

Thanks.

**Comment by bluestreak01** [comment]
We would welcome help here, it is indeed not up to date with JS tech, but to be fair nothing can keep up with that.

Perhaps we could address usability issues or at least start with some symptoms  :)

**Comment by djKooks** [comment]
@bluestreak01 okay~please update an issue if you have plan for refactoring 🙇‍♂️
