### ISSUE TITLE
environment variables in docker-compose not working

### ISSUE THREAD

**Issue by Zapfmeister** [questdb/questdb#1569]
### Describe the bug

Im trying to use the QBD_ environment variables in order to overwrite certain settings.
The variable gets set in the docker container, but it has no effect.

I tried it with:

QBD_PG_ENABLED=false
QBD_TELEMETRY_ENABLED=false

### To reproduce

I published my config here:
https://github.com/Zapfmeister/questdb_compose
git clone https://github.com/Zapfmeister/questdb_compose
docker-compose up

### Expected Behavior

Expecting the variables to apply as described here:

https://questdb.io/docs/reference/configuration#environment-variables-1

### Environment

```markdown
- **QuestDB version**: 6.1.1
- **OS**: docker
- **Browser**: not relevant
```

**Comment by bluestreak01** [comment]
`QBD` -> `QDB`

**Comment by Zapfmeister** [comment]
Oh no. Im so sorry. Thanks a lot
