### ISSUE TITLE
CREATE TABLE IF NOT EXISTS produces SqlException: [27] cannot acquire table lock [lockedReason=busyReader]

### ISSUE THREAD

**Issue by zhmaeff** [questdb/questdb#1575]
### Describe the bug

Concurrent writes and reads lead to `io.questdb.griffin.SqlException: [27] cannot acquire table lock [lockedReason=busyReader]` if `CREATE TABLE IF NOT EXISTS` SQL is called before each `TableWriter#commit`

### To reproduce

1. Clone https://github.com/zhmaeff/questdb-reproducer
2. Run `QuestdbReproducerApplicationTests#exceptionsDuringConcurrentWritesAndReads` test
3. Open `Test Results - QuestdbReproducerApplicationTests_exceptionsDuringConcurrentWritesAndReads.html` in your browser to see one of my exported test results from IntelliJ IDEA.

NOTE: There is also `QuestdbReproducerApplicationTests#noExceptionsDuringConcurrentWritesAndReads` test, where `CREATE TABLE IF NOT EXISTS` is called only once before all writes. In this scenario, there are no exceptions.

### Expected Behavior

No exceptions during concurrent writes and reads using Java Embedded API and SQL

### Environment

```markdown
- **QuestDB version**: 6.1.1-jdk8
- **OS**: macOS Monterey 12.0.1
- **Browser**: N/A
```

### Additional context

Reproducer repo: https://github.com/zhmaeff/questdb-reproducer

**Comment by puzpuzpuz** [comment]
Many thanks for the reproducer!
