### ISSUE TITLE
TLS supported?

### ISSUE THREAD

**Issue by gcomte** [questdb/questdb#1589]
### Describe the bug

When using the Rust library [tokio-postgres-rutls](https://crates.io/crates/tokio-postgres-rustls) to connect to a QuestDB instance, a connection string as such is required:

`sslmode=require host=localhost port=8812 user=root password=passw0rd dbname=qdb`

However, using setting `sslmode=require` gives me the following error:
`error performing TLS handshake: server does not support TLS`

If I remove `sslmode=require` from the connection string, everything works fine. But in this case, does it not encrypt the connection?

### Environment

```markdown
- **QuestDB version**: 6.1.1
- **OS**: Ubuntu 20.04, dockerized QuestDB
```

**Comment by bsmth** [comment]
Hi @gcomte, thanks for opening the issue 🙌🏻 

TLS is not yet supported out of the box, but [pgbouncer](https://www.pgbouncer.org/features.html) might be an option to try in front of QuestDB in the meantime.

**Comment by bsmth** [comment]
I'm going to close this for the moment, as the question appears to be answered. Thanks @gcomte 👍🏻

**Comment by CodeTherapist** [comment]
It's hard to believe that the open-source version still doesn't support TLS in 2025.
I get that TLS is available in the Enterprise edition, but offering only a non-TLS version for open-source feels like a bad joke.
Without TLS, it's simply not viable for any production workload—security shouldn't be a premium feature.
