### ISSUE TITLE
Currently, if a block pattern includes an empty column, it displays a giant inserter button in the editor:

### ISSUE THREAD

**Issue by Rockstar907** [questdb/questdb#1594]
Currently, if a block pattern includes an empty column, it displays a giant inserter button in the editor: 

<img width="1056" alt="Screen Shot 2021-11-18 at 1 13 14 PM" src="https://user-images.githubusercontent.com/1202812/142472886-ad8f7121-8fe1-4040-a935-53b264056e75.png">

This button also appears in the pattern preview: 

<img width="333" alt="Screen Shot 2021-11-18 at 1 11 40 PM" src="https://user-images.githubusercontent.com/1202812/142472967-d028d09e-1c30-433d-a6db-4f2196fe3a67.png">

It generally makes sense to show this inserter in the editor, but it definitely doesn't make much sense to show it in the pattern preview. It only exists to show you that you can insert a block there, but you're not going to be inserting blocks directly within the pattern preview. 

Can we hide this inserter from the block pattern previews?

__Originally posted by @kjellr in https://github.com/WordPress/gutenberg/issues/36625__[]()

**Comment by bluestreak01** [comment]
This is not a correct GitHub repository for such issue

**Comment by ideoma** [comment]
Looks like SPAM

**Comment by Rockstar907** [comment]
Block json color pattern.
