### ISSUE TITLE
Multiple thread write error

### ISSUE THREAD

**Issue by Gszekt** [questdb/questdb#1595]
### Describe the bug

Hello. I used QuestDB 6.1.1 in Springboot. I use one client bean to write data, and the bean is used in 16 threads. When the QuestDb works on CentOS , there is a error 

```
2021-11-17T03:29:22.759826Z E i.q.c.l.t.LineTcpConnectionContext [100] could not process line data [table=gs, msg=could not mmap  [size=12288, offset=0, fd=120, memUsed=3361135068, fileLen=12288], errno=19]
``` 

Then I deploy the QuestDB on Windows 10, version 21H2, I got another error, the log on windows just as the attachment
[stdout-2021-11-19T15-16-53.txt](https://github.com/questdb/questdb/files/7569112/stdout-2021-11-19T15-16-53.txt)
:

On line 231, I find that there is a lot of whitespace at the front of  tablename. 
In addition, the error occurs after my program starts about 40s.

Here is my code:

```
@Autowired
private LineTcpSender sender;

@Override
public void addPoint(HistoryDataDTO hisData) {
    sender.put(getLine(hisData));
}

private CharSequence getLine(HistoryDataDTO hisData) {
    return String.format("%s,tagName=%s,objectName=%s value=%f,quality=\"%s\" %d\n",
            hisData.getTenantName(),
            hisData.getTagName(),
            hisData.getMetricName(),
            Double.parseDouble(hisData.getValue().toString()),
            hisData.getQuality(),
            hisData.getTime() * 1000000);
}
```

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
I don't see any notable errors in the windows log. Do you mind highlighting one please?

On CentOS, that the filesystem type you're writing data to? Errno `19` tells that memory mapping is not supported by the filesystem

**Comment by ideoma** [comment]
What is File System used on CentOS?

It would be more interesting to see more log with error than log without error.

**Comment by Gszekt** [comment]
> I don't see any notable errors in the windows log. Do you mind highlighting one please?
> 
> On CentOS, that the filesystem type you're writing data to? Errno `19` tells that memory mapping is not supported by the filesystem

I am sorry, there is something wrong when I edit the issue. 
I upload the log file. And the filesystem type of data dir is xfs. Thanks !

**Comment by Gszekt** [comment]
> What is File System used on CentOS?
> 
> It would be more interesting to see more log with error than log without error.
I am sorry, there is something wrong when I edit the issue. 
I upload the log file. And the filesystem type of data dir is xfs. Thanks !

**Comment by ideoma** [comment]
We will need to investigate what happens on XFS. Meanwhile if you want to solve it I'd recommend trying EXT4 File System instead of XFS

**Comment by Gszekt** [comment]
> We will need to investigate what happens on XFS. Meanwhile if you want to solve it I'd recommend trying EXT4 File System instead of XFS

Hello , I tried it on EXT4 , but the error still exists. Is there something wrong on my usage ?

`2021-11-22T02:33:49.971145Z E i.q.c.l.t.LineTcpConnectionContext [40] could not process line data [table=�����������������������������������gs, msg=could not mmap  [size=4096, offset=0, fd=128, memUsed=2613275419, fileLen=4096], errno=19]`

And my table name is 'gs' , but it becames '�����������������������������������gs' in the log , maybe it is a bug ?

**Comment by bluestreak01** [comment]
Yes, `����������������������������������������������������������gs` Is definitely the problem. In theory this is what comes on ILP wire. Is there a chance sending application could produce this table name?

**Comment by Gszekt** [comment]
> Yes, `����������������������������������������������������������gs` Is definitely the problem. In theory this is what comes on ILP wire. Is there a chance sending application could produce this table name?

I print all the line message, I find all of them are right. And in this time, the table name is right, but the mmap error still exists. Then I try it again on XFS, the table name is still error. 

EXT4:
![图片](https://user-images.githubusercontent.com/26792853/142829809-a72a8f97-d917-4806-8500-f59ecce2b9c9.png)

XFS:
![图片](https://user-images.githubusercontent.com/26792853/142829917-cc6a66ab-e0c7-411c-8dfd-70d442f491eb.png)

**Comment by bluestreak01** [comment]
I suspect you might be publishing mangled measurement name somehow. It would be good to debug your side.

From our side there is PR to sanitize input: https://github.com/questdb/questdb/pull/1605

**Comment by bluestreak01** [comment]
[questdb-6.1.3-SNAPSHOT-no-jre-bin.tar.gz](https://github.com/questdb/questdb/files/7581974/questdb-6.1.3-SNAPSHOT-no-jre-bin.tar.gz)

This is a `no-jre` build with the sanitizer for your to try
