### ISSUE TITLE
Creating a column called "timestamp" causes issues

### ISSUE THREAD

**Issue by OmgImAlexis** [questdb/questdb#1599]
### Describe the bug

If you create a column called timestamp questdb won't use that for the timestamp when passing a ILP line like below. It remains null. I would have expected when creating the column manually questdb would use it for the `1636845963061000` timestamp below.

```
hits, id=7cefead1-5d29-4eb8-b6df-076f8f55c75e,url=https://google.com,ip="127.0.0.2",property=omgimalexis 1636845963061000
```

The other issue is if you have a column called timestamp trying to use `order by timestamp` or `order by ts` in the web ui just told me both columns don't exist.

Ref: https://questdb.slack.com/archives/C1NFJEER0/p1637391622392200?thread_ts=1636846069.308100&cid=C1NFJEER0

### To reproduce

```SQL
CREATE TABLE servers (id STRING, timestamp TIMESTAMP);
```

Then use the ILP line from above.

### Expected Behavior

The column to be used for the timestamp.

### Environment

- **QuestDB version**: latest
- **OS**: Docker
- **Browser**:

**Comment by bluestreak01** [comment]
we to require timestamp to be explicitly nominated:

```sql
CREATE TABLE servers (id STRING, timestamp TIMESTAMP) timestamp(timestamp);
```

it is verbose but its better to be explicit here

**Comment by bluestreak01** [comment]
Feel free to re-open if the above doesn’t solve the problem

**Comment by OmgImAlexis** [comment]
That doesn't "solve the problem". If there's a column called that then it should use it. This in unintuitive for users.

**Comment by bluestreak01** [comment]
I feel implicit use of timestamp like this leads to:

- order enforcement when not expected
- Ambiguity when column name is not “timestamp”
- Ambiguity when there are multiple columns of type `timestamp`
- there is no feedback from “create table”


This matter is highly subjective, what is intuitive to one individual is not intuitive to another. I personally feel it is better to be explicit about dedicated timestamp at expense of being verbose.
