### ISSUE TITLE
pgadmin and postgres bulk inserts

### ISSUE THREAD

**Issue by rosisoft** [questdb/questdb#1604]
### Describe the solution you'd like.

Support for pgadmin and postgres bulk inserts woudl be high on my priority list. pgadmin makes it easy for developer to use an already familiar tool and postgres bulk inserts would allow to faster inserts into questdb.

### Describe alternatives you've considered.

inflix line protocol is the recommended approach for inserts, but I think it would be better to have one technology for reads and writes. It's also hard to open 3 different ports for just one db.

**Comment by bsmth** [comment]
Hi @rosisoft it looks like this has been resolved in https://github.com/questdb/questdb/issues/593. I'm going to close this one for now, feel free to open a new issue for pgadmin if there are still compatibility issues.

Thank you :)
