### ISSUE TITLE
Incorrect line protocol usage causes SEGFAULT or corruption of timestamps every other row

### ISSUE THREAD

**Issue by damiendr** [questdb/questdb#1608]
### Describe the bug

Consider a table that declares one of its columns as a designated timestamp.

After reading the [ILP guide](https://questdb.io/docs/guides/influxdb-line-protocol/), it's not obvious how to write valid ILP messages to insert data into the table:

- (a) include the designated timestamp as a key-value pair, omiting the ILP timestamp?
- (b) include the designated timestamp as the ILP timestamp, omiting the key-value pair?
- (c) include the designated timestamp twice, once for the ILP timestamp and one for the key-value pair?

On QuestDB 6.1.1 the correct answer seems to be (b). Unfortunately the other two don't generate errors but cause either silent timestamp corruption or a crash.

- (a) strangely causes _every other_ designated timestamp (on alternating rows) to be set to the current time instead of the given value, a bit like the issue reported in #548
- (c) works the first time, but then causes the crash reported in #1338

### To reproduce

```
CREATE TABLE test(time_close TIMESTAMP, number LONG) timestamp(time_close)
```

Option (a):
```
test, number=1i,time_close=1466111018337510t\n
test, number=2i,time_close=1466111018337520t\n
test, number=3i,time_close=1466111018337530t\n
test, number=4i,time_close=1466111018337540t\n
```
Option (b):
```
test, number=1i 1466111018337510000\n
test, number=2i 1466111018337520000\n
test, number=3i 1466111018337530000\n
test, number=4i 1466111018337540000\n
```
Option (c):
```
test, number=1i,time_close=1466111018337510 1466111018337510000\n
test, number=2i,time_close=1466111018337520 1466111018337520000\n
test, number=3i,time_close=1466111018337530 1466111018337530000\n
test, number=4i,time_close=1466111018337540 1466111018337540000\n
```

### Expected Behavior

Ideally the guide should cover the case of designated timestamps.
QuestDB should also throw an error on ingesting these malformed ILP messages or accept them without crashing or corruption.

### Environment

```markdown
- **QuestDB version**: 6.1.1
- **OS**: MacOS 12.0.1
```

**Comment by ideoma** [comment]
It's same as #1213
