### ISSUE TITLE
when will questdb release horizontally scalable?

### ISSUE THREAD

**Issue by shuitai** [questdb/questdb#1613]

**Comment by bsmth** [comment]
Hi @shuitai thanks for asking 🙌🏻 

Horizontal scalability falls under the scope of replication which is planned for Q1 2022. Here is our product roadmap for more information:
https://github.com/orgs/questdb/projects/1/views/5

I'm closing this for the moment as you can ask questions on the [roadmap issue](https://github.com/questdb/roadmap/issues/8) if you like :)

Thank you!
