### ISSUE TITLE
Double parsing produce wrong result when input starts with 2^63

### ISSUE THREAD

**Issue by bziobrowski** [questdb/questdb#1615]
### Describe the bug

Parsing of double number fails when input starts with 9223372036854775808 (max long value without minus sign) and returns 0. 

I've debugged code and it looks like Numbers.parseDouble():664 

if (val < LONG_OVERFLOW_MAX) {
// val * 10 + (c - '0')
val = (val << 3) + (val << 1) + (c - '0');

doesn't detect overlow for val =  922337203685477580
and changes val to -9223372036854775808 (max long value)
on next iteration it clears val ( both shifts produce 0 ) and starts 'from scratch' . 

### To reproduce

1. Go to web console
2. Type 
create table testd (d double);
insert into testd values ( 9223372036854775808.0 );
insert into testd values ( 9223372036854775808123.0 );
select * from testd ; 
3. result is
           0 
        123

### Expected Behavior

Approximate double values should be returned.

### Environment

```markdown
- **QuestDB version**:6.1.3-SNAPSHOT
- **OS**:Windows 10
- **Browser**:Chrome 96
```

**Comment by bolekz** [comment]
Same thing happens with Numbers.parseFloat("2147483648.0") .

**Comment by bolekz** [comment]
Additional issue with double parsing - when input is an integer with more than 19 digits then Numbers.parseDouble incorrectly calculates exponent as 18 .

Example : 

System.out.println(Numbers.parseDouble("82233720368547758071234567") );

prints 8.2233720368547758E18
