### ISSUE TITLE
Refactor error handling

### ISSUE THREAD

**Issue by rstreics** [questdb/questdb#1616]
### Describe the bug

At the moment any sql statement that doesn't produce successful results produces "E" logs.
Error should reserved for the failure of system, general problems with process or something that requires live human action.
If this no possible alternatively we leave sql error with `E` and for actual critical failure use  `C` critical or `F` failure.

Example of things that are reported as errors
* `inconvertible types: LONG -> LONG256`
* `PGConnectionContext error [pos=148, msg=')' expected`
* `internal error [q=SHOW COLUMNS FROM 'users2'`
* `table 'users' does not exist`
* `E i.q.TelemetryJob instance`

### To reproduce

n\a

### Environment

```markdown
- **6.0.9**:
```

**Comment by marregui** [comment]
will revisit if it becomes an actual problem. Closing for now.
