### ISSUE TITLE
QuestDb crashed

### ISSUE THREAD

**Issue by Gszekt** [questdb/questdb#1624]
### Describe the bug

I write about 6 billion row into table gs, and when I query the max timestamp, QuestDb crashed.
line.tcp.default.partition.by=DAY, there are about 2.7 billion rows in per partition. 
The QuestDB works runs in docker
Here is the crash log:
[hs_err_pid14091.log](https://github.com/questdb/questdb/files/7616551/hs_err_pid14091.log)

### Environment

```markdown
- **QuestDB version**:6.1.2
- **OS**:CentOS 7  8 Core  20G RAM  100G ext4 hard disk
- **Browser**:
```

**Comment by ideoma** [comment]
Thanks for submitting the issue. This does not look that it will be straightforward to reproduce.

Would be good to see server log if there was any errors during ingestion and the actual query you execute. Also  would be great if you can join our slack at https://slack.questdb.io/ so we can find what is wrong quicker

Alex Pelagenko

**Comment by bluestreak01** [comment]
This issue could give more context perhaps: https://github.com/questdb/questdb/issues/1595

These are different problems, but same use cause.

**Comment by Gszekt** [comment]
> Thanks for submitting the issue. This does not look that it will be straightforward to reproduce.
> 
> Would be good to see server log if there was any errors during ingestion and the actual query you execute. Also would be great if you can join our slack at https://slack.questdb.io/ so we can find what is wrong quicker
> 
> Alex Pelagenko

I change partitioning strategy from DAY to HOUR, QuestDB works well, no crashed !

**Comment by bsmth** [comment]
I'm going to close this one for now. If the problem resurfaces, feel free to reopen the issue or reply here with more details.

Thank you :)
