### ISSUE TITLE
Multi-model Data

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#164]
**Is your feature request related to a problem? Please describe.**

Having a solid relational data model is great but now many data representations are not always relational. So is it possible to expand to other data models?

**Describe the solution you'd like**

So it is possible to support flexible models:

- Relational (which you already have)
- Key-value
- Graph
- Document

**Describe alternatives you've considered**

Many alternative solutions have SQL Ease + NoSQL Agility:

- [EdgeDB](https://edgedb.com/)
- [CrateDB](https://crate.io/)
- [Apache Ignite](https://ignite.apache.org/)
- [Yugabyte](https://www.yugabyte.com/)
- [ArangoDB](https://www.arangodb.com/)
- [OrientDB](https://orientdb.com/)

**Comment by bsmth** [comment]
I'm closing this as it's out of scope with the features we are focusing on at the moment.

If this feature is something you would like to add, you may also contribute directly by submitting a patch - see the [contribution guide](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) for details. :)

Thank you!
