### ISSUE TITLE
group by big table very slow

### ISSUE THREAD

**Issue by l1t1** [questdb/questdb#1641]
### Describe the bug

the table has 10 column and 60M rows.  group by symbol column took 2 min 

### To reproduce

1.download the csv file

"ftp://ftp.nyse.com/Historical Data Samples/DAILY TAQ/EQY_US_ALL_TRADE_200006.zip"

2.  create table
drop table "CT_200006.csv";

873.021 ms
create table "CT_200006.csv" (
SYMBOL   STRING,
  DATE   DATE  ,
  TIME   TIMESTAMP  ,
PRICE   DOUBLE,
  SIZE      INT,
  G127      INT,
  CORR      INT,
  COND     CHAR,
    EX     CHAR,
  TSEQ      INT);
3. imp use curl
D:\timer64 curl -F data=@d:/nyx/CT_200006.csv http://localhost:9000/imp
+-----------------------------------------------------------------------------------------------------------------+
|      Location:  |                                     CT_200006.csv  |        Pattern  | Locale  |      Errors  |
|   Partition by  |                                              NONE  |                 |         |              |
|      Timestamp  |                                              NONE  |                 |         |              |
+-----------------------------------------------------------------------------------------------------------------+
|   Rows handled  |                                          65252260  |                 |         |              |
|  Rows imported  |                                          65252260  |                 |         |              |
+-----------------------------------------------------------------------------------------------------------------+
|              0  |                                            SYMBOL  |                   STRING  |           0  |
|              1  |                                              DATE  |                     DATE  |           0  |
|              2  |                                              TIME  |                TIMESTAMP  |           0  |
|              3  |                                             PRICE  |                   DOUBLE  |           0  |
|              4  |                                              SIZE  |                      INT  |           0  |
|              5  |                                              G127  |                      INT  |           0  |
|              6  |                                              CORR  |                      INT  |           0  |
|              7  |                                              COND  |                     CHAR  |           0  |
|              8  |                                                EX  |                     CHAR  |           0  |
|              9  |                                              TSEQ  |                      INT  |           0  |
+-----------------------------------------------------------------------------------------------------------------+
4. select sum group by too slow
qdb=> select symbol,sum(price) from CT_200006.csv group by symbol order by symbol limit 10;
symbol |       sum
--------+------------------
A      | 7416381.01953125
AA     | 1246970.23828125
AAABB  |          714.375
AABC   |         226.0625
AAC    |      541.3359375
AACB   |       775.984375
AACE   |         8608.375
AAE    |     9300.4140625
AAG    |       1151.03125
AAGP   |      2260.234375
(10 行记录)

时间：113902.190 ms (01:53.902)

### Expected Behavior

get results in less 10 sec. 
same quer of the table in kdb+ 4.0 took 1 sec. 

### Environment

```markdown
- **QuestDB version**:6.1.2
- **OS**:windows7 x64
- **Browser**:
```

### Additional context

my computer 24 cores CPU.  32GB memory.

**Comment by Trolorol** [comment]
Out of curiosity I ran your test, I'm running on a i5 4 cores with 8gb of ram:

With the limit 10:
10 rows in 3.56s Execute: 3.55s Network: 6.36msTotal: 3.56s

Without: 
26 rows in 3.57s Execute: 3.57sNetwork: 6.81msTotal: 3.57s

I'm using questdb in testing for a product and it hadles well 2/3B rows

**Comment by l1t1** [comment]
26  rows is not correct. as quest db automatic recognized the symbol as char type. it should be string. you could create the empty table first to avoid it.

**Comment by l1t1** [comment]
group by left(symbol,1) took 19s.

**Comment by puzpuzpuz** [comment]
Did you try using SYMBOL type for the symbol column? Storage and query execution should be more efficient this way.

**Comment by l1t1** [comment]
c

> Did you try using SYMBOL type for the symbol column? Storage and query execution should be more efficient this way.
after recreate table with symbol SYMBOL,
curl imp returns (52)empty reply from server

**Comment by l1t1** [comment]
> Did you try using SYMBOL type for the symbol column? Storage and query execution should be more efficient this way.

thanks.  it took 3 seconds.
