### ISSUE TITLE
Continuous Queries + Reactive Queries

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#165]
**Is your feature request related to a problem? Please describe.**

Much of current systems have to deal with reactive data and data which continuously change. Currently one has to poll to see data changes and update.

**Describe the solution you'd like**

Make the DB push the changes and new data to the clients.

**Describe alternatives you've considered**

- https://rethinkdb.com/
- https://ksqldb.io/
- https://github.com/pipelinedb/pipelinedb
- https://geode.apache.org/
- https://crate.io/
- https://ignite.apache.org/

**Comment by sirinath** [comment]
Can this be prioritised. This can be done in 2 phases:
1. Add ability to register listeners to DB changes. E.g. if a new row is added to a particular table the listeners will be notified.
2. When query dataset changes notify listeners of new data inserted and data deselected. This would be a little more difficult than 1

**Comment by bluestreak01** [comment]
Hi @sirinath, why should we prioritise this?

**Comment by sirinath** [comment]
For latency sensitive scenarios rerunning queries and polling to see if new data is added is in efficient. So if a result set changes there should be a more efficient way to know what the change is and process the change. Similarly when there are subsequent changes there should be an more efficient way to know this. For low frequency low volume data one can poll the DB and periodically check. If the time between changes are very small and there a is a lot of types of data which will have changes, it is more efficient, I believe if the DB can tell the application what changed so the application process the changed data.

**Comment by bluestreak01** [comment]
This is not a reason to prioritise this work over everything else we are working on. Is there a real person or organisation who have pain point you are describing? Who are they?

**Comment by sirinath** [comment]
We are a small operation with lesser developer bandwidth. This feature would help up free up development overhead in our projects. Reasonable development effort goes into plumbing code for propagating data and events.  If the DB can be central in propagate the events and data as and when there are updates this will help help in this front.

**Comment by bsmth** [comment]
I'm closing this as the functionality requested appears to be described in https://github.com/questdb/questdb/issues/837.

If we have overlooked the feature you would like to add, you may also contribute directly by submitting a patch - see the [contribution guide](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) for details. :)

Thank you!

**Comment by stolsvik** [comment]
@bsmth @bluestreak01 Is this request not directly asking for Postgres NOTIFY?
https://www.postgresql.org/docs/current/sql-notify.html
Also, this answer to DBA StackExchange question "use postgres as MQ?": https://dba.stackexchange.com/a/171142/260819
.. which then also points to the SKIP LOCKED functionality: https://www.enterprisedb.com/blog/what-skip-locked-postgresql-95

The reason for commenting here, is that I was looking for info whether QuestDB implements NOTIFY, and I found this issue. I am intrigued by the mechanical sympathy, no-GC architecture of QuestDB, and was wondering whether it possibly could be tricked into working as an efficient MQ.
