### ISSUE TITLE
SIGSEGV on QuestDB 6.1.2

### ISSUE THREAD

**Issue by bruksnys** [questdb/questdb#1666]
### Describe the bug

We have started encountering segmentation faults on our QuestDB instance this morning.
Unfortunately we're unable to pinpoint exactly what caused them, as neither our configuration nor the environment changed recently. 

### To reproduce

N/A

### Expected Behavior

N/A

### Environment

```markdown
- **QuestDB version**:
OpenJDK Runtime Environment Corretto-11.0.13.8.1 (build 11.0.13+8-LTS)
QuestDB 6.1.2
- **OS**:
CentOS Stream 8
- **Browser**:
N/A
```

### Additional context

https://pastebin.com/uVR9sNC4 - jvm notifying about sigsegv.
https://pastebin.com/D5zGHhUD - crashlog (note - after the initial crashes the instance was restarted, this is the latest one, thus low uptime).

**Comment by bluestreak01** [comment]
this problem could be related to https://github.com/questdb/questdb/issues/1213

**Comment by bruksnys** [comment]
Seems to be resolved via https://github.com/questdb/questdb/pull/1675/files.
