### ISSUE TITLE
Zero or Minimal Connection, Driver & Communication Overhead - Embeddability | Fast IPC

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#167]
Ability to use the DB as an embedded DB than a separate server running in the same JVM and application process as the application.

This will cut the latency and overhead of connecting to the DB and associated overheads. Also, you need not go through a driver.

E.g.

- https://www.h2database.com/html/main.html
- https://db.apache.org/derby/
- http://hsqldb.org/
- https://ignite.apache.org/

If the database st to be shared with multiple application, a fast IPC scheme can also be provided where the DB is accessible through: 

- [Fast Binary Encoding (FBE)](https://chronoxor.github.io/FastBinaryEncoding/)
- [Simple Binary Encoding (SBE)](https://real-logic.github.io/simple-binary-encoding/)
- [gRPC](https://grpc.io/)
- [MessagePack](https://msgpack.org/)
- [Concise Binary Object Representation (CBOR)](http://cbor.io/)

**Comment by bluestreak01** [comment]
QuestDB is already fully embeddable with Java applications with Java-native API.

Does this help? https://www.questdb.io/docs/embeddedJavaAPI

**Comment by sirinath** [comment]
Yes.

This helps.

**Comment by sirinath** [comment]
If I gather you currently have Java API and REST API. Java will be the fastest but restricted to one application. REST API you can have many clients but has a higher overhead. 

I am wondering if there is an interest to introduce a binary scheme or other scheme here many clients can connect while being more efficient than REST. 

The clients may be in the same node or different nodes. 

Perhaps the same node clients may have a more efficient way to communicate perhaps using memory-mapped files or another scheme. 

If the client is another node the communication can be through the efficient binary scheme. 

If the binary scheme is standard with multiple language implementations you can have multiple languages using this without having to write an explicit driver.

**Comment by igor-suhorukov** [comment]
@sirinath embedded is in process usage without network communication. Why do you think that "another node the communication can be through the efficient binary scheme" is embedded use case?

**Comment by bluestreak01** [comment]
Current API allows multiple processes on the same host read the same table. It is also possible to write data from one process while reading concurrently from the other. In other words, existing Java API allows passing data from one process to another

**Comment by sirinath** [comment]
@igor-suhorukov  The embedded use case is addressed I believe. I overlooked this. I am thinking of another 2 use-cases:

1. Different JVMs on the same node with the DB in one JVM and clients on multiple JVMs - As the DB is in another JVM the option would be IPC, RPC or REST of which IPC would be the most efficient
2. Different nodes - RPC scheme may be more efficient than REST

Maybe as per @bluestreak01's comment 1 above is also implemented but not documented.

**Comment by bluestreak01** [comment]
Perhaps we should write up an example inter-process setup. That said, there is no additional effort required to start using data across processes. As long as TableReader and TableWriter use the same directory they work the same way when instances are in the same process or across different processes.

**Comment by sirinath** [comment]
OK.

That leaves the last item when they are in different nodes without a shared file system.

**Comment by bluestreak01** [comment]
this is where REST or PG wire comes in for now

**Comment by sirinath** [comment]
Could to with more documentation and examples on setting up and use of `PG wire`. I guest there might be more higher priority items to tackle, but at some point in performance tuning, see if this is the most efficient that can be achieved? Can FBE or SBE or another scheme result in a performance boost which might be worthwhile?

**Comment by bluestreak01** [comment]
We are building replication feature, which will be highly efficient. Much more so than SBE or the likes. This could be used to distribute date across multiple nodes.

**Comment by sirinath** [comment]
@bluestreak01 I think you nailed it. Looking forward to this feature.

**Comment by bsmth** [comment]
As mentioned in https://github.com/questdb/questdb/issues/167#issuecomment-615909724, It looks like this feature request is covered in the ability to run QuestDB in an embedded capacity (https://questdb.io/docs/reference/api/java-embedded/) so I will close this for the moment.

Thanks for your feedback! :)
