### ISSUE TITLE
Enhanced Own Query Language for QuestDB

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#168]
Hsing SQL which is the standard is a must but expressing nested queries is very awkward. Can we have [EdgeDB/EdgeQL](https://edgedb.com/) style query language as many DBs have their own style?

Ref: 
- [We Can Do Better Than SQL](https://edgedb.com/blog/we-can-do-better-than-sql)
- [Why Graph Will Win](http://blog.terminusdb.com/2020/03/02/why-graph-will-win/)

**Comment by bluestreak01** [comment]
there is no immediate plans to go down the route of EdgeDB with the language.

**Comment by bsmth** [comment]
I'm closing this as it's out of scope with the features we are focusing on at the moment.

If this feature is something you would like to add, you may also contribute directly by submitting a patch - see the [contribution guide](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) for details. :)

Thank you!
