### ISSUE TITLE
Stop sending spam mails! ⛔

### ISSUE THREAD

**Issue by SimonMayerhofer** [questdb/questdb#1682]
Why the hell do you think is it okay to send unasked spam mails just to advertise your project?
I never signed up for this so stop it.

This is my feedback. Stop sending spam. 

![Screenshot_20211214-102255_Firefox](https://user-images.githubusercontent.com/4314302/145970517-46530e0c-1df2-4676-a983-fd587a94b3e7.png)

**Comment by bluestreak01** [comment]
Hi Simon,
Sorry that our email bothered you - that wasn't our intention; we're looking for feedback on our project. Apologies for reaching out

**Comment by SimonMayerhofer** [comment]
Imagine every open source project would do that. You would be getting unwanted mails all the time

**Comment by bluestreak01** [comment]
I understand, we're reviewing how we seek feedback in future
