### ISSUE TITLE
Demo box is slow

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#1683]
### Describe the bug

When I run simple query on demo.questdb.io it takes 3s to compile which is very slow

```sql
select x, y
from long_sequence(100) ls
 join (
  select x as y from long_sequence(100)
) as ls2
on ls.x = ls2.y
```

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
Possible issue with Java Heap pressure.

**Comment by bziobrowski** [comment]
I think it was due to overly high value set for cairo.sql.map.key.capacity that ended up allocating a lot of memory that was then held via cache and sometimes even caused OOM. 
Query takes about 100ms on demo now vs 6 ms on local .
