### ISSUE TITLE
Add SQL function to flush query cache

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#1705]
### Describe the bug

To simplify diagnosing query cache related mem leaks we should add a new SQL function that would evict all entries from all thread-local query caches on the server.
```sql
select flush_query_cache();
```

The function should stay undocumented.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by GothamsJoker** [comment]
Good evening, I would like to work on this issue. I am generally new to contributing so if you have any guidance as to where to start that would be great!

**Comment by puzpuzpuz** [comment]
Hi @GothamsJoker,

This one is a bit tricky, since it requires message queue communication between PG Wire threads. I don't think we have that in place, so this issue may require some changes in the inter-thread communication.

If you don't need this particular feature in your own QuestDB use case, I'd suggest picking up one of [Good first issues](Good first issue).

**Comment by GothamsJoker** [comment]
> Hi @GothamsJoker,
> 
> This one is a bit tricky, since it requires message queue communication between PG Wire threads. I don't think we have that in place, so this issue may require some changes in the inter-thread communication.
> 
> If you don't need this particular feature in your own QuestDB use case, I'd suggest picking up one of [Good first issues](Good first issue).

Thank you, I will take a look there. If anything changes feel free to let me know.
