### ISSUE TITLE
SIMD compensated summation

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#171]
SIMD based implementation for:

ksum() - Kahan summation
nsum() - Neumaier summation

https://en.wikipedia.org/wiki/Kahan_summation_algorithm

**Comment by sirinath** [comment]
Maybe you can have `k1sum` for `Kahan` and `k2sum` for `Klein` where `2` also implies second-order Kahan–Babuska

**Comment by bluestreak01** [comment]
Kahan–Babuska is another name "neumaier" algorithm.

What would help is to identify a dataset where there is significant accuracy improvement for Kahan vs accuracy-naive summation

**Comment by bluestreak01** [comment]
Done
