### ISSUE TITLE
Sample by with interpolation

### ISSUE THREAD

**Issue by CSharpDummy** [questdb/questdb#1712]
This is a standard feature on many time series databases: you query for a number of values during a time range and get a set of interpolated values back at the exact time stamp. Regression is simply a linear interpolation based on the prev and next data point.

**Comment by bluestreak01** [comment]
We support “linear” fill option, which is linear interpolation 

https://questdb.io/docs/reference/sql/sample-by/#fill-options

**Comment by bsmth** [comment]
@CSharpDummy are linear fills able to resolve your issue? I will close this issue, feel free to comment or reopen if this isn't resolved for you.

Thank you :)
