### ISSUE TITLE
Create Table should not allow to create partitioned table without designated timestamp

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#1726]
### To reproduce

```sql
create table pricetable2
(ts timestamp,symbolname SYMBOL CACHE ,price Double,aggregateTradeId Long,firstTradeId Long,lastTradeId Long,buyerMaker Boolean,qty Double) 
partition by day;
```

Executes without error and crates table without designated timestamp partitioned by DAY

### Expected Behavior

Create table query should fail. Partitioning only makes sense on tables with designated timestamps

### Environment

```markdown
- **QuestDB version**:6.1.3
- **OS**:
- **Browser**:
```

**Comment by kocko** [comment]
Hello @ideoma, 

I would like to work on this bug. Could you please assign it to me? 

Thanks

**Comment by kocko** [comment]
#1760

**Comment by bluestreak01** [comment]
Fix had to be rolled back as it somehow lead to memory corruption. To be investigated in detail

**Comment by bluestreak01** [comment]
PR that rolls back the fix is https://github.com/questdb/questdb/pull/1770
