### ISSUE TITLE
create table as `select` does not correctly report duplicate column names to user

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#1749]
### Describe the bug

I'm trying to create table like this:

```sql
create table all as (
    select
        rnd_byte() b,
        rnd_short() sh,
        rnd_int() i,
        rnd_long() l,
        rnd_float() f,
        rnd_double() d,
        rnd_str() s,
        rnd_symbol('abc', 'cde') sym,
        rnd_boolean() b,
        rnd_date() dt,
        rnd_long256() lt,
        rnd_char() ch,
        rnd_timestamp(0, 1000, 0) ts,
        rnd_bin() bin
    from long_sequence(100)
);
```

The error i receive is:

![image](https://user-images.githubusercontent.com/7276403/147779020-d82d4824-b1a5-4efb-8ac8-338e688da133.png)

### To reproduce

Run the SQL above

### Expected Behavior

I would expect SQL compiler to point at column where duplicate name has occurred.

### Environment

```markdown
- **QuestDB version**: 6.1.4-SNAPSHOT
- **OS**:
- **Browser**:

```

**Comment by kocko** [comment]
#1764

**Comment by zhangliyuSustech** [comment]
I‘m confused that this issue whether has been fixed? It's still open but is similar to 1764

**Comment by marregui** [comment]
hi @zhangliyuSustech the PR for 1764 was stale (abandoned by the author) and the ticket closed.

**Comment by marregui** [comment]
Being approached in PR https://github.com/questdb/questdb/pull/2093
