### ISSUE TITLE
Additional Compatibility

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#176]
Is it possible to add compatibility tests so that this is compatible without any performance regressions on:

- Minimally:
  - Oracle JDK (which you already have)
  - Oracle OpenJDK
  - AdoptOpenJDK OpenJDK + HotSpot
  - AdoptOpenJDK OpenJDK + OpenJ9 - with JITaaS/JITServer
  - GraalVM CE
- Additionally:
  - GraalVM EE
  - Zulu
  - Corretto
- Possibly even:
  - JetBrains JDK - at least for the development though may not be for production
  - RedHat OpenJDK
  - SapMachine
  - Liberica - used by JetBrains JDK
  - Dragonwell - with JWarmup
  - Zing - with ReadyNow

Also, the testing should encompass both JIT and AOT schemes, where available, in addition to JDK specific schemes.

Ideally, platform compatibility should include each platform the JDK has a distribution but minimally Windows, Linux, Mac, BSD on 64-bit platforms.

Also perhaps version compatibility should at least include currently actively supported LTS versions + latest version.

**Comment by mpsq** [comment]
This is a good idea. The minimal set seems sensible, that will be a good start.
Our CI pipeline needs some work and we have other scenarios/tests we also want to factor in. When this work is being done, we will also look into improving the compatibility testing.
Thank you for your feedback!
