### ISSUE TITLE
Add interprocess setup to documentation

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#180]
QuestDB can be used as a communications tool between processes with multiple independent readers and writers.
- Using REST
- Using JAVA where independent processes access the same questdb `root_directory`.

These possibilities are not apparent to the users with the current documentation. This setup should be documented in both the [rest](https://www.questdb.io/docs/restAPI) and the [java](https://www.questdb.io/docs/embeddedJavaAPI) API documentations.

**Comment by bluestreak01** [comment]
done
