### ISSUE TITLE
Support DATE_TRUNC

### ISSUE THREAD

**Issue by Yitaek** [questdb/questdb#1818]
### Is your feature request related to a problem?

When trying to connect to Google Data Studio and graph timeseries, putting Data & Time in the Dimension causes the Postgres connection to throw an error:

```
Failed to execute connection with error: ERROR: unknown function name: DATE_TRUNC(STRING,DATE)
  Position: 13
```

**Comment by jerrinot** [comment]
hello @Yitaek, while working on this function we realized there is a potential issue with timezones. 

QuestDB does not store timezones, timestamps are always internally represented as milliseconds from the epoch. This may or may not be a problem depending on your schema and the type of query the Google Data Studio runs. 

May I ask you how do you ingest data into QuestDB? Are you using Postgres protocol or ILP? If Postgres do you insert timestamps with timezones? Thanks!

**Comment by Yitaek** [comment]
Hi @jerrinot , I ran into this while working on this tutorial: https://blog.devgenius.io/exploring-crypto-prices-with-questdb-and-google-data-studio-cb3ddced0308 

I was using the CSV upload function via console. I don't think dataset has timezone specified, so just assumed UTC (in `2020-04-11 23:59:59` format)

**Comment by jerrinot** [comment]
That's very useful, thank you!
