### ISSUE TITLE
sql is repeatedly executed in the background

### ISSUE THREAD

**Issue by wutongsh** [questdb/questdb#1828]
### Describe the bug

When forcibly inserting data with the same timestamp in the database, the insert statement will be repeatedly executed in the background without returning any results. I think this is a serious bug; moreover, the memory occupied by the database program has been increasing, and the memory will not be released. ? In addition, does the database support modifying data? 

### To reproduce

INSERT into 'telemetry' VALUES('2022-01-22T07:46:56.652269Z', 100, 1)

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bziobrowski** [comment]
Hello Wutongsh.
Telemetry tables - telemetry, telemetry_config & telemetry_users -  are pre-defined and used for gathering anonymous usage stats . As such they should not be inserteg into or dropped manually . 
Telemetry stats are gathered when e.g. when query is executed . Your query clasesh with telemetry  job (which holds a lock on it) and then system tries to re-run it again and clash and again and never inserting any row ...  Normally it would resolve itself after a few attempts but that job never gets rid of the lock so it's an endless loop .  

I'd recommend restarting down qdb and then using new tables for inserts . 

As for the repeated runs : 
A. we need to put a limit on the number of reattempts  and (maybe)
B. disable inserts on telemetry tables
