### ISSUE TITLE
Detect and prevent duplicate timestamps from being inserted into a time-partitioned table

### ISSUE THREAD

**Issue by AaronCQL** [questdb/questdb#1843]
### Is your feature request related to a problem?

In a time-partitioned table, it is currently possible to insert two rows with the exact same timestamp.

### Describe the solution you'd like.

When inserting a row, is it possible to detect if the timestamp of that row already exists in the time-partitioned table and prevent the row from being inserted?

### Additional context.

For example, when using Kafka to populate QuestDB, there may be a situation where a message is processed more than once, causing the exact same row with the same timestamp to be inserted, which we wish to avoid.

**Comment by puzpuzpuz** [comment]
This issue is in the roadmap: https://github.com/questdb/roadmap/issues/3

**Comment by AaronCQL** [comment]
> This issue is in the roadmap: https://github.com/questdb/roadmap/issues/3

Thanks for the quick reply! From a previous conversation I had with @ideoma, I believe that the exact feature referred to in the roadmap is a non-trivial change that would require some time to develop. However, in this use case, only 1 column (timestamp) need to be considered, and according to Alex, can have a relatively easy and cheap workaround while waiting for the roadmap implementation. Would be nice if this can be added first if the roadmap implementation takes a longer time to develop.

**Comment by puzpuzpuz** [comment]
> However, in this use case, only 1 column (timestamp) need to be considered

This would require timestamp values to be unique across all rows. This sounds error-prone to me since non-duplicate rows may be silently erased if we would have such a setting. Imagine two different sensors sending their metrics with the same timestamp - only one row will get inserted into the database. Is that really what you want?

**Comment by AaronCQL** [comment]
> This would require timestamp values to be unique across all rows.

For our use case, timestamp values from our dataset are indeed guaranteed to be unique across all rows (ie. the presence of duplicate timestamps immediately means that the rows are duplicates). 

> This sounds error-prone

Perhaps it can be an optional setting where the default behaviour is to allow duplicate timestamps?

**Comment by puzpuzpuz** [comment]
> For our use case, timestamp values from our dataset are indeed guaranteed to be unique across all rows (ie. the presence of duplicate timestamps immediately means that the rows are duplicates).

So, it's fine in your case. Thanks for the confirmation.

> Perhaps it can be an optional setting where the default behaviour is to allow duplicate timestamps?

For sure, that shouldn't be the default behavior.

**Comment by snenkov** [comment]
Does this mean that after this Issue is resolved, then QDB will be able to work in the same was InfluxDB - i.e. it will be able to ingest without timestamp duplicates and duplicates will be overwritten (or ignored)?

**Comment by puzpuzpuz** [comment]
> Does this mean that after this Issue is resolved, then QDB will be able to work in the same was InfluxDB - i.e. it will be able to ingest without timestamp duplicates and duplicates will be overwritten (or ignored)?

If you refer to [this](https://docs.influxdata.com/influxdb/v2.1/write-data/best-practices/duplicate-points/), than something close to that behavior is covered in https://github.com/questdb/roadmap/issues/3. This particular issue describes a low-hanging fruit: duplicate rows are identified via their timestamps and nothing more. So, once this feature is available and enabled, all row timestamps in a table will be unique.

**Comment by snenkov** [comment]
I am now more confused. :/ 
Currently QDB supports duplicate rows - I like that and without this my whole QDB pipeline will fail.

Are you saying that QDB will no longer support duplicate rows or that a user will be able to choose one or the other?

Separately I don't understand the difference between this issue here and this one https://github.com/questdb/roadmap/issues/3 

Can you please clarify? :)

**Comment by puzpuzpuz** [comment]
> Can you please clarify? :)

Sure. The long story short is that we'll keep the correct behavior as is. This will be an opt-in feature set on, probably, per table basis.

**Comment by snenkov** [comment]
Awesome. I wanted that feature too! Thanks : )

**Comment by Chipply** [comment]
Glad this is on the road map. This feature would aid our current workflow.

**Comment by pswu11** [comment]
Hi @Chipply do you mind sharing more about your workflow and how deduplication could help?

**Comment by Chipply** [comment]
Hello Questdb/Questdb,

The ability to add a simple UNIQUE constraint on the timestamp column would
help us feel more secure with our imports. Otherwise, we need to complete
extra queries to make sure won't break the integrity of the table with
duplicates during an insert.

Best,
Grant

**Comment by puzpuzpuz** [comment]
Update on this one: a while ago we released [data deduplication](https://questdb.io/docs/concept/deduplication/) which prevents duplicates. So, this issue is not relevant anymore.
