### ISSUE TITLE
LIMIT does not work with DISTINCT queries on indexed columns

### ISSUE THREAD

**Issue by afvictory** [questdb/questdb#1854]
### Describe the bug

The following query `SELECT DISTINCT vendor_id FROM trips LIMIT 2` returns all (4) results instead of 2.

### To reproduce

1. Navigate to the QuestDB Live Demo (https://demo.questdb.io)
2. Run the following query `SELECT DISTINCT vendor_id FROM trips LIMIT 2`
3. Observe that all (4) rows are returned instead of 2 (vendor_id is indexed)
4. Run the following query `SELECT DISTINCT origin FROM telemetry` 
5. Observe that 4 rows are returned.
6. Run the following query `SELECT DISTINCT origin FROM telemetry LIMIT 2` 
7. Observe that 2 rows are returned as expected (telemetry is not indexed)

### Expected Behavior

The query in step 2 should return 2 rows instead of 4.

### Environment

```markdown
- **QuestDB version**: 6.1.3 (installed), 6.2 (live demo)
- **OS**: AWS Linux 2, Kernel: Linux 4.14.238-182.422.amzn2.x86_64 (installed) 
- **Browser**: Safari 15.1 (17612.2.9.1.20)
```

**Comment by afvictory** [comment]
I no longer believe having an index on the column has anything to do with this issue. I was able to reproduce this on a non-indexed column in my 6.1.3 installation.

Additionally, It seems like adding a WHERE clause causes the query to return the proper LIMIT.

To reproduce:
1. Create a new table
```CREATE TABLE limit_bug_test(id SYMBOL, reading FLOAT, ts TIMESTAMP) timestamp(ts)```
2. Insert some sample data
```
INSERT INTO limit_bug_test VALUES ('1', 0.3, '2022-02-01')
INSERT INTO limit_bug_test VALUES ('2', 0.5, '2022-02-01')
INSERT INTO limit_bug_test VALUES ('3', 0.1, '2022-02-01')

INSERT INTO limit_bug_test VALUES ('1', 0.3, '2022-02-02')
INSERT INTO limit_bug_test VALUES ('2', 0.5, '2022-02-02')
INSERT INTO limit_bug_test VALUES ('3', 0.1, '2022-02-02')
```
3. Run the following query `SELECT DISTINCT id FROM limit_bug_test LIMIT 2`
4. Observe that 2 results are returned instead of 3.
5. Run the following query `SELECT DISTINCT id FROM limit_bug_test WHERE ts in '2022-02-01' LIMIT 2`
6. Observe that 2 results are properly returned.

**Comment by bziobrowski** [comment]
Hi @afvictory  
I did a quick check and it seems limit is not recognized in 'distinct' query .

For the time being this workaround returns proper results : 

```sql
SELECT * from ( select DISTINCT id FROM limit_bug_test ) LIMIT 2
1
2
```

**Comment by bziobrowski** [comment]
Fixed in https://github.com/questdb/questdb/pull/1893
