### ISSUE TITLE
Web Console missing icons in the editor and warnings in dev tools

### ISSUE THREAD

**Issue by argshook** [questdb/questdb#1866]
### Describe the bug

web console (https://demo.questdb.io) SQL editor sometimes shows missing icons and dev tools contain warnings, see attached screenshot

![image](https://user-images.githubusercontent.com/4284659/152988039-c0505e8a-7671-434e-9c45-8a9cd2e20e81.png)

### To reproduce

1. go to https://demo.questdb.io
1. insert a query that includes nesting, for example:
    ```
    CREATE TABLE my_table
      (symb SYMBOL, price DOUBLE, ts TIMESTAMP)
    timestamp(ts);
    ```
1. hover with your mouse over gutter of the editor (the area with line numbers)
1. observe missing icon showing up
1. open dev tools
1. observe warnings like `Failed to decode downloaded font`

### Expected Behavior

icons should be displayed properly and dev tools console should have no warnings

### Environment

```markdown
- **QuestDB version**: 6.2
- **OS**: *
- **Browser**: *
```

**Comment by bsmth** [comment]
Symptoms look like broken icons in the gutter when queries have indentation:

```sql
CREATE TABLE my_table
  (symb SYMBOL, price DOUBLE, ts TIMESTAMP)
timestamp(ts);
```

![image](https://user-images.githubusercontent.com/43580235/153388078-8491e316-749c-4fb8-be7a-44522f830a0f.png)
