### ISSUE TITLE
Reordering problem in MCSequence

### ISSUE THREAD

**Issue by pveentjer** [questdb/questdb#1881]
### Describe the bug

The following code can behave differently than the documentation wants it to behave.

    
    @Override
    public long next() {
        long cached = cache;
        // this is a volatile read, we should have correct order for "cache" too
        long current = value;
        long next = current + 1;

        if (next > cached) {
   

The load of the cache and the load of the value are not ordered by the fact that the value is volatile. The value will prevent subsequent loads/stores from being reordered due to its acquire semantics, it will not prevent earlier loads/stores from being reordered.

To get an impression of what fences could be involved, check the following link: http://gee.cs.oswego.edu/dl/jmm/cookbook.html

The following JStress Test shows the bug in action
```
package org.openjdk.jcstress.samples.jmm.advanced;

import org.openjdk.jcstress.annotations.Actor;
import org.openjdk.jcstress.annotations.JCStressTest;
import org.openjdk.jcstress.annotations.Outcome;
import org.openjdk.jcstress.annotations.State;
import org.openjdk.jcstress.infra.results.II_Result;

import static org.openjdk.jcstress.annotations.Expect.*;

@JCStressTest
@State
@Outcome(id = {"0, 0", "1, 1"}, expect = ACCEPTABLE, desc = "Boring")
@Outcome(id = {"0, 1", "1, 0"}, expect = ACCEPTABLE, desc = "Plausible")
public class AdvancedJMM_10_WrongAcquireOrder {

    /*
        How to run this test:
            $ java -jar jcstress-samples/target/jcstress.jar -t AdvancedJMM_10_WrongAcquireOrder
     */

    /*
      ----------------------------------------------------------------------------------------------------------

        For completeness, the example that has a wrong acquire order. All these results can be explained by
        sequential execution of the code.

        x86_64:
          RESULT        SAMPLES     FREQ       EXPECT  DESCRIPTION
            0, 0  2,560,656,086   55.33%   Acceptable  Boring
            0, 1      2,961,349    0.06%   Acceptable  Plausible
            1, 0      7,885,064    0.17%   Acceptable  Plausible
            1, 1  2,056,684,125   44.44%   Acceptable  Boring
     */

    int x;
    volatile int g;

    @Actor
    public void actor1() {
        x = 1;
        g = 1;
    }

    @Actor
    public void actor2(II_Result r) {
        r.r1 = x;
        r.r2 = g; // acquiring too late
    }
}
```

**Comment by bluestreak01** [comment]
closing issue, feel free to reopen if problem with `MCSequence` specifically is reproducible.

**Comment by pveentjer** [comment]
I think you don't need the setCachedFence. 

```
  if (_next > _cached) {
            long avail = barrier.availableIndex(_next);
            if (avail > _cached) {
                setCacheFenced(avail);<----
                if (_next > avail) {
                    return -1;
                }
            } else {
                return -1;
            }
        }
```

AFAIK caches will only be accessed by a single thread, nobody can observe if it gets reordered with different memory accesses. A plain store should suffice.

**Comment by pveentjer** [comment]
I think you should also have a look at the padding of the `value`. 

There is insufficient padding (should be at least 64 bytes and better to have 128 due to adjacent cache line prefetching; same as JCTools and Java @Contended).

And there is some false sharing. The `cached` value is on the same line as `value`. So any time a different CPU reads `value`, it invalidates the cacheline of `cached` and effectively you lose the performance benefit. Especially if both if `cached' and 'value' are frequently accessed, you could end up with many cache misses. See the following [link](https://rigtorp.se/ringbuffer/) for some numbers.

I would put all immutable state in one padded class. Then cached in another padded subclass. And then value another padded subclass. JCTools uses a similar approach to reduce false sharing.
