### ISSUE TITLE
Worker fences questionable

### ISSUE THREAD

**Issue by pveentjer** [questdb/questdb#1882]
### Describe the bug

The worker contains the following code:

```
for (int i = 0; i < n; i++) {
     Unsafe.getUnsafe().loadFence();
      try {
          try {
               useful |= jobs.get(i).run(workerId);
          } catch (Throwable e) {
               onError(i, e);
          }
        } finally {
          Unsafe.getUnsafe().storeFence();
          }
     }
```

I believe this is not working the way it is intended to be working.

If any of the jobs has modified its state and such a job is accessed by another thread to reads its state, then there is no guarantee that the access happens after the storeFence and before the loadFence. So you could end up with a plain load seeing the plain store made by a different thread. Because there is no happens-before edge, there is a data race.

If the job.run doesn't modify any unsynchronized state, then I don't see the purpose of the loadFence and the storeFence.

**Comment by marregui** [comment]
Hi @pveentjer ,

Would you be able to provide a test illustrating/showcasing the issue?

Thank you in advance

**Comment by pveentjer** [comment]
I do not have the time to make a test. Ask @puzpuzpuz to have a look at the fencing behavior and perhaps involve the author to explain what the idea is behind using this fencing approach.

The fencing approach is very unusual usage for release/acquire fences, and that is why my alarm bells went of.

**Comment by jerrinot** [comment]
Hello Peter, nice to you see here! :) 

You are right, it does looks rather suspicious. I'm sure we will have a look at this at some point. 
I'm going to remove the "Good first issue" label as this is far from being simple. It's at the opposite spectrum in fact.

**Comment by marregui** [comment]
Thank you very much for the detailed explanation!!, obviously, without a test that proofs all this, I will have to personally verify that all this theory is correct and that it is indeed right (for lack of deeper understanding from my part), by producing a test myself. So far I see no threading issues, nor state conflict, nor races, so I suppose this case will came back to mind when/if I see threading issues. Thank you again for the detailed report.

**Comment by pveentjer** [comment]
These things tend to be extremely hard to reproduce. Nearly impossible to write a test for it. So I would not go in that direction. Make it sound by design is a much better approach

**Comment by pveentjer** [comment]
IMHO the key question is: are other threads going to peek inside the jobs (and their dependencies) of the worker and if so, is there any synchronization on the accessed fields of the jobs/dependencies?

If yes, then there are potential data races and race conditions.

**Comment by marregui** [comment]
I am not 100% of what I am saying here, I am fairly new to the codebase. From my intuition, which has been proven to be wrong time and again, we kind of follow a sort of AKKA pattern, where each worker will peek at a queue, get its job (task) and will perform. Should results need to be propagated, there are message queues for various purposes, and that is how workers communicate with each other. Workers expose no state to each other, but I may be wrong.

**Comment by pveentjer** [comment]
In that case, no synchronization is needed. The queue provides the happens-before edge.

**Comment by marregui** [comment]
happy days!

**Comment by marregui** [comment]
may I close the Issue? thank you in advance.

**Comment by pveentjer** [comment]
Do you understand the reasoning behind the fence logic and have you confirmed that the reasoning is correct? If so; then you can close this topic. But I do know a few things about fences and my gut feeling is something is wrong here. If you still want to close it, then please go ahead.

**Comment by puzpuzpuz** [comment]
To me, these exotic fences deserve at least some comments around them. I remember that I was also surprised when I saw them first time.
