### ISSUE TITLE
SOCountDownLatch long overflow problem

### ISSUE THREAD

**Issue by pveentjer** [questdb/questdb#1883]
### Describe the bug

The following problem has a problem with long overflow:

```
 while (true) {
            long deadline = System.nanoTime() + nanos;
            LockSupport.parkNanos(nanos);

            if (System.nanoTime() < deadline) {
                // this could be spurious wakeup, ignore if count is non-zero
                if (getCount() == 0) {
                    return true;
                }
            } else {
                return false;
            }
        }
```

The consequence could be that instead of ending up in the if branch, you end up in the else branch.

Please check the documentation for the System.nanoTime to correctly handle overflow.

**Comment by GothamsJoker** [comment]
Good afternoon, 

I would like to work on this and this would be my first contribution towards this project.

**Comment by puzpuzpuz** [comment]
> I would like to work on this and this would be my first contribution towards this project.

That would be awesome. Our [contributing guide](https://github.com/questdb/questdb/blob/7c9b146e4f06bfc0b1a51bf1ce423776277c388b/CONTRIBUTING.md) may help you to get going.
