### ISSUE TITLE
AWS marketplace image doesn't honor the pg.passwd in server.conf

### ISSUE THREAD

**Issue by piggybox** [questdb/questdb#1886]
### Describe the bug

After spinning up an instance from the AWS marketplace image, I find I still need to use the default "quest" password to access the server through the pgsql interface. 

Also, what's the standard practice to change password? I don't find it in the doc. 

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by mariusgheorghies** [comment]
Hi, Can you provide more details on how and where (path to server.conf) do you change `pg.passwd`. Did you restart the database after that? I probably have to point out that you need to restart questdb after changing any setting in server.conf as we don't have reload for now.

**Comment by piggybox** [comment]
Hi, I didn't change anything, so it's a little surprised when I created the instance from AMI for the first time I couldn't connect to the database with the generated password inside the config. Yes, after a restart of database, it started using the new password. I think it's quite implicit in the document that one has to use the default "admin/quest" user/pass to log into database to start.

**Comment by mdahlman** [comment]
I hit the same issue today.
@piggybox , I found your comment, "I think it's quite implicit in the document that one has to use the default "admin/quest" user/pass to log into database to start." to be unclear.

Perhaps I'm saying the same thing as you were thinking... but I would say it like this:
I suspect that there's a timing issue when the instance boots up. It seems like the database server starts, THEN `/var/lib/questdb/conf/server.conf` gets modified to use a randomly generated password. So the intended/documented password is not actually in use yet.

In contrast, the web console was up and working immediately. So the server **seemed** good, and I assumed that the PostgreSQL-style connection was just my user error.

The workaround is simple once you understand what's going on:
`sudo systemctl restart questdb`
Or I suppose one could restart the EC2 instance immediately after initially starting it. But you have to SSH to the server to find the password anyway, so restarting just the database seems more reasonable.

Anyway, if the password could be set such that it was actually in use without any action required by the user, it would be a much cleaner user experience.

**Comment by mdahlman** [comment]
In my opinion, this is definitely an _improvement_. It points you to the workaround.
But documenting the workaround is distinct from fixing the bug.

It's still true that the "AWS marketplace image doesn't honor the pg.passwd in server.conf". The password is defined, but it's not in use... this is pretty dirty. So I think it's a stretch to say the bug is fixed.
