### ISSUE TITLE
type conversion in where clause

### ISSUE THREAD

**Issue by atemmo** [questdb/questdb#1889]
### Describe the bug

Using the balances table example from https://questdb.io/docs/reference/sql/latest-by/ and running the following queries produces:

```sql
-- returns nothing
select * from 'balances' where cust_id = 1; 

--returns correct rows
select * from 'balances' where cust_id = '1'; 

-- returns correct latest row
select * from 'balances' where cust_id = 1 latest on ts partition by cust_id;
```

Seems that implicit conversion from int to symbol doesn't work unless latest-by is used in query.

### Environment

```markdown
- **QuestDB version**: 6.2
- **OS**: Macos Monterey 12.2 and PopOS 21.04
```

**Comment by bziobrowski** [comment]
Note: it works in when jit is enabled but fails otherwise due to implicit cast from symbol to timestamp .
