### ISSUE TITLE
Data Versioning and Management 

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#190]
To recreate certain results and scenarios the data need to be snapshot table. Also for experimentation one cannot modify the master copy.

Multiple branches can be worked on at the same time. E.g. as raw data gets inputted cleaned data branch can be updated removing outliers.  

So is it possible to add the ability to:

- tag version of the data
- fork, branch and merge the data
- access a snapshot in time or revision point in a particular fork and branch
- apply relevant security policy to forks and branchers
- rollbacks and roll forwards master or any other branch of data to point of time in another branch

Since QuestDB is append-only perhaps this might be easier to have than other DBs with some additional metadata.

If unversioned is faster ability to create unversioned DBs for production and periodically or continuously synch with versioned if needed.

These techniques have been incorporated into DBs like:

- [LiteTree: SQLite with Branches](https://github.com/aergoio/litetree)
- [Noms: The versioned, forkable, syncable database](https://github.com/attic-labs/noms)
- [OrpheusDB: database system that supports versioning capabilities](https://orpheus-db.github.io/)
- [Dolt – It's Git for Data](https://github.com/liquidata-inc/dolt)

**Comment by bsmth** [comment]
I'm closing this as it's out of scope with the features we are focusing on at the moment.

If this feature is something you would like to add, you may also contribute directly by submitting a patch - see the [contribution guide](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) for details. :)

Thank you!
