### ISSUE TITLE
Sum on Long256 values

### ISSUE THREAD

**Issue by EugeneTeu** [questdb/questdb#1900]
### Is your feature request related to a problem?

I have a `long256` values in my database and was wondering if im able to use `sum` on it to aggregate queries? 

seems this fails for me: 
```sql
CREATE table test (
    a long256,
    b long256
)

INSERT INTO test (a,b) VALUES (0x4f338f76,0x4f338f76);

 SELECT
        sum(a) as sumA, 
        sum(a) as sumB
      FROM test;
```

sum function doesnt work here without casting to double

### Describe the solution you'd like.

sum function to work w long256 values

### Describe alternatives you've considered.

Not sure if you guys could suggest an alternative when working with long256 values

### Additional context.
![Screenshot 2022-02-18 at 12 09 39 AM](https://user-images.githubusercontent.com/43085751/154522194-303cc9f5-600f-4d28-ba05-b96094753875.png)

this here should be `value is double`

**Comment by HeZean** [comment]
Hi, if this feature is considered necessary, I'd like to work on it 😄

**Comment by eugenels** [comment]
implementation of this feature is in progress
