### ISSUE TITLE
Error when using UNION ALL in sub-query

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#1910]
### To reproduce

```
SELECT "orders".status "orders__status", sum("orders".amount) "orders__total_amount"
FROM (
    select 1 as id, 100 as amount, cast('new' as symbol) status
    UNION ALL
    select 2 as id, 200 as amount, cast('new' as symbol) status
    UNION ALL
    select 3 as id, 300 as amount, cast('processed' as symbol) status
    UNION ALL
    select 4 as id, 500 as amount, cast('processed' as symbol) status
    UNION ALL
    select 5 as id, 600 as amount, cast('shipped' as symbol) status
) "orders"
GROUP BY "orders__status" ORDER BY "orders__total_amount" DESC LIMIT 10000;
```
returns `column type mismatch [index=0, A=SYMBOL, B=INT]` (same with STRING type instead of SYMBOL)

The following workaround works:
```
CREATE table orders as (
  with x as (
    select 1 as id, 100 as amount, 'new' status
    UNION ALL
    select 2 as id, 200 as amount, 'new' status
    UNION ALL
    select 3 as id, 300 as amount, 'processed' status
    UNION ALL
    select 4 as id, 500 as amount, 'processed' status
    UNION ALL
    select 5 as id, 600 as amount, 'shipped' status
  )
  select * from x
);

SELECT "orders".status "orders__status", sum("orders".amount) "orders__total_amount"
FROM "orders"
GROUP BY "orders__status" ORDER BY "orders__total_amount" DESC LIMIT 10000;
```

### Environment

```markdown
- **QuestDB version**: latest 6.2.1 master
- **OS**:
- **Browser**:
```

**Comment by bziobrowski** [comment]
This can be triggered with simpler sql : 

```
select status from ( 
select 1 as id, 100 as amount, 'abc' status
union all 
select 2 as id, 100 as amount, 'def' status
) 

```

**Comment by zhangliyuSustech** [comment]
I‘d like to work on it and my teammate finds something interesting. When I change  the second int to double, it will change into this
`column type mismatch [index=0, A=STRING, B=DOUBLE]`
This may help us to understand where is the bug

**Comment by puzpuzpuz** [comment]
Hi @zhangliyuSustech 

AFAIK @bziobrowski is working on this issue. If you'd like to contribute, I suggest picking up one of the good first start issues: https://github.com/questdb/questdb/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22

**Comment by zhangliyuSustech** [comment]
I‘m sorry that I'm not familiar with Github issues for the first time. If you still have some problems about this issue, I 'd like to talk about the solution with developers.

**Comment by bziobrowski** [comment]
@puzpuzpuz  is right as I'm working on the issue . Issue is  much bigger and complex than it seems so it's not a good one to start working on qdb codebase .
