### ISSUE TITLE
NULL for column type SYMBOL INDEX

### ISSUE THREAD

**Issue by robocoder** [questdb/questdb#1916]
### Describe the bug

Query results are inconsistent when `NULL` is stored in a column of type `SYMBOL` vs `SYMBOL INDEX`

Compare:
```
SELECT * FROM symbolic WHERE foobar != '';
```
vs
```
SELECT * FROM symdex WHERE foobar != '';
```

### To reproduce

```
admin=> CREATE TABLE symdex ( foobar SYMBOL INDEX );
OK
admin=> INSERT INTO symdex VALUES ('123456');
INSERT 0 1
admin=> INSERT INTO symdex VALUES ('1');
INSERT 0 1
admin=> INSERT INTO symdex VALUES (NULL);
INSERT 0 1
admin=> SELECT * FROM symdex;
 foobar 
--------
 123456
 1
 
(3 rows)

admin=> SELECT * FROM symdex WHERE foobar = NULL;
 foobar 
--------
 
(1 row)

admin=> SELECT * FROM symdex WHERE foobar = '';
 foobar 
--------
 
(1 row)

admin=> SELECT * FROM symdex WHERE CAST(foobar AS STRING) = '';
 foobar 
--------
(0 rows)

admin=> SELECT * FROM symdex WHERE foobar != NULL;
 foobar 
--------
 123456
 1
(2 rows)

admin=> SELECT * FROM symdex WHERE foobar != '';
 foobar 
--------
 123456
 1
(2 rows)

admin=> SELECT * FROM symdex WHERE CAST(foobar AS STRING) != '';
 foobar 
--------
 123456
 1
 
(3 rows)
```

### Expected Behavior

Contrast above with column type `SYMBOL`.

```
admin=> CREATE TABLE symbolic ( foobar SYMBOL );
OK
admin=> INSERT INTO symbolic VALUES ('123456');
INSERT 0 1
admin=> INSERT INTO symbolic VALUES ('1');
INSERT 0 1
admin=> INSERT INTO symbolic VALUES (NULL);
INSERT 0 1
admin=> SELECT * FROM symbolic;
 foobar 
--------
 123456
 1
 
(3 rows)

admin=> SELECT * FROM symbolic WHERE foobar = NULL;
 foobar 
--------
 
(1 row)

admin=> SELECT * FROM symbolic WHERE foobar = '';
 foobar 
--------
(0 rows)

admin=> SELECT * FROM symbolic WHERE CAST(foobar AS STRING) = '';
 foobar 
--------
(0 rows)

admin=> SELECT * FROM symbolic WHERE foobar != NULL;
 foobar 
--------
 123456
 1
(2 rows)

admin=> SELECT * FROM symbolic WHERE foobar != '';
 foobar 
--------
 123456
 1
 
(3 rows)

admin=> SELECT * FROM symbolic WHERE CAST(foobar AS STRING) != '';
 foobar 
--------
 123456
 1
 
(3 rows)
```

### Environment

```markdown
- **QuestDB version**: questdb-6.2-rt-linux-amd64
- **OS**: Ubuntu 20.04.3 LTS
- **Browser**: N/A
```

**Comment by robocoder** [comment]
Another oddity is `NULL`s appearing in results when we explicitly wanted to exclude them. (See attached SQL to create and populate table.)

[1916.sql.gz](https://github.com/questdb/questdb/files/8138890/1916.sql.gz)

Isn't this weird?
```
admin=> select count() from foobar;
 count 
-------
  1693
(1 row)

admin=> select count() from foobar where country2 = null;
 count 
-------
    16
(1 row)

admin=> select count() from foobar where country2 != null;
 count 
-------
  1693
(1 row)
```

**Comment by robocoder** [comment]
Another oddity is NULLs appearing in results when we explicitly wanted to exclude them. (See attached SQL to create and populate table.)

[1916.sql.gz](https://github.com/questdb/questdb/files/8138965/1916.sql.gz)

Isn't this weird?
```
admin=> select count() from foobar;
 count 
-------
  1693
(1 row)

admin=> select count() from foobar where country2 = null;
 count 
-------
    16
(1 row)

admin=> select count() from foobar where country2 != null;
 count 
-------
  1693
(1 row)
```
(Yes, I know there are duplicate rows in the attached SQL. I anonymized the data by removing the timestamp column and customer identifying info.)

**Comment by Twilight-Shuxin** [comment]
Hi, I'd like to volunteer for this issue. I guess the problem is occuring when indexes are used in the selection process.

**Comment by Twilight-Shuxin** [comment]
I guess I have found the problem. In this function below, before the added line the case of empty string is ignored. If this should be the correct way, I'll pull a request.
`public Function createBindVariable(SqlExecutionContext sqlExecutionContext, int position, CharSequence name) throws SqlException {
        this.sqlExecutionContext = sqlExecutionContext;
        if (name != null && name.length() > 0) {
            switch (name.charAt(0)) {
                case ':':
                    return createNamedParameter(position, name);
                case '$':
                    return parseIndexedParameter(position, name);
                default:
                    return new StrConstant(name);
            }
        }
        if(name.length() == 0) return StrConstant.EMPTY; //added line;
        return NullConstant.NULL;
    }
`
