### ISSUE TITLE
Strange behavior while importing from CSV file

### ISSUE THREAD

**Issue by balexus** [questdb/questdb#1919]
### Describe the bug

i have imported CSV file that contains 5 records twice.
After first time all is OK, but after second time i see that 4 records were skipped besides TIMESTAMP errors.
Also if errors are happen then i must see 5 errors but i see 4 ones only

### To reproduce

1) create the table

CREATE TABLE "tblNewPricesData" (
    "SymbolID" int,
    "AssesstmentDate" timestamp,
    "BateID" byte,
    "Value" double,
    "NewID" int,
    "isActual" boolean
) timestamp("AssesstmentDate");

2) create file for import with name=tblNewPricesData:

SymbolID,AssesstmentDate,BateID,Value,NewID,isActual
23231,1979-01-03T00:00:00.000000Z,1,44.5,966,true
23231,1979-01-03T00:00:00.000000Z,2,44.5,966,true
23231,1979-01-10T00:00:00.000000Z,1,44.5,966,true
23231,1979-01-10T00:00:00.000000Z,2,44.5,966,true
23231,1979-01-17T00:00:00.000000Z,1,44.5,966,true

3) run command for import

curl -F data=@tblNewPricesData 'http://localhost:9191/imp'
and got:

4) result of command
+-----------------------------------------------------------------------------------------------------------------+
|      Location:  |                                  tblNewPricesData  |        Pattern  | Locale  |      Errors  |
|   Partition by  |                                              NONE  |                 |         |              |
|      Timestamp  |                                   AssesstmentDate  |                 |         |              |
+-----------------------------------------------------------------------------------------------------------------+
|   Rows handled  |                                                 5  |                 |         |              |
|  Rows imported  |                                                 5  |                 |         |              |
+-----------------------------------------------------------------------------------------------------------------+
|              0  |                                          SymbolID  |                      INT  |           0  |
|              1  |                                   AssesstmentDate  |                TIMESTAMP  |           0  |
|              2  |                                            BateID  |                     BYTE  |           0  |
|              3  |                                             Value  |                   DOUBLE  |           0  |
|              4  |                                             NewID  |                      INT  |           0  |
|              5  |                                          isActual  |                  BOOLEAN  |           0  |
+-----------------------------------------------------------------------------------------------------------------+

i.e all is ok 5 rows were handled and 5 rows were imported

5) then i repeat the command i.e.

curl -F data=@tblNewPricesData 'http://localhost:9191/imp'
and i expect to see the same result ( i will have duplicate records)
but i see

+-----------------------------------------------------------------------------------------------------------------+
|      Location:  |                                  tblNewPricesData  |        Pattern  | Locale  |      Errors  |
|   Partition by  |                                              NONE  |                 |         |              |
|      Timestamp  |                                   AssesstmentDate  |                 |         |              |
+-----------------------------------------------------------------------------------------------------------------+
|   Rows handled  |                                                 5  |                 |         |              |
|  Rows imported  |                                                 1  |                 |         |              |
+-----------------------------------------------------------------------------------------------------------------+
|              0  |                                          SymbolID  |                      INT  |           0  |
|              1  |                                   AssesstmentDate  |                TIMESTAMP  |           4  |
|              2  |                                            BateID  |                     BYTE  |           0  |
|              3  |                                             Value  |                   DOUBLE  |           0  |
|              4  |                                             NewID  |                      INT  |           0  |
|              5  |                                          isActual  |                  BOOLEAN  |           0  |
+-----------------------------------------------------------------------------------------------------------------+

You can see logs  of questdb in attachments

[questdb_logs.txt](https://github.com/questdb/questdb/files/8152743/questdb_logs.txt)

### Expected Behavior

1) I expected that i will have 10 records in the table tblNewPricesData
but i see 6 only

2) if errors are happen then we must have 5 errors but i see 4 ones only.

### Environment

```markdown
- **QuestDB version**: questdb 6.2 via REST API
- **OS**: CentOS 7.0
- **Browser**: 97.0 Mozilla Firefox for UBUNTU
```

**Comment by bziobrowski** [comment]
Hi @balexus 
Table has desginated timestamp but is not partitioned so Out-Of-Order ingestion doesn't work and input has to be ordered (ascending) . 
I believe you're getting errors on first 4 rows because they're smaller than "1979-01-17T00:00:00.000000Z" and the last one successeds because it's equal to it .

**Comment by balexus** [comment]
Hi @bziobrowski 
You have saved me.
Thanks a lot
