### ISSUE TITLE
Wrong boolean value scan in pgx package (golang)

### ISSUE THREAD

**Issue by OnlyC** [questdb/questdb#1930]
### Describe the bug

Boolean values always return false with default query type.
![image](https://user-images.githubusercontent.com/1250580/156891551-efd8be7c-862f-4c3a-a20f-6c0fe4c6169d.png)

### To reproduce

![image](https://user-images.githubusercontent.com/1250580/156891557-58cf9d22-09d8-4162-a1bd-d201133c2236.png)

### Expected Behavior

Return correct value

### Additional context

You guys can find why this happen & how to solve problem from this issue that I created on pgx's github:

https://github.com/jackc/pgx/issues/1163

**Comment by bluestreak01** [comment]
I can reproduce this with PGX. This is likely to be a bug somewhere, I don't yet know where. Debugging. In the mean time, PQ works fine.
