### ISSUE TITLE
Error: Could not publish writer ALTER TABLE task 

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#1944]
### Describe the bug

When table is constantly written to, ALTER TABLE SQL start to fail after few attempts (32 by default)

### To reproduce

1. Run ILP to constantly write table A
2. Run 
```alter table A set PARAM commitLag = 1s```
32 time or more

### Expected Behavior

ALTER TABLE should not fail

### Environment

```markdown
- **QuestDB version**:6.2.1
- **OS**:
- **Browser**:
```

### Additional context

When number of alter table exceeds queue capacity specified in `cairo.writer.command.queue.capacity` (default is 32) command publish queue overflows and commands will not be executed.

Queue sequence happens because all `TableWriters` have to confirm but only those writers which are not in the pool observe the published command. Also some writers are blocked for writing without observing published commands (telemetery)

**Comment by fmoessbauer** [comment]
We are running into this issue as well, when doing data retention. This becomes critical on systems where you cannot pause data ingestion but have to drop old data at some point in time.
On a system with a high data ingestion rate we where not able to retent data at all (while ingesting).

Sample query: `ALTER TABLE table_a DROP PARTITION WHERE timestamp <  dateadd('h', 36, now());`

**Comment by ideoma** [comment]
Fixed in https://github.com/questdb/questdb/pull/1959
