### ISSUE TITLE
Ability to hide table

### ISSUE THREAD

**Issue by snenkov** [questdb/questdb#1948]
### Is your feature request related to a problem?

My problem is that I see some tables which I don't need to see in the UI as a user.
Examples being:
![image](https://user-images.githubusercontent.com/13110986/158167624-3c15574b-e653-415d-b3e9-930dc08cfc9c.png)

### Describe the solution you'd like.

It would be nice if it's possible to hide table.
For example if a table name starts with `_` then it's considered to be hidden.
Then there can be a square in the UI which says "Show hidden tables" and the user can mark it or unmark it (unmarked is the default).

### Describe alternatives you've considered.

Deleting the tables or no alternative at all.

**Comment by snenkov** [comment]
Like I mentioned in the proposal, I believe it would be nice to be more abstract than this.
I.e. the users themselves can define `_` (hidden or system) tables and then you can have the option in the Settings tab. 
We may be talking about the same thing, but I am just clarifying in case.

**Comment by insmac** [comment]
Does this use case also involve things like filtering out these tables from, say, SQL editor autocomplete?

**Comment by bluestreak01** [comment]
We can filter this out via SQL and configuration. @insmac could you remind me what SQL or view does web console use to return tables ?

**Comment by insmac** [comment]
> We can filter this out via SQL and configuration. @insmac could you remind me what SQL or view does web console use to return tables ?

it's `tables()` 🙂
