### ISSUE TITLE
Validate `server.conf`

### ISSUE THREAD

**Issue by amunra** [questdb/questdb#1975]
### Describe the bug

Currently keys written to `server.conf` go undetected.

This means that not only typos go undetected, but lack of validation is a risk during version migration as settings that used to apply in a previous version have no effect in a newer one without warning -- even if new settings are supposed to be used.

### To reproduce

* Create a key with a typo.
* Watch the QuestDB instance start up wthout error.

### Expected Behavior

The instance should not start, the invalid key should then be logged as an error. Bonus if we also log the line in `server.conf` where the invalid key is present.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by GothamsJoker** [comment]
Good afternoon,

I would like to look into this issue if it is open to contributors. I looked into the server.conf but I do not see where the keys are being written to. Can you point me in the correct direction and or suggest the correct place to start? 

Thank you!

**Comment by amunra** [comment]
Thanks for volunteering to help out!
I can walk you through this over Zoom if you like (contact me on https://slack.questdb.io/ - My name is "Adam Cimarosti").

In the meantime, here are some pointers:
* Track which properties exist used in `core/src/main/java/io/questdb/PropServerConfiguration.java` into a `HashSet known`.
* Then `bad_names = new HashSet(properties.keys()); bad_names.remove_all(known)`.
* Raise an exception with a helpful message.

Tests are in core\src\test\java\io\questdb\PropServerConfigurationTest.java.

You'll notice that the configuration has a few conditional parsing (`if/else` branches).
It may be better to flatten out and remove the conditional logic and have a separate validation step.

**Comment by GothamsJoker** [comment]
> Thanks for volunteering to help out! I can walk you through this over Zoom if you like (contact me on https://slack.questdb.io/ - My name is "Adam Cimarosti").
> 
> In the meantime, here are some pointers:
> 
> * Track which properties exist used in `core/src/main/java/io/questdb/PropServerConfiguration.java` into a `HashSet known`.
> * Then `bad_names = new HashSet(properties.keys()); bad_names.remove_all(known)`.
> * Raise an exception with a helpful message.
> 
> Tests are in core\src\test\java\io\questdb\PropServerConfigurationTest.java.
> 
> You'll notice that the configuration has a few conditional parsing (`if/else` branches). It may be better to flatten out and remove the conditional logic and have a separate validation step.

Thank you for helping me get started! I am working on setting this up.

Are we testing if the the properties key is valid as in potential typos in the server.conf or typos created in PropServerConfiguration? For instance one being "shared.worker.yield.threshold" in server.conf should match "this.sharedWorkerYieldThreshold = getLong(properties, env, "shared.worker.yield.threshold", 100);" in PropServerConfiguration.java. I see multiple methods within PropServerConfiguration taking in a Properties but also a String "key". I assume I should create a set of the keys used in these methods?

Thank you for the help! I will reach out if I have anymore questions.

**Comment by amunra** [comment]
We care about typos in the server configuration.

**Comment by puzpuzpuz** [comment]
@amunra can we close this one considering that #1998 is now merged?

**Comment by amunra** [comment]
Yes, closed.
