### ISSUE TITLE
Why can't the sampling function be based on microseconds? Currently, it can only be based on milliseconds

### ISSUE THREAD

**Issue by VansirCQ** [questdb/questdb#1984]
### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/37134815/160073726-1b54a396-2077-4e64-80ea-57ef6a022981.png)
here is details, in griffin\engine\groupby\TimestampSamplerFactory.java

### Describe the solution you'd like.

The sampling dimension provided by questDB is at least 'T', which means milliseconds, but the scene on my side is microseconds, so I want questDB to adapt.
The code in the screenshot is the part where I found the suspected related sampling logic. The case 'U' in the screenshot is added by myself. I don't know if this can solve this microsecond sampling, and I don't know how I should verify my Is the modification logic correct?

What is the outsourcing method of questDB so that I can verify my modification logic
In addition, I would like to ask the code managers, can I support microsecond sampling with this modification?

**Comment by VansirCQ** [comment]
is there any owner can resolve this question :)

**Comment by VansirCQ** [comment]
@fuzzthink @laa @mpolden @marregui

**Comment by marregui** [comment]
hi @VansirCQ the solution is correct, minus the comment (should be micros). You could push a PR with this modification. For tests, possibly:

- SampleBySqlParserTest : extend tests to cover the new case (would be nice to cover all cases).
- TimestampSamplerFactoryTest : as above :) 
- SampleByTest : Possibly a test to exemplify use of micro sampling, with your specific use case to validate it.

will you push it? 

best regards

**Comment by KevinChen16** [comment]
Hi, could I have the chance to finish the pull request with tests?

**Comment by VansirCQ** [comment]
you wanna try this logic?&nbsp; appreciate it!&nbsp; please test it and push thoese code



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 19, 2022 18:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [questdb/questdb] Why can't the sampling function be based onmicroseconds? Currently, it can only be based on milliseconds (Issue #1984)




 
Hi, could I have the chance to finish the pull request with tests?

**Comment by KevinChen16** [comment]
Sure. But I would like to know how your scene uses microseconds as you described above so that I could write the test to exemplify its use. Could you please share the scene or its description with me? Thanks!

**Comment by KevinChen16** [comment]
And @marregui I've read your requirements for tests, and could you please tell me whether the requirement to extend tests means writing brand new test cases only for microseconds or reusing the similar tests as existing cases just by changing the parameter of "sample by"? Thanks!

**Comment by KevinChen16** [comment]
Hi! I've pulled the test cases in #2050 , please check it to confirm whether my tests are correct, thanks! @marregui @VansirCQ @bluestreak01

**Comment by marregui** [comment]
hey hey @KevinChen16 thank you for the PR! I had a look and left some comments :), overall looks good, well done.

**Comment by KevinChen16** [comment]
> hey hey @KevinChen16 thank you for the PR! I had a look and left some comments :), overall looks good, well done.

I have modified some codes in the new commit, please check, thanks!

**Comment by marregui** [comment]
Hey @KevinChen16 I have left a comment, almost there!

**Comment by KevinChen16** [comment]
> Hey @KevinChen16 I have left a comment, almost there!

Thanks! And I've just pulled the newest version there, please check if I mislead anything or make mistakes. Appreciate it!
