### ISSUE TITLE
Make all config keys available in server.conf

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#199]
The current `server.conf` file comes in empty and the configuration keys are set with default values in `PropServerConfigurations.java`. When I want to amend a configuration key, I need to find it in the documentation and add it to the configuration file which is currently only meant as a means of overriding default config. This makes it difficult to explore the available configuration keys and edit them.

I suggest to transfer all the configuration keys available to `server.conf` with a short description in the comments near each key, and optional configurations commented out. This would make it easier to navigate and explore different configurations.

**Comment by mpsq** [comment]
Done
