### ISSUE TITLE
Default worker count

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#200]
**Is your feature request related to a problem? Please describe.**
When starting the http server out of the box, it starts with 2 workers, independently of how many cores the host machine may have. To get more, you need to go into the configuration file and add key `shared.worker.count`.

**Describe the solution you'd like**
Change the default behaviour so QuestDB starts using the whole computing power available to the machine by default. 

**Additional context**
This may require some analysis at startup such as numa nodes etc to generate a suitable configuration.
To make it easier for users to change these properties easily, they should probably be present but commented out by default in the configuration file.

**Comment by mpsq** [comment]
Done
