### ISSUE TITLE
No such file or directory when installed from brew

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#2001]
### Describe the bug

Installed QuestDB on a rather fresh MacOS (running on ARM64) via brew and I'm getting an error when starting it.
Installation:
```
➜  questdb git:(feats/date-trunc/master) brew install questdb
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and hazelcast/hz).
==> New Formulae
autocannon                                            difftastic                                            ifacemaker                                            kmod                                                  mariadb@10.6
==> Updated Formulae
Updated 196 formulae.
==> Deleted Formulae
griffon
==> New Casks
accord                        anypointstudio                bettermouse                   free-gpgmail                  kdenlive                      osp-tracker                   polymc                        postman-agent                 readyapi
==> Updated Casks
Updated 230 casks.

==> Downloading https://ghcr.io/v2/homebrew/core/openjdk/11/manifests/11.0.14.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openjdk/11/blobs/sha256:324343594a56ee43fd2f0064cf29f63edfa537e4dc4ab481d6d7be868a51d0cd
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:324343594a56ee43fd2f0064cf29f63edfa537e4dc4ab481d6d7be868a51d0cd?se=2022-04-04T12%3A05%3A00Z&sig=w0A1vYCpjgecCCaav8WfCb%2BEX44SF%2BgWr1zeHwuTxIU%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/questdb/manifests/6.2.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/questdb/blobs/sha256:da206250457617c9f6f09c3547387ddcaf5c41f83a1c37ed6b3730e3841e67eb
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:da206250457617c9f6f09c3547387ddcaf5c41f83a1c37ed6b3730e3841e67eb?se=2022-04-04T12%3A05%3A00Z&sig=uGjP7Zcolwx74TZnFXiE76AHyP0zxjqwCDexpm%2Bc%2Bzc%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Installing dependencies for questdb: openjdk@11
==> Installing questdb dependency: openjdk@11
==> Pouring openjdk@11--11.0.14.1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/openjdk@11/11.0.14.1: 677 files, 298.4MB
==> Installing questdb
==> Pouring questdb--6.2.1.arm64_big_sur.bottle.tar.gz
==> Caveats
To start questdb now and restart at login:
  brew services start questdb
Or, if you don't want/need a background service you can just run:
  questdb start
==> Summary
🍺  /opt/homebrew/Cellar/questdb/6.2.1: 7 files, 6MB
==> Running `brew cleanup questdb`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Caveats
==> questdb
To start questdb now and restart at login:
  brew services start questdb
Or, if you don't want/need a background service you can just run:
  questdb start
```
I didn't want to run QuestDB as a service hence I did what brew told me to do: `questdb start`. However I got this error:
```
➜  questdb git:(feats/date-trunc/master) questdb start

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                        www.questdb.io

JAVA: /Users/jara/.sdkman/candidates/java/current/bin/java
Created QuestDB ROOT directory: /usr/local/var/questdb
mkdir: /usr/local/var: Permission denied
mkdir: /usr/local/var: Permission denied
/opt/homebrew/Cellar/questdb/6.2.1/libexec/questdb.sh: line 187: /usr/local/var/questdb/log/stdout-2022-04-04T13-58-18.txt: No such file or directory
```

I'm a total MacOS noob, but I guess the brew package is running on behalf of a non-priviledged user who cannot write to /usr/local/var. Or perhaps it's the MacOS security system playing a role? I'm not sure really. 

### Environment

```markdown
- **QuestDB version**: 6.2.1 (what brew gave me)
- **OS**: MacOS 12.3 Monterey @ ARM64
```

**Comment by jerrinot** [comment]
This is likely the culprit: https://github.com/questdb/questdb/blob/c16b1e0a2654b266329e99ea8e6c7a0ee4f1bc04/core/src/main/bin/questdb.sh#L34

It's assuming the default installation path is `/usr/local/var/questdb`, but when installed via brew on ARM then the path is different: `/opt/homebrew/opt/questdb`. The when QuestDB is starting it tried to create a bunch of subdirectories in a non-existing based directory -> errors. 

According to [homebrew documentation](https://docs.brew.sh/Installation) the brew basepath is different for Intel and ARM architectures: `This script installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for Apple Silicon and /home/linuxbrew/.linuxbrew for Linux) so that [you don’t need sudo](https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad) when you brew install.`

**Comment by jerrinot** [comment]
Just a note to avoid forgetting: Once this is fixed we should update [documentation](https://questdb.io/docs/get-started/homebrew#install-questdb) too - it's referring to the brew installation path:
<img width="879" alt="image" src="https://user-images.githubusercontent.com/158619/161544809-658adbc6-f78f-49f0-895f-96ef0b315f4c.png">

**Comment by pivovarit** [comment]
> we should update [documentation](https://questdb.io/docs/get-started/homebrew#install-questdb) too

Even better: create a periodic job that would ensure that such a basic operation succeeds (GitHub Actions is free for public projects, wink wink)

**Comment by jerrinot** [comment]
good idea!

FYI: the brew formula is [fixed](https://github.com/Homebrew/homebrew-core/pull/98593), this issue is left open as a reminder to update the documentation. And you just reminded it to me, thanks for that!

**Comment by jerrinot** [comment]
the documentation was fixed too. a long time ago.
