### ISSUE TITLE
Put PGwire in read-only mode

### ISSUE THREAD

**Issue by mariusgheorghies** [questdb/questdb#2005]
### Describe the solution you'd like.

QuestDB does not have RBAC yet and I would like to expose pgwire in read-only mode without putting the whole db in read-only. (I still want to be able to ingest via ILP)

**Comment by jerrinot** [comment]
a self-note: this looks like an interesting place: https://github.com/questdb/questdb/blob/2fcf366fe8cc29da8a08ad4f4cea36d563703c7b/core/src/main/java/io/questdb/cutlass/pgwire/PGBasicAuthenticator.java#L60
