### ISSUE TITLE
UX: Consider printing port numbers when starting

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#2011]
### Is your feature request related to a problem?

As a new user I'm starting questdb (installed via `brew`) and all I see is this:
```
$ questdb start

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                        www.questdb.io

JAVA: /Users/jara/.sdkman/candidates/java/current/bin/java
QuestDB server 6.2.1
Copyright (C) 2014-2022, all rights reserved.
```
 I need to guess/search documentation/remember on what port(s) is qdb listening. 

### Describe the solution you'd like.

It would be nice if questdb printed ports where it listens to. that would make the life of new users simpler. 

### Describe alternatives you've considered.

RTFM :)

### Additional context.

There is a possible issue: Printing its own port could be misleading when running as a container. Because the port where qdb is listening at is not necessarily the same as the port where it's exposed.

**Comment by bluestreak01** [comment]
Port numbers are printed into log file. Perhaps we can print URL on a documentation page ?

**Comment by jerrinot** [comment]
That could work too. 

As a user I like when servers print their own URL/ports. 
Something like:
```
- postgres endpoint: ...
- rest endpoint: ...
- web console URL: ...
```
As a user, I find it very convenient. But it can get chatty easily and there is this issue with containers where it can be straight misleading. And adding caveats means more noise. So perhaps a link to docu "Getting Started" is a good compromise.

**Comment by jerrinot** [comment]
I just realized just printing the path to logfile might be the best. the logfile already contains the port numbers. and it's useful in other cases too.
