### ISSUE TITLE
6.2.1 version have problem accessed from postgres and  odbc

### ISSUE THREAD

**Issue by Luyang2902** [questdb/questdb#2026]
### Describe the bug

![image](https://user-images.githubusercontent.com/98975457/162906915-f5ba9c03-2500-4e31-8ad7-b59e79c0ecf3.png)

the 6.2.0 version can access from postgres odbc ,but 6.2.1 can't

I can get records from odbc and "pass through"  in 6.2.0 version ,but failed in 6.2.1

### Environment

```markdown
- **QuestDB version 6.2.1:
- **OS**: windows and linux
- **Browser**:
```

### Additional context

![image](https://user-images.githubusercontent.com/98975457/162907674-b8a3c8c2-6e21-439a-8b20-205cbca63459.png)

**Comment by bluestreak01** [comment]
What version of PostgreSQL ODBC driver do you have ?
