### ISSUE TITLE
Available in Azure?

### ISSUE THREAD

**Issue by fabiomilheiro** [questdb/questdb#2034]
### Describe the solution you'd like.

Can we make QuestDB available in Azure please?

### Describe alternatives you've considered.

Creating a new GCP or AWS account creates a bureaucratic hassle I'd prefer to avoid. I'm trying to keep everything in Azure.

### Additional context.

If you have already considered this, do you have an ETA please?

**Comment by jerrinot** [comment]
hi @fabiomilheiro, thank you for opening this request. Can you please elaborate on what exactly you mean by "Making in Available in Azure"? Do you mean a marketplace? A ready-to-use disk image? 

Depending on your deployment strategy you can use QuestDB on Azure right now: If you are using bare VM instances then you can [download the binaries](https://questdb.io/docs/get-started/binaries), you can also use the quest db [container image](https://questdb.io/docs/get-started/docker) or [Kubernetes](https://questdb.io/docs/deployment/kubernetes)

**Comment by fabiomilheiro** [comment]
Thanks, @jerrinot. Initially, I was just thinking of getting a something ready to deploy like the droplets in Digital Ocean or equivalent solutions but you are correct and I did just that yesterday, actually. Cheers!
