### ISSUE TITLE
DDL should be disabled via /exp

### ISSUE THREAD

**Issue by HeZean** [questdb/questdb#2045]
### Describe the bug

Currently we can execute DDL commands via `/exp` API endpoint, which doesn't seem to make sense, since `/exp` is for exporting data, the correct way to execute a DDL command should be using the `/exec` endpoint.

I'm not sure if this is a feature or a bug, the docs doesn't mention this. If I'm wrong, please close this issue.

### To reproduce

1. Assume that the QDB is running on port `9000`, and there doesn't exist a table named `tab`
2. Run the command
   ```bash
   ~ curl "http://localhost:9000/exp?query=create%20table%20tab%20(x%20int)"
   DDL Success
   ```
3. The DDL command is executed without any error. Then check the tables, you can find a table was created
   ```bash
   ~ curl "http://localhost:9000/exec?query=show%20tables"
   {"query":"show tables","columns":[{"name":"table","type":"STRING"}],"dataset":[["tab"], 
   ["telemetry"],["telemetry_config"]],"count":3}
   ```

### Expected Behavior

Some error prompts that one shouldn't run a DDL command via `/exp`

### Environment

- **QuestDB version**: 6.2.1
- **OS**: macOS 12.3.1
- **Browser**: Chrome 99.0.4844.83 / cURL 7.79.1

**Comment by MatthewLENG2002** [comment]
I'm also not sure if this is a bug or should this be fixed? If it is, can I work on this issue?

**Comment by bluestreak01** [comment]
It’s an oversight, @MatthewLENG2002 it would be awesome if you could help 👍
