### ISSUE TITLE
Aggregate function FIRST is slow and crashes.

### ISSUE THREAD

**Issue by CurriedFloat** [questdb/questdb#2052]
### Describe the bug

After some testing on https://demo.questdb.io/ to confirm what we were seeing in our system.
FIRST seems slow compared to for example AVG.

-- testing on trips table --

select vendor_id, **avg**(passenger_count) from trips group by vendor_id
=>
4 rows in 521ms
Execute: **390.09ms**
Network: 130.91ms
Total: 521ms
Count: 3.88s Compile: 567.46μs

select vendor_id, **first**(passenger_count) from trips group by vendor_id
=>
QuestDB is not reachable [503]

select vendor_id, **first**(cab_type) from trips group by vendor_id
=>
QuestDB is not reachable [503]

select **first**(cab_type) from trips
=>
QuestDB is not reachable [503]

select cab_type from trips limit 1
=>
1 row in 151ms
Execute: **302.39μs**
Network: 150.7ms
Total: 151ms
Count: 2.72s Compile: 227.46μs

-- testing on weather table --

select skyCover, **avg**(visMiles) from weather group by skyCover
=>
5 rows in 123ms
Execute: **2.08ms**
Network: 120.92ms
Total: 123ms
Count: 0 Compile: 631.16μs

select skyCover, **first**(visMiles) from weather group by skyCover
=>
5 rows in 227ms
Execute: **149.43ms**
Network: 77.57ms
Total: 227ms
Count: 0 Compile: 136.96ms

select tempF, **first**(skyCover) from weather group by tempF
=>
103 rows in 308ms
Execute: **152.1ms**
Network: 155.9ms
Total: 308ms
Count: 0 Compile: 139.42ms

select skyCover from weather limit 1
=>
1 row in 82ms
Execute: **232.73μs**
Network: 81.77ms
Total: 82ms
Count: 0 Compile: 183.73μs

select **first**(skyCover) from weather
=>
1 row in 129ms
Execute: **2.78ms**
Network: 126.22ms
Total: 129ms
Count: 1.23μs Compile: 0

### Expected Behavior

AVG beats FIRST by a lot, and FIRST seems to crash on big tables.
My naive assumption would be that FRIST should perform better than it does.

Also in the docs FIRST is only defined for SYMBOL but it seems to work for other types.

> first(SYMBOL) - returns the first value of a SYMBOL column.
https://questdb.io/docs/reference/function/aggregation/#first

### Environment

Chrome browser on live demo site

**Comment by bluestreak01** [comment]
thank you for spotting this, `first` is un-optimised compared to `avg`. We can fix this for sure. 503 on demo is proxy override. There seem to be max time SQL can take is 30s before proxy returns 503 to the web console. So it doesn't crash - just slow

**Comment by bluestreak01** [comment]
thanks for the doc spot too!

**Comment by CurriedFloat** [comment]
I think `last` has the same problems

**Comment by goodroot** [comment]
Both `first` & `last` correctly list their supported types. Also, there's been a solid number of performance related fixes across the board since this issue was declared. 

Closing, but please let us know if you notice anything suboptimal in the current version (`7.3.4`).
