### ISSUE TITLE
when "readonly=true"

### ISSUE THREAD

**Issue by Luyang2902** [questdb/questdb#2059]
### Describe the bug

hi,   when  I ran this program with the config of http security  as  "readonly=true" , the python program can't quit
when I　change the config as "readonly=false" there is no this problem.
import pandas as pd
import psycopg2 as pg
import io
conn = pg.connect(user="admin",
                                  password="quest",
                                  host=" myhost",
                                  port="8812",
                                  database="qdb")
cursor = conn.cursor()
cursor.execute('drop table if exists try   ')
cursor.execute('copy try from "s.csv" ')
conn.commit()
cursor.close()
connection.close() 

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by jerrinot** [comment]
a related PR was merged: https://github.com/questdb/questdb/pull/2061
@Luyang2902 could you please try the latest master? do you know how to do it?

**Comment by pswu11** [comment]
@Luyang2902 the fix mentioned above is included in [our latest release 6.3](https://github.com/questdb/questdb/releases/tag/6.3), would be great if you can test it out and let us know whether this issue still occurs. 🙏🏼

**Comment by bluestreak01** [comment]
closing due to lack of response
