### ISSUE TITLE
Webconsole reports "QuestDB not reachable" when there is SQL execution error

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#2062]
I'm on the latest master(d28ebe906) and when I try to query a non-existing table via webconsole then I'm getting a misleading error: "QuestDB is not reachable [400]"

It appears any kind of an error, including SQL syntax error, is interpreted like this. 
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/158619/165102314-6041f4a5-9dc9-4323-8a31-fff8bec9114c.png">

This is working as expected with 6.2.1:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/158619/165103011-08559fad-2a5e-4ae9-aec3-b35080c494c9.png">

See the HTTP response code is 200 on 6.2.1, but 400 on the master.

**Comment by bluestreak01** [comment]
@argshook there was a recent contribution, which changed HTTP response codes from 200 to 400. I think this is what broke the web console

**Comment by jerrinot** [comment]
@HeZean you are right. I was using new backend code with old console. 
When I rebuild it with the `build-web-console` profile then it behaves as expected. sorry for the false alarm.
