### ISSUE TITLE
Update of org.postgresql to latest v42.3.4 leads to crashes in tests

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#2086]
### Describe the bug

After changing dependencies in core/pom.xml

```
       <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.3.4</version>
            <scope>test</scope>
        </dependency>
```

There were few crash dumps in Azure CI run
[questdb-crash-merge-3902d950f47558eac9816e6b3473aa1b2d553e0c-1-Linux-1.11.log](https://github.com/questdb/questdb/files/8591183/questdb-crash-merge-3902d950f47558eac9816e6b3473aa1b2d553e0c-1-Linux-1.11.log)
[hs_err_pid12150.log](https://github.com/questdb/questdb/files/8591184/hs_err_pid12150.log)

### Environment

```markdown
- **QuestDB version**: 68b00f9
- **OS**: Linux ARM64, Windows
- **Browser**:
```

**Comment by bluestreak01** [comment]
Fixed in https://github.com/questdb/questdb/pull/2087
