### ISSUE TITLE
>= doesn't seem to work for a float point precision 

### ISSUE THREAD

**Issue by rahilbhansali** [questdb/questdb#2095]
### Describe the bug

I have a query which checks if a stock price falls within a specific low-high range. It works well in postgresql. However, when I use the same query in QuestDB, it fails to pick up the price data. 

I've attached the sample for the day's data to this. When you run this on QuestDB, it'll show no results found. However, the right answer is the price data from 7:33am which has the high price of 11.65. If you change the high to >= 11.64 in the query below, it'll work. 

```
SELECT data_price_history_candlestick_minute_symbol.id, data_price_history_candlestick_minute_symbol.created_at, data_price_history_candlestick_minute_symbol.updated_at, data_price_history_candlestick_minute_symbol.date, data_price_history_candlestick_minute_symbol.open, data_price_history_candlestick_minute_symbol.high, data_price_history_candlestick_minute_symbol.low, data_price_history_candlestick_minute_symbol.close, data_price_history_candlestick_minute_symbol.volume, data_price_history_candlestick_minute_symbol.symbol_id 
FROM data_price_history_candlestick_minute_symbol 
WHERE data_price_history_candlestick_minute_symbol.symbol_id IN (224) 
AND data_price_history_candlestick_minute_symbol.date >= '2021-10-07 04:30:00' 
AND to_str(data_price_history_candlestick_minute_symbol.date, 'yyyy-MM-dd') = to_str('2021-10-07 04:30:00', 'yyyy-MM-dd') 
AND data_price_history_candlestick_minute_symbol.date <= '2021-10-07 08:59:00' 
AND (data_price_history_candlestick_minute_symbol.low <= 11.65 
AND data_price_history_candlestick_minute_symbol.high >= 11.65 OR 
data_price_history_candlestick_minute_symbol.open >= 11.65)
AND data_price_history_candlestick_minute_symbol.volume * data_price_history_candlestick_minute_symbol.low >= 7805490
ORDER BY data_price_history_candlestick_minute_symbol.date ASC 
LIMIT 1
```

[data_price_history_candlestick_minute_symbol_202205031406.csv](https://github.com/questdb/questdb/files/8609275/data_price_history_candlestick_minute_symbol_202205031406.csv)

### To reproduce

1. Upload the attached file as a table in questdb and maybe postgresql or another relational database.
2. Run the query in the description above. It'll fail to pick the price data for 07:33am.

[data_price_history_candlestick_minute_symbol_202205031406.csv](https://github.com/questdb/questdb/files/8609292/data_price_history_candlestick_minute_symbol_202205031406.csv)
 

### Expected Behavior

It should pick the price data for 7:33am since the price is 11.65. 

### Environment

```markdown
- **6.2.1**:
- **Mac Monterrey**:
- **Google Chrome**:
```

**Comment by jerrinot** [comment]
hello @rahilbhansali,

I tried to reproduce the issue. I'm on QuestDB 6.2.1. I imported the CVS file by running `curl -F data=@data_price_history_candlestick_minute_symbol_202205031406.csv 'http://localhost:9000/imp'`

I used QuestDB web console to run the query and I can see a result being returned: 
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/158619/166553595-3755a260-c05b-49c2-9cdf-205e92ee7ce6.png">

Are you doing anything differently?

**Comment by jerrinot** [comment]
for what is worth: I'd recommend not to use floating point types to represent price. It has inherit precision issues and some numbers cannot be represented at all. The simple/usual workaround is to choose a base unit - for example cents - and use that. Example: Instead of storing 11.65 as a floating type you store 1165 as an integer. This way you avoid floating point precision issues.

**Comment by bziobrowski** [comment]
Issue can be reproduced only if high is a float .
Under the hood record's float is converted to double in LtDoubleVVFunctionFactory and that assigns value slightly lower than the constant argument - 11.65 .

**Comment by rahilbhansali** [comment]
@jerrinot - Appreciate the comments and the thought. I think the issue is the double and the float. My bigger table had the column as a 'Float' but the csv I attached auto-detected the column as a double. I think @bziobrowski's explanation is probably the reason. 

I'll take your recommendation to store it as an integer, appreciate it!! 

Also - apologies for the serious delay in the response, I didn't get a notification so missed the response.
