### ISSUE TITLE
Unhandled Error causing :9003 to report unhealthy status

### ISSUE THREAD

**Issue by ospqsp** [questdb/questdb#2106]
### Describe the bug

not entirely sure as not immediately detected

(sorry!...will upgrade process to more immediately flag unhandled errors/unhealthy status)

i run at terminal prompt :~/qdb/log$ grep -B 20 -ir 'unhandled error \[job=' '.'

### OCCURANCE A:

```
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:08.536226Z I i.q.c.TableWriter sorting o3 [table=EOD]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:08.536535Z I i.q.c.TableWriter sorted [table=EOD]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:08.539416Z I i.q.c.TableWriter merged partition [table=`EOD`, ts=2007-01-01T00:00:00.000000Z, txn=28]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:08.539878Z I i.q.c.TableWriter purged [path=/REDACTED_PATH]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:08.539910Z I i.q.c.p.WriterPool << [table=`EOD`, thread=17]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:08.583007Z I http-server scheduling disconnect [fd=7, reason=12]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:08.583049Z I http-server disconnected [ip=127.0.0.1, fd=7, src=queue]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:11.912711Z I http-server connected [ip=127.0.0.1, fd=7]
./stdout-2022-05-02T05-00-33.txt-oops2: 9
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:12.040412Z I i.q.c.t.TextLoader configured [table=`EOD`, overwrite=false, durable=false, atomicity=2, partitionBy=YEAR, timestamp=TradeDate]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:12.040601Z I i.q.c.t.TextDelimiterScanner not enough lines [table=EOD]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:12.040617Z I i.q.c.h.HttpConnectionContext failed query result cannot be delivered. Kicked out [fd=7, error=not enough lines [table=EOD]]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:12.040684Z I http-server scheduling disconnect [fd=7, reason=14]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:12.045229Z I http-server disconnected [ip=127.0.0.1, fd=7, src=queue]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:17.674614Z I http-server connected [ip=127.0.0.1, fd=7]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:17.674810Z I i.q.c.t.TextLoader configured [table=`EOD`, overwrite=false, durable=false, atomicity=2, partitionBy=YEAR, timestamp=TradeDate]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:17.674961Z I i.q.c.t.TextDelimiterScanner not enough lines [table=EOD]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:17.674973Z I i.q.c.h.HttpConnectionContext failed query result cannot be delivered. Kicked out [fd=7, error=not enough lines [table=EOD]]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:17.675040Z I http-server scheduling disconnect [fd=7, reason=14]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:55:17.676600Z I http-server disconnected [ip=127.0.0.1, fd=7, src=queue]
./stdout-2022-05-02T05-00-33.txt:2022-05-02T05:55:17.676711Z E server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@3a6f2de3, ex=
```

### OCCURANCE B:

```
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:50.649042Z I i.q.c.TableWriter sorting o3 [table=EOD]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:50.649385Z I i.q.c.TableWriter sorted [table=EOD]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:50.653030Z I i.q.c.TableWriter merged partition [table=`EOD`, ts=2007-01-01T00:00:00.000000Z, txn=31]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:50.653576Z I i.q.c.TableWriter purged [path=/REDACTED_PATH/2007.30]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:50.653621Z I i.q.c.p.WriterPool << [table=`EOD`, thread=16]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:50.780798Z I http-server scheduling disconnect [fd=7, reason=12]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:50.780812Z I http-server disconnected [ip=127.0.0.1, fd=7, src=queue]
./stdout-2022-05-02T05-00-33.txt-oops2: 9
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:53.209580Z I http-server connected [ip=127.0.0.1, fd=7]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:53.230886Z I i.q.c.t.TextLoader configured [table=`EOD`, overwrite=false, durable=false, atomicity=2, partitionBy=YEAR, timestamp=TradeDate]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:53.231030Z I i.q.c.t.TextDelimiterScanner not enough lines [table=EOD]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:53.231044Z I i.q.c.h.HttpConnectionContext failed query result cannot be delivered. Kicked out [fd=7, error=not enough lines [table=EOD]]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:53.231111Z I http-server scheduling disconnect [fd=7, reason=14]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:53.235641Z I http-server disconnected [ip=127.0.0.1, fd=7, src=queue]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:59.868201Z I http-server connected [ip=127.0.0.1, fd=7]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:59.995069Z I i.q.c.t.TextLoader configured [table=`EOD`, overwrite=false, durable=false, atomicity=2, partitionBy=YEAR, timestamp=TradeDate]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:59.995214Z I i.q.c.t.TextDelimiterScanner not enough lines [table=EOD]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:59.995224Z I i.q.c.h.HttpConnectionContext failed query result cannot be delivered. Kicked out [fd=7, error=not enough lines [table=EOD]]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:59.995279Z I http-server scheduling disconnect [fd=7, reason=14]
./stdout-2022-05-02T05-00-33.txt-2022-05-02T05:57:59.999182Z I http-server disconnected [ip=127.0.0.1, fd=7, src=queue]
./stdout-2022-05-02T05-00-33.txt:2022-05-02T05:57:59.999259Z E server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@3a393455, ex=
```

### Expected Behavior

no unhandled error.

### Environment

```markdown
- **QuestDB version**: 6.2.1
- **OS**: ubuntu
- **Browser**: edge / python request lib
```

### Additional context

please let me know how i can better log these issues--or create a self reporting module for errors...?

**Comment by ospqsp** [comment]
another example--perhaps unrelated...same result though.


./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.MCSequence.root(MCSequence.java:31)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.FanOut.root(FanOut.java:128)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.AbstractSSequence.root(AbstractSSequence.java:71)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.MPSequence.root(MPSequence.java:31)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.AbstractSSequence.root(AbstractSSequence.java:71)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.MCSequence.root(MCSequence.java:31)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.FanOut.root(FanOut.java:128)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.AbstractSSequence.root(AbstractSSequence.java:71)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp2022-05-06T17:30:24.675135Z I i.q.c.h.HttpConnectionContext kicked out [fd=69]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.675141Z I http-server scheduling disconnect [fd=69, reason=5]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.675174Z I http-server disconnected [ip=127.0.0.1, fd=69, src=queue]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.676834Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-5, sql=
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.813688Z I http-server connected [ip=127.0.0.1, fd=69]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.934987Z I i.q.c.h.p.JsonQueryProcessorState [69] exec [q='
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate']
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.935015Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-6, sql=
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.935577Z I i.q.g.SqlCompiler plan [q=`select-group-by TradeDate, count() count from (select [TradeDate, RIC, Bid, Ask] from PJ timestamp (TradeDate) where RIC ~ 'SPX' and RIC != '.SPX' and Bid != null and Ask != null)`, fd=69]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.956989Z I i.q.c.h.p.JsonQueryProcessorState [69] execute-new [skip: 0, stop: 1000]
./stdout-2022-05-06T17-29-09.txt:2022-05-06T17:30:24.963746Z E server-main unhandled error [job=io.questdb.cairo.sql.async.PageFrameReduceJob@60957c0f, ex=

**Comment by ospqsp** [comment]
that last error is on 6.3

**Comment by bluestreak01** [comment]
oh, sorry! We'll fix asap

**Comment by bluestreak01** [comment]
it would also be good to get log lines just after error message (last line in your log)

**Comment by ospqsp** [comment]
restating the log with +50 lines post unhandled error notice



./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.MCSequence.root(MCSequence.java:31)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.FanOut.root(FanOut.java:128)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.AbstractSSequence.root(AbstractSSequence.java:71)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.MPSequence.root(MPSequence.java:31)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.AbstractSSequence.root(AbstractSSequence.java:71)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.MCSequence.root(MCSequence.java:31)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.FanOut.root(FanOut.java:128)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.AbstractSSequence.root(AbstractSSequence.java:71)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp2022-05-06T17:30:24.675135Z I i.q.c.h.HttpConnectionContext kicked out [fd=69]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.675141Z I http-server scheduling disconnect [fd=69, reason=5]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.675174Z I http-server disconnected [ip=127.0.0.1, fd=69, src=queue]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.676834Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-5, sql=
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.813688Z I http-server connected [ip=127.0.0.1, fd=69]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.934987Z I i.q.c.h.p.JsonQueryProcessorState [69] exec [q='
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate']
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.935015Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-6, sql=
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.935577Z I i.q.g.SqlCompiler plan [q=`select-group-by TradeDate, count() count from (select [TradeDate, RIC, Bid, Ask] from PJ timestamp (TradeDate) where RIC ~ 'SPX' and RIC != '.SPX' and Bid != null and Ask != null)`, fd=69]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.956989Z I i.q.c.h.p.JsonQueryProcessorState [69] execute-new [skip: 0, stop: 1000]
./stdout-2022-05-06T17-29-09.txt:2022-05-06T17:30:24.963746Z E server-main unhandled error [job=io.questdb.cairo.sql.async.PageFrameReduceJob@60957c0f, ex=
./stdout-2022-05-06T17-29-09.txt-java.lang.IndexOutOfBoundsException: start 0, end 10, length 9
./stdout-2022-05-06T17-29-09.txt-       at java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1716)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:631)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.StringBuilder.append(StringBuilder.java:213)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.StringBuilder.append(StringBuilder.java:85)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:578)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.StringBuilder.append(StringBuilder.java:204)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.std.str.StringSink.put(StringSink.java:82)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.std.str.AbstractCharSequence.getString(AbstractCharSequence.java:35)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.std.str.AbstractCharSequence.toString(AbstractCharSequence.java:58)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.std.Chars.toString(Chars.java:657)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.SymbolMapReaderImpl.fetchAndCache(SymbolMapReaderImpl.java:216)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.SymbolMapReaderImpl.cachedValue(SymbolMapReaderImpl.java:209)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.SymbolMapReaderImpl.valueOf(SymbolMapReaderImpl.java:189)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.sql.PageAddressCacheRecord.getSym(PageAddressCacheRecord.java:237)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.columns.SymbolColumn.getSymbol(SymbolColumn.java:50)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.SymbolFunction.getStr(SymbolFunction.java:115)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.regex.MatchStrFunctionFactory$MatchConstPatternFunction.getBool(MatchStrFunctionFactory.java:99)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.bool.AndFunctionFactory$MyBooleanFunction.getBool(AndFunctionFactory.java:86)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.bool.AndFunctionFactory$MyBooleanFunction.getBool(AndFunctionFactory.java:86)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.bool.AndFunctionFactory$MyBooleanFunction.getBool(AndFunctionFactory.java:86)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.table.AsyncFilteredRecordCursorFactory.filter(AsyncFilteredRecordCursorFactory.java:164)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.sql.async.PageFrameReduceJob.reduce(PageFrameReduceJob.java:153)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:120)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.sql.async.PageFrameReduceJob.run(PageFrameReduceJob.java:174)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.Worker.run(Worker.java:116)
./stdout-2022-05-06T17-29-09.txt-]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.969468Z I i.q.c.h.p.JsonQueryProcessorState [69] timings [compiler: 21941514, count: 0, execute: 34522684, q=`
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate`]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.969533Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=69, lastRequestBytesSent=528, nCompletedRequests=3, totalBytesSent=20441]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.969608Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-6, sql=
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.817434Z I http-server connected [ip=127.0.0.1, fd=840]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.817849Z I i.q.c.h.p.JsonQueryProcessorState [69] exec [q='
./stdout-2022-05-06T17-29-09.txt-
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from EOD where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate']
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.817874Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-5, sql=
./stdout-2022-05-06T17-29-09.txt-
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from EOD where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.818261Z I i.q.c.p.ReaderPool open 'EOD' [at=0:0]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.818921Z I i.q.g.SqlCompiler plan [q=`select-group-by TradeDate, count() count from (select [TradeDate, RIC, Bid, Ask] from EOD timestamp (TradeDate) where RIC ~ 'SPX' and RIC != '.SPX' and Bid != null and Ask != null)`, fd=69]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.841482Z I i.q.c.h.p.JsonQueryProcessorState [69] execute-new [skip: 0, stop: 1000]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.846208Z I i.q.c.TableReader open partition /home/ubuntu/qdb/db/EOD/2005 [rowCount=1273, partitionNameTxn=-1, transientRowCount=1780898, partitionIndex=0, partitionCount=18]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.846287Z I i.q.c.TableReader open partition /home/ubuntu/qdb/db/EOD/2006 [rowCount=1281, partitionNameTxn=-1, transientRowCount=1780898, partitionIndex=1, partitionCount=18]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.846366Z I i.q.c.TableReader open partition /home/ubuntu/qdb/db/EOD/2007.2 [rowCount=161380, partitionNameTxn=2, transientRowCount=1780898, partitionIndex=2, partitionCount=18]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.846416Z I i.q.c.TableReader open partition /home/ubuntu/qdb/db/EOD/2008 [rowCount=214897, partitionNameTxn=-1, transientRowCount=1780898, partitionIndex=3, partitionCount=18]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.846454Z I i.q.c.TableReader open partition /home/ubuntu/qdb/db/EOD/2009 [rowCount=237643, partitionNameTxn=-1, transientRowCount=1780898, partitionIndex=4, partitionCount=18]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.846490Z I i.q.c.TableReader open partition /home/ubuntu/qdb/db/EOD/2010 [rowCount=455371, partitionNameTxn=-1, transientRowCount=1780898, partitionIndex=5, partitionCount=18]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.846525Z I i.q.c.TableReader open partition /home/ubuntu/qdb/db/EOD/2011 [rowCount=445714, partitionNameTxn=-1, transientRowCount=1780898, partitionIndex=6, partitionCount=18]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:32.846560Z I i.q.c.TableReader open partition /home/ubuntu/qdb/db/EOD/2012 [rowCount=543246, partitionNameTxn=-1, transientRowCount=1780898, partitionIndex=7, partitionCount=18]

**Comment by ospqsp** [comment]
let me know if you need more

**Comment by bluestreak01** [comment]
thank you, this is enough for now. Just to confirm that last log is 6.3 ?

**Comment by ospqsp** [comment]
> thank you, this is enough for now. Just to confirm that last log is 6.3 ?

many thanks vlad--you're correct. the last log snippet is 6.3, the others were 6.2.1

**Comment by bluestreak01** [comment]
i think i know what the issue is, could you try adding this config to your server.conf as a workaround:

```
cairo.sql.parallel.filter.enabled=false
```

**Comment by bluestreak01** [comment]
@puzpuzpuz there is issue using symbol functions with async offload, multiple threads are using same table reader instance.

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz there is issue using symbol functions with async offload, multiple threads are using same table reader instance.

Is that issue related with this one?

**Comment by bluestreak01** [comment]
i'll tackle it asap, fairly serious issue

**Comment by puzpuzpuz** [comment]
OK, I missed the latest messages. Filter functions being stateless is too good to be true.
