### ISSUE TITLE
An CAST ERROR occurred while writing data using ILP

### ISSUE THREAD

**Issue by yiwojiu** [questdb/questdb#2110]
### Describe the bug

For high write performance, I use the ILP to write data.
When I have created a table and then write data through ILP, there will be errors related to value type cast.
From the release note，I know in questdb-6.3 user can set the default column type.However, if there are multiple numeric types in different tables, such as byte/int/short/float/double/long , this configuration may not be applicable. So I want to create tables first and then write data. Finally, this cast error appears.

### To reproduce

1. Pre created table：
```sql
CREATE TABLE IF NOT EXISTS xush_string  
  (objectName symbol,tagName symbol, value string,quality short, timestamp TIMESTAMP)   
  timestamp(timestamp) PARTITION BY HOUR
```
2. use java ILP to send message to questdb:
```java
try {
              LineTcpSender sender = new LineTcpSender(Net.parseIPv4(hostIPv4), port, bufferCapacity);
              String line="xush_string,tagName=tag1,objectName=object1 value=\"yes\",quality=192 1651910400000000000\n";
              sender.put(line);
              sender.flush();
        } catch (Exception e) {
              e.printStackTrace();
        }
```
3. in the server log can find errors:
`2022-05-09T02:36:43.657599Z E i.q.c.l.t.LineTcpConnectionContext [7] could not process line data [table=xush_string, msg=cast error for line protocol float [columnWriterIndex=3, columnType=SHORT], errno=0]
2022-05-09T02:36:43.657618Z E i.q.c.l.t.LineTcpConnectionContext [7] could not parse measurement, NONE at 87, line (may be mangled due to partial parsing): 'xush_string,tagName=tag1,objectName=object1 value="yes",quality=192 1651910400000000000'`

### Expected Behavior

The numeric type in line can be normally parsed to the corresponding type of table field when using ILP。

### Environment

```markdown
- **QuestDB version**:6.3
- **OS**: CentOS Linux release 7.9.2009 (Core)
- **Browser**:Microsoft Edge 87.0.664.75
```

**Comment by puzpuzpuz** [comment]
Hello,

You should be using `i` suffix for all integer types, like long or short. If you don't use the suffix, the type is assumed to be a floating point type, `double`. So, your ILP message should look something like the following:
```
xush_string,tagName=tag1,objectName=object1 value="yes",quality=192i 1651910400000000000\n
```

**Comment by yiwojiu** [comment]
> Hello,
> 
> You should be using `i` suffix for all integer types, like `long` or `short`. If you don't use the suffix, the type is assumed to be a floating point type, `double`. So, your ILP message should look something like the following:
> 
> ```
> xush_string,tagName=tag1,objectName=object1 value="yes",quality=192i 1651910400000000000\n
> ```

thanks a lot!
Can you give a message line example of type char?

**Comment by puzpuzpuz** [comment]
Char column should be as simple as `char_col1="a",char_col2="z"`
