### ISSUE TITLE
Support for stdin bulk copy?

### ISSUE THREAD

**Issue by ckennerknecht** [questdb/questdb#2111]
Hii devs and community,

For my bachelor thesis I need to export ~1 trillion rows historical data in a proprietary storage format to a TSDB for some benchmarks.
I have already implemented a C++ exporter to PostgreSQL/TimescaleDB with the [libpqxx](https://github.com/jtv/libpqxx) library and now I would also like to benchmark QuestDB.

I have hoped that I can target my local QuestDB instance with the same exporter, but unfortunately I cannot use the recommended way of libpqxx for bulk inserting data ([pqxx::stream_to::write_values](https://libpqxx.readthedocs.io/en/7.1.1/a01109.html#a0535e4526cd9b17c87376bb206895504)) since it uses a stdin stream as copy source:
![image](https://user-images.githubusercontent.com/47369419/167460528-336217fe-399e-4bcb-b373-be8ae9468c61.png)

Could you support this feature in the future?

For now, can I somehow disable the copy root check for csv files on the local disk or is there any quick workaround?
Or do you have any tips on what's the fastest way to get data from Postgres to QuestDB?
Otherwise I am going to implement an exporter with QuestDB´s official C++ Client. 

Thank you for your help!
Chris

**Comment by bziobrowski** [comment]
Hi @ckennerknecht . 
While COPY FROM filepath works (for CSV format) , COPY FROM STDIN is not implemented . 
If you plan to use the former then you need to set cairo.sql.copy.root in server.conf. 
Best way to import data to QDB is through ILP or CSV  . 
I'm working on speeding up loading of huge files to partitioned tables . 
Regards,
Bolek

**Comment by ckennerknecht** [comment]
Alright, thank you.

**Comment by Roh-codeur** [comment]
Hi @bziobrowski 

thanks for your work on this database, this is quite awesome indeed. 

Do we know if and when "COPY FROM STDIN" will be implemented, please?

thanks! 
Roh
