### ISSUE TITLE
Comparison between "infinities" isn't as expected

### ISSUE THREAD

**Issue by HeZean** [questdb/questdb#2112]
### Describe the bug

Consider such query:
```sql
select 'inf'::real = 'inf'::double precision  -- true in psql, regardless the precision of inf
select cast('Infinity' as float) = cast('Infinity' as double)  -- false in QDB, even when they are in the same type
```

the behavior of `inf = inf` is different from both Java (follows IEEE754):
```java
Float.POSITIVE_INFINITY == Double.POSITIVE_INFINITY  // true, vice versa for negative
```
and Postgres ("Ideally, QuestDB should behave as Postgres.")

### Expected Behavior

Should at least return true for the following examples:
```sql
select cast('Infinity' as float) = cast('Infinity' as double);
select cast('Infinity' as float) = cast('Infinity' as float);
select cast('Infinity' as double) = cast('Infinity' as double);
```
An alternative solution: provide some function like `is_infinity(float)` + `is_infinity(double)`

### Environment

- **QuestDB version**: 6.3

### Additional context

[IEEE 754](https://irem.univ-reunion.fr/IMG/pdf/ieee-754-2008.pdf): Ch 6.1 (pp. 34) may be helpful.

**Comment by HeZean** [comment]
@jerrinot could you please help add more related information about the standards? I believe any contributor who want to solve this will appreciate it :)

BTW, I couldn't find any official document that specifies the equivalent comparisons between infinities, only discussions in StackOverflow or so were found.

**Comment by HeZean** [comment]
For some related discussions, please see #2109

**Comment by jerrinot** [comment]
@HeZean I am certainly not an expert, but I found [this JavaDoc](https://github.com/openjdk/jdk/blob/9835678a8658110cd2dac489cf55ab3d9074ea6d/src/java.base/share/classes/java/lang/Double.java) to be a decent intro to IEEE 754 surprises. 

As a general rule: We aim to behave the same as Postgres whenever it's possible. Postgres does not always honour IEEE 754. If there is a conflict between IEEE 754 spec and Postgres behaviour I would lean towards doing the same thing as Postgres does.

**Comment by KevinChen16** [comment]
Hey @jerrinot! I would like to solve this, but could you please tell me where the '=' is used to be calculated in the main code? Thanks a lot!

**Comment by jerrinot** [comment]
hi @KevinChen16 that's awesome! 

The factory for checking equality of two doubles is [this](https://github.com/questdb/questdb/blob/a9e369826f3e1923194926a16366b31f4fb64392/core/src/main/java/io/questdb/griffin/engine/functions/eq/EqDoubleFunctionFactory.java#L40) But my guess is that it never makes it there. To fix this you will likely have to change the [expression parser](https://github.com/questdb/questdb/blob/30e7c63241b7a3eb474d3a57b6c78bd315b86f74/core/src/main/java/io/questdb/griffin/ExpressionParser.java#L161) There is already a [special treatment](https://github.com/questdb/questdb/blob/30e7c63241b7a3eb474d3a57b6c78bd315b86f74/core/src/main/java/io/questdb/griffin/ExpressionParser.java#L822) for values like `NaN` so chances are you will have to add a special treatment for Infinity too. Whether that's the best approach to fix this, I am not sure. I'm not too familiar with this part of the code, but it looks like a good start. Debugger is your friend! :)

**Comment by KevinChen16** [comment]
> hi @KevinChen16 that's awesome!
> 
> The factory for checking equality of two doubles is [this](https://github.com/questdb/questdb/blob/a9e369826f3e1923194926a16366b31f4fb64392/core/src/main/java/io/questdb/griffin/engine/functions/eq/EqDoubleFunctionFactory.java#L40) But my guess is that it never makes it there. To fix this you will likely have to change the [expression parser](https://github.com/questdb/questdb/blob/30e7c63241b7a3eb474d3a57b6c78bd315b86f74/core/src/main/java/io/questdb/griffin/ExpressionParser.java#L161) There is already a [special treatment](https://github.com/questdb/questdb/blob/30e7c63241b7a3eb474d3a57b6c78bd315b86f74/core/src/main/java/io/questdb/griffin/ExpressionParser.java#L822) for values like `NaN` so chances are you will have to add a special treatment for `Infinity` too. Whether that's the best approach to fix this, I am not sure. I'm not too familiar with this part of the code, but it looks like a good start. Debugger is your friend! :)

Thanks! And that's what I have just done -- adding special treatment for `Infinity`, and I think I will make a PR in minutes or 1 hour. I hope that you can check it, thanks!
