### ISSUE TITLE
Support for string_agg

### ISSUE THREAD

**Issue by kallewesth** [questdb/questdb#2118]
### Is your feature request related to a problem?

I'd like to be able aggregate distinct values of a column into a string.

### Describe the solution you'd like.

Add an aggregating function which does the equivalent of what `string_agg` does in PostgreSQL. The `count_distinct` function almost does what I want, but instead of counting the different distinct values, I'd like to get them. Alternative would be adding something like `array_agg`, but if I understood things correctly, array types isn't well supported in questdb.

### Describe alternatives you've considered.

I do the aggregation now in a layer above, which isn't the most scalable solution and brings some overhead.

**Comment by bluestreak01** [comment]
To help us understand broader use case and clear assumptions, do you mind providing an example of `string_agg` in a SQL that `SELECT DISTINCT value from table` cannot substitute ?

**Comment by kallewesth** [comment]
If `SELECT DISTINCT value, sum(number) as count from table` would return this:
```
value    | number
---------+-----------
x        | 10
y        | 20
z        | 30
```
Then I'd like to be able to do something like `SELECT string_agg(DISTINCT value, ',') as values, sum(number) as total from table`:
```
 values   | total
----------+-----------
x,y,z     | 60
```
Today I could do `SELECT count_distinct(value) as values, sum(number) as total from table`:
```
values | total
-------+------
3      | 60
```
I don't know what makes most sense, if it should be named like `string_agg_distinct` and only support distinct values or if it should be more generic and accept duplicates.

**Comment by KevinChen16** [comment]
Hi @bluestreak01 and @kallewesth ! If this issue could be considered a valuable feature, could I have the chance to realize it? Thanks!

**Comment by bluestreak01** [comment]
Thank you @kallewesth 

sure, @KevinChen16 you can have a go!

My concern is with limits, what if there is 1M distinct values? We might need to restrict the implementation from potentially destroying instance.

**Comment by KevinChen16** [comment]
> Thank you @kallewesth
> 
> sure, @KevinChen16 you can have a go!
> 
> My concern is with limits, what if there is 1M distinct values? We might need to restrict the implementation from potentially destroying instance.

I think we can count the number of strings that need to be aggregated in advance and throw failure when the amount is larger than a boundary value? Or do you have any better thoughts? Thanks!

**Comment by kallewesth** [comment]
> > Thank you @kallewesth
> > sure, @KevinChen16 you can have a go!
> > My concern is with limits, what if there is 1M distinct values? We might need to restrict the implementation from potentially destroying instance.
> 
> I think we can count the number of strings that need to be aggregated in advance and throw failure when the amount is larger than a boundary value? Or do you have any better thoughts? Thanks!

Yes that's a valid point, some boundary value would be good. Thanks a lot @KevinChen16 for picking this up!

**Comment by KevinChen16** [comment]
Hi @kallewesth! I had some ideas about the issue now, but I wonder where I should add this feature, in other words, what file path should I use to put the new function. Thank you!

**Comment by KevinChen16** [comment]
This issue couldn't be fixed soon I'm afraid. Currently, I'm preparing for my final exams -- I'll try to be back on this in my summer vacation (in about 1mo), if anyone has a brilliant idea and cannot wait to have it fixed, please pick it up.

**Comment by devcydo** [comment]
Hi! I would like to take this issue but I can see that is already in progress, is someone else working on it?

**Comment by KevinChen16** [comment]
> Hi! I would like to take this issue but I can see that is already in progress, is someone else working on it?

Sure! Feel free to take this issue!

**Comment by bziobrowski** [comment]
FYI, string_agg  does work as a 'not-keyed' aggregate :
```sql
select string_agg(s, ',') from tab;
```
but it doesn't work as 'keyed', e.g. 
```sql
select k, string_agg(s, ',') from tab group by k;
--returns 'value type is not supported: STRING' error
```
because FastMap can't handle it .

**Comment by Zahlii** [comment]
Came across this issue, I started working on a similar string aggregation in https://github.com/questdb/questdb/pull/2388 hitting the same roadblock with FastMap

**Comment by mohana888** [comment]
value    | count
---------+-----------
x        | 10
y        | 20
z        | 30
Then I'd like to be able to do something like SELECT string_agg(DISTINCT value, ',') as values, sum(number) as total from table:

 values   | total
----------+-----------
x,y,z     | 60

**Comment by BVAnderson** [comment]
> value | count
> ---------+-----------
> x | 10
> y | 20
> z | 30

@mohana888 , I'm going to make a small tweak to your example that highlights what missing. That table of data would do exactly what you want with regular string_agg(). But if we add a row, it highlights why this functionality would be really helpful.


value | count
---------+-----------
x | 10
y | 20
z | 30
z | 15

With the String_agg() we have now this will return 

values | total
----------+-----------
x,y,z,z | 75

What we would like to see is a String_agg_distinct() so that the results come back like this

values | total
----------+-----------
x,y,z | 75

**Comment by javier** [comment]
String_agg now works with keyd groups, but string_agg(distinct col) is not supported just yet, so re-opening this to be able to track

**Comment by puzpuzpuz** [comment]
A heads-up: `string_distinct_agg()` function which acts like `string_agg(DISTINCT col_name)` in Postgres will be added in #5000
