### ISSUE TITLE
Subquery failed for count(*)

### ISSUE THREAD

**Issue by HeZean** [questdb/questdb#2121]
### Describe the bug

When placing a subquery as the argument of `long_sequence`, it may fails.

### To reproduce

On https://demo.questdb.io/, you can use the 'trips' table to test it:
```sql
select x from long_sequence(select count(*) from 'trips');
```
the error message was `too few arguments for '*' [found=0,expected=2]`

### Expected Behavior

Executes as
```sql
select x from long_sequence(1634599313);
```

### Environment

```markdown
https://demo.questdb.io/
```

**Comment by ideoma** [comment]
`long_sequence` function accepts constant argument only at the moment as it's mostly used in tests.

What is your use case for it to accept variable argument?

**Comment by HeZean** [comment]
> `long_sequence` function accepts constant argument only at the moment as it's mostly used in tests.
> 
> What is your use case for it to accept variable argument?

Only to reproduce #2063, not in the production env.

Just to second confirm that, is `long_sequence` designed not to parse any inner braces?
I will close this issue then, or maybe we can have some modifications to make it support that :)

**Comment by ideoma** [comment]
It does parse inner braces as far as I can tell, but even if it doesn't and then fixed next problem will be that `select count(*) from 'trips'` is not a constant and in fact in QuestDB world it's not even a scalar, so there are few problems to make it work.

**Comment by HeZean** [comment]
Yeah I understand, thanks for pointing that out. Users can bypass this anyway, by running multiple queries.
