### ISSUE TITLE
unhandled error

### ISSUE THREAD

**Issue by ospqsp** [questdb/questdb#2127]
### Describe the bug

occurred after seemingly normal usage; 
`select-group-by TradeDate, count() count from (select [TradeDate, RIC, Bid, Ask] from PJ timestamp (TradeDate) where RIC ~ 'SPX' and RIC != '.SPX' and Bid != null and Ask != null)

### To reproduce

./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate']
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.935015Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-6, sql=
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.935577Z I i.q.g.SqlCompiler plan [q=`select-group-by TradeDate, count() count from (select [TradeDate, RIC, Bid, Ask] from PJ timestamp (TradeDate) where RIC ~ 'SPX' and RIC != '.SPX' and Bid != null and Ask != null)`, fd=69]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.956989Z I i.q.c.h.p.JsonQueryProcessorState [69] execute-new [skip: 0, stop: 1000]
./stdout-2022-05-06T17-29-09.txt:2022-05-06T17:30:24.963746Z E server-main unhandled error [job=io.questdb.cairo.sql.async.PageFrameReduceJob@60957c0f, ex=
./stdout-2022-05-06T17-29-09.txt-java.lang.IndexOutOfBoundsException: start 0, end 10, length 9
./stdout-2022-05-06T17-29-09.txt-       at java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1716)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:631)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.StringBuilder.append(StringBuilder.java:213)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.StringBuilder.append(StringBuilder.java:85)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:578)
./stdout-2022-05-06T17-29-09.txt-       at java.lang.StringBuilder.append(StringBuilder.java:204)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.std.str.StringSink.put(StringSink.java:82)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.std.str.AbstractCharSequence.getString(AbstractCharSequence.java:35)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.std.str.AbstractCharSequence.toString(AbstractCharSequence.java:58)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.std.Chars.toString(Chars.java:657)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.SymbolMapReaderImpl.fetchAndCache(SymbolMapReaderImpl.java:216)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.SymbolMapReaderImpl.cachedValue(SymbolMapReaderImpl.java:209)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.SymbolMapReaderImpl.valueOf(SymbolMapReaderImpl.java:189)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.sql.PageAddressCacheRecord.getSym(PageAddressCacheRecord.java:237)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.columns.SymbolColumn.getSymbol(SymbolColumn.java:50)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.SymbolFunction.getStr(SymbolFunction.java:115)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.regex.MatchStrFunctionFactory$MatchConstPatternFunction.getBool(MatchStrFunctionFactory.java:99)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.bool.AndFunctionFactory$MyBooleanFunction.getBool(AndFunctionFactory.java:86)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.bool.AndFunctionFactory$MyBooleanFunction.getBool(AndFunctionFactory.java:86)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.functions.bool.AndFunctionFactory$MyBooleanFunction.getBool(AndFunctionFactory.java:86)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.griffin.engine.table.AsyncFilteredRecordCursorFactory.filter(AsyncFilteredRecordCursorFactory.java:164)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.sql.async.PageFrameReduceJob.reduce(PageFrameReduceJob.java:153)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.sql.async.PageFrameReduceJob.consumeQueue(PageFrameReduceJob.java:120)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.cairo.sql.async.PageFrameReduceJob.run(PageFrameReduceJob.java:174)
./stdout-2022-05-06T17-29-09.txt-       at io.questdb.mp.Worker.run(Worker.java:116)
./stdout-2022-05-06T17-29-09.txt-]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.969468Z I i.q.c.h.p.JsonQueryProcessorState [69] timings [compiler: 21941514, count: 0, execute: 34522684, q=`
./stdout-2022-05-06T17-29-09.txt-select TradeDate, count from PJ where RIC ~ 'SPX' and RIC != '.SPX' and Bid!=null and Ask!=null group by TradeDate`]
./stdout-2022-05-06T17-29-09.txt-2022-05-06T17:30:24.969533Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=69, lastRequestBytesSent=528, nCompletedRequests=3, totalBytesSent=20441]

### Expected Behavior

handled error (or no error)

### Environment

```markdown
- **QuestDB version**: 6.3.
- **OS**: ubuntu
- **Browser**: python requests REST
```

**Comment by ospqsp** [comment]
@ideoma thanks alex--i added this one as i had thought it shouldn't occurr with cairo.sql.parallel.filter.enabled=false
(which previously was true, but the current unhandled error occurred with it as false)

**Comment by ospqsp** [comment]
i had thought i had, but perhaps not. i've certainly just restarted it and I'll keep a watch out.

**Comment by bluestreak01** [comment]
this is fixed in https://github.com/questdb/questdb/releases/tag/6.3.1
