### ISSUE TITLE
The helm chart index.yaml is corrupt

### ISSUE THREAD

**Issue by jscarrott** [questdb/questdb#2135]
### Describe the bug

It looks like half a merge conflict has been left in the index.yaml available here: https://helm.questdb.io/index.yaml 
These lines specifically 518:522
```
<<<<<<< HEAD
generated: "2022-05-17T14:58:28.249716+01:00"
=======
generated: "2022-05-05T19:15:06.532136+01:00"
>>>>>>> repo
```

This is causing some of our terraform to fail as it is invalid.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by mariusgheorghies** [comment]
@jscarrott Thank you for submitting the issue.
It was fixed in the PR https://github.com/questdb/questdb-kubernetes/pull/58

`helm repo update` and you should be able to use version 0.20.1 of the helm chart
