### ISSUE TITLE
Failed to sync from Debezium to QuestDB via JDBC

### ISSUE THREAD

**Issue by huuhait** [questdb/questdb#2141]
### Describe the bug

Kafka connect payload
![image](https://user-images.githubusercontent.com/40519768/169425889-8c095d24-eb0a-43f8-b1d0-09c77affc1bd.png)

But i always get error message:
```
Unsupported source data type: STRUCT
```

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by jerrinot** [comment]
hello @huuhait thanks for reporting the issue!  
Is this working when you configure the Connect Sink to write to Postgres instead of QuestDB?

**Comment by jerrinot** [comment]
this issue seems remarkably similar to https://github.com/confluentinc/kafka-connect-jdbc/issues/585
Please try to use one of the flattening transforms described in the linked issue and report back. Thanks a lot!

**Comment by jerrinot** [comment]
@huuhait this looks like the way the go: https://docs.confluent.io/platform/current/connect/transforms/flatten.html

**Comment by huuhait** [comment]
Hi problem by my CDC
thanks for support

**Comment by jerrinot** [comment]
hello @huuhait, can you please elaborate on what exactly was wrong in your setup and how did you fix it? It could help others facing the same issue. Thanks a ton!
