### ISSUE TITLE
Parallel import

### ISSUE THREAD

**Issue by bziobrowski** [questdb/questdb#2143]
### Is your feature request related to a problem?

Currently imports (via COPY command or /imp endpoint) are done sequentially and import data in file order.
When importing to table with designated timestamp that is : 
- non-partitioned - out of order rows are skipped 
- partitioned - out of order rows are stored but ingestion speed suffers if such row(s) are added to already closed partitions . 
Moreover - import is CPU-bound (on parsing) and doesn't fully utilize capabilities of modern SSDs . 

### Describe the solution you'd like.

I'd like import to  : 
- create index of timestamps + row offsets 
- sort it 
- split into per-partition chunks 
- import partitions 
in parallel . 

This approach is likely to use much more resources than current method so it should be optional and user should be able to set resource constraints (e.g. workers and/or memory).

**Comment by pswu11** [comment]
This is implemented by #2155
