### ISSUE TITLE
SIGILL at select where-query

### ISSUE THREAD

**Issue by operatorpk** [questdb/questdb#2161]
### Describe the bug

executing the following query via web interface crashes questdb

select date_time, e10 from prices where e10 = 0 limit 500

excerpt from log file, omitted duplicate error lines:

> 2022-05-28 07:17:08,stdout,"2022-05-28T07:17:08.249920Z I i.q.g.SqlCompiler plan [q=`select-choose date_time, e10 from (select [date_time, e10] from prices timestamp (date_time) where e10 = 0) order by date_time desc limit 500`, fd=7]"
> 2022-05-28 07:17:08,stdout,limit 500]
> 2022-05-28 07:17:08,stdout,"2022-05-28T07:17:08.254639Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=prices, fd=7]"
> 2022-05-28 07:17:08,stdout,"2022-05-28T07:17:08.256408Z I i.q.c.h.p.JsonQueryProcessorState [7] execute-new [skip: 0, stop: 1000]"
> 2022-05-28 07:17:08,stdout,# A fatal error has been detected by the Java Runtime Environment:
> 2022-05-28 07:17:08,stdout,#
> 2022-05-28 07:17:08,stdout,"#  SIGILL (0x4) at pc=0x00007fdb25cd2026, pid=1, tid=22
> 2022-05-28 07:17:08,stdout,#
> 2022-05-28 07:17:08,stdout,# JRE version: OpenJDK Runtime Environment (17.0.1+12) (build 17.0.1+12-39)
> 2022-05-28 07:17:08,stdout,"# Java VM: OpenJDK 64-Bit Server VM (17.0.1+12-39, mixed mode, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
> 2022-05-28 07:17:08,stdout,# Problematic frame:
> 2022-05-28 07:17:08,stdout,# C  0x00007fdb25cd2026
> 2022-05-28 07:17:08,stdout,#
> 2022-05-28 07:17:08,stdout,# Core dump will be written. Default location: Core dumps may be processed with "/usr/syno/sbin/syno-dump-core.sh /volume1 %p %s" (or dumping to /root/.questdb/core.1)
> 2022-05-28 07:17:08,stdout,#
> 2022-05-28 07:17:08,stdout,# An error report file with more information is saved as:
> 2022-05-28 07:17:08,stdout,# /root/.questdb/hs_err_pid1.log
> 2022-05-28 07:17:08,stdout,#
> 2022-05-28 07:17:08,stdout,
> 2022-05-28 07:17:08,stdout,"[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007fdb3e099529]
> 
> ...
> 
> 2022-05-28 07:17:08,stdout,"[Too many errors, abort]

`

### To reproduce

1. CREATE TABLE prices (ID LONG, station_id STRING, e5 DOUBLE, e10 DOUBLE, diesel DOUBLE, date_time TIMESTAMP)
2. SELECT  date_time , e10 from 'prices' where e10 = 0

### Expected Behavior

successful query and query results

### Environment

```markdown
- QuestDB 6.3.1
- server: docker on linux, client: macOS 12.4
- Safari 15.5 (17613.2.7.1.8)
```

**Comment by jerrinot** [comment]
hell @operatorpk thanks for reporting the issue! Can reproduce it with an empty table? Is QuestDB server running on Intel CPU? I tried to reproduce it, but it seems to work fine for me. Is it crashing reliably for you? Did you modify QuestDB configuration or is it all on default? Can you share /root/.questdb/hs_err_pid1.log ?

**Comment by puzpuzpuz** [comment]
@operatorpk do you have an x86 CPU or it's ARM? Could you also share exact Docker version you're using? The issue might do something with Rosetta.

**Comment by puzpuzpuz** [comment]
Could you also share full server logs? I'm interested in JIT compiler setting logging.

**Comment by operatorpk** [comment]
QuestDB is running in docker on an Synology NAS using Intel CPU. Docker version is 20.10.3-1239. As you can see from the logs the error is quite reproducable. But indeed it works fine for empty tables. QuestDB configuration is all default.

[QuestDB log.csv](https://github.com/questdb/questdb/files/8791123/QuestDB.log.csv)
[hs_err_pid1.log](https://github.com/questdb/questdb/files/8791126/hs_err_pid1.log)
.

**Comment by operatorpk** [comment]
to reproduce the error: CREATE TABLE prices (ID LONG, station_id STRING, e5 DOUBLE, e10 DOUBLE, diesel DOUBLE, date_time TIMESTAMP);
1. create table: 
2. add some data: INSERT INTO pricestest (ID, station_id, e5, e10, diesel, date_time)
VALUES(
    5,
    'e1a15081-2573-9107-e040-0b0a3dfe563c',
    0,
    0,
    0,
    to_timestamp('2021-12-31T11:25:00', 'yyyy-MM-ddTHH:mm:ss')
);
3. query data: select date_time, e5 from 'pricestest' where e5=0

**Comment by puzpuzpuz** [comment]
I can't reproduce this on i7-1185G7 and Ubuntu 20.04. As a workaround, you could disable JIT-compilation. That could be done with `cairo.sql.jit.mode=off` config property or `QDB_CAIRO_SQL_JIT_MODE=off` environment variable.

Also, looks like your CPU (Celeron J4025) doesn't support AVX-2 (and not only this instruction set), so JIT compiler has to use scalar instructions. To help us debugging this problem, you could keep JIT compilation enabled and enable compiler debug logging via `cairo.sql.jit.debug.enabled=true` config property. Then run the problematic query and share the server log - it should contain the emitted instructions.

**Comment by operatorpk** [comment]
Now I enabled JIT compiler debugging and executed the query, see log attached.

[QuestDB JIT debug 2022-05-29.csv](https://github.com/questdb/questdb/files/8792865/QuestDB.JIT.debug.2022-05-29.csv)

For now disabling JIT-compilation via the proposed environment variable fixes the problem. Thanks for helping although it's note quite satisfying.
