### ISSUE TITLE
CEP Window Construct | Complex Even Processing | Streaming Analytics | Reactive Data Processing

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#218]
Is it possible to introduce `tumbling` and `slidings` `windows` which are based on:

- time
- count
- filter

And operation on `windows`. This will make it easy to do Complex Even Processing & Streaming Analytics.

Also, it might be worthwhile to have control over how often the window updates so it does not trigger too many computations.

E.g.

- https://siddhi.io/
- https://flink.apache.org/
- https://www.drools.org/
- https://ignite.apache.org/
- http://www.espertech.com/
- https://liflab.github.io/beepbeep-3/index.html

**Comment by sirinath** [comment]
Maybe when creating windows as a side benefit you can add `views` also.

**Comment by bsmth** [comment]
Closing this as the requested functionality is covered under #219
