### ISSUE TITLE
A column has date type,but display datetime.

### ISSUE THREAD

**Issue by b0123456789** [questdb/questdb#2187]
### Describe the bug

![a](https://user-images.githubusercontent.com/21169660/171856241-12fd56b8-9bf8-40e3-bb8b-3e4573965eab.png)

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
What is the issue here?

**Comment by bziobrowski** [comment]
@b0123456789  Please have a look at date definition at https://questdb.io/docs/reference/sql/datatypes/ .

**Comment by b0123456789** [comment]
> @b0123456789 Please have a look at date definition at https://questdb.io/docs/reference/sql/datatypes/ .

thanks
