### ISSUE TITLE
Status: Unhealthy Unhandled errors: 3

### ISSUE THREAD

**Issue by ospqsp** [questdb/questdb#2188]
### Describe the bug

as you can see from the log file, I created an empty table, then tried to insert a small amount of data intoo it ~ 150MB. it took an inordinately long amount of time so I killed the client code. 

I redacted the data to 10 lines of CSV and re-attempted client code is still hung after ~10 minutes of collecting log files etc. 

the schema I was using is this:
'[{"name": "RIC", "type": "SYMBOL"}, {"name": "DateTime", "type": "TIMESTAMP", "pattern": "yyyy-MM-dd HH:mm:ssZZZZZZ"}, {"name": "Last", "type": "FLOAT"}, {"name": "CloseAsk", "type": "FLOAT"}, {"name": "CloseBid", "type": "FLOAT"}]'

this is the csv file:
RIC,DateTime,Last,CloseBid,CloseAsk
.SPX,2022-06-02 14:58:00-05:00,4176.74,4176.35,4177.13
SPXWC312380000.U,2022-06-02 15:58:00-04:00,,3334.8,3358.7
SPXWF032260000.U,2022-06-02 15:58:00-04:00,,3570.1,3581.8
SPXWF032280000.U,2022-06-02 15:58:00-04:00,,3370.1,3381.8
SPXWF102280000.U,2022-06-02 15:58:00-04:00,,3369.0,3380.8

### To reproduce

./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:39:29.385704Z I i.q.c.p.WriterPool closed [table=`ID`, reason=IDLE, by=20]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:06.960959Z I http-server connected [ip=127.0.0.1, fd=7]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:06.983775Z I i.q.c.h.p.JsonQueryProcessorState [7] exec [q='CREATE TABLE IF NOT EXISTS ID_tmp AS( SELECT * FROM ID WHERE false)  timestamp(DateTime) PARTITION BY DAY']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:06.983785Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-6, sql=CREATE TABLE IF NOT EXISTS ID_tmp AS( SELECT * FROM ID WHERE false)  timestamp(DateTime) PARTITION BY DAY]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:06.983959Z I i.q.c.p.ReaderPool open 'ID' [at=0:0]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:06.984560Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=7, lastRequestBytesSent=210, nCompletedRequests=38, totalBytesSent=4586577]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.086805Z I http-server scheduling disconnect [fd=7, reason=12]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.086825Z I http-server disconnected [ip=127.0.0.1, fd=7, src=queue]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.094691Z I http-server connected [ip=127.0.0.1, fd=7]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.148130Z I i.q.c.h.p.JsonQueryProcessorState [7] exec [q='TRUNCATE TABLE ID_tmp']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.148138Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-8, sql=TRUNCATE TABLE ID_tmp]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.148213Z I i.q.c.p.WriterPool open [table=`ID_tmp`, thread=19]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.148270Z I i.q.c.TableWriter open 'ID_tmp'
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.148845Z I i.q.c.TableWriter purging non attached partitions [path=/home/ubuntu/qdb/db/ID_tmp]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.148905Z I i.q.c.p.WriterPool >> [table=`ID_tmp`, thread=19]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.153152Z I i.q.c.p.WriterPool << [table=`ID_tmp`, thread=19]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.153225Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=7, lastRequestBytesSent=210, nCompletedRequests=40, totalBytesSent=4586787]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.174483Z I http-server scheduling disconnect [fd=7, reason=12]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.174493Z I http-server disconnected [ip=127.0.0.1, fd=7, src=queue]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:51:07.261170Z I http-server connected [ip=127.0.0.1, fd=7]
./stdout-2022-05-31T21-24-09.txt:2022-06-03T15:51:07.292768Z E server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@485e36bc, ex=
./stdout-2022-05-31T21-24-09.txt-java.lang.AssertionError
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.BytecodeAssembler.newInstance(BytecodeAssembler.java:435)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:1593)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:233)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:193)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:189)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatFactory.map(TimestampFormatFactory.java:53)
./stdout-2022-05-31T21-24-09.txt-       at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatFactory.get(TimestampFormatFactory.java:49)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextMetadataParser.createImportedType(TextMetadataParser.java:256)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextMetadataParser.onEvent(TextMetadataParser.java:170)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.json.JsonLexer.parse(JsonLexer.java:194)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextLoader.parseJsonMetadata(TextLoader.java:225)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextLoader.parse(TextLoader.java:191)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.processors.TextImportProcessor.onChunk(TextImportProcessor.java:93)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpMultipartContentParser.onChunkWithRetryHandle(HttpMultipartContentParser.java:234)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpMultipartContentParser.parse(HttpMultipartContentParser.java:188)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.parseMultipartResult(HttpConnectionContext.java:641)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.continueConsumeMultipart(HttpConnectionContext.java:368)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.consumeMultipart(HttpConnectionContext.java:352)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:559)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:253)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:95)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:166)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:107)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.mp.Worker.run(Worker.java:116)
./stdout-2022-05-31T21-24-09.txt-]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T15:54:29.440843Z I i.q.c.p.ReaderPool closed 'ID' [at=0:0, reason=IDLE]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:39.688042Z I http-server connected [ip=127.0.0.1, fd=8]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:39.788140Z I i.q.c.h.p.JsonQueryProcessorState [8] exec [q='tables();']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:39.788154Z I i.q.c.h.p.QueryCache hit [thread=questdb-worker-7, sql=tables();]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:39.788161Z I i.q.c.h.p.JsonQueryProcessorState [8] execute-cached [skip: 0, stop: 9223372036854775807]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:39.788705Z I i.q.c.h.p.JsonQueryProcessorState [8] timings [compiler: 0, count: 0, execute: 571589, q=`tables();`]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:39.788732Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=8, lastRequestBytesSent=1344, nCompletedRequests=14, totalBytesSent=808453286]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:39.788785Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-7, sql=tables();]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:41.189102Z I i.q.c.h.p.JsonQueryProcessorState [8] exec [q='tables();']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:41.189115Z I i.q.c.h.p.QueryCache hit [thread=questdb-worker-11, sql=tables();]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:41.189123Z I i.q.c.h.p.JsonQueryProcessorState [8] execute-cached [skip: 0, stop: 9223372036854775807]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:41.189666Z I i.q.c.h.p.JsonQueryProcessorState [8] timings [compiler: 0, count: 0, execute: 571808, q=`tables();`]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:41.189695Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=8, lastRequestBytesSent=1344, nCompletedRequests=15, totalBytesSent=808454630]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:41.189720Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-11, sql=tables();]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:52.196700Z I i.q.c.h.p.JsonQueryProcessorState [8] exec [q='
./stdout-2022-05-31T21-24-09.txt-
./stdout-2022-05-31T21-24-09.txt-
./stdout-2022-05-31T21-24-09.txt-ALTER TABLE ID DROP COLUMN 'Type'']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:52.196713Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-9, sql=
./stdout-2022-05-31T21-24-09.txt-
./stdout-2022-05-31T21-24-09.txt-
./stdout-2022-05-31T21-24-09.txt-ALTER TABLE ID DROP COLUMN 'Type']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:00:52.196786Z I i.q.c.p.ReaderPool open 'ID' [at=0:0]
--
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:15.237680Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-9, sql=TRUNCATE TABLE ID_tmp]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:15.237738Z I i.q.c.p.WriterPool >> [table=`ID_tmp`, thread=20]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:15.238621Z I i.q.c.p.WriterPool << [table=`ID_tmp`, thread=20]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:15.238676Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=17, lastRequestBytesSent=210, nCompletedRequests=17, totalBytesSent=66709]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:15.367111Z I http-server scheduling disconnect [fd=17, reason=12]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:15.367122Z I http-server disconnected [ip=127.0.0.1, fd=17, src=queue]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:18.624208Z I i.q.c.h.p.JsonQueryProcessorState [79] exec [q='tables();']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:18.624223Z I i.q.c.h.p.QueryCache hit [thread=questdb-worker-13, sql=tables();]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:18.624232Z I i.q.c.h.p.JsonQueryProcessorState [79] execute-cached [skip: 0, stop: 9223372036854775807]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:18.624611Z I i.q.c.h.p.JsonQueryProcessorState [79] timings [compiler: 0, count: 0, execute: 410071, q=`tables();`]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:18.624633Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=79, lastRequestBytesSent=1344, nCompletedRequests=10, totalBytesSent=4501]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:18.624654Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-13, sql=tables();]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:19.896930Z I i.q.c.h.p.JsonQueryProcessorState [79] exec [q='SHOW COLUMNS FROM 'ID_tmp';']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:19.896943Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-6, sql=SHOW COLUMNS FROM 'ID_tmp';]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:19.897050Z I i.q.c.h.p.JsonQueryProcessorState [79] execute-new [skip: 0, stop: 9223372036854775807]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:19.897075Z I i.q.c.p.ReaderPool open 'ID_tmp' [at=0:0]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:19.897389Z I i.q.c.h.p.JsonQueryProcessorState [79] timings [compiler: 102396, count: 0, execute: 465343, q=`SHOW COLUMNS FROM 'ID_tmp';`]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:19.897406Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=79, lastRequestBytesSent=807, nCompletedRequests=11, totalBytesSent=5845]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:19.897426Z I i.q.c.h.p.QueryCache push [thread=questdb-worker-6, sql=SHOW COLUMNS FROM 'ID_tmp';]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:12:28.404423Z I http-server connected [ip=127.0.0.1, fd=82]
./stdout-2022-05-31T21-24-09.txt:2022-06-03T16:12:28.423179Z E server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@18c5069b, ex=
./stdout-2022-05-31T21-24-09.txt-java.lang.AssertionError
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.BytecodeAssembler.newInstance(BytecodeAssembler.java:435)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:1593)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:233)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:193)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:189)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatFactory.map(TimestampFormatFactory.java:53)
./stdout-2022-05-31T21-24-09.txt-       at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatFactory.get(TimestampFormatFactory.java:49)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextMetadataParser.createImportedType(TextMetadataParser.java:256)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextMetadataParser.onEvent(TextMetadataParser.java:170)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.json.JsonLexer.parse(JsonLexer.java:194)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextLoader.parseJsonMetadata(TextLoader.java:225)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextLoader.parse(TextLoader.java:191)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.processors.TextImportProcessor.onChunk(TextImportProcessor.java:93)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpMultipartContentParser.onChunkWithRetryHandle(HttpMultipartContentParser.java:234)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpMultipartContentParser.parse(HttpMultipartContentParser.java:188)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.parseMultipartResult(HttpConnectionContext.java:641)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.continueConsumeMultipart(HttpConnectionContext.java:368)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.consumeMultipart(HttpConnectionContext.java:352)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:559)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:253)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:95)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:166)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:107)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.mp.Worker.run(Worker.java:116)
./stdout-2022-05-31T21-24-09.txt-]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:13:33.593773Z I http-server disconnected [ip=127.0.0.1, fd=8, src=idle]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:14:29.491514Z I i.q.c.TableWriter closed 'ID'
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:14:29.491522Z I i.q.c.p.WriterPool closed [table=`ID`, reason=IDLE, by=18]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:14:29.491590Z I i.q.c.p.ReaderPool closed 'ID' [at=0:0, reason=IDLE]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:14:29.491662Z I i.q.c.p.ReaderPool closed 'ID_tmp' [at=0:0, reason=IDLE]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:17:19.903470Z I http-server disconnected [ip=127.0.0.1, fd=79, src=idle]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:24:29.517463Z I i.q.c.TableWriter closed 'ID_tmp'
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:24:29.517472Z I i.q.c.p.WriterPool closed [table=`ID_tmp`, reason=IDLE, by=18]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.336351Z I http-server connected [ip=127.0.0.1, fd=8]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.363343Z I i.q.c.h.p.JsonQueryProcessorState [8] exec [q='CREATE TABLE IF NOT EXISTS ID_tmp AS( SELECT * FROM ID WHERE false)  timestamp(DateTime) PARTITION BY DAY']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.363353Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-9, sql=CREATE TABLE IF NOT EXISTS ID_tmp AS( SELECT * FROM ID WHERE false)  timestamp(DateTime) PARTITION BY DAY]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.363559Z I i.q.c.p.ReaderPool open 'ID' [at=0:0]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.364071Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=8, lastRequestBytesSent=210, nCompletedRequests=28, totalBytesSent=344263]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.454242Z I http-server scheduling disconnect [fd=8, reason=12]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.454258Z I http-server disconnected [ip=127.0.0.1, fd=8, src=queue]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.459463Z I http-server connected [ip=127.0.0.1, fd=8]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.517850Z I i.q.c.h.p.JsonQueryProcessorState [8] exec [q='TRUNCATE TABLE ID_tmp']
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.517857Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-7, sql=TRUNCATE TABLE ID_tmp]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.517938Z I i.q.c.p.WriterPool open [table=`ID_tmp`, thread=18]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.517987Z I i.q.c.TableWriter open 'ID_tmp'
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.518357Z I i.q.c.TableWriter purging non attached partitions [path=/home/ubuntu/qdb/db/ID_tmp]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.518417Z I i.q.c.p.WriterPool >> [table=`ID_tmp`, thread=18]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.519295Z I i.q.c.p.WriterPool << [table=`ID_tmp`, thread=18]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.519356Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=8, lastRequestBytesSent=210, nCompletedRequests=30, totalBytesSent=344473]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.622604Z I http-server scheduling disconnect [fd=8, reason=12]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.622618Z I http-server disconnected [ip=127.0.0.1, fd=8, src=queue]
./stdout-2022-05-31T21-24-09.txt-2022-06-03T16:28:37.625388Z I http-server connected [ip=127.0.0.1, fd=8]
./stdout-2022-05-31T21-24-09.txt:2022-06-03T16:28:37.667069Z E server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@2a79d4b1, ex=
./stdout-2022-05-31T21-24-09.txt-java.lang.AssertionError
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.BytecodeAssembler.newInstance(BytecodeAssembler.java:435)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:1593)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:233)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:193)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatCompiler.compile(TimestampFormatCompiler.java:189)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatFactory.map(TimestampFormatFactory.java:53)
./stdout-2022-05-31T21-24-09.txt-       at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.std.datetime.microtime.TimestampFormatFactory.get(TimestampFormatFactory.java:49)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextMetadataParser.createImportedType(TextMetadataParser.java:256)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextMetadataParser.onEvent(TextMetadataParser.java:170)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.json.JsonLexer.parse(JsonLexer.java:194)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextLoader.parseJsonMetadata(TextLoader.java:225)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.text.TextLoader.parse(TextLoader.java:191)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.processors.TextImportProcessor.onChunk(TextImportProcessor.java:93)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpMultipartContentParser.onChunkWithRetryHandle(HttpMultipartContentParser.java:234)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpMultipartContentParser.parse(HttpMultipartContentParser.java:188)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.parseMultipartResult(HttpConnectionContext.java:641)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.continueConsumeMultipart(HttpConnectionContext.java:368)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.consumeMultipart(HttpConnectionContext.java:352)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:559)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:253)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:95)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:166)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:107)
./stdout-2022-05-31T21-24-09.txt-       at io.questdb.mp.Worker.run(Worker.java:116)
./stdout-2022-05-31T21-24-09.txt-]

### Environment

```markdown
- **QuestDB version : 6.4
- **OS**: ubuntu 18
- **Browser**: python requests
```

**Comment by ospqsp** [comment]
Expected Behavior:
fail quickly and gracefully if something isn't correctly encoded (i am guessing at the timestamp encoding as I couldn't find an example or lexical definition that unambigously applies to my scenario)

**Comment by bluestreak01** [comment]
Thanks, we should be able to fix this asap

**Comment by marregui** [comment]
Hi @ospqsp 

There has been some work done on the CSV import area, including the release of this interesting article: https://questdb.io/blog/2022/09/12/importing-3m-rows-with-io-uring/

As of releas 6.5:

```
This release brings a new algorithm for the SQL COPY statement [[Reference]](https://questdb.io/docs/reference/sql/copy/), which is specifically designed to enable fast and easy CSV Import for large and unsorted data files. This feature comes in handy when there's a need to migrate a large amount of data from other databases to QuestDB [[Guide: CSV import]](https://questdb.io/docs/guides/importing-data). In addition, there are several improvements and fixes for the Influx line protocol, Core, and SQL engine.
```

Would you please be able to upgrade to the latest release (https://github.com/questdb/questdb/releases) and check that the issue was fixed?

Thank you in advance.
