### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by cumtqiangqiang** [questdb/questdb#2204]
### Describe the bug

Batch insert about 1h later, I select some data use web console sql ,then the questdb service will crashed. I can you have fixed the similar issue. is it the same issue ?

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f83b06a2d62, pid=8977, tid=8996
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.9.1+1) (build 11.0.9.1+1)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.9.1+1, mixed mode, tiered, compressed oops, parallel gc, linux-amd64)
# Problematic frame:
# J 1928 c1 sun.misc.Unsafe.getInt(J)I jdk.unsupported@11.0.9.1 (8 bytes) @ 0x00007f83b06a2d62 [0x00007f83b06a2cc0+0x00000000000000a2]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /data/home/user/soft/questdb-6.4-rt-linux-amd64/hs_err_pid8977.log
Compiled method (c1)  152646 1928       3       sun.misc.Unsafe::getInt (8 bytes)
 total in heap  [0x00007f83b06a2b10,0x00007f83b06a2ec0] = 944
 relocation     [0x00007f83b06a2c88,0x00007f83b06a2cb8] = 48
 main code      [0x00007f83b06a2cc0,0x00007f83b06a2e00] = 320
 stub code      [0x00007f83b06a2e00,0x00007f83b06a2e30] = 48
 oops           [0x00007f83b06a2e30,0x00007f83b06a2e38] = 8
 metadata       [0x00007f83b06a2e38,0x00007f83b06a2e48] = 16
 scopes data    [0x00007f83b06a2e48,0x00007f83b06a2e78] = 48
 scopes pcs     [0x00007f83b06a2e78,0x00007f83b06a2eb8] = 64
 dependencies   [0x00007f83b06a2eb8,0x00007f83b06a2ec0] = 8
Compiled method (c1)  152648 1924       3       io.questdb.cutlass.http.HttpResponseSink$ResponseSinkImpl::put (14 bytes)
 total in heap  [0x00007f83b06a5810,0x00007f83b06a5f08] = 1784
 relocation     [0x00007f83b06a5988,0x00007f83b06a59f8] = 112
 main code      [0x00007f83b06a5a00,0x00007f83b06a5d00] = 768
 stub code      [0x00007f83b06a5d00,0x00007f83b06a5d50] = 80
 oops           [0x00007f83b06a5d50,0x00007f83b06a5d68] = 24
 metadata       [0x00007f83b06a5d68,0x00007f83b06a5d98] = 48
 scopes data    [0x00007f83b06a5d98,0x00007f83b06a5e38] = 160
 scopes pcs     [0x00007f83b06a5e38,0x00007f83b06a5ee8] = 176
 dependencies   [0x00007f83b06a5ee8,0x00007f83b06a5ef0] = 8
 nul chk table  [0x00007f83b06a5ef0,0x00007f83b06a5f08] = 24
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues

```

### Environment

```markdown
- **QuestDB version**:6.4
- **OS**:linux centos
- **Browser**: chrome
```

**Comment by cumtqiangqiang** [comment]
> ### Describe the bug
> Batch insert about 1h later, I select some data use web console sql ,then the questdb service will crashed. I can you have fixed the similar issue. is it the same issue ?
> 
> # A fatal error has been detected by the Java Runtime Environment:
> # SIGSEGV (0xb) at pc=0x00007f83b06a2d62, pid=8977, tid=8996
> # JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.9.1+1) (build 11.0.9.1+1)
> # Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.9.1+1, mixed mode, tiered, compressed oops, parallel gc, linux-amd64)
> # Problematic frame:
> # J 1928 c1 sun.misc.Unsafe.getInt(J)I jdk.unsupported@11.0.9.1 (8 bytes) @ 0x00007f83b06a2d62 [0x00007f83b06a2cc0+0x00000000000000a2]
> # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> # An error report file with more information is saved as:
> # /data/home/user/soft/questdb-6.4-rt-linux-amd64/hs_err_pid8977.log
> Compiled method (c1) 152646 1928 3 sun.misc.Unsafe::getInt (8 bytes) total in heap [0x00007f83b06a2b10,0x00007f83b06a2ec0] = 944 relocation [0x00007f83b06a2c88,0x00007f83b06a2cb8] = 48 main code [0x00007f83b06a2cc0,0x00007f83b06a2e00] = 320 stub code [0x00007f83b06a2e00,0x00007f83b06a2e30] = 48 oops [0x00007f83b06a2e30,0x00007f83b06a2e38] = 8 metadata [0x00007f83b06a2e38,0x00007f83b06a2e48] = 16 scopes data [0x00007f83b06a2e48,0x00007f83b06a2e78] = 48 scopes pcs [0x00007f83b06a2e78,0x00007f83b06a2eb8] = 64 dependencies [0x00007f83b06a2eb8,0x00007f83b06a2ec0] = 8 Compiled method (c1) 152648 1924 3 io.questdb.cutlass.http.HttpResponseSink$ResponseSinkImpl::put (14 bytes) total in heap [0x00007f83b06a5810,0x00007f83b06a5f08] = 1784 relocation [0x00007f83b06a5988,0x00007f83b06a59f8] = 112 main code [0x00007f83b06a5a00,0x00007f83b06a5d00] = 768 stub code [0x00007f83b06a5d00,0x00007f83b06a5d50] = 80 oops [0x00007f83b06a5d50,0x00007f83b06a5d68] = 24 metadata [0x00007f83b06a5d68,0x00007f83b06a5d98] = 48 scopes data [0x00007f83b06a5d98,0x00007f83b06a5e38] = 160 scopes pcs [0x00007f83b06a5e38,0x00007f83b06a5ee8] = 176 dependencies [0x00007f83b06a5ee8,0x00007f83b06a5ef0] = 8 nul chk table [0x00007f83b06a5ef0,0x00007f83b06a5f08] = 24 Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
> 
> # If you would like to submit a bug report, please visit:
> # https://github.com/AdoptOpenJDK/openjdk-support/issues
> ### To reproduce
> _No response_
> 
> ### Expected Behavior
> _No response_
> 
> ### Environment
> ```gfm
> - **QuestDB version**:6.4
> - **OS**:linux centos
> - **Browser**: chrome
> ```
> 
> ### Additional context
> _No response_

sorry,there is an issue show on this page, looks bad.

**Comment by bluestreak01** [comment]
@cumtqiangqiang could you attach the /data/home/user/soft/questdb-6.4-rt-linux-amd64/hs_err_pid8977.log please ?

**Comment by ideoma** [comment]
Closing this one, embedded DB use, let's try to figure out what's going on in #2202
