### ISSUE TITLE
why questdb cannot insert rows out of order?

### ISSUE THREAD

**Issue by vino486** [questdb/questdb#2207]
I'm trying to insert live stream data. Sometimes there is the following error message: "questdb cannot insert rows out of order".

**Comment by puzpuzpuz** [comment]
Out of order ingestion is not supported on non-partitioned tables. It could be what you observe. Could you check your table schema, say, via Web Console? To do that hover the mouse over the table name and click the right mouse button. There will be a Copy schema menu item that you should use.
