### ISSUE TITLE
ILP: Support parsing floating point with exponential notation

### ISSUE THREAD

**Issue by amunra** [questdb/questdb#2225]
The ILP protocol fails to parse floating points with exponential notation.

For example, the following line can't be parsed:

```
tbl1 a=1e-16
```

Currently, as a work-around, client libraries need to avoid exponential notation.

```
tbl1 a=0.0000000000000001
```

**Comment by amunra** [comment]
For more context, see: https://github.com/questdb/c-questdb-client/issues/3.

**Comment by ideoma** [comment]
QuestDB supports exponential notation especially after #2211
