### ISSUE TITLE
ALTER TABLE RENAME COLUMN

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#223]
**Is your feature request related to a problem? Please describe.**
Not linked to an issue but it would be great to add the ability to rename columns to the ddl.

**Describe the solution you'd like**
SQL implementation of ALTER TABLE .. RENAME COLUMN

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bluestreak01** [comment]
the important part here is to make sure TableReader is able to see data consistently while rename is taking place
