### ISSUE TITLE
Add substring function

### ISSUE THREAD

**Issue by jacksonlancaster** [questdb/questdb#2241]
substring(string strtoeval, star int, end int)

**Comment by jerrinot** [comment]
Hello @jacksonlancaster,

thanks for raising a feature request. Can you please describe the use-case a bit? Is meant clean data before presenting them to the application? Or perhaps for joining?

**Comment by HeZean** [comment]
Hi @jerrinot, what about just let me first impl a `substring` function which works same as psql? Don't let my proposal interrupt your discussion : )

**Comment by jacksonlancaster** [comment]
@jerrinot Yes the purpose is to help filter out the data before presenting to the applicaiton.

**Comment by devcydo** [comment]
Hi. I would like to take this issue but I can see that is already in status Todo, is someone else working on it?
