### ISSUE TITLE
Use of deprecated NodeJS package in documentation

### ISSUE THREAD

**Issue by juancastellano115** [questdb/questdb#2256]
Hi!

I was reviewing this page of the documentation https://questdb.io/docs/develop/query-data#http-rest-api, and just noticed the NodeJS example in the **HTTP REST API** section is using the `querystring` package, which has been deprecated.

SOLUTION:

- Use the URLSearchParams built-in function

The NodeJS example could be something like this:

``` javascript
const fetch = require("node-fetch")

const HOST = "http://localhost:9000"

async function run() {
  try {
    const queryData = {query: "SELECT x FROM long_sequence(5);"}
    const response = await fetch(`${HOST}/exec?${new URLSearchParams(queryData).toString()}`)
    const json = await response.json()

    console.log(json)
  } catch (error) {
    console.log(error)
  }
}

run()

```

Thanks for your time!

**Comment by puzpuzpuz** [comment]
One small addition. There is a simpler way to URL encode query params - that's [`encodeURIComponent()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) function:
```js 
const response = await fetch(`${HOST}/exec?query=${encodeURIComponent(query)}`)
```

**Comment by juancastellano115** [comment]
Great suggestion @puzpuzpuz! Thanks for sharing it, I just created the [PR](https://github.com/questdb/questdb.io/pull/916) using [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) in all the NodeJS examples of the documentation. 😄

**Comment by stephenspol** [comment]
Can this issue be closed? It seems like it is resolved.

**Comment by puzpuzpuz** [comment]
Closing this one as it's indeed resolved.
