### ISSUE TITLE
An undeletable partition appears in questdb

### ISSUE THREAD

**Issue by pokliu** [questdb/questdb#2267]
### Describe the bug

Run: select * from aws_iot_device_shadow_update order by ts desc limit 10;

[19:47:20] Partition '54448-04-21' does not exist in table 'aws_iot_device_shadow_update' directory. Run [ALTER TABLE aws_iot_device_shadow_update DROP PARTITION LIST '54448-04-21'] to repair the table or restore the partition directory.

Run: ALTER TABLE aws_iot_device_shadow_update DROP PARTITION LIST '54448-04-21';

[19:50:19] 'YYYY-MM-DD' expected[errno=0]

### To reproduce

I'm not sure, but I recreated the table structure, migrated the data by creating a new table name, executing insert into select, then removing the old table and renaming the new table

### Environment

```markdown
- **QuestDB version**: 6.2.1
- **OS**: Linux 10-10-20-115 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Browser**:  Chrome
```

**Comment by pokliu** [comment]
I may have reproduced the bug, but it has nothing to do with the datatable migration. When I submit data using `pg` protocol and the timestamp is wrong (1000 times larger than the nanosecond value), questdb may not verify the timestamp, so an illegal partition is created

**Comment by marregui** [comment]
Hi,

Two exemplifying examples in the codebase on how to use timestamps:

https://github.com/questdb/questdb/blob/master/core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java#L5934
https://github.com/questdb/questdb/blob/master/core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java#L6059

It is a feature :P

**Comment by pokliu** [comment]
Hi @marregui ,

This can be a feature, but if there is a bug in the user's application code that causes the timestamp precision to be wrong, it should not generate a wrong partition, or at least allow the user to delete the wrong partition, instead of the current SQL statement that cannot be run This makes it impossible to migrate data to fix the situation.

**Comment by marregui** [comment]
Hi @pokliu ,

If I could copy/paste code into a test then I would be able to reproduce this quickly and see if there is a way to validate the sent timestamp. It would give me more grounds to address this situation.

Would you please be able to paste here some client code sending the misconstructed timestamp?.

Thank you in advance.

**Comment by pokliu** [comment]
Hi @marregui ,

Sorry I didn't describe clearly. I encountered this bug when using the ILP protocol.

But I can't reproduce it in v6.5 now, I don't know if this bug has been fixed recently.

**Comment by marregui** [comment]
Hi,

I could not accurately tell you which release sorted it out, but yes, we have recently released the official python client (https://github.com/questdb/py-questdb-client) and there has been work done.

ILP/TCP is compatible with dropping/attaching/detaching any partitions except for the active one (the one receiving the data). TCP/UDP is NOT compatible with the above however.

So all good an well then?
