### ISSUE TITLE
SQL: Negative limit with indexed symbol filtering incorrect

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#2308]
### To reproduce

On https://demo.questdb.io/ run 

```SQL
select * from trips
where vendor_id = 'CMT'
limit -10
```

`pickup_datetime` of the rows is in `2013-05-14`

Run without `WHERE`

```SQL
select * from trips
-- where vendor_id = 'CMT'
limit -10
```

`pickup_datetime` of the rows is in `2019-06-30`

### Expected Behavior

Limit with symbol filter should return latest rows e.g. in `2019-06-30`

### Environment

```markdown
- **QuestDB version**:6.4.2
```

**Comment by puzpuzpuz** [comment]
> Also, the `vendor_id` column does seem to be indexed.

Could be the case that @bluestreak01 dropped the index. That explains why I'm not able to reproduce the issue on the demo box.
