### ISSUE TITLE
/usr/bin/env: 'bash\r': No such file or directory

### ISSUE THREAD

**Issue by selmanfarukyilmaz** [questdb/questdb#2326]
### Describe the bug

Hi, ı have docker packages in my virtual env. When ı type 
sudo docker run -p 9000:9000 -p 9009:9009 -p 8812:8812 questdb/questdb

ı have 
(venv) d@E:~/PycharmProjects/binance_end$ sudo docker run -p 9000:9000 -p 9009:9009 -p 8812:8812 questdb/questdb
Unable to find image 'questdb/questdb:latest' locally
latest: Pulling from questdb/questdb
461246efe0a7: Pull complete 
19407d44f491: Pull complete 
cdd0d9fc3bdc: Pull complete 
1843d0ac0426: Pull complete 
0ca1d96b12c8: Pull complete 
4f4fb700ef54: Pull complete 
802dcfe58a6f: Pull complete 
Digest: sha256:fd4403fe9c7d44db7e141436b4373d32a84dae24f2b0018d96fc19e7d5437a24
Status: Downloaded newer image for questdb/questdb:latest
/usr/bin/env: 'bash\r': No such file or directory

error. And my QuestDB is not running. Is this kind a bug ?

### To reproduce

sudo docker run -p 9000:9000 -p 9009:9009 -p 8812:8812 questdb/questdb

error

### Expected Behavior

ı expect nothing should go wrong because ı am doing the same with docs.

### Environment

```markdown
- **QuestDB version**: last
- **OS**: python 3.10
- **Browser**: ı am using ide
```

**Comment by bluestreak01** [comment]
@selmanfarukyilmaz should be fixed now unless you're on ARM, in which case it will take 30 mins more
