### ISSUE TITLE
slow limit -N queries without order by ts queries 

### ISSUE THREAD

**Issue by bziobrowski** [questdb/questdb#2330]
### Describe the bug

Looks like in latest release queries that use limit -N without explicit order by issued against tables with designated timestamp traverse partitions from first to last . This can make a big difference for tables with many partitions that get queried rarely  enough to not be present in os cache . 

### To reproduce

```sql
create table test ( ts timestamp, d double, f float, i int, l long, s1 string, s2 string, sy symbol index) timestamp(ts) partition by day;

insert into test 
SELECT cast( (x*2500000)  as timestamp), x, x, cast(x as int), x, 's1' || (x%10), 's2' || (x%10), 'sy' || (x%10) 
from long_sequence(100000000);

selecT count(*) from test limit -5; 
--observe many 'open partition'  messages in logs

--after restart run
selecT * from test order by ts desc limit 5; 
--check that there's only 1 'open partition' message
```

### Environment

```markdown
- **QuestDB version**:  6.4.4-snapshot
- **OS**: Windows
- **Browser**: Chrome
```

**Comment by newskooler** [comment]
Hi @bziobrowski does this confirm that I cannot improve this and it's a bug or both you (on QDB end) and I on my end can improve it separately?

**Comment by bziobrowski** [comment]
Hi @newskooler  . The "workaround" for now is to use explicit order by clause with timestamp column  as given in issue description :
```sql
selecT * from test order by ts desc limit 5; 
```
To be honest I reckon it's always better to specify order if you depend on it because when it's missing databases can return data in any order . 
I should fix it for the next release .

**Comment by newskooler** [comment]
Specifying order does improve the speed significantly (I guess because it does not open each partition).

It may be more prudent to call it like this, but it comes at the cost of user experience, so if this can happen on the background when the users sets `limit -x` it would be preferable (to me at least).
