### ISSUE TITLE
to_str(time, 'D') not available, documentation says otherwise

### ISSUE THREAD

**Issue by Zahlii** [questdb/questdb#2367]
### Describe the bug

In the documentation, it is written that we can get the day of year using the to_str(time, 'D') approach. However, using the latest docker images, this will return the string 'D' as a result. See https://questdb.io/docs/reference/function/date-time/#date-and-timestamp-format 

I assume this may be tracked down somewhere around here, where the capital D is never being registered 

https://github.com/questdb/questdb/blob/826f3e677fd976d686cbdfa9fb3091fc58e6936d/core/src/main/java/io/questdb/std/datetime/millitime/DateFormatCompiler.java

### To reproduce

select to_str(systimestamp(), 'D')

### Expected Behavior

select to_str(systimestamp(), 'D') -> 211 (as of today)

### Environment

```markdown
- **QuestDB version**: 6.4.3 docker
- **OS**:
- **Browser**:
```

**Comment by salsasepp** [comment]
I checked out more format string parameters for `to_str()` and at least these also don't work:
`w W F`
On the other hand, at least these do something, but are not documented:
`kk KK SSS x xx`

The above list is not exhaustive.

**Comment by Zahlii** [comment]
I have no idea what "Day of week of month / F" is supposed to contain. The rest I should be able to implement in the attached PR.

**Comment by bziobrowski** [comment]
Hi @Zahlii . Thanks for the pull request .
It looks good but it would use more tests . 
The changes you pushed apply to to_str(date, format) and not to select to_str(timestamp, format). 
Please have a look at ToStrDateFunctionFactoryand ToStrTimestampFunctionFactory . 
The latter uses TimestampFormatCompiler actually .
