### ISSUE TITLE
Casting bool -> numeric data types yields unexpected results

### ISSUE THREAD

**Issue by Zahlii** [questdb/questdb#2379]
### Describe the bug

For some aggregation, I would like to do a "sum where condition holds" calculation. In order to do so, I am currently using the approach described below. When casting bool to int or float numbers, FALSE unexpectedly gets mapped to the value 1, destroying this attempt.  I thus will try doing a where first.

In pandas for example, we can use sum/mean etc easily on booleans to get the percentage of true/false values, and I would hope that 
a) Casting bool -> float/int will continue yielding the correct semantics
b) Averaging over bools will attempt using (a) to calculate aggregated statistics.

Probably b) is more like a feature request, though.

### To reproduce

select cast((150 < 120) as float)

### Expected Behavior

-> returns  FALSE -> 0

### Environment

```markdown
- **QuestDB version**: 6.4.3 Docker
- **OS**:
- **Browser**:
```

**Comment by salsasepp** [comment]
To illustrate further:
```
SELECT cast(0 as boolean) -> false
SELECT cast(false as int) -> 1
```
Sorry @Zahlii for adding to your issues for the 2nd time, but the bugs you find are just too interesting to stand aside.

**Comment by Zahlii** [comment]
It seems to me that there IS a test supposedly testing the described function in https://github.com/questdb/questdb/blob/master/core/src/test/java/io/questdb/griffin/engine/functions/cast/CastTest.java - However, that operates on what is assume is a column instead of a value, so maybe that is the isue. In general, I couldn't find any test cases in the way that I described earlier.

**Comment by eugenels** [comment]
There is also a problem with Num -> Boolean casting:
```
SELECT cast(-1 as boolean) -> false
SELECT cast(0 as boolean) -> false
SELECT cast(1 as boolean) -> true
SELECT cast(2 as boolean) -> false
```

**Comment by Zahlii** [comment]
Good catch, I aligned that also in the added PR

**Comment by salsasepp** [comment]
Side note: Maybe the result of `SELECT cast(NULL as boolean)` should be included in the tests. Right now the result is `false`. Other SQL databases return `NULL`, but `boolean` is not a nullable type in QuestDB. So should this query result in an error? I can't say.

**Comment by Zahlii** [comment]
I think that is already being tracked in https://github.com/questdb/questdb/issues/1701 ?

**Comment by salsasepp** [comment]
Correct, thx!
