### ISSUE TITLE
Add support continuous query like influxdb 1.8 to make data like kline

### ISSUE THREAD

**Issue by huuhait** [questdb/questdb#2395]
I think for optimize sql query like kline or candle query we should have something like continuous query in influxdb 1.8

Reason why RESAMPLE is not powerful for k-line data:
- still missing FILL by `PREV BY COLUMN`
- still missing data if this time is not avaible any data (time from or time end)

Hope questdb team will check this

**Comment by dgoadby** [comment]
I am migrating from InfluxDb and I too think the Continuous Query is a desirable feature. Although this issue is marked as Closed, and also as a New Feature, I cannot see if any equivalent functionality is currently in QuesrtDB.
