### ISSUE TITLE
Persisted/Durable Messages | Table/DB Backed Message Queue | Table/DB Backed Messaging Patterns | Table/DB Backed Enterprise Integration Patterns 

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#241]
I raised this before but since the issue is before (https://github.com/questdb/questdb/issues/14) but since this stale, I am opening a new issue to see if there might be interest to reconsider.

Instead of using a technology zoo, it is best if one can use one technology for all.

Is it possible to implement messaging patterns? This can be a thin layer on top of the DB and would be a natural next step for https://github.com/questdb/questdb/issues/165, https://github.com/questdb/questdb/issues/218.

E.g.

- Message DB - https://github.com/message-db/message-db, http://docs.eventide-project.org/user-guide/message-db/
- https://eventide-project.org/
- http://pumpkindb.org/ - EventSourcing DB
- https://www.benthos.dev/

**Comment by bluestreak01** [comment]
yes, this has been vaguely requested before. As soon as someone commits to using these patterns we will implement them :)

**Comment by sirinath** [comment]
[Publish–subscribe pattern](https://en.wikipedia.org/wiki/Publish–subscribe_pattern) will require very little effort with https://github.com/questdb/questdb/issues/165 and queues, streams, message bus, channels will very easy to have with https://github.com/questdb/questdb/issues/218.

Request-response, channel, duplex type communication may used 2 underlying tables.

The API can be simple wrapper API and for performance may not need o go through SQL or user-facing API for performance. You get persistence for free as you are using tables.

**Comment by bsmth** [comment]
I'm closing this as it's out of scope with the features we are focusing on at the moment.

If this feature is something you would like to add, you may also contribute directly by submitting a patch - see the [contribution guide](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) for details. :)

Thank you!
