### ISSUE TITLE
COPY and FORMAT error

### ISSUE THREAD

**Issue by javier** [questdb/questdb#2411]
### Describe the bug

When I issue a `COPY` command using `FORMAT`, it works only when using lowercase. Autocompletion also shows the lowercase form

### To reproduce

try to issue a command such as 

```
COPY so_posts FROM 'posts/so_posts.csv' 
WITH HEADER true FORMAT 'yyyy-MM-ddTHH:mm:ss.SSS' ON ERROR ABORT;
```

You will get an error

Try now using lowercase `format`

```
COPY so_posts FROM 'posts/so_posts.csv' 
WITH HEADER true format 'yyyy-MM-ddTHH:mm:ss.SSS' ON ERROR ABORT;
```

### Expected Behavior

It should be case insensitive, as the rest of keywords

### Environment

```markdown
- **QuestDB version**: 6.5
- **OS**: Linux
- **Browser**:
```

**Comment by puzpuzpuz** [comment]
Closed by #2407
