### ISSUE TITLE
SQL query result incorrect

### ISSUE THREAD

**Issue by pokliu** [questdb/questdb#2418]
### Describe the bug

I have a questdb table with schema:
``` sql
CREATE TABLE 'aws_iot_data_rule' (
  ts TIMESTAMP,
  region SYMBOL capacity 8 CACHE,
  product_id SYMBOL capacity 128 CACHE,
  device_uid SYMBOL capacity 131072 CACHE index capacity 4096,
  sn STRING,
  dtype SYMBOL capacity 256 CACHE index capacity 4096,
  dvalue STRING
) timestamp (ts) PARTITION BY HOUR;
```

This data table has about 20,000,000 entries per day written(o3) by 5 ILP TCP clients.

Recently I found that when querying in the console, the query result does not match the SQL statement intent.

![image](https://user-images.githubusercontent.com/7621696/183899346-d68ef384-d5e5-46c5-a1a7-226380f588c4.png)
For example, in the query above, I try to get data with `dtype` of `pm25`, but the returned result contains data with `dtype` of other values.

![image](https://user-images.githubusercontent.com/7621696/183900063-8c65d421-06f6-404b-8c54-5f2182e3d821.png)
Based on the previous query, the query in the above figure only removes the filter condition of `and dtype='pm25'`, but the returned result can find the data of earlier time.

Also I have not manually modified the db data file of the file system.

### Expected Behavior

The query results can correctly filter the data.

### Environment

```markdown
- **QuestDB version**: v6.4.1
- **OS**: Linux
- **Browser**: Chrome
```

### Additional context

I copied the file system of questdb to another server, and installed version 6.5 of questdb. After startup, the query result is correct. I wonder if questdb might have index corruption under O3 data submission?

**Comment by bziobrowski** [comment]
I think both issues could be fixed in latest version so could you please re-test on 6.5 ?

**Comment by pokliu** [comment]
> I think both issues could be fixed in latest version so could you please re-test on 6.5 ?

OK. I will try to migrate to the latest version and keep watching~

**Comment by pswu11** [comment]
Hi @pokliu do you still experience the same issue in 6.5?

**Comment by pswu11** [comment]
Thanks a lot for reporting back. I will close this issue for now, if it appears again feel free to reopen it. 
Also, we have a user community for discussions: https://slack.questdb.io/
