### ISSUE TITLE
support of rank() function

### ISSUE THREAD

**Issue by Luyang2902** [questdb/questdb#2422]
### Is your feature request related to a problem?

rank() function is very useful when we want to develop a BI tools on questdb,  rankings is uesed to filter.

view is a useful to simplify sql code and this is very important for low-code platform and helpful to get query result in realtime

**Comment by pswu11** [comment]
Hi @Luyang2902 for clarity, I removed "view" from the title and improved the title for your previous issue #2201.

**Comment by blackstar-baba** [comment]
LGTM， can i develop this？

**Comment by pswu11** [comment]
Hi @blackstar-baba anyone interested in the issue can feel free to make a pull request :) 
pay attention to https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md

**Comment by blackstar-baba** [comment]
Thank you, i will read this markdown doc.

**Comment by blackstar-baba** [comment]
Hi @pswu11,do we have some docs to help with development?

**Comment by pswu11** [comment]
Hi @blackstar-baba our CONTRIBUTING.md is the only one available now. 
As for the context of this feature, perhaps you could refer to how `rank()` works in PostgreSQL:
https://www.postgresql.org/docs/14/functions-window.html#FUNCTIONS-WINDOW-TABLE
https://www.postgresql.org/docs/14/tutorial-window.html

If you have more specific questions about the code base you could join our community https://slack.questdb.io/; in #contributors channel
