### ISSUE TITLE
could not open read-only [file=H:\BuleDb\QuestDb\bin\qdbroot\db\BoolTest\default\a.d]

### ISSUE THREAD

**Issue by donet5** [questdb/questdb#2425]
could not open read-only  ，Restarts have no effect and appear randomly

.NET CORE     PGSQL

**Comment by donet5** [comment]
![image](https://user-images.githubusercontent.com/12455385/184515675-b6289a14-bb1b-478d-901a-fb69e6a23358.png)

**Comment by donet5** [comment]
You can insert but you can't read

**Comment by donet5** [comment]
Single-threaded randomness can be reproduced

**Comment by donet5** [comment]
The program Tuncate table is updated after executing the insert query

**Comment by bluestreak01** [comment]
The error usually comes with OS error number, eg “[2] could not open”. Could you share the error value please ?

**Comment by donet5** [comment]
Do you have.NET CORE? Let me write a DEMO for you

**Comment by donet5** [comment]
[QuestDbTest.rar](https://www.donet5.com/_theme/ueditor/utf8-net/net/upload/file/20220815/6379617345139276526675852.rar)

​

**Comment by donet5** [comment]
This is very serious, after locking the table can not be used, rather the database is invalid

**Comment by donet5** [comment]
I found a way to unlock it



1. Restart the service

2. Disable Turncate Table SQL 

3. Insert a record in C#


The lock can be unlocked in three steps

**Comment by pswu11** [comment]
@donet5 thanks a lot for raising the issue. We'll look into it.
