### ISSUE TITLE
the same code but different results

### ISSUE THREAD

**Issue by Luyang2902** [questdb/questdb#2426]
### Describe the bug

there are two code snap,after execute ,the first report an error :
![image](https://user-images.githubusercontent.com/98975457/184562465-86baaf6a-afff-463d-8322-c8f4fc4ae95e.png)

but the second snap works! who can tell me the difference between the two snaps

 select a.code , closeprice/close-1 as r  
  from ( select code,close 
  from 'kline_5M'
  latest on timestamp partition by code) as a join( select code,closeprice from 'RealtimeTick'
  latest on timestamp partition by code) as b  
on a.code=b.code

  select a.code ,closeprice/close-1 as r   
  from ( select code,close 
  from 'kline_5M'
  latest on timestamp
  PARTITION by code) as a join( select code,closeprice
  from 'RealtimeTick'
  latest on timestamp
  PARTITION by code) as b on a.code=b.code

### Environment

```markdown
- **QuestDB version**: 6.5
- **OS**:
- **Browser**:
```

**Comment by bziobrowski** [comment]
Both sqls seem to work in 6.5.2 .
