### ISSUE TITLE
Why does the column index file take up a lot of storage space?

### ISSUE THREAD

**Issue by pokliu** [questdb/questdb#2432]
### Is your feature request related to a problem?

Run sql in console:
``` sql
create table test(
  ts timestamp,
  uid SYMBOL capacity 131072 index capacity 4096
) timestamp(ts) partition by hour;

insert into test 
select 
  systimestamp() ts, 
  rnd_str(10000, 32, 32, 0) uid
from long_sequence(10000);
```

Then `cd` into `db/test/{partition}` folder, and `du -sh *`:
```
[root@*** 2022-08-16T09]# du -sh *
16M	ts.d
16M	uid.d
512K	uid.k
209M	uid.v
```

I have generated `10000` different strings of length `32` here to insert into the `test` table. I found that as the cardinality of the uid field increases, the storage space of the `uid.v` file in the file system becomes very large.

The documentation on the official website does not explain the role of the `.v` file, but it seems to form an index table together with the `.k` file. Through calculation, we can see that `32bytes * 10000 = 320KB`, I don't know why `uid.v` is enlarged hundreds of times.

Actually I have a high device cardinality data table, and the unique number of the device is a `UUID` which is 32 bytes long. Due to the need to perform real-time query as much as possible, I set `commitLag` to `5s`, but the data time reported by different device is out-of-order, it is inevitable that such a high combined IO will be generated. So if the partition is by `DAY`, each merge will occupy a huge amount of IO resources and cause the service to be unavailable. So I use `HOUR` partitions to reduce IO usage, but as a result each partition of the table has a huge `.v` file causing heavy disk usage.

### Describe the solution you'd like.

If possible, reduce the storage footprint of `.v` files, or use some mechanism to reuse `.v` files instead of having a copy in each partition folder

### Describe alternatives you've considered.

Update the official website documentation to clarify the purpose and generation mechanism of each file (such as `.v` `.o` `.i`) in the partition folder.

**Comment by ideoma** [comment]
You can reduce symbol capacity. How many rows per symbol values are you going to have within 1 Hour partition? You probably reduce it by 24 if 4096 is the capacity of the index on daily partitioning.

We do not recommend to use indexes anymore, parallel scans are faster if you have available CPU resources. Sounds like you will benefit more from 128bit UUID type you could use instead of symbols

**Comment by pokliu** [comment]
> You can reduce index capacity. How many rows per symbol value are you going to have within 1 Hour partition? You can probably reduce it to 128 if 4096 is the capacity of the index on daily partitioning.
> 
> We do not recommend to use indexes anymore, parallel scans are faster if you have available CPU resources. Sounds like you will benefit more from 128bit UUID type you could use instead of symbols

Thank you for your help! 

I have found that reducing the index capacity size can greatly reduce the storage footprint. But I don't understand `You can probably reduce it to 128 if 4096 is the capacity of the index on daily partitioning.` How is this calculated, why is the index capacity planning set to `128` (instead of `4096`) can fit each partition single `4096` data reports for symbol? Also, is `on daily partitioning` a typo (hourly partitioning)?

In addition, for the `parallel scans` you mentioned, I did not find the corresponding documentation on the official website. Since my query will be filtered by the unique device number, does this `UUID` have to use the `symbol` type?

**Comment by ideoma** [comment]
>  How is this calculated, why is the index capacity planning set to `128` (instead of `4096`) can fit each partition single `4096` data reports for symbol? Also, is `on daily partitioning` a typo (hourly partitioning)?

`4096 / 24 = 170.66` which is close to 128 (real allocated capacity is power of 2)
