### ISSUE TITLE
Cannot access data for specific period of time

### ISSUE THREAD

**Issue by langustav** [questdb/questdb#2433]
### Describe the bug

When we try to query data with timestamps within a specific period of time we get an error. Affected timestamps are approx. between 2022-07-01 12:00:00 and 2022-07-02 02:00:00 UTC
The whole QuestDB is restarted. 

It is a window of several hours at our table. Timestamps before and after are fine. The data are a few weeks old. 

### To reproduce

We cannot reproduce it with a new table or data. 

### Expected Behavior

It should return data. 

### Environment

```markdown
- **QuestDB version**: 6.4.3
- **OS**: Docker
- **Browser**: it is not related to a browser
```

### Additional context

[qdb-preprod-coredump-6.4.3.txt](https://github.com/questdb/questdb/files/9351227/qdb-preprod-coredump-6.4.3.txt)

**Comment by puzpuzpuz** [comment]
@langustav the crash dump looks weird, as if your database files were corrupted due to power loss or `kill -9`. Would it be possible to share an archive with the table directory with me over our community [Slack](https://slack.questdb.io/)?

**Comment by marregui** [comment]
Hola @langustav 

All good?

**Comment by langustav** [comment]
Sorry. Thanks for the suggestion. In the end, we found that we are restarting our docker container once a day. There was an issue that if it was taking too long (more than a few seconds) the container was killed by the parent process. I think we can close the issue now.

**Comment by marregui** [comment]
oh!, excellent! have a great weekend!
