### ISSUE TITLE
Definition of a delimiter for CSV exports

### ISSUE THREAD

**Issue by ostermannIAO** [questdb/questdb#2452]
### Is your feature request related to a problem?

Recently we started using QuestDB in one of our projects. We wanted to implement the export-function into our backend-services and realized, that exporting data with a predefined delimiter is not possible (see documentation here: https://questdb.io/docs/reference/api/rest/#exp---export-data)

### Describe the solution you'd like.

We would like to have an additional attribute to be able to define the delimiter as predefined character in order to export CSV-files with it.

### Describe alternatives you've considered.

The alternative would be to export the data first, iterate over the complete content (like a post-process) and then use this data.

**Comment by pswu11** [comment]
Hi @ostermannIAO thank you for creating the feature request! 
In case you're not aware of it, we also have a community on Slack for QuestDB developers: https://slack.questdb.io/
