### ISSUE TITLE
QDB Crashes On Simple 'WHERE' Queries (on indexed SYMBOLs?)

### ISSUE THREAD

**Issue by ozitrance** [questdb/questdb#2466]
### Describe the bug

Just trying to run simple WHERE queries on fresh database resulting in a crash every time. 

Table was initially created using python/SQL with:
`CREATE TABLE IF NOT EXISTS {name}(side SYMBOL index, type SYMBOL index, price DOUBLE, qty DOUBLE, ts TIMESTAMP) timestamp(ts) PARTITION BY DAY`

Importing rows was done using TCP Line Writer (python)
Table currently has ~ 2 million rows.

Seems to happen with other indexed symbols as well but NOT with prices/qty fields (numeric?) and NOT with non-indexed SYMBOLs.

Seems to happen with any table I create (all have similar structure but completely different values and tried many different/non-related ones).
Seems to happen through the web interface and/or querying SQL.

Other than that everything seems fine. SELECT queries return all results immediately (great performance!) and 'ORDER BY' seems to be fine as well, so really not sure what's going on...

I attached the log files.

### To reproduce

You can use the web interface or run simple python code as below, the result is the same:

```
import psycopg2 as pg
connection = None
cursor = None
try:
    connection = pg.connect(
        user='admin',
        password='quest',
        host='127.0.0.1',
        port='8812',
        database='qdb')
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM CTKUSDT WHERE side = 'ask';") 
    records = cursor.fetchall()
```

OR From the web:
`SELECT * FROM CTKUSDT WHERE side = 'ask';`

### Expected Behavior

Return results without crashing  :)

### Environment

```markdown
- **QuestDB version**: 6.5
- **OS**: Windows 10 21H2 (OS Build 19044.1865)
- **Browser**: Chrome 104.0.5112.102 (Official Build) (64-bit)
```

### Additional context

[stdout-2022-08-25T17-19-45.txt](https://github.com/questdb/questdb/files/9428957/stdout-2022-08-25T17-19-45.txt)
[qdb-preprod-coredump-6.4.3.txt](https://github.com/questdb/questdb/files/9428959/qdb-preprod-coredump-6.4.3.txt)

**Comment by ozitrance** [comment]
Ok I was able to narrow it down to wrong configuration on my part...
I was using an oversized value for: `cairo.index.value.block.size`
A little more reasonable yet still oversized value seems to be working fine..

**Comment by pswu11** [comment]
@ozitrance thanks for reporting back!
