### ISSUE TITLE
does questdb has any plans to develop plugins in dbveaver?

### ISSUE THREAD

**Issue by john1337** [questdb/questdb#2475]
### Is your feature request related to a problem?

does questdb has any plans to develop plugins in dbveaver?now i can only do such things on web console which is not conveient

### Describe the solution you'd like.

does questdb has any plans to develop plugins in dbveaver?now i can only do such things on web console which is not conveient

**Comment by bluestreak01** [comment]
yeah, there are plans of course. We're looking to implement missing syntax and views in Q4

**Comment by marregui** [comment]
clossing the issue. We do plan on improving the dbeaver experience, however we ourselves will not be creating plugins for this product. We kindof have our own version, which lags behind somewhat https://github.com/questdb/desktop-questdb-client
