### ISSUE TITLE
Automatic log file deletion in LogRollingFileWriter

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2477]
### Is your feature request related to a problem?

`LogRollingFileWriter` should support automatic log file deletion based on time or space. The check can take place each time when a new log file is rolled.

### Describe alternatives you've considered.

A cron job that would delete older log files does the trick, but having a built-in feature is better.

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing a little time explaining how I can solve this and pointing me to some resources to get started.

**Comment by puzpuzpuz** [comment]
Hello,

The main point of interest in this one is the `LogRollingFileWriter` class. The idea is that it should support additional configuration based on total number of files or the log directory size. Whenever one of these options is provided, the writer should check and delete older log files each time it rolls a new log file.

**Comment by joanneong** [comment]
@sreenath-tm Are you still working on this?

@puzpuzpuz For log directory size, consider the case where the size specified by the user is small and a single log file ends up being larger than that. We can either delete all the log files in the file directory, or leave just the most recent log file be. What do you think is better? Personally I'm more inclined to leave at least one log file in the file directory (but this may not be as consistent with what the user set in the config)

**Comment by puzpuzpuz** [comment]
We should definitely keep the most recent file even if it exceeds the threshold.

**Comment by sreenath-tm** [comment]
Yes I am working on this issue. As you said we will defenitely keep the latest log file generated.

**Comment by joanneong** [comment]
@sreenath-tm Alright then. Let me know if you are not - I'm keen to help out for Hacktoberfest :)

**Comment by sreenath-tm** [comment]
@joanneong I am working on the issue currently, If I am not able to do it will defenitely let you know.
