### ISSUE TITLE
Support backward interval generation in IN operator

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2509]
### Is your feature request related to a problem?

IN operator support interval generation:
```
select timestamp, price
from trades
where timestamp in '2018-01-01T13:00:00;1h;24h;10000'
```

The above query would return results from 13:00-14:00 intervals for 10K days starting with 2018-01-01, so the results are in future when compared with the start date.

Would be nice to support backward iteration syntax, e.g. '2018-01-01T13:00:00;1h;-24h;10000', which would return intervals in the past.

**Comment by anonymous-baaka** [comment]
Hi, I would definitely love to work on this feature

**Comment by puzpuzpuz** [comment]
@anonymous-baaka awesome to hear that. The logic is located in `IntervalUtils#parseInterval()` while some correlated tests may be found in `WhereClauseParserTest#testComplexInterval*()` tests. Let me know if you have any questions.

**Comment by anonymous-baaka** [comment]
@puzpuzpuz thank you for your reply. Will definitely look into it.

**Comment by akshaybhadange** [comment]
i would also like to work on it ! . plz guide me this as it my first contribution

**Comment by puzpuzpuz** [comment]
Hi @akshaybhadange,

Please refer to the [contributing guide](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) as the first step. Then [this comment](https://github.com/questdb/questdb/issues/2509#issuecomment-1242722784) has essential details necessary for this feature.

**Comment by joanneong** [comment]
@akshaybhadange Are you going to work on this? I took a look at the code and I think I can pick it up if you aren't

**Comment by akshaybhadange** [comment]
@joanneong yes sure thanks
