### ISSUE TITLE
log append issue.

### ISSUE THREAD

**Issue by cumtqiangqiang** [questdb/questdb#2519]
### Describe the bug

w.file.rollEvery=day
w.file.rollSize=1g

For std log, such as stdout-2022-09-08T13-57-54.txt
for the default config rollSize = 1g, it is not rolled, according to size and  rollEvery, it is increased to 8G, and I delete it.Then There's no log file generation here after I delete it.

### Environment

```markdown
- **QuestDB version**:6.5.2
- **OS**:
- **Browser**:
```

**Comment by puzpuzpuz** [comment]
Closing since the configuration wasn't enabling LogRollingFileWriter
