### ISSUE TITLE
[ONGOING] Add contributors to the readme

### ISSUE THREAD

**Issue by mpsq** [questdb/questdb#252]
We now integrate with [all-contributors](https://allcontributors.org/) :tada:.

We can start adding those who help us a lot to our readme. This is a way for us to recognize really valuable contributions. Those can be commits and code related but also testing, help on finding bugs, new issues, new ideas, documentation improvements, etc.

You can find the list of emojis [here](https://allcontributors.org/docs/en/emoji-key), and pick the right one depending on the type of contribution.

If you just started looking at QuestDB and want to contribute, please have a look at our [CONTRIBUTING.md](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md), there is many ways you can help!

**Comment by mpsq** [comment]
@all-contributors bot, please add @sirinath for ideas

**Comment by mpsq** [comment]
@all-contributors bot, please add @tonytamwk for code and userTesting.
[This](https://github.com/questdb/questdb/pull/193) was an amazing PR, thanks again!

**Comment by mpsq** [comment]
Also, @all-contributors, please add @ideoma for code, userTesting and test.

**Comment by mpsq** [comment]
@all-contributors bot, please add @ideoma for code, userTesting, test.

**Comment by mpsq** [comment]
@all-contributors bot, please add @igor-suhorukov for code and ideas.
Thanks for you contributions and feedback, it is really appreciated :pray:

**Comment by mpsq** [comment]
@all-contributors bot, please add @mick2004 for code and platform.
Thanks a lot for your work Abhishek, and welcome to our community :tada:

**Comment by mpsq** [comment]
@all-contributors bot, please add @rawkode for code and infra.
Thanks David for your work on k8s :100:

**Comment by mpsq** [comment]
@all-contributors bot, please add @solidnerd for code and infra.
Thanks Niclas for your help on our Helm chart, support for Helm Hub will come soon, I will keep you updated :wink:

**Comment by mpsq** [comment]
@all-contributors bot, please add @solanav for code and doc.
Kudos for the Rust driver! I am not a Rust expert but I reviewed the code and it is a great implementation. Thank you for taking the time to implement this and welcome to the QuestDB ecosystem :boom:.

**Comment by mpsq** [comment]
@all-contributors bot, please add @shantanoo-desai for blog and example.
Thanks for your contribution Shan, great work on `questitto` :muscle:

**Comment by mpsq** [comment]
@all-contributors bot, please add @alexprut for code and maintenance.
Thanks for your refactoring work Alex! Let me know if you are around at some point, it would be good to catch-up!

**Comment by mpsq** [comment]
@all-contributors bot, please add @chankeypathak for blog.
Thanks for the guide (#594), this is great! :tada:

**Comment by mpsq** [comment]
@all-contributors bot, please add @chankeypathak for blog.
Thanks for the guide (#594), this is great! :tada:

**Comment by mpsq** [comment]
@all-contributors bot, please add @upsidedownsmile for code.
Thanks for the PR improving the SQL parser (#629) :slightly_smiling_face:

**Comment by mpsq** [comment]
@all-contributors bot, please add @Nagriar for code.
Thanks for the PR (#724) slightly_smiling_face

**Comment by mpsq** [comment]
@all-contributors bot, please add @piotrrzysko for code and test.
Thanks for the PR (#796) :pray:

**Comment by bsmth** [comment]
@all-contributors bot, please add @siddheshlatkar for code

Thanks for the contribution! 🎉 (https://github.com/questdb/questdb/pull/830)

**Comment by bsmth** [comment]
@all-contributors bot, please add @Yitaek for tutorial, example

Thanks for the awesome [Kafka](https://questdb.io/tutorial/2021/02/18/realtime-crypto-tracker-with-kafka-and-questdb/) and [Iot Core](https://questdb.io/tutorial/2021/02/05/streaming-heart-rate-data-with-iot-core-and-questdb/) tutorials! :books:

**Comment by bsmth** [comment]
@all-contributors bot, please add @gabor-boros for tutorial, example 

Thanks for the awesome [tutorial](https://questdb.io/tutorial/2021/01/13/application-uptime-monitoring-with-python-nuxtjs-questdb/) and [example application](https://github.com/gabor-boros/questdb-statuspage) 🔧 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @kovid-r for tutorial, example 

Thanks Kovid for brilliant contributions about [SQL extensions](https://towardsdatascience.com/sql-extensions-for-time-series-data-in-questdb-f6b53acf3213) for time series and how to use [Influx line protocol](https://towardsdatascience.com/schemaless-ingestion-in-questdb-using-influxdb-line-protocol-18850e69b453) 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @TimBo93 for bug, userTesting

Thanks Tim for [filing multiple bug reports](https://github.com/questdb/questdb/issues?q=is%3Aissue+author%3ATimBo93+), and your feedback which greatly helps us improve the stability of the system! 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @Yitaek for tutorial, example

Thanks for the awesome [Kafka](https://questdb.io/tutorial/2021/02/18/realtime-crypto-tracker-with-kafka-and-questdb/) and [Iot Core](https://questdb.io/tutorial/2021/02/05/streaming-heart-rate-data-with-iot-core-and-questdb/) tutorials! :books:

**Comment by bluestreak01** [comment]
End of an era. From now on we can comment at allcontributors in PRs and other issues
