### ISSUE TITLE
Add ability to drop the latest partition

### ISSUE THREAD

**Issue by newskooler** [questdb/questdb#2529]
### Is your feature request related to a problem?

Often I need to drop the latest partition (i.e. the "active" one), however that's not possible to do as noted in the [docs](https://questdb.io/docs/reference/sql/alter-table-drop-partition/).

### Describe the solution you'd like.

It would be nice to have the ability to do this.

### Describe alternatives you've considered.

None really... Always the last partition cannot be removed.

**Comment by marregui** [comment]
Hi, it is going to happen. Very likely in the next release, within the month of October.

Thank you for requesting the feature, and thank you for the upvotes!

**Comment by marregui** [comment]
Related discussion, for reference: https://github.com/questdb/questdb/discussions/2568
