### ISSUE TITLE
brew services start questdb fails

### ISSUE THREAD

**Issue by sklarsa** [questdb/questdb#2534]
### Describe the bug

After a fresh `brew install questdb`, I want to run the database as a service on my local machine, so I ran the following command (see output included)

```
% brew services start questdb
==> Successfully started `questdb` (label: homebrew.mxcl.questdb)
steven@Stevens-MBP questdb % brew services info questdb
questdb (homebrew.mxcl.questdb)
Running: ✘
Loaded: ✔
Schedulable: ✘
```

In an attempt to gain more information, I inspected the `/opt/homebrew/opt/questdb/homebrew.mxcl.questdb.plist` file for the log path.  Unfortunately, there was no file in the specified path: `cat: /opt/homebrew/var/log/questdb.log: No such file or directory`

This could be user error, since I've never used `brew services` before, but it could also be related to the homebrew formula itself.

### To reproduce

```
brew install questdb
brew services start questdb
```

### Expected Behavior

The service starts

### Environment

```markdown
- **QuestDB version**: 6.5.2
- **OS**: Monterey 12.3
- **Browser**: N/A


steven@Stevens-MBP questdb % brew info questdb
==> questdb: stable 6.5.2 (bottled)
Time Series Database
https://questdb.io
/opt/homebrew/Cellar/questdb/6.5.2 (8 files, 7.9MB) *
  Poured from bottle on 2022-09-19 at 16:56:37
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/questdb.rb
License: Apache-2.0
==> Dependencies
Required: openjdk@11 ✔
```
```


### Additional context

_No response_

**Comment by jerrinot** [comment]
interesting. it's working for me:) but perhaps it's because I started QuestDB before. Are you on M1?

**Comment by jerrinot** [comment]
ok, I see the problem. This is the reproducer: 
1. uninstall questdb `brew remove ...`
2. manually remove quest data: `rm -rf /opt/homebrew/var/questb`
3. `brew install questdb`
4. `brew services start questdb` -> qdb fails to start

When I manually start and stop questdb `questdb start && questdb stop`, then `brew services start questdb` starts working. 

A hypothesis to validate: When starting as a service it relies on a directory structure in `/opt/homebrew/var/questdb` to be already created.

**Comment by jerrinot** [comment]
fix candidate: https://github.com/Homebrew/homebrew-core/pull/111335

**Comment by carlocab** [comment]
Do
```
brew update
brew postinstall questdb
```
then try again.

Thanks @jerrinot for the fix!
