### ISSUE TITLE
Pivoting - Dense and Sparse Vectors, Matrices, Cubes, Tensors and Dimensional Data

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#255]
Is it possible to add the ability to zero-copy dense and sparse pivots which can represent a table as vectors, matrices, cubes and tensors? Also, perform calculations on these structures where the underlying data in the pivot keep changing and the changes being propagated. Most of the time pivoting needs to be used with data windows (https://github.com/questdb/questdb/issues/218).

The data for the axis need to come from common queries or tables more than 1 pivot needs the same labelling and shape. Outer joints will be needed for this. If the window, table or the query does not have all the data against the axis labels a sparse pivot will be created.

The pivoting can be on top of a moving or tumbling window as mentioned in: https://github.com/questdb/questdb/issues/218. The data is reactive and needs recomputing as the underlying data changes.

This can be further used as a foundation to build AI, ML, DS applications and general scientific computing and modelling.

[TileDB](https://tiledb.com/) can give some ideas on the DB aspect. [xarray](http://xarray.pydata.org/en/stable/) and to a lesser extent [ND4J](https://nd4j.org/) are useful to get ideas for the representation.

Ref:

- [MADlib](https://madlib.apache.org/) - ML on top of Postgress. 
- [CubeDB ](https://github.com/cubedb/cubedb) - dimensional analysis.
- [TileDB](https://tiledb.com/) - dimensional data structure
- [Ignite](https://ignite.apache.org/) - has ML feature though not necessary way to represent dimetional data.
- [xarray](http://xarray.pydata.org/en/stable/) - good project to study to get ideas
- [ND4J](https://nd4j.org/) - N-Dimensional Arrays for Java

**Comment by sirinath** [comment]
When benchmarking the operations of the pivot implementation, it might be worth considering benchmarking against [Petalisp](https://github.com/marcoheisig/Petalisp).

**Comment by bsmth** [comment]
I'm closing this as it's out of scope with the features we are focusing on at the moment.

If this feature is something you would like to add, you may also contribute directly by submitting a patch - see the [contribution guide](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) for details. :)

Thank you!
