### ISSUE TITLE
Support CREATE TABLE LIKE syntax

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2565]
### Is your feature request related to a problem?

Postgres supports the following syntax
```sql
CREATE TABLE tab_2 (LIKE tab_1);
```
to avoid having to copy-paste schema from another table when exactly same schema is required. We could support this [syntax](https://www.postgresql.org/docs/current/sql-createtable.html) too, for now without `like_options`.

**Comment by akki1306** [comment]
Hi @puzpuzpuz I would like to pick this up could you assign me? Appreciate any initial pointers for working on this as a first time contributor. Thanks in advance.

**Comment by puzpuzpuz** [comment]
Hi @akki1306

First of all, you should check our [contribution guide](https://github.com/questdb/questdb/blob/88202e73aff990d149ce95aeaa3a21f46a921d40/CONTRIBUTING.md).

The entry points are `SqlParser#parseCreateStatement()` and `SqlCompiler#createTableWithRetries()` methods. First, you need to update parser (and its tests in `SqlParserTest`) to accept the new syntax. Then `SqlParser` would need to acquire a table reader for the source table, read the metadata and prepare a `CreateTableModel` to pass it to the existing create table methods. The integration tests are in the `CreateTableTest` class.

Look forward to your contribution. Have fun!

**Comment by akki1306** [comment]
Thanks for the helpful explanation. Will start working on it.

**Comment by singloon** [comment]
@puzpuzpuz when we pass in the query `SqlParser`, how would we evaluate `LIKE tab_1`? Would we lookup to see if the tab_1 table exists, since now we're checking if its one of the column types e.g. boolean, byte?

**Comment by puzpuzpuz** [comment]
No, the parser itself doesn't do any existence checks - it's only job is to validate the syntax and extract necessary tokens, such as table names. The existence check has to be done at the `SqlCompiler` level.

**Comment by singloon** [comment]
@puzpuzpuz ok, so now if the lexer is not a columnType we'll still allow it through but it does mean we lose that protection?

**Comment by puzpuzpuz** [comment]
`SqlParser` has a `tok(GenericLexer, String)` method to deal with that - check how it parses the table name in CREATE TABLE statements and also the following `GenericLexer#assertNoDotsAndSlashes()` validation:
https://github.com/questdb/questdb/blob/88202e73aff990d149ce95aeaa3a21f46a921d40/core/src/main/java/io/questdb/griffin/SqlParser.java#L526

Or course, the patch should include negative tests for invalid table names to verify that the user gets a meaningful error message.

**Comment by akki1306** [comment]
Hi @puzpuzpuz, apart from the following, which other fields need to be populated from Metadata to CreateTableModel?

1. Column Names
2. Column Types
3. Column Indexes

I couldn't figure out how to set partitionBy and timestamp in the CreateTableModel from TableReaderMetadata.

**Comment by puzpuzpuz** [comment]
You should be able to read all values via `TableReaderMetadata` (see `TableReader#getMetadata()`): `timestamp`, `partitionBy`, `maxUncommittedRows`, `commitLag` and `walEnabled` should be read apart from what you have listed.
