### ISSUE TITLE
Performance degradation when aliasing columns

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#2566]
### Describe the bug

This query executes on the demo box in around 100ms:
```
select symbol, count() 
from trades 
group by symbol;
```

but this query executes 10s (100x more!)
```
select symbol as s, count() 
from trades 
group by s;
```

Both queries are functionally equivalent and should result in the same query plan. Apparently, that's not the case. 
I reckon aliasing disables an optimization. 

### Environment
https://demo.questdb.io/
- **QuestDB version**: 6.5.3

**Comment by HariniKrishnan** [comment]
Hi the problem seems to be interesting if it is not assigned already, can I take this?!

**Comment by bluestreak01** [comment]
sure thing!

**Comment by HariniKrishnan** [comment]
thanks will work on this please assign this to me..
