### ISSUE TITLE
Feature: Change type of a column from SQL

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#257]
**Describe the solution you'd like**
I would like to be able to change the type of a column from SQL, possibly with an expression similar to `ALTER COLUMN`.

**Additional context**
Current SQL for adding an index to an existing column:

```sql
ALTER TABLE trades ALTER COLUMN instrument ADD INDEX;
```

### implementation

This can be broken down into tasks

- [ ] Save column order in table `_metadata` that is used in `SELECT *` queries
- [ ]  Support of SQL syntax and create `AlterOperation` 
- [ ] Support of changing the column type as a single transaction in `TableWriter`. This will add the column of the new type, copy the data into it, drop the old column, and change the order of SELECT * columns in metadata.
- [ ] Support of the column type change in WAL writers
- [ ] Support of the column type update in WAL ILP writing pipelines

**Comment by ideoma** [comment]
This can be broken down into tasks

- [ ] Save column order in table `_metadata` that is used in `SELECT *` queries
- [ ]  Support of SQL syntax and create `AlterOperation` 
- [ ] Support of changing the column type as a single transaction in `TableWriter`. This will add the column of the new type, copy the data into it, drop the old column, and change the order of SELECT * columns in metadata.
- [ ] Support of the column type change in WAL writers
