### ISSUE TITLE
🌏 Hacktoberfest 2022: list of SQL functions for contributors

### ISSUE THREAD

**Issue by pswu11** [questdb/questdb#2578]
Hello everyone, [happy Hacktoberfest](https://hacktoberfest.com/)!

QuestDB is accepting PRs for Hacktoberfest 2022! 
We create this issue to list some feature ideas you can contribute to our core database! 

# Ideas

We collect a list of ideas you could contribute to QuestDB, focusing on PostgreSQL compatibility. 

🐥 Junior
🐔 Experienced

## Numeric 🐥 
- [x] `ceiling` https://github.com/questdb/questdb/pull/2600
- [x] `log10` https://github.com/questdb/questdb/pull/2579
- [x] align the use of `log` and use it as `ln` https://github.com/questdb/questdb/pull/2605
- [ ] `width_bucket` https://github.com/questdb/questdb/pull/2630

## String 🐥 
- [x] add `lower` and `upper` as aliases to our existing functions to_lower, to_upper to be PostgreSQL compatible https://github.com/questdb/questdb/pull/2582
- [x] add `position` as alias of `strpos` to be PostgreSQL compatible https://github.com/questdb/questdb/pull/2599
- [x] `ltrim`, `rtrim`,`trim`, https://github.com/questdb/questdb/pull/2613
- [x] `lpad`, `rpad`, https://github.com/questdb/questdb/pull/2631
- [x] `starts_with`, https://github.com/questdb/questdb/pull/2608
- [x] `split_part`,  https://github.com/questdb/questdb/pull/2644

Reference: https://www.postgresql.org/docs/15/functions-string.html

## Window functions 🐔 

- [ ] corr
- [ ] stddev
- [ ] mode
- [ ] percentile_count, percentile_disc https://github.com/questdb/questdb/issues/1371
- [x] rank, https://github.com/questdb/questdb/pull/2624 
- [ ] dense_rank
- [ ] percent_rank
- [ ] ntile
- [ ] lag
- [ ] lead
- [ ] first_value
- [ ] last_value
- [ ] nth_value

# Tips

- Pay attention to [our contribution guidelines](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md).
- Start with existing issues (or refer to the above ideas) rather than creating new ones. While new ideas are generally welcomed, they don't always fit the project roadmap.
- Filter issues with `good first issues` or `help wanted` tags if you're new to the projects.
- Avoid commenting on all the available issues but those you really plan to work on, leaving some opportunities to other contributors.
- Our maintainers will review your pull requests, please make sure you address all the comments before asking for another review. 
- Join our [Slack](https://slack.questdb.io/) in #contributors channel if you need extra help. 

# Others

Not familiar with SQL functions or database development? Here are other repositories that accept contributions: 
- [Web console](https://github.com/questdb/ui/tree/main/packages/web-console): Monorepo that contains the code of QuestDB GUI. It is a web application written with Typescript and React.
- [Documentation](https://github.com/questdb/questdb.io): QuestDB's website for documentation, suitable for technical writers who have experience with Markdown and Docusaurus. Read [our guidelines for docs contributors](https://github.com/questdb/questdb.io#contributing).

**Comment by AbhishekTiwari23** [comment]
I want to contribute to this one, please allow me.

**Comment by pswu11** [comment]
Hi @AbhishekTiwari23 you can create a pull request with your solution and mention this issue directly, thanks!

**Comment by Ln11211** [comment]
>align the use of log and use it as ln in PostgreSQL https://www.postgresql.org/docs/15/functions-math.html

hey @pswu11 , what does the align the use of log and use it as ln mean ?, does it have anything to do with the preceding issue and PR- log10 https://github.com/questdb/questdb/pull/2579 ?

 what exactly should be done?

**Comment by pswu11** [comment]
Hi @Ln11211 so basically what `log()` means in QuestDB and in PostgreSQL are different right now. For compatibility, it'd be better if we align the definition with PostgreSQL so users can adapt more easily. You can refer to the docs and try them out to see that they work differently. 

QuestDB docs 

> log[#](https://questdb.io/docs/reference/function/numeric/#log)
> log(value) return the natural logarithm (loge) of a given number.


PostgreSQL docs

> ln ( double precision ) → double precision
> Natural logarithm

> log ( double precision ) → double precision
> Base 10 logarithm

> log10 ( double precision ) → double precision
> Base 10 logarithm (same as log)

**Comment by techrajdeep** [comment]
I am looking for an issue for my first contribution . Can you help me here. Can I take on this .

**Comment by daniel-shuy** [comment]
I've come up with some strategies to reduce code duplication in SQL function implementations, see #2644 as an example

**Comment by pswu11** [comment]
> The floor() function already exists. Ideally the ceiling() function should have aliased the existing ceil() function instead of re-implementing it.

Hi @daniel-shuy good gatch, it's one of the undocumented functions that we overlooked. 👀

**Comment by siddharthans2000** [comment]
Hey is it issue still open?
can I start for the remaining tasks which are incomplete?

**Comment by pswu11** [comment]
Hi @siddharthans2000 Hacktoberfest is over, but if you're interested in contributing certain features / fixing bugs here - feel free to try make a pull request. Or, you could try to look up existing GitHub issues, and see if there are other more interesting ones to work on.

**Comment by SyedImtiyaz-1** [comment]
I'm interested to contribute here. Can you please assign this to me @pswu11

**Comment by AKACHI-4** [comment]
Hey @pswu11 U would like to work on a task under this issue. Can u assign it to me I will try to complete that task ASAP

**Comment by pswu11** [comment]
Hi @javier perhaps you could advise on how to handle this issue? Thanks!

**Comment by GSV13719833** [comment]
Hi, I want to contribute to this topic, please allow me.

**Comment by Somya2010** [comment]
Hi @pswu11 I want to contribute to this one pls allow me
