### ISSUE TITLE
ILIKE SQL operator is not case-insensitive

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2585]
### Describe the bug

In [Postgres](https://www.postgresql.org/docs/current/functions-matching.html), ILIKE can be used instead of LIKE to make the match case-insensitive according to the active locale. Yet, our implementation uses the same code for both LIKE and ILIKE (see `LikeStrFunctionFactory` and `ILikeStrFunctionFactory` classes). We should fix it.

### Environment

```markdown
- **QuestDB version**: 6.5.3
- **OS**:
- **Browser**:
```

**Comment by TheZal** [comment]
I would like to try to work on that if possible!

**Comment by AMAN2202** [comment]
Hi, I would  love to work on this issue

**Comment by Ln11211** [comment]
@puzpuzpuz I read the attached Postgres documentation and also checked the classes out but I still don't understand how to fix it, any other inputs please?

**Comment by puzpuzpuz** [comment]
`java.util.regex.Pattern` supports a [case-insensitive matching flag](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html#CASE_INSENSITIVE) and that flag should be used by ILIKE.
