### ISSUE TITLE
bogus TTL values in server.conf

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#2595]
### Describe the bug

server.conf in 6.5.3 distributions has this as a sample:
```
# defines frequency in milliseconds with which the reader pool checks for inactive readers.
#cairo.inactive.reader.ttl=-10000

# defines frequency in milliseconds with which the writer pool checks for inactive readers.
#cairo.inactive.writer.ttl=-10000
```
Negative values make no sense to me, most likely it's bogus. It should be sync with: https://github.com/questdb/questdb/blob/b33459673138985fd3a776f67f3cbad2ef05afd9/core/src/main/java/io/questdb/PropServerConfiguration.java#L689-L690

### Environment

```markdown
- **QuestDB version**: 6.5.3
- **OS**:
- **Browser**:
```

**Comment by ShubhamPalriwala** [comment]
Hey @jerrinot, would like to get started in QuestDB with this issue.
Basically, we shuld change the values present here:
https://github.com/questdb/questdb/blob/8c663f0d242d6c10de2e61a33c7a37cce17aad25/pkg/ami/marketplace/assets/server.conf#L169
https://github.com/questdb/questdb/blob/8c663f0d242d6c10de2e61a33c7a37cce17aad25/pkg/ami/marketplace/assets/server.conf#L172

 and 
https://github.com/questdb/questdb/blob/8c663f0d242d6c10de2e61a33c7a37cce17aad25/core/src/main/resources/io/questdb/site/conf/server.conf#L169
https://github.com/questdb/questdb/blob/8c663f0d242d6c10de2e61a33c7a37cce17aad25/core/src/main/resources/io/questdb/site/conf/server.conf#L172

Now about what to change it to, I'm taking a guess that we will set it as default:
cairo.inactive.reader=120000
cairo.inactive.writer.ttl=5*60*1000.

Let me know your thoughts on this

**Comment by jerrinot** [comment]
hello @ShubhamPalriwala, thank you  for getting involved! 
 
Yes, I think you identified the right places! 

As for the values: reader ttl should be `120000` and write should be `600000`. The same as the default at https://github.com/questdb/questdb/blob/b33459673138985fd3a776f67f3cbad2ef05afd9/core/src/main/java/io/questdb/PropServerConfiguration.java#L690-L691
