### ISSUE TITLE
Incorrect partition name is shown in the repair table hint

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2619]
### Describe the bug

The following error may be shown when a table has a missing partition:
```
[0]: Partition '2022-10-08.1634154936' does not exist in table 'test_table' directory. 
Run [ALTER TABLE test_table DROP PARTITION LIST '2022-10-08.1634154936'] to repair the table or restore the partition directory.
```

Here the partition name should be `2022-10-08`, not `2022-10-08.1634154936`.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by sharmadhiraj86** [comment]
Hello, I am interested in working on this issue. Can you please assign this issue to me? @puzpuzpuz

**Comment by bluestreak01** [comment]
sure thing 👍

**Comment by Ln11211** [comment]
> sure thing 👍

Hello, I think I found why it is printing the long number with the partition and I fixed it, but how do I reproduce the same error to see if it is fixed and can I raise a PR?

**Comment by puzpuzpuz** [comment]
You'd need to write a test that reproduces the error scenario. See `AlterTableDropPartitionTest#testPartitionDeletedFromDiskWithoutDropByDay()` for some inspiration. Obviously, you'd need to produce several versions of the partition, so that you get the suffix. That can be done by inserting out-of-order (older) rows into an existing table.

**Comment by sharmadhiraj86** [comment]
> > sure thing 👍
> 
> Hello, I think I found why it is printing the long number with the partition and I fixed it, but @puzpuzpuz  how do I reproduce the same error to see if it is fixed and can I raise a PR?

@Ln11211 Hii. This issue has been assigned to me and this is a part of my academic curriculum. So please can you allow me to solve this issue? And if you find any solution to this issue, please let me know, I would apply that to solve the issue.
 Thank you

**Comment by Ln11211** [comment]
Hello @sharmadhiraj86,
very well, here is what I found after searching for the **_does not exist in table_** message in the code, The message is from the code in `TableReader.java` , to be exact, lookout for the variable `partitionnameTXN` in lines 834 and 839, I am convinced that this is being printed along with the message although I am not sure but I checked the declaration and implementation of `partitionnameTXN` and it is being put with a period and it is likely the number you see after the partition name.


Once you do your investigation, try to reproduce the same message and then try commenting out those lines(834 and 839) and reproduce the message again and see if there is any change.

Hope this helps :-)
