### ISSUE TITLE
UPDATE support

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#262]
**Is your feature request related to a problem? Please describe.**
Tables with [designated timestamp](https://www.questdb.io/docs/designatedTimestamp) support inserts with a `timestamp` superior or equal to the latest. In some instances, new entries could be unnecessary duplicates, for example if a sensor sends the same reading several times, or if the reading does not change (only the timestamp).

**Describe the solution you'd like**
Supporting UPSERT to complement INSERT and avoid writing data unnecessarily.

**EDIT**: This should actually be called `UPDATE`. Renaming the issue.

**Comment by wojtek2kdev** [comment]
Can I try to handle that?

**Comment by bluestreak01** [comment]
of course!

**Comment by wojtek2kdev** [comment]
I'm new in this project and I need more details about that task. Can you describe this more widely by some use case? Besides I got a few doubts:
1. How is this supposed to looks like from SQL side? Should UPSERT be SQL keyword? Is it implemented now or should I add this? Does it have to be coupled with INSERT keyword or should it be separated command?
2. Should UPSERT reject duplicate or update certain columns if some value already exists? That misconception comes from solution description "avoid writing data unnecessarily". For instance - Can database user specify columns which UPSERT has to observe for trigger (update instead of insert). Maybe it should work only if all values are duplicated?
I'd be thankful for some advices.

**Comment by TheTanc** [comment]
Hey, first of all Welcome! And thanks for picking up the issue. The first description I wrote is confusing, so let me clarify here. 

QuestDB is append-only but supports synthetic [UPDATE using LATEST BY](https://www.questdb.io/docs/crudOperations#update). However, writing updates is tedious. It is done via [INSERT](https://www.questdb.io/docs/insert) and requires to explicitly set every column (skipped columns will default to `null` otherwise). It also requires one `INSERT` statement per row update.

This new statement allows to
- create several updates with one command specifying filters
- not have to set values when they don't change

Note: upon second thought, this would actually be better described by `UPDATE` statement. I will rename the issue.

**Example** 
Consider the following table.
|ts | a | b | c|
|-- | -- | -- | --|
|2020-05-03T22:24:09.841341Z | x | abc | 123|
|2020-05-03T22:24:15.498426Z | y |abc | 234|
|2020-05-03T22:24:29.193676Z | z | def | 345|

Currently, an update would be inserted as follows.
```
INSERT INTO tableName VALUES(systimestamp(), 'y', 'abc', 999);
```

1- The new statement would require to implement new SQL keywords `UPDATE` and `SET` but would not require `INSERT`.

**Example**
```
UPDATE tableName
SET ts = systimestamp(), c = 999
WHERE a = y;
```

In both cases the end-table would look like this 
|ts | a | b | c|
|-- | -- | -- | --|
|2020-05-03T22:24:09.841341Z | x | abc | 123|
|2020-05-03T22:24:15.498426Z | y |abc | 234|
|2020-05-03T22:24:29.193676Z | z | def | 345|
|**2020-05-03T22:24:41.9483712Z**|**y** | **abc** | **999**|

2 - There is a twist. Let's say I run the UPDATE command a second time. The resulting table would be the following.
|ts | a | b | c|
|-- | -- | -- | --|
|2020-05-03T22:24:09.841341Z | x | abc | 123|
|2020-05-03T22:24:15.498426Z | y |abc | 234|
|2020-05-03T22:24:29.193676Z | z | def | 345|
|2020-05-03T22:24:41.9483712Z | y | abc | 999|
|**2020-05-03T22:24:41.9483734Z** | **y** | **abc** | **999**|
|**2020-05-03T22:24:41.94837156** | **y** | **abc** | **999**|

We now appended 2 rows to the table instead of 1. This is because we inserted an update for all matching records, but in reality only wanted to update the latest. For this reason, the implementation requires to implicitly use `LATEST BY`. 

In practice, the server would work as follows.
1- find all records corresponding to a certain criteria (using only the latest)
2-append to the end of the table except for the values in the `SET` part of the statement

This could take model on [`CREATE TABLE AS(select_statement)`](https://www.questdb.io/docs/createTable#create-table-as). The differences being that
- it requires the ability to use values from `SET` statement rather than the cursor
- the select statement would require implicit `latest by` to avoid the problem described in (2)

**Comment by mpsq** [comment]
@wojtek2kdev welcome to our repository! If you want to know more about how the project is structured and how to setup QuestDB locally, you can look at our [contributing](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) guidelines. I can tell that you are already on Slack, please don't hesitate to ping us there too :).

**Comment by wojtek2kdev** [comment]
@TheTanc Ok I guess I get it. So in short:

Having such query: 
```sql 
UPDATE table SET c=3210 WHERE a='y';
 ```
1. Find all rows that match the criteria. (e.g rows with column **a** equal to 'y')
2. Get only latest one.
3. Copy all columns except those included after SET statement. (e.g all except **c** column)
4. Insert new row with copied values and SET values.

Am I right that such solution is similar to **event store**?

**Comment by TheTanc** [comment]
That's right! And yes, the mechanism is similar to event store.

For step 2 I would just point out that for the latest can be several rows. Consider the following example:

ts | a | b | c
-- | -- | -- | --
2020-05-03T22:24:09.841341Z | x | 1 | 100.1
2020-05-03T22:24:15.498426Z | x | 2 | 100.2
2020-05-03T22:24:29.193676Z | x | 3 | 100.3
2020-05-03T22:24:41.9483712Z | y | 1 | 100.4
2020-05-03T22:24:41.9483734Z | y | 2 | 100.5
2020-05-03T22:24:41.94837156 | y | 3 | 100.6

This statement `UPDATE table SET c=101.1 where a in ('x','y');` would actually aim to insert two updates. So latest needs to be keyed by value of `a`. The equivalent select statement is `table where a in ('x','y') latest by a;`

Expected result from `SELECT`
ts | a | b | c
-- | -- | -- | --
2020-05-03T22:24:29.193676Z | x | 3 | 100.3
2020-05-03T22:24:41.94837156 | y | 3 | 100.6

Expected `table` after the `UPDATE` statement:
ts | a | b | c
-- | -- | -- | --
2020-05-03T22:24:09.841341Z | x | 1 | 100.1
2020-05-03T22:24:15.498426Z | x | 2 | 100.2
2020-05-03T22:24:29.193676Z | x | 3 | 100.3
2020-05-03T22:24:41.9483712Z | y | 1 | 100.4
2020-05-03T22:24:41.9483734Z | y | 2 | 100.5
2020-05-03T22:24:41.94837156 | y | 3 | 100.6
**2020-05-03T22:24:49.12394321** | **x** | **3** | **101.1**
**2020-05-03T22:24:55.38473489** | **x** | **3** | **101.1**


To generalise, I think any column invoked in the `WHERE` part of the statement should be used in `latest by`. As an example, for `UPDATE table SET c=102.2 where a in ('x','y') and b in (1,2);` the equivalent `SELECT` would be `table where a in ('x','y') and b in (1,2) latest by a,b;`. This select would return 4 results and therefore `UPDATE` would insert 4 rows.

@bluestreak01  do you have more comments?

**Comment by wojtek2kdev** [comment]
I must consider another cases. What is desired behavior if we will try to update table without **where** clause? Taking into account above principles, db should copy all rows with changed column. Should we have possibility to use explicit **latest by** in **update** statement? 

Another one - is it even possible to make column "unique"? For example - what if I want to keep in db user which email should be unique? Every user update results email copy to next row with updated data. So how to distinguish user update from new user insert with same email, what is unwanted? If we would have some key column in table, then we won't need to use **latest by** explicit, instead we could use something like **head/tail rows_number** or **all** to select whole history, or **head/tail** to occur particular value in column e.g 
```sql
user where email=value; --get latest.
user where email=value head 3; --get 3 latest rows.
user where email=value tail 3; --get oldest 3 rows.
user where email=value head ts=some_day; --get all user history to particular day from latest row.
user where email=value tail ts=some_day; --get all user history to some_day from the beginning. 
```

**Comment by postol** [comment]
Support for update/delete would be much appreciated - it is a number 1 item on our list which we would like to see in questdb soon.

**Comment by puzpuzpuz** [comment]
UPDATE support was added in 6.4.

**Comment by sjamesc** [comment]
> Can I effectively `UPSERT` or not? I don't want to switch between `INSERT` and `UPDATE` when in theory `UPSERT` can do the job. Timescaledb allows it.

A little old now but for anyone else wondering, this works well for upserting when there's a common key (e.g timestamp): https://questdb.io/docs/concept/deduplication/

**Comment by puzpuzpuz** [comment]
> A little old now but for anyone else wondering, this works well for upserting when there's a common key (e.g timestamp): https://questdb.io/docs/concept/deduplication/

Yes, deduplication effectively works as UPSERT. It's certainly less expensive than UPDATE, so it should be preferred over UPDATE when possible.
