### ISSUE TITLE
Built In ORM | Serialize Graph to DB | Object Graph Deserialisation from DB Data | Generate Proxy Objects Backed by DB

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#263]
Having to use a 3rd party ORM library will reduce the benefits of using QuestDB to overhead and perhaps GC.

So it is possible to have QuestDB specific ORM which is lightweight and performant. 

The cases to support are;

- serialised and deserialize objects from and to memory from and to the DB
- generate proxies to data residing in the DB

Also, objects in DB should be directly accessible and manipulatable without having to deserialise object into memory. Field updates can be captured and updated directly in the DB data structures. As the DB is append-only this would mean new entries need to be inserted with new version ID. An object ID will also be needed to distinguish between different object instances and also a way to know if the object is active or live. Also, updates on the object may be transactional on issuing a commit or auto committed on each mutation of the object. In the former, a separate buffer may be needed but in the latter, the DB data structures can be directly mutated for speed.

E.g.

```Java
class C {
   int f1;
   int f2;
}
```

will map into

```
TABLE C(
   SYS$_ts TIMESTAMP, 
   SYS$_ID LONG, 
   SYS$VER LONG, 
   f1 INT, 
   f2 INT, 
   SYS$_live boolean
) timestamp(SYS$_ts)
```

Also coupled with https://github.com/questdb/questdb/issues/218 and https://github.com/questdb/questdb/issues/241 ability to pass deserialised or proxy objects as results reactively.

**Comment by bsmth** [comment]
I'm closing this as it's out of scope with the features we are focusing on at the moment.

If this feature is something you would like to add, you may also contribute directly by submitting a patch - see the [contribution guide](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) for details. :)

Thank you!
