### ISSUE TITLE
incorrect `FILL` results

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#2636]
### Describe the bug

```
select
  id,
  time,
  last(lat) lat,
  last(lon) lon,
  geo6
from
  pos
where
  id = 'YWPCEGICTJSGGBRIJCQVLJ' sample by 15m fill(null) ALIGN to CALENDAR;
```

### To reproduce

compare SQL output with and without `fill` clause

### Environment

```markdown
Demo
```

**Comment by TalhaQuddoos** [comment]
Hi, I'm interested in this issue. Can you please assign this to me?

**Comment by puzpuzpuz** [comment]
@TalhaQuddoos sure thing. Done.

**Comment by TalhaQuddoos** [comment]
@bluestreak01 I haven't been a user of QuestDB. Can you please tell me how the output should ideally look like when the FILL keyword is present?

**Comment by bluestreak01** [comment]
without `fill` you should be able to observe aggregated data for each of 15 min interval. From eyeballing the output it looks like all intervals are present (no gaps in time).

When you add `fill(null)` to this particular SQL - the net effect should be 0 - there are no intervals to fill.
