### ISSUE TITLE
Attach partitions as soft links to directories from different drive

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#2641]
### Is your feature request related to a problem?

It's useful to support tables with partition located on different physical (network) drives attached to the same box. QuestDB should support to procedure to move some (older / inactive) partitions to other drive / directories in Linux file system and have them in the Table directory as soft links to the partition folders.

### Describe the solution you'd like.

We can archive that by detaching partition, then allow user to move it to another drive / folder in the background and then attach it back as soft link. The scenario will be

1. User has table a with data located at `/home/questdb/db/a` and partitions `2022-02-24`, `2022-02-25`
2. User runs `ALTER TABLE a Detach partition LIST '2022-02-24'`
3. User moves directory `2022-02-24.detached` from table directory `a` to another drive `/mnt/driveb/a/2022-02-24.detached`
4. User creates soft link from `/mnt/driveb/a/2022-02-24.detached` to `/home/questdb/db/a/2022-02-24.attachable`
5. User runs `ALTER TABLE a Attach partition LIST '2022-02-24'`

At the end of the step 5 table `a` has 2 partitions `2022-02-24`, `2022-02-25` while directory `/home/questdb/db/a/2022-02-24` is a soft link to `/mnt/driveb/a/2022-02-24.detached`

### Describe alternatives you've considered.

Attaching from another drive can automatically create soft links instead of copying files

**Comment by lasse-tarp-CA** [comment]
I like the fact that you can add more drives over time (fast/expensive or slow/cheap) and move files without having limitations in conf file.
Using .attachable as identifier is a good idea.
