### ISSUE TITLE
Support short date formats in queries

### ISSUE THREAD

**Issue by clickingbuttons** [questdb/questdb#265]
**Is your feature request related to a problem? Please describe.**
I used to be able to write dates in queries like `select * from table where date<'2010-02-04'` in v4.2.0.

**Describe the solution you'd like**
I'd like to be able to write dates using a short format in queries like this:
- `'2010-02-03'`
- `'2010-02'`
- `'2010'`

They could fairly easily be translated to their long format counterparts:
- `'2010-02-03T00:00:00.000Z'`
- `'2010-02-01T00:00:00.000Z'`
- `'2010-01-01T00:00:00.000Z'`

**Describe alternatives you've considered**
I've considered using the long format and I find it harder to read/write. I frequently am writing time-based queries surround days, months, and years rather than hours, minutes, seconds, and microseconds.

**Comment by TheTanc** [comment]
+1
This used to be supported and should be reinstated.

**Comment by bluestreak01** [comment]
fixed
