### ISSUE TITLE
Unable to import data when a designated timestamp column is present on the table

### ISSUE THREAD

**Issue by Recodify** [questdb/questdb#2675]
### Describe the bug

When trying a COPY import on data that includes a microsecond unix timestamp to a table that has a designated timestamp column the following error is logged:

`i.q.c.t.CsvFileIndexer could not parse timestamp [line=475318, column=3]`

When performing a COPY import using the same data, but to a table without the designated timestamp column, all is well.

Does not work:
```
CREATE TABLE 'reading' (
  deviceId STRING,
  readingTypeId SYMBOL,
  value FLOAT,
  readingDate TIMESTAMP
) timestamp (readingDate) PARTITION BY DAY;
```

Works:
```
CREATE TABLE 'reading' (
  deviceId STRING,
  readingTypeId SYMBOL,
  value FLOAT,
  readingDate TIMESTAMP
);
```

### To reproduce

Data:

```
"deviceId","readingTypeId","value","readingDate"
"09e23486-d607-44b8-a488-329180f8b495","electricity.gbp.saving","3600.0000","1577836800000000"
"c7fc76e4-b07f-4ed6-8707-8b9f66f98b4a","electricity.gbp.saving","3600.0000","1577836800000000"
"c9f29f4d-2f10-4c4c-ab4e-05c85143c314","electricity.power.hour","0.1010","1577836800000000"
"52575f52-d662-436e-903a-9a57284e5394","electricity.power.hour","0.1020","1577836800000000"
"09e23486-d607-44b8-a488-329180f8b495","electricity.power.hour","0.1564","1577836800000000"
"0ed9469d-22cc-425a-9311-da6fa5ce147a","electricity.power.hour","0.2580","1577836800000000"
"c7fc76e4-b07f-4ed6-8707-8b9f66f98b4a","electricity.power.hour","0.2838","1577836800000000"
"94549bfb-db75-4d23-a552-f70ae9f38a7d","electricity.power.hour","0.2860","1577836800000000"

```

SQL:

```
CREATE TABLE 'reading' (
  deviceId STRING,
  readingTypeId SYMBOL,
  value FLOAT,
  readingDate TIMESTAMP
) timestamp (readingDate) PARTITION BY DAY;

COPY reading from 'readings.csv';
```

Check logs and you'll see: `i.q.c.t.CsvFileIndexer could not parse timestamp [line=475318, column=3]`

Repro video: 

https://user-images.githubusercontent.com/5644228/197521443-a412cc51-9693-40b1-ba26-1747893fa60d.mp4

### Expected Behavior

Imports data successfully. 

### Environment

- QuestDb Version: 6.5.3
- OS: Ubuntu 20.4
- Browser: Chrome/na

### Additional context

Works ok on questDb 6.4.2

Discussed on slack With Javier Ramirez, Nicolas Hourcard and @puzpuzpuz 

Here: https://questdb.slack.com/archives/C1NFJEER0/p1666609980466839?thread_ts=1666609590.192809&cid=C1NFJEER0

and here: https://questdb.slack.com/archives/C1NFJEER0/p1666609073077389

**Comment by Recodify** [comment]
@puzpuzpuz You suggested in slack that COPY always expects a datetime format, not long, so I gave this a go.

Data:
```
"09e23486-d607-44b8-a488-329180f8b495","electricity.gbp.saving",3600.0000,"2020-01-01 00:00:00.000"
"c7fc76e4-b07f-4ed6-8707-8b9f66f98b4a","electricity.gbp.saving",3600.0000,"2020-01-01 00:00:00.000"
"c9f29f4d-2f10-4c4c-ab4e-05c85143c314","electricity.power.hour",0.1010,"2020-01-01 00:00:00.000"
"52575f52-d662-436e-903a-9a57284e5394","electricity.power.hour",0.1020,"2020-01-01 00:00:00.000"
```

Error: `E i.q.c.t.ParallelCsvFileImporter could not import [phase=analyze_file_structure, ex=column is not a timestamp [no=3, name='']]`

So I tried changing my timestamp column to a date, but it looks like this isn't allowed for designated timestamp?

```
CREATE TABLE reading (
  deviceId STRING,
  readingTypeId SYMBOL,
  value FLOAT,
  readingDate DATE
) timestamp (readingDate) PARTITION BY DAY;
```
Error:

```
2022-10-25T07:14:24.476121Z I i.q.c.h.p.JsonQueryProcessorState [130] sql error [q=`CREATE TABLE reading (
  deviceId STRING,
  readingTypeId SYMBOL,
  value FLOAT,
  readingDate DATE
) timestamp (readingDate) PARTITION BY DAY;
`, at=113, message=`TIMESTAMP column expected [actual=DATE]`]
```

**Comment by Recodify** [comment]
Thanks @puzpuzpuz, no dice with that one either. 

Data:
```
"deviceId","readingTypeId","value","readingDate"
"09e23486-d607-44b8-a488-329180f8b495","electricity.gbp.saving",3600.0000,"2020-01-01T00:00:00.000000Z"
```
Error: `E i.q.c.t.ParallelCsvFileImporter could not import [phase=analyze_file_structure, ex=column is not a timestamp [no=3, name='']]`

**Comment by puzpuzpuz** [comment]
Let me check it locally.

**Comment by puzpuzpuz** [comment]
```sql
CREATE TABLE reading (
  deviceId STRING,
  readingTypeId SYMBOL,
  value FLOAT,
  readingDate TIMESTAMP
) timestamp (readingDate) PARTITION BY DAY;
```

```csv
"deviceId","readingTypeId","value","readingDate"
"09e23486-d607-44b8-a488-329180f8b495","electricity.gbp.saving",3600.0000,"2020-01-01T00:00:00.000000Z"
"07e23486-d607-44b8-a488-329180f8b495","electricity.gbp.saving",3600.0000,"2020-01-02T00:00:00.000000Z"
"05e23486-d607-44b8-a488-329180f8b495","electricity.gbp.saving",3600.0000,"2020-01-03T00:00:00.000000Z"
```

With the above, both of the following COPY statements work fine:
```sql
COPY reading FROM 'input.csv' WITH HEADER true TIMESTAMP 'readingDate' FORMAT 'yyyy-MM-ddTHH:mm:ss.SSSUUUZ';
COPY reading FROM 'input.csv' WITH HEADER true;
```

I used v6.5.4, but v6.5.3 should be similar.
