### ISSUE TITLE
Persisting and retrieving object state and method invocation history for fully reproducible systems - Event Sourcing DB | Active Objects

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#268]
The main idea here is to periodically persist object state and subsequent method calls to have programs which are fully reproducible. If something goes wrong: the last snapshot state is loaded followed by the event to method call translations for the subsequent events. Having this built-in help develop very highly reliable and resilient systems.

Is  it possible to have a way by means of proxy:

- Capture and store call followed by reflectively recalling the stored calls:
  - capture object creation followed by all calls to an object or group of objects stored in a collection
  - re-create the object and replay all the calls to the object or collection of objects
- Capture and store object state and retrieve and replay from stored object state
  - capture object state from change to change or periodically from objects or a group of objects in a collection
  - replay object state from the captured state
- Mix of both above in replay, i.e, retore state followed by evoking stored/captured calls

The objects can be:

- objects in memory which can be serialised and deserialised from and to the DB through https://github.com/questdb/questdb/issues/263
- objects in DB accessed as in-memory proxy objects through https://github.com/questdb/questdb/issues/263

In applying the method evocations they can be on:

- a single object - the table has only a method name and parameters
- multiple objects - the table has an object key to select the object in addition to the above

Messaging patterns mentioned in https://github.com/questdb/questdb/issues/241 which would enable finer control over:

- object selection
- which method evocations to apply

In conjunction with https://github.com/questdb/questdb/issues/263 distributed replicated and synchronised objects can be created. Also using supervisory structure if there is an error a new object can be created with last know good state and subsequent events played to bring it up to date.

Very rudimentary active object scheme is found in:

- https://github.com/LMAX-Exchange/disruptor-proxy

But does not deal with the capture, storage and retrieval of the invocations but only linearisation of requests. The method calls are separated from the actual calls and stored in a queue. Plus there would be more choice of messaging patterns with https://github.com/questdb/questdb/issues/241 which would enable finer control over which method evocations to apply to which objects, even distributed replicating objects and state. In the proposed solutions the method evocations are stored in the DB. Also, the state snapshots are serialised to recreate the state at any point. This will use https://github.com/questdb/questdb/issues/263.

Also see:

- https://eventuate.io/
- https://axoniq.io/
- https://github.com/commanded/eventstore
- https://martendb.io/
- Message DB - https://github.com/message-db/message-db, http://docs.eventide-project.org/user-guide/message-db/
- https://eventide-project.org/
- http://pumpkindb.org/

**Comment by bluestreak01** [comment]
Is there a specific example where storing application state in background is beneficial. I can see significant issues with this approach when it comes to providing any consistency guarantees. I can't help but think that restoring application state to some random snapshot in time is largely unhelpful.

**Comment by sirinath** [comment]
An account will have the current asset and cash balances. As new transactions are applied this will change. The transaction needs to be applied in order and in entirety otherwise, the balances will be wrong and failed and the successful transaction may not be the same.

If the system crash when bringing it live again you can get the last account state and apply the subsequent transaction to make accounts up to date.

In this case, what would be convenient is:

1. All accounts being mapped to both in-memory proxy objects and stored objects in DB where an update to in-memory proxy or DB will reflect on the other. In-memory, proxy objects will come into play in https://github.com/questdb/questdb/issues/263 which are light weigh proxies which can be accessed as any Java object but backed my data in the DB.
2. All method calls which effectively apply the transactions are also captured in the DB so starting given sate (i.e., list of holdings and balances) the current state or holdings and balances can be deduced.

**Comment by sirinath** [comment]
Similarly, any use case where `state_1 = state_0 + transaction_1` format which is about many cases mutating sate update on and an object can be modelled using this system. Here `state_n = state_0 + apply(transaction_1 .. transaction_n)`. `state_0` is the sate snapshot to store and `transaction_1 .. transaction_n` is the list of method invocations to store. This way if the system crash at `transaction_m` where `m < n` then what is needed is to restore `state_0` and apply `transaction_1 .. transaction_n`. With periodic snapshots, it will be the last stored state and subsequent transactions.

**Comment by sirinath** [comment]
[ObjectBox ](https://objectbox.io/) a DB for IoT and Edge computing supports the part where object state can be stored without an ORM as discussed in https://github.com/questdb/questdb/issues/263. It does not, however, have the options to retain old object version and store and replay method calls as seamlessly.

**Comment by bsmth** [comment]
I'm closing this as it's out of scope with the features we are focusing on at the moment.

If this feature is something you would like to add, you may also contribute directly by submitting a patch - see the [contribution guide](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md) for details. :)

Thank you!
