### ISSUE TITLE
Timestamps from Postgres are not imported

### ISSUE THREAD

**Issue by leon-sony** [questdb/questdb#2687]
### Describe the bug

Postgres emits timestamps with varying numbers of digits in the milliseconds place, omitting trailing `0`s. Importing these into QuestDB fails.

### To reproduce

1. In Postgres:
    ```sql
    CREATE TABLE demo (timestamp TIMESTAMP, data FLOAT);
    INSERT INTO demo (timestamp, data) VALUES ('2022-01-01T01:01:01.123456Z', 1), ('2022-02-02T02:02:02.12345Z', 2);
    COPY demo TO '/tmp/demo.csv';
    ```
2. Note contents of `/tmp/demo.csv` contains microsecond timestamps with varying numbers of digits:
    ```csv
    2022-01-01 01:01:01.123456,1
    2022-02-02 02:02:02.12345,2
    ```
3. Copy `demo.csv` to the QuestDB import directory.
4. In QuestDB:
    ```sql
    CREATE TABLE demo (timestamp TIMESTAMP, data FLOAT) TIMESTAMP (timestamp);
    COPY demo FROM "demo.csv" CSV;
    SELECT * FROM demo;
    ```
5. Note that there is no data present in table `demo`.

### Expected Behavior

The data I exported from Postgres would be copied into the QuestDB `demo` table.

### Environment

```markdown
- **QuestDB version**: Docker questdb/questdb:6.4.3
- **OS**: Ubuntu 20.04
- **sql client**: psql 14.5
- **PostgreSQL version**: Docker docker.io/library/postgres:11@sha256:5d2aa4a7b5f9bdadeddcf87cf7f90a176737a02a30d917de4ab2e6a329bd2d45
```

**Comment by bluestreak01** [comment]
thanks Leon, i'm on it

**Comment by leon-sony** [comment]
Awesome, thanks!
