### ISSUE TITLE
CREATE TABLE with INDEX causing error 

### ISSUE THREAD

**Issue by SuriZhang** [questdb/questdb#2689]
### Describe the bug

I was implementing sqlancer support for questdb, and have found the bug below:

when executing a `CREATE TABLE` query with INDEX, it does check not constraint on INDEX column type so allows me to create index on a non-symbol column and got the error: 
```
[14:53:28]
Invalid metadata at fd=139. Index flag is only supported for SYMBOL at [1]
```

### To reproduce

Execute the query:

`CREATE TABLE t100(c0 INT, c1 BOOLEAN), INDEX (c1);`

### Expected Behavior

this should fail and gives an error like `Index flag is only supported for SYMBOL`
### Environment

```markdown
- **QuestDB version**: 6.5.3
- **OS**: MacOS 11.7
- **Browser**: Version 106.0.5249.119 (Official Build) (x86_64)
```

**Comment by bziobrowski** [comment]
Possibly related : 
```sql
CREATE TABLE t100 as (select x from long_sequence(1000) ), index(x);
```
returns "Could not create table. See log for details." error with 
"io.questdb.cairo.CairoException: [-100] Invalid metadata at fd=2900. Index flag is only supported for SYMBOL at [0]" appearing in log. Table doesn't get created but it'd be better to show "Index flag is only supported for SYMBOL" .

**Comment by SuriZhang** [comment]
yes! sorry I just saw this. 
I have further implemented some code in sqlancer and have found some potential bugs. I'm taking a look at the logs now. let's move the thread to slack for better comm : )

**Comment by puzpuzpuz** [comment]
Many thanks. Sure, let's do it.
