### ISSUE TITLE
High idle CPU usage

### ISSUE THREAD

**Issue by PiotrDabkowski** [questdb/questdb#269]
**Describe the bug**
The **idle** CPU usage is pretty high at ~3%.

**To Reproduce**
Follow https://www.questdb.io/docs/installFromDockerImage
Run `docker stats` to measure CPU usage.

Sometimes the idle cpu usage reaches even 10%, but most of the time it stays stable at ~3%.

**Expected behavior**
Idle CPU usage is <0.1%.

**Screenshots**
<img width="1054" alt="Screenshot 2020-05-10 at 00 07 01" src="https://user-images.githubusercontent.com/4052440/81486102-cb0fb800-9252-11ea-9c3b-65626476cc20.png">

**Environment (please complete the following information):**
 - Ubuntu 18
 - Latest Docker image

**Comment by bluestreak01** [comment]
CPU should "calm down" after a period of inactivity. Otherwise threads are "busy" rather than blocking.

**Comment by PiotrDabkowski** [comment]
Thanks! For some reason this does not happen, I have checked after ~8 hours of inactivity and still at ~3%. Not a big deal - 3% is not too bad, but would be great to not waste CPU unnecessarily.

Unfortunately, I do not know Java so I am unable to help with this.

**Comment by tandr** [comment]
I am getting 30-36% idle (I suspect on one core)  on macbook pro 2.3 GHz 8-Core Intel Core i9 . I used questdb-5.0.3-rt-osx-amd64.tar.gz to get it running (would be nice if questdb.sh would have a `version` option, that prints  troubleshooting-related info.)

<img width="630" alt="Screen Shot 2020-09-03 at 2 49 19 PM" src="https://user-images.githubusercontent.com/5227075/92165721-b6a08e00-edf4-11ea-9cac-ee253d6a5f4c.png">

**Comment by nslocum** [comment]
@tandr on my macbook pro I'm also seeing idle cpu usage at ~25% of a single core.
I'm using questdb-5.0.3 which was installed using brew

**Comment by tomarus** [comment]
Hey i'm seeing the same. Around 50% (out of 1200%) cpu usage. It doesn't really look right and it's not cooling down after a period of idling. I want to run this on a low-power wardrobe server but with this cpu usage it's actually not really that efficient.

**Comment by bluestreak01** [comment]
could you try this configuration?

```
shared.worker.count=1
shared.worker.yield.threshold=1
shared.worker.sleep.threshold=1
line.tcp.io.worker.yield.threshold=1
line.tcp.io.worker.sleep.threshold=1
```

**Comment by tomarus** [comment]
> could you try this configuration?

Thanks a lot, this certainly helped a lot, except the 2nd and 3rd didn't make really much of a difference.

After playing around with other settings i've added those below and the cpu usage is 50% less than yesterday. Which is perfect for my usecase :-)

```
line.tcp.io.worker.count=1
line.tcp.writer.worker.count=1
line.tcp.writer.worker.sleep.threshold=1
line.tcp.writer.worker.yield.threshold=1
```

Also i've noticed when i completely disable the tcp line protocol almost all of the cpu usage is gone. Disabling udp didn't make any difference.

**Comment by jfcalvo** [comment]
I have similar high CPU usage values. 

~15% CPU idle after run questdb/questdb:6.1` docker image without configuration changes of any type:

![Captura de pantalla 2021-10-30 a las 16 25 29](https://user-images.githubusercontent.com/446497/139537088-9c6c4224-8f7a-4d04-860d-7914c3e8875d.png)

I will try suggested configuration values.

**Comment by vizovitin** [comment]
Same here, and none of the configurations suggested here make situation better for QuestDB server 6.0.9 (via `questdb/questdb:latest` docker image). CPU usage is consistently at 5-6% without any external load.

**Comment by Geequlim** [comment]
Same problem.
Start an empty instance from docker hub, nothing write. Just place it 10min. 
The memory is keep flying!
![image](https://user-images.githubusercontent.com/6964556/142732435-27ff6343-92e8-4a28-a516-e8e1cf7bb77a.png)

**Comment by pswu11** [comment]
@Geequlim thanks for the information! @bluestreak01 could you help take a look please? thanks!

**Comment by kaybinwong** [comment]
Same problem on version 6.1.3.
cpu usage keeps 40% without any ops.

![image](https://user-images.githubusercontent.com/5570216/146123104-a8cb009f-4c10-40ec-9de6-dc03b137c2ee.png)

> > could you try this configuration?
> 
> Thanks a lot, this certainly helped a lot, except the 2nd and 3rd didn't make really much of a difference.
> 
> After playing around with other settings i've added those below and the cpu usage is 50% less than yesterday. Which is perfect for my usecase :-)
> 
> ```
> line.tcp.io.worker.count=1
> line.tcp.writer.worker.count=1
> line.tcp.writer.worker.sleep.threshold=1
> line.tcp.writer.worker.yield.threshold=1
> ```
> 
> Also i've noticed when i completely disable the tcp line protocol almost all of the cpu usage is gone. Disabling udp didn't make any difference.

**Comment by hschultz1960** [comment]
![image](https://user-images.githubusercontent.com/43204191/149543297-8a7ed706-7983-417c-9183-38163ae66f8b.png)
FWIW ... problem is stretching into 2022 
Same observation here on an up-to-date binary installation on Ubuntu 20.04 LTS.
Java process constantly hovering 20-25%, and a virtual footprint of close to 12 GB

Guys, I think you have a fairly reproducible issue to look at here ;-)

**Comment by thomas0bernard** [comment]
![image](https://user-images.githubusercontent.com/14042277/149677925-082b8f3e-41ea-4f1f-bb3d-aac7d4abf440.png)
I have the same issue on Debian 11 running the latest Docker image (6.1.3). I have tried the suggested configurations and it doesn't affect CPU usage.

**Comment by bluestreak01** [comment]
guys, thank you for reporting these - am I right to assume there is no load on the database and you expect CPU to stabilise around single digit utilisation?

**Comment by thomas0bernard** [comment]
@bluestreak01 Yes you are right. In my case this happens on a fresh container with no load at all, and no tables except the defaults "telemetry" and "telemetry_config".

**Comment by bluestreak01** [comment]
Hi Thomas, thanks for confirming. I don't have access to Ubuntu at this hour but I think I managed to make a difference. On Apple's M1 CPU was hovering at 6% and I got it 0.4-0.9%. Let's wait until tomorrow morning to confirm other platforms.

**Comment by hschultz1960** [comment]
@bluestreak01 Yes, for an idle instance I expect to see zero utilization on system resources.
If you would like me to test dev branches on Ubuntu let me know. 
Please note that I am in the UTC+1 timezone (Copenhagen) so perhaps there is a lag in response.

**Comment by jfcalvo** [comment]
> guys, thank you for reporting these - am I right to assume there is no load on the database and you expect CPU to stabilise around single digit utilisation?

Yes, no load in the database at all. Just running the 6.1.3 Docker image and this is the CPU utilization:

![Captura de pantalla 2022-01-17 a las 10 58 30](https://user-images.githubusercontent.com/446497/149748316-9b663452-34f9-4634-bbd7-33903bc15fc6.png)

I expect zero utilization of the CPU some minutes after running the container.

**Comment by bluestreak01** [comment]
@hschultz1960 Hi Henrik, thank you for the offer, i'd like to take you up on it! Dev branch is here: https://github.com/questdb/questdb/tree/vi_high_cpu if you able to test from that - it would be awesome. Otherwise let me know and i'll cut a docker image.

On my Ubuntu (WSL2) CPU utilisation is <1%

**Comment by hschultz1960** [comment]
@bluestreak01 Done. I can confirm that this branch does not exhibit the anomalous behavior described above. I am also now seeing <1% CPU when idling. Good job on a quick fix, it seems :-)

![image](https://user-images.githubusercontent.com/43204191/149820032-b8736892-1a51-44ae-b840-3c28614f20bf.png)

Unrelated to this, what I **am** seeing is average CPU of ~10% for inserting just 150 records every 10 seconds. Maybe it is due to the heavy debugging going on in the Java console, so I won't distract the present case with that. I'll get back if that issue persists with the final build.

**Comment by bluestreak01** [comment]
thank you Henrik 👍 We should be able to release this in couple of days. Feel free to open another issue to discuss CPU usage under mild load.

**Comment by akamick86** [comment]
I get the same issue with both questdb-7.2-rt-linux-amd64.tar.gz and questdb-7.2-no-jre-bin.tar.gz

To reproduce:
- download and unpack questdb-7.2
- ./questdb.sh start
- connect with psql from and create a new table via 

IDLE CPU is 100-200% in the machine with 8 cores. No queries are executed. I have waited to hours and the CPU usage remains stable.

Expected behavior
Idle CPU usage is <0.1%.

**Comment by MWP** [comment]
Can confirm.
Running in a docker container using the "questdb/questdb" image. Default configuration.
No queries, only a few inserts every 15 seconds.
Average CPU use is far too high, at approx 100% (of one core).
