### ISSUE TITLE
Invalid ALTER syntax

### ISSUE THREAD

**Issue by PiotrDabkowski** [questdb/questdb#270]
**To Reproduce**
Invalid (syntax error), taken from docs:
```ALTER TABLE ratings ADD COLUMN y int```

```
Failed, it looks like there is an error with the query:
1:21  'add' or 'drop' expected
```

The lower case version works as expected (it even has test cases):
```alter table ratings add column y int```

**Comment by jaugsburger** [comment]
fixed  as issue #275
