### ISSUE TITLE
Import by REST Request `/imp` as JSON Result

### ISSUE THREAD

**Issue by QuadStingray** [questdb/questdb#2703]
### Describe the bug

Im you send the `/imp?name=default_tablename&fmt=json` you got sometimes the table style informations back. (In my Tests with Postman in 5 of 10 cases.

### To reproduce

curl --location --request POST 'QUESTDB_REST/imp?name=default_tablename&fmt=json' --form 'data=@"9094422795565268681.csv"'

### Expected Behavior

Always the JSON Result.

### Environment

```markdown
- **QuestDB version**: 6.5.4
- **OS**: QuestDB on Docker (questdb/questdb:6.5.4)
- **Browser**: Postman and other Restclients
```

**Comment by puzpuzpuz** [comment]
Could you provide a reproducer CSV file?

**Comment by QuadStingray** [comment]
[16716932497141043641.csv](https://github.com/questdb/questdb/files/9902617/16716932497141043641.csv)

You can use the fixed CSV File from the Issue #2704 ;-) 
With the fixed file I had 6 wrong formattings in 20 request in relativ short time. (I clicked in postman to send after the last request was fulfilled.

**Comment by puzpuzpuz** [comment]
Thanks for these details! They're helpful.

**Comment by radolin** [comment]
I'm also seeing this, importing csv files with python requests. I can't see a pattern, looks a bit like a race condition.
