### ISSUE TITLE
Upload CSV some rows date (TIMESTAMP) is null

### ISSUE THREAD

**Issue by QuadStingray** [questdb/questdb#2704]
### Describe the bug

I create a table by sql  and upload an CSV-File by the REST-API. After the Upload 50% oft the rows doesn`t have a timestamp in the database table. 

I also tested it with the same file multiple times and in nearly 50% of the cases the value of the timestamp field is randomly null or have a value. So it can not be the format. I also tested it with an UNIX timestamp in the CSV Field an had the same response.

### To reproduce

1. Create Table with SQL `CREATE TABLE IF NOT EXISTS default_request_log(date TIMESTAMP, eventType SYMBOL, controller SYMBOL, controllerMethod SYMBOL,httpVerb SYMBOL,authIdentity SYMBOL,authId SYMBOL,comment SYMBOL,methodName SYMBOL,version SYMBOL,containerName String,localhostName String,remoteAddress String,uri String,requestId String,requestBody String,duration LONG,responseCode INT) timestamp(date) PARTITION BY DAY;`
2. Import CSV by REST API `curl --location --request POST 'QUESTDB_URL/imp?name=default_request_log&fmt=json' --form 'data=@"16716932497141043641.csv"'`

### Expected Behavior

Every Line should have a timestamp ;-)

### Environment

```markdown
- **QuestDB version**: 6.5.4
- **OS**: QuestDB on Docker (questdb/questdb:6.5.4)
- **Browser**: Postman and other Restclients
```

### Additional context

Extended Question: Is it possible the add a default value for a column? Like "now()" if the field could not parsed?

**Comment by QuadStingray** [comment]
[16716932497141043641.csv](https://github.com/questdb/questdb/files/9899517/16716932497141043641.csv)

**Comment by puzpuzpuz** [comment]
@QuadStingray your CSV file has problematic first row:
```csv
my-application,NOT_FOUND,NOT_FOUND,MY COMMENT,fileNotFoundException,2022-10-31T08:02:32.663Z
```

The timestamp column is 6th value here while in all subsequent rows it's 8th value. If I remove the first row, the import seems to work fine.

One more thing to notice is that your CREATE TABLE DDL statement misses the `applicationName` column.

**Comment by QuadStingray** [comment]
@puzpuzpuz Thanks I fixed my CSV Generation. Sometimes it is better to look on a file with new eyes. I debuged 2h an didn`t saw the missing field value!
