### ISSUE TITLE
Getting syntax error on detach partition attemt.

### ISSUE THREAD

**Issue by siberianhunger** [questdb/questdb#2718]
### Describe the bug

Getting following error on detach partition query attemt via python3.8 psycopg2 execution:
query - `ALTER TABLE 'test_markets' DETACH PARTITION WHERE timestamp < '2022-10-31';`
error - `'add', 'drop', 'attach', 'set' or 'rename' expected`
If I try to run this query in questdb browser interface it highlits DETACH instrustion
![image](https://user-images.githubusercontent.com/43884384/199704058-0eaf7d28-bbc2-4fcc-9200-dd0aab12c424.png)

table partitioned by day

### Expected Behavior

it works

### Environment

```markdown
- **QuestDB version**: 6.5
- **OS**: Ubuntu 20.04.4 LTS
- **Browser**: Google Chrome Version 106.0.5249.119 (Official Build) (64-bit)
```

**Comment by ideoma** [comment]
Detach partition functionality added in 6.5.1

https://github.com/questdb/questdb/releases/tag/6.5.1
