### ISSUE TITLE
Flaky testMetaDataSizeToHitExactly16K test fails with FD leak on Windows

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#2741]
### Describe the bug

`testMetaDataSizeToHitExactly16K` WAL run on Windows with File Descriptor leak. FD is ILP connection context socket file descriptor.

See debug log attached
[scratch_41.txt](https://github.com/questdb/questdb/files/9953039/scratch_41.txt)

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
Fixed in https://github.com/questdb/questdb/pull/2457/commits/2954d742b0a4bd640f4515dc102026f08007f797

not just windows
