### ISSUE TITLE
archive partition

### ISSUE THREAD

**Issue by viper1** [questdb/questdb#2816]
### Is your feature request related to a problem?

The new symlink functionality for detached partitions (#2650) is fantastic, thanks for the great work!

An addition to qdb could completely automate a number of archive/"offload to slower storage" use cases.

### Describe the solution you'd like.

1. "ARCHIVE PARTITION" keyword
2. New config option cairo.archivedb=/db-archive/

Two possible implementations for this call:
1. Qdb internally runs an automated detach/move/symlink/attach sequence to the cairo.archivedb location.
2. Internally create the partition in the cairo.archivedb folder perhaps via CREATEAS, insert into the new partition then drop the partition from the original table. This will be slower, but not require any filesystem access for the mv;ln -s part

ARCHIVE TABLE could do the same, but for a whole table instead of just a partition. The most recent partition can then be frozen if it is not possible to have it be writable at the new location.

### Describe alternatives you've considered.

#2650 works great, but requires a manual step on the filesystem side (mv the partition, then create the symlink) that cannot be handled via a simple qdb sql or http request. 

If the client is not running on the same machine as the qdb instance, it also requires client calls for the detach then switching to the qdb machine for the mv;ln -s, then back to the client machine for the attach. Doable but error-prone and quite manual.

**Comment by marregui** [comment]
hola @viper1 

Thank you very much for the excellent feedback. 

The feature that you describe, more or les verbatim, along with partition table visualization, and automations, will be part of QuestDB Enterprise, and will be available from mid Q1 2023.

We do not have plans at the moment on porting this/these feature/s to QuestDB OpenSource, but we would welcome contributions, and ovbiously we would help to get them into master (as implemented by the community).
