### ISSUE TITLE
GSSAPI authnetication is closed abruptly

### ISSUE THREAD

**Issue by vjuranek** [questdb/questdb#2820]
### Describe the bug

When user has a kerberos ticket and tries to connect to the questdb, most of the tools tries GSSAPI authentication first and if not supported, continues with another type authentication (if there is any). QuestDB doesn't refuse GSSAPI gracefully, which leads to terminating the client program, with strange error like this:
```
$ psql postgresql://admin:quest@localhost:8812/qdb -c "CREATE TABLE IF NOT EXISTS t1 (name STRING, value INT);"                                                                     :main
psql: error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

### To reproduce

1. `kinit` (obtain a kerberos ticket)
2. `docker run -p 9000:9000 -p 9009:9009 -p 8812:8812 -p 9003:9003 -v "$(pwd):/var/lib/questdb" questdb/questdb:6.6.1`
3. `psql postgresql://admin:quest@localhost:8812/qdb -c "CREATE TABLE IF NOT EXISTS t1 (name STRING, value INT);"`

### Expected Behavior

QuestDB should refuse GSSAPI authentication gracefully and eventually continue with another type of authnetication supported by the client.

**Comment by jerrinot** [comment]
fixed by #2821
