### ISSUE TITLE
Slow inserts

### ISSUE THREAD

**Issue by Roh-codeur** [questdb/questdb#2831]
### Describe the bug

Hi, I absolutely love this product, QuestDB team has done an amazing job! I do face an issue

I have a table which has 3 Symbol columns(Ticker, Exchange, etc), a Date/Timestamp column and OHLCV columns. the Symbol columns have indices on them as well. When I try to insert rows in this table, the performance is quite bad, I am afraid. it takes more than an hour to insert 1 million rows. (I commit about 100 tickers at a time, could be between 100k - 200k rows). 

1. the bad performance could be because of the Indices - can you confirm? if so, is there a way to disable indices?
2. I tried without indices on Symbol columns, the query performance with indices is far better - is this expected?
3. I note that the new version of QuestDB is better at handling commits. I have some code to close connection using close(true). should I batch the results myself or let QuestDB handle it? 
4. I havent tried disabling indices and reinserting. looks like the only I can do that is by dropping indices and then Reindex - is there another way

I use the python lib to insert data in the database. even with the above, I cant match the million rows per second performance. I must admit my knowledge of the lib is quiet nascent, a piece of documentation on optimizing inserts would help users like me a lot. 

thanks again
Roh

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by pswu11** [comment]
Hi @Roh-codeur thanks a lot for raising the issue. Could you provide more context? e.g. which QuestDB version you are using, and perhaps your deployment setup.

**Comment by Roh-codeur** [comment]
QuestDB version: 6.6.1. I use the official client, latest version. I am on a Mac with SSD drive

**Comment by Roh-codeur** [comment]
@puzpuzpuz is this something you can help with please? 

Thanks

**Comment by puzpuzpuz** [comment]
> * the bad performance could be because of the Indices - can you confirm? if so, is there a way to disable indices?

Indices slow things down due to larger volume of disk writes, but the impact should be dramatic. Still, it's a good idea to start with no indices and add them later, if necessary.

> * I tried without indices on Symbol columns, the query performance with indices is far better - is this expected?

That depends on your table schema, data volume and the particular query. Hard to suggest anything without knowing these aspects.

> * I note that the new version of QuestDB is better at handling commits. I have some code to close connection using close(true). should I batch the results myself or let QuestDB handle it?

You should write to ILP connection in batches. The ideal size is in the order of 1K. If that's not possible, smaller batches are fine as they still allow you to achieve decent performance.

> * I havent tried disabling indices and reinserting. looks like the only I can do that is by dropping indices and then Reindex - is there another way

Dropping indices and adding them later is the way to go.

Are you trying to do single time import or you're testing the expected load for your application? Could you share the table schema and tell us how many out-of-order (O3) rows you're writing into the database. In many cases, O3 rows are the main source of problems. Ways to deal with them are using a partition strategy of smaller granularity (e.g. DAY -> HOUR, MONTH -> DAY) and fine-tuning commit related settings, so that commits happen less frequently and, thus, write more rows in one go.

**Comment by Roh-codeur** [comment]
@puzpuzpuz: thanks for your suggestions. I load OHLCV data into a database. I have to load >6M rows, I try to batch them while inserting. I also load ~10k rows everyday. 

SQL schema:
```SQL
CREATE TABLE ohlcv(
        Ticker SYMBOL CAPACITY 10000,
        Exchange SYMBOL CAPACITY 50,
        DataSource SYMBOL CAPACITY 10,
        Date TIMESTAMP,
        Open double,
        High double,
        Low double,
        Close double,
        AdjustedClose double,
        Volume double,
        timestamp TIMESTAMP)
  TIMESTAMP(date) 
  PARTITION BY MONTH;
```

1. Removed indices. 
2. changed the batch size to 1000. flush when have 1000 rows. I played around with batchsize, going up to 10000. it looks like it doesn't have much effect in total time taken. it takes **15 seconds to insert 320,732 rows** with a batch size of 1000!!!
``` python
        if i == batchSize
            i = 1
            @info "flushing"
            sender.flush()

```
3. I tried changing the "PARTITION BY" as well. moving it to HOUR _increased the time_ and modifying it to YEAR made it slightly faster. 

code to insert. Please note I call Python code from Julia. it looks something like the below

``` julia
    for row in eachrow(df)
        colsDict = convertRowToDict(row, cols)
        colsDict["timestamp"] = questdb.TimestampMicros.from_datetime(
                datetime.datetime(year(nowTime), month(nowTime), day(nowTime), hour(nowTime), minute(nowTime), second(nowTime), second(nowTime), tzinfo=datetime.timezone.utc)).value    
        sender.row(tableName, 
                            symbols = symbols,
                            columns=colsDict
        )
        if i == batchSize
            i = 1
            @info "flushing"
            sender.flush()
        else
            i = i + 1
        end
    end
    sender.close(true)
```

hope this helps. Please do let me know if I am missing something. thanks a lot for your help in sorting this out.

**Comment by puzpuzpuz** [comment]
What kind of hardware do you use to run QuestDB?

> 3\. I tried changing the "PARTITION BY" as well. moving it to HOUR _increased the time_ and modifying it to YEAR made it slightly faster.

This is weird. Could you share around 10 minutes of server logs collected when ingesting the data?

> 4\. I also tried sorting the dataframe by Date before inserting. I thought it would help with O3 - what do you think?

No need to do that. The server does it anyway.

**Comment by Roh-codeur** [comment]
> What kind of hardware do you use to run QuestDB?

Macbook pro Apple M1 Max with SSD. 

> > 3. I tried changing the "PARTITION BY" as well. moving it to HOUR _increased the time_ and modifying it to YEAR made it slightly faster.
> 
> This is weird. Could you share around 10 minutes of server logs collected when ingesting the data?

Sure, do you have an email where I can send it pls? 

> 
> > 4. I also tried sorting the dataframe by Date before inserting. I thought it would help with O3 - what do you think?
> 
> No need to do that. The server does it anyway.
yeah, sorting beforehand did not have any impact. I thought this would help with out of order inserts

**Comment by Roh-codeur** [comment]
Update:

so, it turns out that the method was adding an overhead. the culprit was the below line. I was calling it in a loop, for each row, and it slowed it down. 

``` python
    tsMicros = questdb.TimestampMicros.from_datetime(
                            datetime.datetime(year(nowTime), month(nowTime), day(nowTime), hour(nowTime), minute(nowTime), second(nowTime), second(nowTime), tzinfo=datetime.timezone.utc)
                ).value
```

I have now changed the method and its a lot more performant. I checked and it appears that actual time taken by below lines is 7 seconds.

```python
sender.row(symbols = columns=colsDict)
```
[stdout-2023-01-18T20-52-50.txt](https://github.com/questdb/questdb/files/10451106/stdout-2023-01-18T20-52-50.txt)

**Comment by puzpuzpuz** [comment]
Are you happy with the current performance level? If not, please join our [Slack community](https://slack.questdb.io/) and write me there.

**Comment by Roh-codeur** [comment]
Sure, I will request an invite to slack channel

**Comment by puzpuzpuz** [comment]
@Roh-codeur could you confirm that the ingestion is fast enough now so that we can close the issue?

**Comment by Roh-codeur** [comment]
@puzpuzpuz : sorry about the delay, I have a pinched nerve, am resting nowadays. the ingestion speeds are a lot better than they were. I will keep playing around with this and report back with results. 

ta!

**Comment by puzpuzpuz** [comment]
@Roh-codeur thanks for the feedback!
