### ISSUE TITLE
StackOverflowError in PGWireServer

### ISSUE THREAD

**Issue by tpreclik** [questdb/questdb#2833]
### Describe the bug

In our data retention service we hit #1944. After upgrading to 6.3.1 this error is gone. However, we now run into a `java.lang.StackOverflowError` in `i.q.c.p.PGWireServer` when executing an `ALTER TABLE table_a DROP PARTITION WHERE timestamp < dateadd('h', 36, now());` query. The following function sequence is called recursively:

```
io.questdb.mp.FanOut.root (FanOut.java:128)
io.questdb.mp.AbstractSSequence.root (AbstractSSequence.java:71)
io.questdb.mp.MPSequence.root (MPSequence.java:31)
```

### To reproduce

Same steps as in #1944

### Expected Behavior

ALTER TABLE should suceed

### Environment

```markdown
- **QuestDB version**: docker.io/questdb/questdb:6.3.1
```

**Comment by jerrinot** [comment]
hello @tpreclik, did you try a version newer than 6.3.1? ideally the latest and greatest. which currently is 6.6.1.

**Comment by tpreclik** [comment]
I can no longer reproduce this with 6.6.1.
