### ISSUE TITLE
User Management along with Auth

### ISSUE THREAD

**Issue by ranjithkumarmv** [questdb/questdb#2837]
### Describe the solution you'd like.

similar to what influxdb has - https://docs.influxdata.com/influxdb/v2.5/users/

**Comment by pswu11** [comment]
Hi @ranjithkumarmv thanks a lot for the feature request! 🙏🏼 Currently, we plan to include this feature in QuestDB Cloud.  Feel free to join our slack community in case you have more feedback/thoughts on this: https://slack.questdb.io/
