### ISSUE TITLE
trigonometric functions for real-time analytics in Grafana

### ISSUE THREAD

**Issue by BouarfaMahi** [questdb/questdb#2842]
### Is your feature request related to a problem?

there is  no simple way that can approximate cos(x) whatever the value of x.  

### Describe the solution you'd like.

Trigonometric function(x), x in radians.

**cos(x)**            cosine
**sin(x)**             sine

acos(x)           inverse cosine
asin(x)            inverse sine
atan(x)           inverse tangent
atan2(y, x)     inverse tangent of y/x
cot(x)            cotangent
tan(x)            tangent

### Describe alternatives you've considered.

following Maclaurin series gives some cosine values larger that one. I don't know where the error comes from.

```
SELECT 
timestamp,
price,
amount,
1 - power(amount,2)/2*1 + power(amount,4)/(4*3*2*1) - power(amount,6)/(6*5*4*3*2*1) +  power(amount,8)/(8*7*6*5*4*3*2*1) 
-  power(amount,10)/(10*9*8*7*6*5*4*3*2*1) AS cos_amount
FROM trades
WHERE symbol = 'ETH-USD' AND timestamp > dateadd('d', -1, now())
SAMPLE BY 1T ALIGN TO CALENDAR; 
```

**Comment by nik132-eng** [comment]
Don't know what to do with this issue but if you assign me I will search and learn how to solve. Can you please assign me?

**Comment by sreenath-tm** [comment]
@nik132-eng please feel free to use the community slack channel to get a head start on how to solve the issue.

**Comment by marregui** [comment]
Hi, I have accidentally addressed this issue when I also had the requirement of trigonometical functions. Here is my approach: https://github.com/questdb/questdb/pull/2890
