### ISSUE TITLE
Simple alerts framework on streaming data

### ISSUE THREAD

**Issue by Shudh** [questdb/questdb#2853]
### Is your feature request related to a problem?

Currently I am streaming financial market data in questdb. It would be nice to have a simple alerts framework api that will track if the market is above/is below / is equal to last traded price. I am aware that this can be achieved by grafana or even having the quest db api to poll on the streaming table but for my needs a separate grafana is overkill and the latency of repeated polling is undesirable. Quest DB would be self sufficient if we have some kind of event generated based on which I can call the brokers endpoints directly without using any other systems..Kindly consider this or if there is some other way to have this functionality without polling or grafana then please guide me with an example.

### Describe the solution you'd like.

Quest DB simple alert api monitoring streaming values and generating events..

### Describe alternatives you've considered.

Used Grafana and also used polling using quest db api

**Comment by marregui** [comment]
Hi @Shudh 

Thank you for the feature suggestion. Possibly in the future we might add something like this, however now we are focusing on cold storage, and clustering, so it is not a priority. Would you be able to contribute this feature?

An alternative, would be for you to explore the possibility of creating a java app that instantiates the server like `testServerMainPgWireConcurrentlyWithLineTcpSender` does, and then you could embed logic to run a periodic query in the server's threads, local to the data, and you could try to maintain state and decide whether to push an event on a redpanda queue. It might not be as hard as it sounds, but it requires you own this.

Best
