### ISSUE TITLE
Java ILP does not treat nanosecond timestamps as expected

### ISSUE THREAD

**Issue by wolfig** [questdb/questdb#2854]
### Describe the bug

I am not sure if this a bug or wrong usage. I am working on an Apache Camel producer for QuestDB. I persist data via the Java ILP using the following code:

```
       long timestamp = dataObject.getTimestamp();

        // based on input precision scale to nanoseconds
        switch (dataObject.getTimestampPrecision()) {
        case microseconds:
            timestamp = timestamp * 1000;
            break;
        case milliseconds:
            timestamp = timestamp * 1000000;
            break;
        case seconds:
            timestamp = timestamp * 1000000000;
            break;
        default:
            break;
        }

        try {

            for (Field fieldObject : dataObject.getData()) {

                if (fieldObject.getType().equals(Boolean.class)) {
                    sender.boolColumn(fieldObject.getName(), (Boolean) fieldObject.getValue());
                } else if (fieldObject.getType().equals(Double.class)) {
                    sender.doubleColumn(fieldObject.getName(), (Double) fieldObject.getValue());
                } else if (fieldObject.getType().equals(Integer.class)) {
                    sender.longColumn(fieldObject.getName(), (Integer) fieldObject.getValue());
                } else if (fieldObject.getType().equals(Long.class)) {
                    sender.longColumn(fieldObject.getName(), (Long) fieldObject.getValue());
                } else if (fieldObject.getType().equals(String.class)) {
                    sender.stringColumn(fieldObject.getName(), (String) fieldObject.getValue());
                } else {
                    throw new IllegalArgumentException("Unknown field type: " + fieldObject.getClass().getName());
                }
            }

            sender.timestampColumn("time", (timestamp));
            sender.at(timestamp);
```
Hence, the variable `timestamp` is always a 19-digit nanosecond epoch timestamp. 

The statement `sender.timestampColumn("time", (timestamp));` is reflected in the database, I never managed to assign a designated timestamp using statement `sender.at(timestamp);`. What is surprising is that the data in the `timestampColumn` seems to contain timestamps in microseconds rather than nanoseconds. If I check the data in the Web-CLI, data injected as 16-digit microsecond TS is represented as proper date time, data injected with a 19-digit epoch timestamp leads to dates like 54906-08-05...

I checked as well what happens if I inject a microsecond timestamp to `server.at(timestamp)` and to timestampColumn. In this case the timestampColumn looks OK, a designated timestamp is not reflected in the database.

NOTE: I explicitly set `line.tcp.timestamp=n` in the `server.conf`

### To reproduce

Implement a simple sender scenario using Java ILP.

### Expected Behavior

I expect that a 19 digit nanosecond timestamp leads to the right date time and if I use the `at(...)` statement, a designated timestamp is created.

### Environment

```markdown
- **QuestDB version**: 6.6.1
- **OS**: Rocky Linux
- **Browser**: Firefox
- **JAVA Version**: 11
```

**Comment by wolfig** [comment]
Hi Jerrinot, thanks for the hints. I will try them tomorrow.
Concerning the Camel Component: in principle I could make that public, but I think I need support from the QuestDB-Team. I was able to build an Camel adapter, but I am a bit reluctant wondering if I will be able to support this for the world-wide community. And it needs a look/Code review from the QuestDB team to ensure that the more exotic features and use cases are covered by my code.

**Comment by jerrinot** [comment]
@jerrinot I'd be very happy to review it and provide help where I can! 

As for long-term maintenance - I think it would be best to contribute to the Apache Camel project. They maintain a massive connector library and QuestDB would be a nice addition.

**Comment by wolfig** [comment]
OK, let's go like this: I will finish implementing the connector and when I think the code is reviewable, I'll contact you. Might be next year...

**Comment by wolfig** [comment]
May problem has been solved. I needed to drop an re-create the table and I introduced a more strict time conversion. Now the data is visible as expected. Thanks for you help.

**Comment by jerrinot** [comment]
@wolfig sounds good, I am glad it's working for you now!
Good luck with the connector and if you need any help just pop in at [QuestDB slack](https://slack.questdb.io/)
