### ISSUE TITLE
ALTER TABLE DROP PARTITION should automatically truncate the given timestamp to the partition timestamp

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#2879]
### Is your feature request related to a problem?

Reported by @javier 

Currently in the alter table query one needs the timestamp to be at the same resolution level than your partitioning.

For example, if we have a table with daily partitioning but microsecond resolution in the timestamps. Now, if we try to drop a partition `where ts = '2022-10-28T19:15:48.741819Z'`, we're getting an error saying `no partitions matched WHERE clause`. To fix that, we have to use `timestamp_floor()` function: `where timestamp = timestamp_floor('d', '2022-10-28T19:15:48.741819Z');`.

### Describe the solution you'd like.

The database should calculate the partition the timestamp filtered timestamp belongs to, so that the `timestamp_floor()` function isn't needed.

**Comment by ideoma** [comment]
You can write

```
where ts = '2022-10-28'
```

and no `floor` needed

**Comment by puzpuzpuz** [comment]
> You can write
> 
> ```
> where ts = '2022-10-28'
> ```
> 
> and no `floor` needed

That doesn't match the described use case. Say, you want to drop the oldest partition (ref #2878). To do that, you run `select min(ts) from x;` and then execute `alter table x drop partition where ts = ?;`. This won't work unless you truncate the timestamp additionally.

**Comment by marregui** [comment]
`list`, instead of `where`, would be easier to implement:

```sql
alter table x drop partition list '?';
```

and then have the compiler truncate according to partition-by schema. Would this be a happy compromise?

**Comment by marregui** [comment]
being addressed in https://github.com/questdb/questdb/pull/3002
