### ISSUE TITLE
Metadata function table_partitions('tableName') returns the partitions of a table

### ISSUE THREAD

**Issue by marregui** [questdb/questdb#2885]
### Is your feature request related to a problem?

This is a usability enhancement, to avoid having to enquire the file system and metadata files to know the status of the database.

### Describe the solution you'd like.

Add the new function so that this SQL query is possible:

```sql
SELECT * FROM table_partitions('my_table');
```

It should return a table of the current view of the partitions, with metadata:

- **index**: index of the partition 0..n-1, where n is the number of attached partitions, -1 otherwise
- **partitionBy**: YEAR, MONTH, DAY, HOUR
- **timestamp**: timestamp of the partition
- **minTimestamp**: min timestamp in the partition
- **maxTimestamp**: max timestamp in the partition
- **readOnly**: can it be written to, or is it read only
- **active**: is it the partition we are currently appending to
- **attached**: is it attached, or not (table folder, and additional detached path)
- **detached**: is it detached
- **attachable**: is it detacched and attachable
- **location**: path to the parent folder of the partition in disk
- **txn**: current transaction version, available from _txn, if attached
- **cv**: current column version, available from _txn, if attached
- **numRows**: size
- **fixedRowCount**: size if not active
- **transientRowCount**: size if active

### Describe alternatives you've considered.

guess work

**Comment by puzpuzpuz** [comment]
Seems to be similar to #2877

**Comment by marregui** [comment]
https://github.com/questdb/questdb/issues/2877
