### ISSUE TITLE
Client gets disconnected when rounding a value in SQL (used `pcli`)

### ISSUE THREAD

**Issue by vbmithr** [questdb/questdb#2892]
### Describe the bug

```
2022-12-29T17:46:01.841044Z I i.q.g.SqlCompiler batch [text=select trade.ts, trade.sym, first(px) o, max(px) h, min(px) l, last(px) c, log(last(px)) - log(first(px)) logr, round(sum(abs(qty)),2) v, avg(leverage) avglvg, log(last(leverage)) - log(first(leverage)) loglvgchg from trade asof join byb_ltinfo on (sym) where trade.sym = 'BTC3LUSDT' sample by 5m ;]
2022-12-29T17:46:01.841679Z C i.q.c.p.PGWireServer internal error [ex=
java.lang.AssertionError
        at io.questdb.std.ObjList.getQuick(ObjList.java:173)
        at io.questdb.griffin.SqlOptimiser.rewriteSelectClause0(SqlOptimiser.java:3158)
        at io.questdb.griffin.SqlOptimiser.rewriteSelectClause(SqlOptimiser.java:2975)
        at io.questdb.griffin.SqlOptimiser.optimise(SqlOptimiser.java:3546)
        at io.questdb.griffin.SqlCompiler.compileExecutionModel(SqlCompiler.java:1112)
        at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1193)
        at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1146)
        at io.questdb.griffin.SqlCompiler.compileBatch(SqlCompiler.java:314)
        at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:2237)
        at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1557)
        at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:385)
        at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
        at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:83)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:169)
        at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:110)
        at io.questdb.mp.Worker.run(Worker.java:118)
]
```

### Environment

```markdown
- **QuestDB version**: 6.6.1
- **OS**: Linux
- **Browser**:
```

**Comment by vbmithr** [comment]
The bug happens when using the `round` function on a computed column.

**Comment by vbmithr** [comment]
Also in this query
```
WITH syms AS (SELECT 'ETHUSDT')
SELECT tr.ts, tr.sym, AVG(px) px, SUM(ABS(qty)) qty, COUNT() cnt, round(AVG(px)*SUM(ABS(qty)),0) usdqty,
       FIRST(A) op, LAST(a) cl, round(log(LAST(A))-log(FIRST(A)), 4) pctchg
  FROM (SELECT * FROM trade WHERE sym IN (SELECT * FROM syms)) AS tr
         asof JOIN (SELECT * FROM quote WHERE sym IN (SELECT * FROM syms)) AS qu
                     sample BY 30s
 ORDER BY ABS(qty) DESC
 LIMIT 20 ;
```

If for `pctchg`, `LAST(A)` is written `last(a)`, an exception is raised too.

**Comment by marregui** [comment]
hola @vbmithr happy almost new year.

I have created a reproducer and tested it in both 6.6.1 and HEAD (from master). You are correct, this is an issue in 6.6.1 (both reports), and both have been fixed and will be released in January. 


```sql
create table trade (
    sym symbol index capacity 128,
    px long,
    qty int,
    leverage float,
    ts timestamp
) timestamp(ts) partition by day;
insert into trade values('A', 200000, 3, 0.9, '2022-12-31T12:00:00.000000Z');
insert into trade values('B', 198000, 4, 0.97, '2022-12-31T12:00:10.000000Z');
insert into trade values('C', 199000, 4, 0.85, '2022-12-31T12:00:11.000000Z');
insert into trade values('A', 200000, 3, 0.9, '2023-01-01T12:00:00.000000Z');
insert into trade values('B', 198000, 4, 0.97, '2023-01-01T12:00:10.000000Z');
insert into trade values('C', 199000, 4, 0.85, '2023-01-01T12:00:11.000000Z');

create table byb_ltinfo (
    sym symbol index capacity 128,
    price long,
    quantity int,
    ts timestamp
) timestamp(ts) partition by day;
insert into byb_ltinfo values('A', 200300, 2, '2022-12-31T12:00:01.000000Z');
insert into byb_ltinfo values('B', 198200, 1, '2022-12-31T12:00:11.000000Z');
insert into byb_ltinfo values('C', 199000, 1, '2022-12-31T12:00:12.000000Z');
insert into byb_ltinfo values('A', 200300, 2, '2023-01-01T12:00:01.000000Z');
insert into byb_ltinfo values('B', 198200, 1, '2023-01-01T12:00:11.000000Z');
insert into byb_ltinfo values('C', 199000, 1, '2023-01-01T12:00:12.000000Z');

select 
    trade.ts, 
    trade.sym, 
    first(px) o, 
    max(px) h, 
    min(px) l, 
    LAST(px) c, 
    log(LAST(px)) - log(first(px)) logr, 
    round(sum(abs(qty)),2) v, 
    avg(leverage) avglvg, 
    log(LAST(leverage)) - log(first(leverage)) loglvgchg 
from trade asof join byb_ltinfo on (sym) where trade.sym = 'B' sample by 5m;

-- result in master HEAD: (while in 6.6.1 we get a crash)
-- 2022-12-31 12:00:10.0, B, 198000, 198000, 198000, 198000, 0.0   
-- 2023-01-01 12:00:10.0, B, 198000, 198000, 198000, 198000, 0.0
```

**Comment by marregui** [comment]
would you be able to send a more accurate reproducer scenario (as above) so that I can add the specific test to the codebase?

**Comment by vbmithr** [comment]
Thank you. Happy ny too @marregui
More accurate, i.e. you mean with real data, or?

**Comment by marregui** [comment]
The schemas and some data where the query fails, so that I can attempt to reproduce with 6.6.1

**Comment by vbmithr** [comment]
I'm finding it difficult to generate the insert lines from actual data in the DB. Any way to do it easily? I have tried to play with string concatenation, but it's a bit a hell to do string escaping with the `concat()` function…

**Comment by marregui** [comment]
hola we have released!! https://github.com/questdb/questdb/releases/tag/6.7 so the bug is gone. You can update the server :)

**Comment by vbmithr** [comment]
Indeed fixed, thanks.

**Comment by marregui** [comment]
marvellous, thank you for using QuestDB.

Your query looks like a black belt's, from the perspective of a core developer :). What is your use case if I may ask?, what are you working on?, how do you use QuestDB?, is there anything we can do better?

thank you for the feedback :D

**Comment by vbmithr** [comment]
```sql
SELECT trade.ts, trade.sym, first(px) o, max(px) h, min(px) l, last(px) c, log(last(px)) - log(first(px)) logr, round(sum(abs(qty)),2) v, avg(leverage) avglvg, log(last(leverage)) - log(first(leverage)) loglvgchg 
FROM trade asof join byb_ltinfo on (sym) 
WHERE trade.sym = 'BTC3LUSDT' 
SAMPLE BY 5m
```

This query is just some something I wrote in the middle of trying to get what I wanted and is not correct/interested as such.

I have a state table `byb_ltinfo`, that contains data about the state/composition of an "leveraged token" (sort of synthetic asset which aims to provide leverage in say, Bitcoins), and an event table of trades `trade` and I wanted to observe if anything happens to the trade data in the vicinity of a change of state. The leveraged token is "rebalanced" regularly as part of its contract definition so the leverage will change suddently when rebalance events happens.

- `o, h, l, c` is "open high low close", extreme values of prices inside the bucket, aka "candles" or "klines".
- `logr` is log return, which is a good approximation of the return per bucket r = (priceLast - priceFirst) / priceFirst when priceLast is close to priceFirst.
- v is the volume (quantity of money exchanged) during the period bucket, I need to abs because the table has positive and negative values depending if the book impacted by the trade was the bid side or ask side. Rounding was to avoid displaying lots of insignificant digits…
- `avglvg` and `loglvgchg` are resp. the avg leverage and the percentage change, I intended to sort by percentage change of leverage and see if trade values (ohlc + logr) were unusual in this period of time.

I'm developing a service to provide historical data on crypto financial markets, currently focusing on delivering batch data to customers, but I'm also playing with time series DBs for doing OLAP with this data (both as a potential future offering and for me to do some research sometimes).

I use questdb on Archlinux (thanks @sunng87 for the AUR package) and we also used it successfully in the cloud.
Currently I'm playing/evaluating different OLAP products, QuestDB ClickHouse DuckDB GrepTimeDB… I have played with KDB+ and basically was looking for an opensource version of that or something close enough.

The main things I'm looking for is:

- Rich SQL with timeseries/finance oriented stuff (Basically all that KDB+ has out of the box is useful: especially window functions like `lag` or `delta` to compute difference of one row with the previous row: not sure QuestDB has that yet).
- Easy to load existing dataset. I use Parquet for storing historical data. I would like to be able to load my Parquet files inside QuestDB efficiently. So I would be happy with an extension of `COPY` to Parquet files. ClickHouse seems very good at loading any kind of data (though it was not flawless on my use cases last time either).

But basically right now the thing I'd like to do is the Parquet import, I can probably manage to do something with the `COPY` import. DuckDB has amazing support for that (https://duckdb.org/docs/data/parquet)

**Comment by marregui** [comment]
Thank you for the transparency, and the details, I love details.

I have never used kdb+ myself directly. I wrote some java annotations some time in the past to interact with it, when I worked for a large financial institution, but the actual q was indeed for non mortals, and coded with by quants. You must be a quant!, I suppose it takes time, context, opportinity, to getting access to q, and then a whole lot of domain knowledge, as well as data analysis skills, to use it.

I am personally delighted that you have considered QuestDB as a replacement for ^ ^. I wish I knew how narrow the GAP is, so then we could speak about narrowing it further. You mentioned  the delta function. We do not have much support yet for analytical functions, we focus more on bucketing with sample by, still https://questdb.io/docs/reference/function/analytic/, in principle a foundation is there. Can always be extended, I believe the main issue is to know what to work on, what direction to take.

Parquet is in our horizon. It is an essential part of the cold storage infrastructure in our cloud offering. There are at least 3 developers working on it, myself includded. The 15K ft high view of this would be:

- tables are assigned a retention period, on create, or with an alter statement
- any partition whose data is older than the retention gets detatched, parquetified, sent to s3 to become cold, or gets deleted forever
- any partition that contains data out of retention is automatically trimmed
- when a cold partition is required, the reverse flow happens, and the parquet file becomes usable by QuestDB

The details require some research. We want to do the parquet integration using rust and the https://crates.io/crates/parquet crate. We have a maven plugin that allows us to bind rust libraries and expose them to java through jni. At present we are  progressing through the backlog for release 7.0, which does not include cold storage, and then all this comes next, so should be available within the next Q. However it is likely that this functionality will only be available for the cloud platform, or a license might be required.

I will ask around, or will try myself, to see about 

``` 
The limitation of COPY to require an empty table is hard. Would it be possible to load data sequentially, partition per partition? Like I have one CSV per day, and I load them in order? One use case would be to keep a DB of a rolling month of data, and each day, delete a partition and add a new partition.
```

Will report back.

**Comment by vbmithr** [comment]
KDB+ is really not directly comparable to anything else, there is no "gap" so to speak it is a completely different product. In my opinion its strength derives from being a bespoke solution to a very specific problem. When you're trying to solve many problem at once, say, OLAP in general, you must be generic and therefore can't beat a bespoke solution to a specific problem. "Weakness" of KDB+ is that it is proprietary software, very expensive, and therefore does not benefit from the energy of an opensource community… KDB+ was basically a runtime to write things, with just the right primitives to write trading systems, sort of QuestDB/Kafka/RAM database combined, with a steep learning curve (especially the language) and the lack of docs for people using the opensource version (much better nowadays).
I sort of disagree about `q`, it is "just" an incarnation of a type of programming languages (APL) and per se, it's not connected to data science, quant things/analytics things at all. Being good at `q` and at data analysis is completely orthogonal in my point of view.

I said "replacement" but I just don't want/can't pay an expensive license and want to explore alternatives in the opensource ecosystem. Much more heavyweight and stuff (Kafka…) but eventually "does the job".

I'm surprised that all the Opensource OLAP DB have tried don't give a simple solution to use cases like, "I want to compute the difference between one line and its previous line". It's not just QuestDB! Clickhouse is the same here :

```
lag/lead(value, offset) | Not supported. Workarounds: …
```

I guess there is an aspect of "wanting to solve a more generic problem", but in the meantime you end up with a product that does not offer simple solutions to simple problems for a long time and as a user it is very frustrating.

We also use S3/Cold storage, I believe it is an extremely common use case indeed and integration with S3 (if done well) is very interesting. Clickhouse does it also, probably it already works for them.

Another idea is to provide tools to produce QuestDB partitions offline, without even using QuestDB, and then just plug those partitions in. I would definitely use that. Or just a specification/doc of the DB format (might already exist perhaps). I'll have a look.

**Comment by marregui** [comment]
APL is very exotic, in my mind it takes a special kind of person, in a good way:

```apl
crt←{m|⍵+.×⍺(⊣×⊢|∘⊃{0=⍵:1 0 ⋄ (⍵∇⍵|⍺)+.×0 1,⍪1,-⌊⍺÷⍵})¨⍨⍺÷⍨m←×/⍺} ⍝ From APL Cart
```

Whatever the above code does, it does it in a hardware friendly SIMD way. What we are trying to do in QuestDB is a SQL based DSL for timeseries type data, stored in a SIMD friendly way, very aware of the underlaying hardware, and capitalising on the os's paging. This is one of the components of performance. 

At present we ingest at alarmingly high rates, like a super massive black hole. This is streaming in reverse. To enable streaming out we need to tacke materialised views first which is in the pipeline.

```
```
