### ISSUE TITLE
UPDATE with JOIN errors

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#2900]
### Describe the bug

The update example from doc 
https://questdb.io/docs/reference/sql/update/

```SQL
UPDATE spreads s
SET s.spread = p.ask - p.bid
FROM prices p
JOIN instruments i ON p.symbol = i.symbol
WHERE s.timestamp = p.timestamp AND i.type = 'BOND';
```

fails with error `JOIN is not supported on UPDATE statement`

### Expected Behavior

Update documentation to say that UPDATE with JOIN can be re-written as `WITH ... UPDATE ... FROM` (next example in docs) or allow the JION in `SqlParser.parseDmlUpdate()`.

### Environment

```markdown
- **QuestDB version**:6.6.1
```

**Comment by puzpuzpuz** [comment]
cc @amyshwang as this issue suggests a doc change

**Comment by goodroot** [comment]
Updated https://questdb.io/docs/reference/sql/update/
