### ISSUE TITLE
Get TABLE and COLUMN list with SQL

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#293]
**Is your feature request related to a problem? Please describe.**
Working with multiple tables with multiple columns is difficult as there is no easy way to access the table list and description. This makes data exploration difficult for unknown tables and forces users to remember column names or to alternate between their query and `select * from tablename limit 1` to get the column list. In addition, the latter gives out the column names but not the type.

**Describe the solution you'd like**
Expose SQL to obtain a list of tables, for example `SHOW TABLES`, and another to obtain a list of columns and types for a given table, for example `SHOW COLUMNS FROM tableName`

**Describe alternatives you've considered**
`select * from pg_catalog.pg_class()`, however this only exposes list of tables

**Comment by igor-suhorukov** [comment]
You should at least support query emitted by following methods of PG JDBC driver:
```
org.postgresql.jdbc.PgDatabaseMetaData#getTables
org.postgresql.jdbc.PgDatabaseMetaData#getColumns
org.postgresql.jdbc.PgDatabaseMetaData#getSchemas // may be you should return 'public' schema as QuestDB doesn't support schema
org.postgresql.jdbc.PgDatabaseMetaData#getCatalogs // and default catalog/database name
```

Please also implement [pg_catalog.pg_description](https://www.postgresql.org/docs/current/catalog-pg-description.html) as it used under the hood in PgDatabaseMetaData queries. It is create foundation for https://github.com/questdb/questdb/issues/194


Please implement this feature in the same way as H2Console works


This code should help to check metadata support:
```
//mvn dependency: com.h2database:h2:1.4.200
DbContents dbContents = new DbContents();
dbContents.readContents(jdbcConnectionUrl, connection);
```

psql also should work with implemented metadata.

Also nice to have support of following clients:
https://en.wikipedia.org/wiki/SQuirreL_SQL_Client
https://www.jetbrains.com/help/idea/relational-databases.html#

Also please mind that exist more standard way to support DB metadata https://en.wikipedia.org/wiki/Information_schema (but it is optional feature)

See also: https://www.postgresql.org/docs/current/catalogs.html

**Comment by patrickSpaceSurfer** [comment]
```SHOW TABLES``` and ```SHOW COLUMNS FROM tableName``` implemented along with respective functions
