### ISSUE TITLE
List of tables and columns in UI

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#294]
**Is your feature request related to a problem? Please describe.**
Exploring new datasets with the web console is difficult due to the absence of a list of available tables and columns.

**Describe the solution you'd like**
Once #293 is implemented, expose a menu that shows the list of available tables in the database, and the list of available columns and type in each table. Ideally this is collapsable at table level, and columns/table names are added to the SQL being edited by click in the list.

**Example**
Table: Trades
 -> TS (timestamp)
 -> Instrument (symbol)
 -> Quantity (int)
 -> Price (double)

Table: Traders
 -> Name (string)
 -> Age (int)
 -> Sex (symbol)

**Describe alternatives you've considered**
`pg_catalog.pg_class()` to get table list and `select * from table limit 1` to get column list.

**Comment by igor-suhorukov** [comment]
Please also support popup (on hover event) description of tables/columns in UI. It will help data science/data analytics specialists use this tool with large database with plenty of tables / hundred of columns.

Nice to have "markdown" comment formatting in table/column description visualization. We extensively use schemaspy with [pegdown](https://github.com/schemaspy/schemaspy/issues/642) which was an implementation daringfireball markdown dialect.

**Comment by mpsq** [comment]
Implemented in #314

**Comment by mpsq** [comment]
@igor-suhorukov 

This is what has been done:
![2020-05-23-160243_grim](https://user-images.githubusercontent.com/5734722/82733867-dcef6180-9d0e-11ea-888b-eaa3014e21e7.png)

Don't hesitate to play with #314 and let us know if this works for you ;)

**Comment by igor-suhorukov** [comment]
@mpsq  new web console looks amazing, thanks

I have only one feedback about issue: theme inconsistency, light theme on "upload" tab
![Screenshot from 2020-05-23 23-40-31](https://user-images.githubusercontent.com/10332206/82740171-f912f300-9d4e-11ea-9350-bab7c6ff93c2.png)

**Comment by mpsq** [comment]
That is true, the import tab is still using the old styles. Refreshing the UI is a non trivial piece of work. Phase I was the console but this section will be migrated in the really near future ;). That's the phase II!

**Comment by igor-suhorukov** [comment]
I am understood, @mpsq thank you for your efforts
