### ISSUE TITLE
Copy schema does not work in UI from Safari

### ISSUE THREAD

**Issue by newskooler** [questdb/questdb#2955]
### Describe the bug

Copy schema does not work in UI from Safari

### To reproduce

Open a Sfari browser and try to Copy Schema of an existing table and then paste it.
It does not work for me.

### Expected Behavior

It should copy it :)

### Environment

```markdown
- **QuestDB version**: 6.5.2
- **OS**: MacOS Monterey 12.0.1
- **Browser**: Safari
```

**Comment by insmac** [comment]
As a test, could you please try the same command in https://demo.questdb.io ? This does work fine for me on Safari. We have updated the Safari issue some time ago - could you upgrade QuestDB to a newer version?

**Comment by newskooler** [comment]
Yes this does work for me. So it's just my version of QDB. Thanks!
