### ISSUE TITLE
Inconsistent timestamp format

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#296]
This is something that came up on slack:

/imp end point requires timestamp format in micros and fails on millis format with:

```
java.lang.ClassCastException: io.questdb.cutlass.text.types.BadTimestampAdapter cannot be cast to io.questdb.cutlass.text.types.TimestampAdapter
```

SQL requires timestamp in millis and fails on micros

Both SQL and import should support gracefully both milli and micro formats. e.g

```
2019-10-18T00:00:00.000Z vs 2019-10-17T00:00:00.000000Z
```

**Comment by jaugsburger** [comment]
The second part of this issue has already been fixed and SQL now supports querying with micros, at least in SELECT statements. I will check  INSERT and will fix import
