### ISSUE TITLE
DISTINCT keyword UI highlight

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#298]
**Describe the solution you'd like**
`DISTINCT` keyword should be highlighted in the web console

<img width="476" alt="Screenshot 2020-05-18 at 12 17 02" src="https://user-images.githubusercontent.com/52114895/82207298-81ce0100-9901-11ea-90a7-09ba0eebf6f2.png">

**Comment by mpsq** [comment]
Closing, fixed in #314
