### ISSUE TITLE
Add support for SQL: CUMULATIVE SUM

### ISSUE THREAD

**Issue by newskooler** [questdb/questdb#2995]
### Is your feature request related to a problem?

I am trying to compute the cumulative sum of time-series.

### Describe the solution you'd like.

Ideally It would work like so:
```
SELECT cumsum(values) cumsum_value, timestamp, some_symbol
FROM my_table
```

### Describe alternatives you've considered.

None that I could find so far. Not even in Grafana ([source](https://stackoverflow.com/questions/57203156/how-can-i-make-a-cumulative-sum-graph-in-grafana-from-an-elasticsearch-data-sou)). 

Update:
I did find an ugly solution which is to read the data from QuestDB -> process it however I want -> expose via API -> read via this api (or save back to Quest and read via questAPI).
It's not really a solution, but that's one way to go around it and still expose to Grafana or elsewhere.

**Comment by marregui** [comment]
this is comming. Window functions are in our immediate roadmap, buy popcorn, you will start seeing PRs soon in this direction.

**Comment by newskooler** [comment]
That is music to my ears! Can't wait to give them a spin. Thank you 🙏

**Comment by puzpuzpuz** [comment]
Cumulative sum was shipped some time ago.
