### ISSUE TITLE
ERROR: inconvertible types: CHAR -> STRING

### ISSUE THREAD

**Issue by river320** [questdb/questdb#3004]
### Describe the bug

HI，I have a table，and a COLUMN named op, this  field data type is "string",when i update it,.
for example ，update table set op='u' where name='test';  
this sql return the ERROR: inconvertible types: CHAR -> STRING [from=, to=op];

the ”PostgreSQL wire protocol“ way and the ”Web Console“ way return the same error

How can i update this success ?

Thank you

### Expected Behavior

the sql "update table set op='u' where name='test';  “ can be success when the field data type is string

### Environment

```markdown
- **QuestDB version**: 7.0.0
- **OS**:centos7.0
- **Browser**: chrome
```

**Comment by puzpuzpuz** [comment]
Thanks for raising the issue. As a workaround could you try this syntax?
```sql
update table set op='u'::string where name='test';
``

**Comment by river320** [comment]
this syntax is  ok, thank you
