### ISSUE TITLE
Cannot insert Long.MIN_VALUE over line protocol

### ISSUE THREAD

**Issue by davidcooke2** [questdb/questdb#3009]
### Describe the bug

According to the [docs](https://questdb.io/docs/reference/sql/datatypes/), a long is a "Signed integer 0x8000000000000000L to 0x7fffffffffffffffL".

We have a value that happens to be `Long.MIN_VALUE` that we would like to record in questdb, but inserting it over the line protocol gets the following error recorded in the server logs:

```
2023-02-22T10:50:58.020358Z E i.q.c.l.t.LineTcpConnectionContext [24] could not parse measurement, INVALID_FIELD_VALUE at 26, line (may be mangled due to partial parsing): 'long_col_only big_boy=NaNi'
```

We have seen that [`Long.MIN_VALUE` is special cased to `NaN` in the line protocol](https://github.com/questdb/questdb/blob/7.0.0/core/src/main/java/io/questdb/std/Numbers.java#L162), but don't see why this was done if the server side cannot handle this?

### To reproduce

1. Create a table with a long column
```sql
CREATE TABLE long_col_only (
  big_boy LONG
);
```
2. Attempt to insert `Long.MIN_VALUE` over the line protocol
```java
    public static void main(String[] args)
    {
        try (Sender sender = Sender.builder().address("localhost:9009").build())
        {
            sender.table("long_col_only")
                    .longColumn("big_boy", Long.MIN_VALUE)
                    .atNow();
        }
    }
```

### Expected Behavior

```sql
SELECT * FROM 'long_col_only';
```

Should return a row with the value being either `0x8000000000000000` or `null` (as mentioned in the [docs](https://questdb.io/docs/reference/sql/datatypes/#type-nullability))

### Environment

```markdown
- **QuestDB version**: 7.0.0 (jdk11)
- **OS**: Fedora 36
- **Browser**: Firefox 100.0 (64-bit)
```

**Comment by ideoma** [comment]
QuestDB uses Long.MIN_VALUE as a NULL value for timestamp.

If you skip the field in ILP, it will be inserted as null.

You cannot save Long.MIN_VALUE explicitly, it will be returned back as NULL when you query it and will have all the NULL logic.

**Comment by davidcooke2** [comment]
> QuestDB uses Long.MIN_VALUE as a NULL value for timestamp.

Okay, we're not talking about the timestamp here, we're talking about another column.

> If you skip the field in ILP, it will be inserted as null.

For a table with one column that's a long, as in the reproduction scenario, you cannot skip the field:

```
Exception in thread "main" io.questdb.cutlass.line.LineSenderException: no symbols or columns were provided
	at io.questdb.cutlass.line.AbstractLineSender.atNow(AbstractLineSender.java:86)
	at org.example.Main.main(Main.java:24)
```

> You cannot save Long.MIN_VALUE explicitly

You can via SQL:

```sql
INSERT INTO long_col_only (big_boy) VALUES (0x8000000000000000::long);
```

> it will be returned back as NULL when you query it and will have all the NULL logic.

Yes, that would be good. That's the result when running a `SELECT` after the above `INSERT`.

---

If trying to write a `Long.MIN_VALUE` is not supported, it would be nice if it was documented or threw in the client, rather than be serialised to `NaN` and fail to be parsed on the server side?

Or the server side should be handling the `NaN` that got serialised and interpret that as null?

**Comment by ideoma** [comment]
Thanks for the context. I see 3 issues here

1. ILP does not support lines with table name only. This is done to protect against malformed input where every rogue line can create a table. We can probably add a way to relax this limitation.
2. It is possible to insert Long.MIN_VALUE in SQL. It seems to be actually a bug rather than a feature.
3 There is no way to insert NULL value from ILP explicitly. We can probably allow that but solving 1. seems to be a preferable way, doesn't it?

**Comment by davidcooke2** [comment]
For a bit more context, our application also happens to use `Long.MIN_VALUE` to signify null. We figured since questdb did the same we'd be fine. The fact this failed was _surprising_.


> 1. ILP does not support lines with table name only. This is done to protect against malformed input where every rogue line can create a table. We can probably add a way to relax this limitation.

Yes, this may help.

> 2. It is possible to insert Long.MIN_VALUE in SQL. It seems to be actually a bug rather than a feature.

This seems like a good bug to me ;)

> 3. There is no way to insert NULL value from ILP explicitly. We can probably allow that but solving 1. seems to be a preferable way, doesn't it?

Point 1 would likely be a way to do this. I still think the API is unintuitive if it accepts a `Long.MIN_VALUE`, transforms it to `NaN` in ILP, and the server doesn't handle that.

As it is right now, I don't know why the ILP client code even transforms the `Long.MIN_VALUE` to `NaN` since it's unsupported.

Ideally I think that the server should be able to handle long values coming in over ILP as `NaN` and insert a null, which would be much less surprising and more in line with what we thought it would do.
