### ISSUE TITLE
UNION shows weird behaviour when combined with order by

### ISSUE THREAD

**Issue by javier** [questdb/questdb#3010]
### Describe the bug

If we UNION several statements then wrap around a select with order by, the results show inconsistent (and unexpected) behaviour. 

Adding some queries below to show the problem

### To reproduce

1. go to demo site and run this query

```
WITH full_range AS (  
  SELECT timestamp, galon_price FROM (
    SELECT * FROM (
      SELECT * FROM gas_prices
      UNION
      SELECT to_timestamp('1999-01-01', 'yyyy-MM-dd'), NULL as galon_price -- First Date
      UNION 
      SELECT to_timestamp('2023-02-20', 'yyyy-MM-dd'), NULL  as galon_price -- Last Date
    ) AS unordered_data order by timestamp
  ) TIMESTAMP(timestamp)
) 
select * from full_range
```

Even if the statements are not in order inside the UNION, when we do the final `select * from full_range` we see results are ordered. So far, this is what I would expect, as after the UNION we are doing a `AS unordered_data order by timestamp`

Now let's just add order by to the external select, as in

```
WITH full_range AS (  
  SELECT timestamp, galon_price FROM (
    SELECT * FROM (
      SELECT * FROM gas_prices
      UNION
      SELECT to_timestamp('1999-01-01', 'yyyy-MM-dd'), NULL as galon_price -- First Date
      UNION 
      SELECT to_timestamp('2023-02-20', 'yyyy-MM-dd'), NULL  as galon_price -- Last Date
    ) AS unordered_data order by timestamp
  ) TIMESTAMP(timestamp)
) 
select * from full_range order by timestamp
```

Now results are not in order. We see all the results from the original gas_prices table first, then the results from the other two statements in the end. If we` order by timestamp ASC` we see the same problem, but interestingly `order by timestamp DESC `works as expected. However, when we do the order by timestamp DESC the console is showing results in white, meaning it is not interpreted as a designated timestamp

![image](https://user-images.githubusercontent.com/3839/220626409-4cc10e11-fc9b-4c60-b067-2cf9309a0fa9.png)

Just to make sure it was not happening because the two "literal queries" don't have a designated timestamp, I rewrote the query as 

```
WITH first_date AS (
select * from (select * FROM (SELECT to_timestamp('1999-01-01', 'yyyy-MM-dd') as timestamp, NULL as galon_price)) timestamp(timestamp)
),
last_date AS (
select * from (select * FROM (SELECT to_timestamp('2023-02-20', 'yyyy-MM-dd') as timestamp, NULL as galon_price)) timestamp (timestamp)
),
full_range AS (  
  SELECT timestamp, galon_price FROM (
    SELECT * FROM (
      SELECT * FROM gas_prices
     UNION
      SELECT * FROM first_date
      UNION
      SELECT * FROM last_date
    ) order by timestamp 
  ) TIMESTAMP(timestamp)
) 
select * from full_range  order by timestamp desc;
```
Now every statement there should have a designated timestamp, however the behaviour is the same as above. Order by ASC fails, order by DESC misses the designated timestamp, no order by produces good results.

If however we change the queries (with or without designated timestamps) so the UNION statements are in chronological order, the results are always in the right order (without order by or with and without ASC and DESC), but however the DESC statement still misses the designated timestamp meaning.

The next two versions of the query (both with and without extra designated timestamp statements) return those results

```
WITH full_range AS (  
  SELECT timestamp, galon_price FROM (
    SELECT * FROM (
      SELECT to_timestamp('1999-01-01', 'yyyy-MM-dd') as timestamp, NULL as galon_price -- First Date
      UNION
      SELECT * FROM gas_prices           
      UNION 
      SELECT to_timestamp('2023-02-20', 'yyyy-MM-dd') as timestamp, NULL  as galon_price -- Last Date
    )  AS unordered_data order by timestamp
  ) TIMESTAMP(timestamp)
) 
select * from full_range order by timestamp ASC
```

```
WITH first_date AS (
select * from (select * FROM (SELECT to_timestamp('1999-01-01', 'yyyy-MM-dd') as timestamp, NULL as galon_price)) timestamp(timestamp)
),
last_date AS (
select * from (select * FROM (SELECT to_timestamp('2023-02-20', 'yyyy-MM-dd') as timestamp, NULL as galon_price)) timestamp (timestamp)
),
full_range AS (  
  SELECT timestamp, galon_price FROM (
    SELECT * FROM (
      SELECT * FROM first_date
      UNION 
      SELECT * FROM gas_prices
      UNION
      SELECT * FROM last_date
    ) order by timestamp 
  ) TIMESTAMP(timestamp)
) 
select * from full_range  order by timestamp ASC;
```

### Expected Behavior

I would expect since we are forcing ORDER BY after the UNION results should be in order. If ORDER BY cannot be used in combination with UNION then it should probably throw an error

### Environment

```markdown
- **QuestDB version**: 7.0.1 (dev version on the demo site)
- **OS**: demo site
- **Browser**:chrome
```

### Additional context

This was surfaced at the public slack conversation at https://questdb.slack.com/archives/C1NFJEER0/p1676890276428389

**Comment by ujjwalsinha2518** [comment]
I am interested in solving this bug ,please tell me how to go to demo site and code as I am new on github,so not very familiar with the interface rn

**Comment by puzpuzpuz** [comment]
`TIMESTAMP(column_name)` is supposed to be applied to an in-order result set. It's basically a hint for the query engine to tell it that the result set is ordered as if the specified column was a designated timestamp one. Considering this, the above behavior seems fine to me. @javier am I missing something?

**Comment by javier** [comment]
Thanks for the comment @puzpuzpuz. I understand what you are saying, but we are doing an ORDER BY then applying a timestamp, so the expectation would be that the results are ordered (in memory) by the time we are using the timestamp hint. If using order by and timestamp together is not supported then we should probably raise an error

**Comment by puzpuzpuz** [comment]
> but we are doing an ORDER BY then applying a timestamp, so the expectation would be that the results are ordered (in memory) by the time we are using the timestamp hint

I'm looking at the results of the following query on demo:
```sql
WITH first_date AS (
select * from (select * FROM (SELECT to_timestamp('1999-01-01', 'yyyy-MM-dd') as timestamp, NULL as galon_price)) timestamp(timestamp)
),
last_date AS (
select * from (select * FROM (SELECT to_timestamp('2023-02-20', 'yyyy-MM-dd') as timestamp, NULL as galon_price)) timestamp (timestamp)
),
full_range AS (  
  SELECT timestamp, galon_price FROM (
    SELECT * FROM (
      SELECT * FROM gas_prices
     UNION
      SELECT * FROM first_date
      UNION
      SELECT * FROM last_date
    ) order by timestamp 
  ) TIMESTAMP(timestamp)
) 
select * from full_range;
```
and they look fine to me: `1999-01-01T00:00:00.000000Z` is the first row, `2023-02-20T00:00:00.000000Z` is the last one. Could it be something that was fixed recently or am I missing something?

**Comment by mdahlman** [comment]
@puzpuzpuz , take a look at second query:
```
/* Let's call this QUERY_2 */
WITH full_range AS (  
  SELECT timestamp, galon_price FROM (
    SELECT * FROM (
      SELECT * FROM gas_prices
      UNION
      SELECT to_timestamp('1999-01-01', 'yyyy-MM-dd'), NULL as galon_price -- First Date
      UNION 
      SELECT to_timestamp('2023-02-20', 'yyyy-MM-dd'), NULL  as galon_price -- Last Date
    ) AS unordered_data order by timestamp
  ) TIMESTAMP(timestamp)
) 
select * from full_range order by timestamp;
```

QUERY_2 should return results ordered by the column `timestamp`. It does not.

`2000-06-05T00:00:00.000000Z` is the first row.
`2000-06-12T00:00:00.000000Z` is the second row.
`1999-01-01T00:00:00.000000Z` is the penultimate row. This appears to be the critical problem.
`2023-02-20T00:00:00.000000Z` is the last one.
1029 records are ordered as expected. But the record from 1999 is not in order.

**Comment by puzpuzpuz** [comment]
Thanks for the clarification. This variant of QUERY_2 works:
```sql
WITH full_range AS (  
  SELECT timestamp, galon_price FROM (
    SELECT * FROM (
      SELECT * FROM gas_prices
      UNION
      SELECT to_timestamp('1999-01-01', 'yyyy-MM-dd'), NULL as galon_price -- First Date
      UNION 
      SELECT to_timestamp('2023-02-20', 'yyyy-MM-dd'), NULL  as galon_price -- Last Date
    ) AS unordered_data order by timestamp
  ) TIMESTAMP(timestamp)
) 
select * from full_range;
```

Notice the absence of the training ORDER BY.

When this ORDER BY is in place the query engine seems to be too aggressive as it wrongly removes the sorting (this may be seen with EXPLAIN).
