### ISSUE TITLE
Jupysql integration

### ISSUE THREAD

**Issue by idomic** [questdb/questdb#3064]
### Is your feature request related to a problem?

This will allow jupyter users easy access to QuestDB.

### Describe the solution you'd like.

It'd be great to see a tutorial or documentation of the 2 frameworks.

Probably a user working locally via a jupyter notebook and [jupysql](https://github.com/ploomber/jupysql) to query QuestDB and perform EDA/modeling work.

**Comment by javier** [comment]
Thank you! We have the documentation in a separate repo (questdb.io). In particular, third party guides live under this folder https://github.com/questdb/questdb.io/tree/master/docs/third-party-tools

**Comment by javier** [comment]
redirecting original poster to our docs/website repository
