### ISSUE TITLE
How to continue to maintain the presence of web console functionality when using the Java embedded API

### ISSUE THREAD

**Issue by daodol** [questdb/questdb#3084]
### Is your feature request related to a problem?

Hi, I am using the Java embedded API, and I want to continue using the functionality provided by the web console. What should I do. I want to use the web console as a database management tool

**Comment by marregui** [comment]
Hi @daodol ,

Have you tried it yet?, I have a personal project (a GUI) that starts QuestDB in process (alongside my app) on the press of a toggle button:

```java
private void onToggleQuestDB(ActionEvent ignore) {
        if (questDb == null) {
            try {
                questDb = new ServerMain("-d", Store.ROOT_PATH.getAbsolutePath());
                questDb.start(false);
                toggleQuestDB.setText("Shutdown QuestDB");
            } finally {
                results.displayMessage("QuestDB is UP");
            }
        } else {
            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(
                frame,
                "Shutdown QuestDB?",
                "Choice",
                JOptionPane.YES_NO_OPTION)
            ) {
                questDb.close();
                questDb = null;
                toggleQuestDB.setText("Run QuestDB");
            }
        }
    }
```
while QuestDB is running I can go to a browser and access localhost:9000 and manage the instance like that.

Best

**Comment by daodol** [comment]
> The `questDb.start(false);` is so that I control when I shutdown QuestDB, rather than when my app terminates.

good idea.thanks for ur answer.

**Comment by daodol** [comment]
> > The `questDb.start(false);` is so that I control when I shutdown QuestDB, rather than when my app terminates.
> 
> good idea.thanks for ur answer.

@marregui hi,I am implementing it in your way, but in doing so, the storage path of the embedded questdb table is inconsistent with the storage path of the console. The console mode is stored in the db directory, and the embedded requestdb is directly stored in the root directory

**Comment by marregui** [comment]
hey hey @daodol I have attached a small project illustrating how to run QuestDB from your program.
If you run it with `./example data` and then you go to the web console and create a table:

```

CREATE TABLE tab AS (
    SELECT
        rnd_str('Jan', 'Feb', 'Mar') owner,
        rnd_long() value,
        rnd_timestamp(
            to_timestamp('2022-01-01T00', 'yyyy-MM-ddTHH'),
            to_timestamp('2023-03-23T13', 'yyyy-MM-ddTHH'),
        0) ts
    FROM long_sequence(200000)
) TIMESTAMP(ts) PARTITION BY DAY;
```

then you will see:

```
~/workspace/example/build/distributions/example-1.0.0/bin/data$ ls -l
total 0
drwxr-xr-x   5 marregui  staff  160 Apr  3 15:14 conf
drwxr-xr-x  14 marregui  staff  448 Apr  3 15:14 db
drwxr-xr-x   2 marregui  staff   64 Apr  3 15:14 log
drwxr-xr-x  13 marregui  staff  416 Apr  3 15:14 public
```

and 


```
~/workspace/example/build/distributions/example-1.0.0/bin/data/db$ ls -la
total 24
drwxr-xr-x  14 marregui  staff   448 Apr  3 15:14 .
drwxr-xr-x   6 marregui  staff   192 Apr  3 15:14 ..
-rw-r--r--   1 marregui  staff  4096 Apr  3 15:14 _tab_index.d
-rw-r--r--   1 marregui  staff  4096 Apr  3 15:14 _upgrade.d
drwxrwxr-x  16 marregui  staff   512 Apr  3 15:14 sys.column_versions_purge_log
-rw-r--r--   1 marregui  staff     0 Apr  3 15:14 sys.column_versions_purge_log.lock
drwxrwxr-x   8 marregui  staff   256 Apr  3 15:14 sys.telemetry_wal
-rw-r--r--   1 marregui  staff     0 Apr  3 15:14 sys.telemetry_wal.lock
-rw-r--r--   1 marregui  staff  4096 Apr  3 15:14 tables.d.0
-rw-r--r--   1 marregui  staff     0 Apr  3 15:14 tables.d.lock
drwxrwxr-x   9 marregui  staff   288 Apr  3 15:14 telemetry
-rw-r--r--   1 marregui  staff     0 Apr  3 15:14 telemetry.lock
drwxrwxr-x  21 marregui  staff   672 Apr  3 15:14 telemetry_config
-rw-r--r--   1 marregui  staff     0 Apr  3 15:14 telemetry_config.lock
```

this would use the default configuration, where `db` is where the root of the tables is.

**Comment by daodol** [comment]
> hey hey @daodol I have attached a small project illustrating how to run QuestDB from your program. If you run it with `./example data` and then you go to the web console and create a table:
> 
> ```
> 
> CREATE TABLE tab AS (
>     SELECT
>         rnd_str('Jan', 'Feb', 'Mar') owner,
>         rnd_long() value,
>         rnd_timestamp(
>             to_timestamp('2022-01-01T00', 'yyyy-MM-ddTHH'),
>             to_timestamp('2023-03-23T13', 'yyyy-MM-ddTHH'),
>         0) ts
>     FROM long_sequence(200000)
> ) TIMESTAMP(ts) PARTITION BY DAY;
> ```
> 
> then you will see:
> 
> ```
> ~/workspace/example/build/distributions/example-1.0.0/bin/data$ ls -l
> total 0
> drwxr-xr-x   5 marregui  staff  160 Apr  3 15:14 conf
> drwxr-xr-x  14 marregui  staff  448 Apr  3 15:14 db
> drwxr-xr-x   2 marregui  staff   64 Apr  3 15:14 log
> drwxr-xr-x  13 marregui  staff  416 Apr  3 15:14 public
> ```
> 
> and
> 
> ```
> ~/workspace/example/build/distributions/example-1.0.0/bin/data/db$ ls -la
> total 24
> drwxr-xr-x  14 marregui  staff   448 Apr  3 15:14 .
> drwxr-xr-x   6 marregui  staff   192 Apr  3 15:14 ..
> -rw-r--r--   1 marregui  staff  4096 Apr  3 15:14 _tab_index.d
> -rw-r--r--   1 marregui  staff  4096 Apr  3 15:14 _upgrade.d
> drwxrwxr-x  16 marregui  staff   512 Apr  3 15:14 sys.column_versions_purge_log
> -rw-r--r--   1 marregui  staff     0 Apr  3 15:14 sys.column_versions_purge_log.lock
> drwxrwxr-x   8 marregui  staff   256 Apr  3 15:14 sys.telemetry_wal
> -rw-r--r--   1 marregui  staff     0 Apr  3 15:14 sys.telemetry_wal.lock
> -rw-r--r--   1 marregui  staff  4096 Apr  3 15:14 tables.d.0
> -rw-r--r--   1 marregui  staff     0 Apr  3 15:14 tables.d.lock
> drwxrwxr-x   9 marregui  staff   288 Apr  3 15:14 telemetry
> -rw-r--r--   1 marregui  staff     0 Apr  3 15:14 telemetry.lock
> drwxrwxr-x  21 marregui  staff   672 Apr  3 15:14 telemetry_config
> -rw-r--r--   1 marregui  staff     0 Apr  3 15:14 telemetry_config.lock
> ```
> 
> this would use the default configuration, where `db` is where the root of the tables is.

hi,I resolved the database path issue by modifying the embedded requestdb configuration, but now that I have both the requestdb console and the embedded requestdb enabled, it seems that this is not allowed

**Comment by daodol** [comment]
log：Invocation of init method failed; nested exception is io.questdb.cairo.CairoException: [0] cannot lock table name registry file [path=D:\workspace\things-bootstrap\questDb\db]

**Comment by daodol** [comment]
Is there a way to handle it?

**Comment by marregui** [comment]
Hi, not sure I am understanding. I am assuming that you run a single instance of QuestDB, started from your program. The first time you run it a directory was created containint directories conf, public, db and log. Then I imagine you went to this directory and changed settings in conf/server.conf. Then you start/stop your program, which starts/stops QuestDB, correct?, Could you please post the logs here so that I can see the root cause of `[0] cannot lock table name registry file [path=D:\workspace\things-bootstrap\questDb\db]`?

Thank you in advance.

**Comment by daodol** [comment]
@marregui 
hi，I am using the embedded API, and the code in the picture is a helper class for manipulating requestdb. This can only be done using synchronous methods. How to use concurrent operations
<img width="791" alt="16811804042178" src="https://user-images.githubusercontent.com/16305190/231040725-aaabbb32-3261-413a-9638-0fde015bc7b3.png">

**Comment by daodol** [comment]
@marregui In this case, every time a row is created, a new wal folder will be created in the table folder. Will the wal folder become more and more as the row is created, and even result in the inability to create a new folder in the end

**Comment by marregui** [comment]
hi @daodol are you starting the server alongside this code and then you are creating a CairoEngine aside from the server's?

ServerMain should give you access the the CairoEngine required (getCairoEngine).

**Comment by daodol** [comment]
Do you mean that I should start a requestdb console through ServerMain, obtain a cairoEngine instance through ServerMain, and then use cairoEngine in the embedded API?
![1681262238870](https://user-images.githubusercontent.com/16305190/231322369-9a5d0c4c-e7c8-4faa-8d96-5efc794516a4.jpg)
If we do this, do we need to release sqlExecutionContext and sqlCompiler every time? Will sqlExecutionContext and cairoEngine automatically refresh after creating tables through sqlCompiler?

**Comment by daodol** [comment]
> Do you mean that I should start a requestdb console through ServerMain, obtain a cairoEngine instance through ServerMain, and then use cairoEngine in the embedded API? ![1681262238870](https://user-images.githubusercontent.com/16305190/231322369-9a5d0c4c-e7c8-4faa-8d96-5efc794516a4.jpg) If we do this, do we need to release sqlExecutionContext and sqlCompiler every time? Will sqlExecutionContext and cairoEngine automatically refresh after creating tables through sqlCompiler?

hi,I have tested this usage and it is a very good idea. Now there is a new issue with the production line. I need to dynamically create a table, and the table creation operation needs to be executed with a lock. It seems feasible, but if I concurrently create a SqlCompiler to insert data, the generated files will have multiple folders with names starting with wal. These folders existed for several minutes, and while I was writing this message, I noticed that these folders had disappeared. Does that mean there are relevant settings? How long will the WAL folder merge and disappear?

**Comment by marregui** [comment]
hi!, I have been working on an issue and been keeping you in mind. In this PR https://github.com/questdb/questdb/pull/3183/files#diff-fac2030b90f1d9e80a597c778dad544393d8d1fe7885bff19ca89403009736b5

there is a new test class `core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java` that sort of exemplifies what you are doing (_testServerMainBackupDatabase_):

- create start QuestDB:
   
   ```java
   try (
       ServerMain qdb = new ServerMain("-d", rootDir, Bootstrap.SWITCH_USE_DEFAULT_LOG_FACTORY_CONFIGURATION);
       SqlCompiler defaultCompiler = new SqlCompiler(qdb.getCairoEngine());
       SqlExecutionContext defaultContext = executionContext(qdb.getCairoEngine())
   ) {
       qdb.start();
       ...
   } // QuestDB server ends here
   ```
   in this case we launch the server and it will close automatically. After `qdb.start()` the webconsole will be available.

- use the server as a framework. In the test I get the **engine** and I use it to create as many compilers as I need.

Notes:
- compilers are not thread safe, make sure only one thread at the time is using a given compiler.
- each compiler requires a context, so create a context every time you create a compiler.
- use each compiler, context as many times as you need.
- when you are done with the compilers, free them and their resources (a call to close will do).

In the test, we create a defaultCompiler for convenience, and N compilers because they will be used by N threads concurrently.

The test deals with backups, but if you look in the codebase for classes that are named `ServerMain...` you will find **ServerMainForeignTableTest** which creates tables concurrently.

Notes on dissapearing directories:
- WAL tables do generate ephemeral directories that are culled aynchronously when there are no readers for them.
- when you have readers on the table, any SQL that changes the table will version upwards all required partition folders and metadata files. For instance if you have partition 2023-04-20 and a reader is selecting on it, and at the same time there is an insert for that partition, or an update, or drop/detach, alter..., then all those changes will be done to a copy on write copy of 2023-04-20 which will be called 2023-04-20.1. When the select is over, QuestDB will remove 2023-04-20. 
- not only partition folders and metadata files are versioned, also the WAL metadata files. In the end, once a WAL has been applied, it can be removed.

If you notice that these directories' versions shoot up like bamboo, it means that you probaby have too high a granularity for the table (partition by) and perhaps if you lowered (YEAR -> MONTH, MONTH -> WEEK, ...) then there would be less collisions on write, there would be less overhead.

**Comment by daodol** [comment]
> hi!, I have been working on an issue and been keeping you in mind. In this PR https://github.com/questdb/questdb/pull/3183/files#diff-fac2030b90f1d9e80a597c778dad544393d8d1fe7885bff19ca89403009736b5
> 
> there is a new test class `core/src/test/java/io/questdb/test/ServerMainBackupDatabaseTest.java` that sort of exemplifies what you are doing (_testServerMainBackupDatabase_):
> 
>     * create start QuestDB:
>       ```java
>       try (
>           ServerMain qdb = new ServerMain("-d", rootDir, Bootstrap.SWITCH_USE_DEFAULT_LOG_FACTORY_CONFIGURATION);
>           SqlCompiler defaultCompiler = new SqlCompiler(qdb.getCairoEngine());
>           SqlExecutionContext defaultContext = executionContext(qdb.getCairoEngine())
>       ) {
>           qdb.start();
>           ...
>       } // QuestDB server ends here
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       in this case we launch the server and it will close automatically. After `qdb.start()` the webconsole will be available.
> 
>     * use the server as a framework. In the test I get the **engine** and I use it to create as many compilers as I need.
> 
> 
> Notes:
> 
>     * compilers are not thread safe, make sure only one thread at the time is using a given compiler.
> 
>     * each compiler requires a context, so create a context every time you create a compiler.
> 
>     * use each compiler, context as many times as you need.
> 
>     * when you are done with the compilers, free them and their resources (a call to close will do).
> 
> 
> In the test, we create a defaultCompiler for convenience, and N compilers because they will be used by N threads concurrently.
> 
> The test deals with backups, but if you look in the codebase for classes that are named `ServerMain...` you will find **ServerMainForeignTableTest** which creates tables concurrently.
> 
> Notes on dissapearing directories:
> 
>     * WAL tables do generate ephemeral directories that are culled aynchronously when there are no readers for them.
> 
>     * when you have readers on the table, any SQL that changes the table will version upwards all required partition folders and metadata files. For instance if you have partition 2023-04-20 and a reader is selecting on it, and at the same time there is an insert for that partition, or an update, or drop/detach, alter..., then all those changes will be done to a copy on write copy of 2023-04-20 which will be called 2023-04-20.1. When the select is over, QuestDB will remove 2023-04-20.
> 
>     * not only partition folders and metadata files are versioned, also the WAL metadata files. In the end, once a WAL has been applied, it can be removed.
> 
> 
> If you notice that these directories' versions shoot up like bamboo, it means that you probaby have too high a granularity for the table (partition by) and perhaps if you lowered (YEAR -> MONTH, MONTH -> WEEK, ...) then there would be less collisions on write, there would be less overhead.

cool！！！
