### ISSUE TITLE
SAMPLE BY on a UNION ALL query returns an error when used in CTE

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#3085]
### Describe the bug

```sql
WITH all_rows AS (
    SELECT CAST(1676837104 * 1000000L AS TIMESTAMP) as ts, 'foobar' as address, 0 as value
    union all
    SELECT CAST(1679429108 * 1000000L AS TIMESTAMP) as ts, 'foobar' as address, 1 as value
), just_foobar as (
    select * from all_rows where address in ('foobar')
), ordered as (
    select * from just_foobar order by ts asc
), timed as (
    select * from ordered timestamp(ts)
), sampled as (
    SELECT ts, sum(value) as value
    FROM timed
    SAMPLE BY 1d FILL(0) ALIGN TO CALENDAR 
)
select * from sampled;
```
returns `ASC order over TIMESTAMP column is required but not provided`.

The bug seems to have something to do with the `just_foobar` CTE since without it the query runs fine.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by sani639** [comment]
WITH all_rows AS (
    SELECT CAST(1676837104 * 1000000L AS TIMESTAMP) as ts, 'foobar' as address, 0 as value
    UNION ALL
    SELECT CAST(1679429108 * 1000000L AS TIMESTAMP) as ts, 'foobar' as address, 1 as value
), just_foobar as (
    SELECT * FROM all_rows WHERE address IN ('foobar')
), ordered as (
    SELECT * FROM just_foobar ORDER BY ts ASC
), timed as (
    SELECT * FROM ordered TIMESTAMP(ts) AS t
), sampled as (
    SELECT t, SUM(value) as value
    FROM timed
    SAMPLE BY 1d FILL(0) ALIGN TO CALENDAR 
    GROUP BY t
)
SELECT * FROM sampled ORDER BY t ASC;



The main change is the addition of the "AS t" clause after the TIMESTAMP function call in the "timed" subquery, which assigns a name to the resulting timestamp column.

**Comment by puzpuzpuz** [comment]
> The main change is the addition of the "AS t" clause after the TIMESTAMP function call

This syntax is not supported by QuestDB, so the above SQL won't work.

**Comment by Nkashyap-anand** [comment]
`WITH all_rows AS (
    SELECT CAST(1676837104 * 1000000L AS TIMESTAMP) as ts, 'foobar' as address, 0 as value
    UNION ALL
    SELECT CAST(1679429108 * 1000000L AS TIMESTAMP) as ts, 'foobar' as address, 1 as value
), just_foobar AS (
    SELECT * FROM all_rows WHERE address IN ('foobar')
), ordered AS (
    SELECT * FROM just_foobar ORDER BY ts
), timed AS (
    SELECT CAST(ts AS TIMESTAMP) AS ts, value FROM ordered
), sampled AS (
    SELECT to_timestamp(floor(ts / 86400000000) * 86400000000) AS ts, SUM(value) AS value
    FROM timed
    GROUP BY floor(ts / 86400000000)
    FILL(previous)
)
SELECT * FROM sampled;
`
we use CAST to convert the ts column in the timed CTE to the TIMESTAMP data type. We then use the floor function to round the ts column down to the nearest day, divide by the number of microseconds in a day (86400000000), and then multiply by the same value to get the timestamp at the start of each day. We then group the results by the rounded timestamp and use the previous fill policy to fill in any missing values.

does this work?
