### ISSUE TITLE
Style_Loader

### ISSUE THREAD

**Issue by RAJEEVKUMAR9598** [questdb/questdb#3099]
### Is your feature request related to a problem?

Yes! i think when we open your website then we use a page loader which is setup all backend data. When all data set by backend then we show a frontend page which is user friendly and creative. like as .
![START](https://user-images.githubusercontent.com/99285150/227705466-0c3e98e4-fa13-49e0-86f2-e688bb716b07.PNG)

### Describe the solution you'd like.

I create a style loading page by using html,css,js. html and css  creates a page. js will revert time and many more.

### Describe alternatives you've considered.

No ,i think it is normal using frontend.

### Additional context.

NA

**Comment by bluestreak01** [comment]
Spam
