### ISSUE TITLE
Function to_timestamp without format does not work in v 7

### ISSUE THREAD

**Issue by EshaanDikshit** [questdb/questdb#3100]
### Describe the bug

This used to work in 6.5.3

select to_timestamp('2023-03-03 10:36:11.228932+00:00') 
but in 7.0.1 returns null

**Quest version**:7.0.1

**Comment by EshaanDikshit** [comment]
Please enable this syntax or pattern in v 7 of quest db also

**Comment by Sohan064** [comment]
Please enable this syntax or pattern in v 7 of quest db also

**Comment by diptanusaha2001** [comment]
This used to work in 6.5.3

select to_timestamp('2023-03-03 10:36:11.228932+00:00')
but in 7.0.1 returns null

Quest version:7.0.1

Please enable this syntax or pattern in v 7 of quest db also

**Comment by bluestreak01** [comment]
spam
