### ISSUE TITLE
QuestDB's Slack channel joining link not working

### ISSUE THREAD

**Issue by ArnabC27** [questdb/questdb#3115]
### Describe the bug

There are several sections on the [QuestDB Website](https://questdb.io/) where **_Join Slack_** links are displayed.
But upon clicking any of them an application error is displayed on the screen.

https://user-images.githubusercontent.com/70847577/227744229-09c6290a-8d6f-44b0-8088-4aef01a7347c.mp4

### To reproduce

1. Go to https://questdb.io/
2. Find Join Slack option towards the bottom of the Home page.
3. Click on Join Slack

### Expected Behavior

Upon clicking on Join Slack, the user should be redirected to QuestDB's Slack channel for joining.

### Environment

```markdown
- **Windows 11**:
- **Google Chrome**:
```

**Comment by bluestreak01** [comment]
thank you, we're investigating

**Comment by bluestreak01** [comment]
it is fixed now
