### ISSUE TITLE
Problem "Not Found" in Quest DB 6 6.1-server with web proxy and nginx

### ISSUE THREAD

**Issue by jatingulati1264** [questdb/questdb#3118]
### Describe the bug

I am running quest db server 6 6.1 on my pc and I want to increase the protection of quest db and want to put the web gui behind nginx proxy but when I tried i will give a bug and not found is there on the screen

### Expected Behavior

I want that quest db reach should not produce errors or issues if we want to increase the protection of this server with using nginx behind web proxy.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
spam
