### ISSUE TITLE
How to view the created table in Quest DB

### ISSUE THREAD

**Issue by jatingulati1264** [questdb/questdb#3119]
### Describe the bug

I want to view the table which have been created after the users put up their values and whenever I am using quest db 6 6.1 server I get a error not found issue.

### Expected Behavior

I am using and running quest db 6 6.1 server and want that no issues or errors like not found will be there when using web proxy

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bluestreak01** [comment]
spam
