### ISSUE TITLE
Exception throws on query on a table with a large number of colums

### ISSUE THREAD

**Issue by arnav398** [questdb/questdb#3123]
### Describe the bug

When attempting to perform a SELECT query on a table with a large number of columns, QuestDB throws an exception and fails to return any results.

### To reproduce

1. Create a table with 5000 columns using the following SQL statement:
  CREATE TABLE my_table (
  id INT,
  col_1 INT,
  col_2 INT,
  ...
  col_4999 INT,
  col_5000 INT
)

2.Insert some data into the table using the following SQL statement:
INSERT INTO my_table VALUES (1, 1, 2, ..., 4999, 5000)4

3.Attempt to perform a SELECT query on the table using the following SQL statement:
SELECT * FROM my_table

### Expected Behavior

The SELECT query should return all rows and columns from the `my_table` table.
java.lang.IllegalArgumentException: number of arguments: 5002 > maximum: 5000

### Environment

```markdown
QuestDB version: 6.0.0
Operating system: Windows 10
Java version: 11.0.10
```

### Additional context

This issue appears to be related to the maximum number of function arguments in QuestDB. When attempting to execute a query that selects fewer than 5000 columns, the query executes successfully. However, when attempting to select 5000 or more columns, QuestDB throws the exception described above.

**Comment by bluestreak01** [comment]
spam
