### ISSUE TITLE
avg() handling of null values

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#313]
**Describe the bug**
When using max(x), x is correctly ignored in the calculation when null/NaN. However, when using max(f(x)), f(x) is not always ignored when null/NaN making the whole aggregation return null.

**To Reproduce**
Let's create a table with values either equal to 1.0 or null
```
create table test as(select 
case 
     when rnd_double() > 0.6 then 1.0 
     else cast(NaN as double) 
end val 
from long_sequence(100));
```
NaN values are correctly ignored for calculation
```
select avg(val) from test; -- returns some value
```

Now, the below creates a table with values either equal to 1.0 or null
```
create table test2 as(select 
case 
     when rnd_double() > 0.6 then 1.0 
     else 0.0 
end val 
from long_sequence(100));
```
0.0 values are passed on, the result of 1/0.0 is NaN. Instead of ignoring this value, it is passed on to the whole aggregation which subsequently returns null
```
select avg(1/val) from test2; -- returns null
```

**Expected behavior**
When using avg(f(x)), the value of f(x) should be ignored if null or NaN.

**Comment by bluestreak01** [comment]
fixed
