### ISSUE TITLE
web console UI grid not showing results

### ISSUE THREAD

**Issue by tolap22** [questdb/questdb#3168]
### Describe the bug

simply as per title, any query on the editor show the number of columns of the result but the grid in the UI is always empty.

Apparently the component has been updated in [3068](https://github.com/questdb/questdb/pull/3068)

### To reproduce

open web console UI
write a "select * from tableName"
the grid shows no results

the javascript of the UI fails with:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'digest')
    at qdb.js:2:913132
    at qdb.js:2:913264
    at qdb.js:2:913268
```

### Expected Behavior

the table should show result

### Environment

```markdown
- **QuestDB version**: 7.1
- **OS**: Any
- **Browser**: Any
```

**Comment by bluestreak01** [comment]
This version is deployed on demo.questdb.io. Can you check if queries work there on your browser. Please narrow down the browser

**Comment by bluestreak01** [comment]
I would love to fix the bug if only I could reproduce it

**Comment by puzpuzpuz** [comment]
It could be the case that your browser doesn't support `crypto` Web API. If so, using another browser might help. This page lists the browsers: https://caniuse.com/?search=crypto

To support such browsers we could use a polyfill library (if any - I didn't check) or check the presence of `crypto` global and, if it's missing, use an alternative code path.

**Comment by bluestreak01** [comment]
Could you check if your browser is in one of green boxes here https://caniuse.com/mdn-api_crypto_subtle

**Comment by 0liu** [comment]
Same here. Pulled latest docker image to upgrade, and then query results don’t show up anymore.

**Comment by mgumz** [comment]
@bluestreak01 crypto-api is usable only in a "secure context": https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey

which means, any local installation which is not operated behind a https-proxy or the like will face the issue.

i have tested with safari, firefox, google-chrome: all the same result of what @tolap22 reported.
https://demo.questdb.io works like a charm.

**Comment by tolap22** [comment]
Hello, tried the demo at https://demo.questdb.io/ and I can correctly view the results in the UI grid with Chrome Version 111.0.5563.147 (Official Build) (64-bit), I also can see the results on my mobile phone.
At this point I think it is not browser related as I tried with both my mobile phone and Chrome browser on the PC and the result are the same: the results in the UI grid are not shown.
I don't think it is related with the antivirus either otherwise the phone would work, I tried exporting the schema of the example tables in demo.questdb.io and using them on our server and the result is the same, no results in the UI grid, so it is not related to the specific schema of our tables.
The only evidence something is gone awry is the debugger tools output:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'digest')
    at qdb.js:2:913132
    at qdb.js:2:913264
    at qdb.js:2:913268
:9000/exec?limit=0%2C1000&explain=true&count=true&src=con&query=SHOW%20CREATE%20TABLE%20rsrut1&timings=true:1          Failed to load resource: the server responded with a status of 400 (Bad request)
```

**Comment by tolap22** [comment]
> @bluestreak01 crypto-api is usable only in a "secure context": https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey
> 
> which means, any local installation which is not operated behind a https-proxy or the like will face the issue.
> 
> i have tested with safari, firefox, google-chrome against http://localhost:9000: all the same result of what @tolap22 reported. https://demo.questdb.io works like a charm.

In our deployment, we have always operated QuestDB without the use of certificates since both the QuestDB server and client run within our network, allowing for local data flow without being exposed to the outside. We believed that disabling TLS encryption could potentially remove a possible failure point and improve performance, thus we have kept it cleartext. Previously, this setup had worked without any issues up to version 7.1, which exhibited the problem described above. Therefore, we recommend either resolving the problem or explicitly stating that local connections without certificates cause issues with the web UI (in most browsers given that two random browsers exhibit the same behaviour).

**Comment by Vangreen** [comment]
I have same problem on all of our tests environments after update from 7.0.1. We use docker version. Same problem on fresh install and upgrade from 7.0.1
```
qdb.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'digest')
    at qdb.js:2:913132
    at qdb.js:2:913264
    at qdb.js:2:913268
```

Download result as CSV works so there is problem with web console UI

**Comment by puzpuzpuz** [comment]
As a fix, we should consider using alternative implementations in insecure contexts like https://github.com/digitalbazaar/forge#sha256 or https://github.com/bitwiseshiftleft/sjcl/

**Comment by tolap22** [comment]
> As a fix, we should consider using alternative implementations in insecure contexts like https://github.com/digitalbazaar/forge#sha256 or https://github.com/bitwiseshiftleft/sjcl/

Still not clear to me why the behaviour was different in 7.0.1 and we had this regression in 7.1. Using the same implementation as in 7.0.1 is possible?

**Comment by mgumz** [comment]
@puzpuzpuz if the "new" behaviour is clearly documented, i do not see that much of an issue or a hard requirement to introduce additional deps. i have now slapped traefik in front of questdb to provide tls. operation within k8s and port-forwarding allows that `localhost` situation … if one is aware of that.

an improvement i do see is to catch the js-error itself and slap a warning into the face of the user to instantly have clear expectation management at work =)

**Comment by tris0laris** [comment]
This issue is fixed with the new release, 7.1.1. 
Link: https://github.com/questdb/questdb/releases/tag/7.1.1

**Comment by mgumz** [comment]
i tried 7.1.1 on a pure http setup (no secure context anywhere in sight): 7.1.1 works like a charm.

thanks for the fix

**Comment by bluestreak01** [comment]
fixed in https://github.com/questdb/questdb/releases/tag/7.1.1
