### ISSUE TITLE
Get started  docker image changed owner of directory

### ISSUE THREAD

**Issue by joejustesen** [questdb/questdb#3169]
### Describe the bug

Using the Get Started info for docker, I opened a terminal window and ran the docker command from here:  https://questdb.io/docs/get-started/docker/
```
docker run \
  -p 9000:9000 -p 9009:9009 -p 8812:8812 -p 9003:9003 \
  -v "$(pwd):/var/lib/questdb" \
  questdb/questdb:7.1
```

Starting getting errors after the image was downloaded and started to run.  Local user account became unusable as I started getting errors of 'Permission Denied'.

Killed terminal and switched users.  Most of the files in the user's in the home directory had been changed to be owned by user 10001.    

### To reproduce

Run this from your home directory:

``` 
docker run \
  -p 9000:9000 -p 9009:9009 -p 8812:8812 -p 9003:9003 \
  -v "$(pwd):/var/lib/questdb" \
  questdb/questdb:7.1
```

### Expected Behavior

I expected docker to start the database and allow me to connect to the web console.

### Environment

```markdown
- **QuestDB version**: 7.1
- **OS**: Ubuntu 22.10
- **Browser**: Firefox
```

**Comment by Shaheer313** [comment]
hey can u assigne this to me ?
