### ISSUE TITLE
NPE when importing CSV via HTTP

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#3170]
### Describe the bug

```
2023-04-08T00:16:14.582042Z I i.q.c.h.HttpConnectionContext retrying query [fd=33]
--
  |   | ]
  |   | at io.questdb.mp.Worker.run(Worker.java:118)
  |   | at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:101)
  |   | at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
  |   | at io.questdb.cutlass.http.HttpServer$1.lambda$0(HttpServer.java:86)
  |   | at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:203)
  |   | at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:588)
  |   | at io.questdb.cutlass.http.HttpConnectionContext.consumeMultipart(HttpConnectionContext.java:380)
  |   | at io.questdb.cutlass.http.HttpConnectionContext.continueConsumeMultipart(HttpConnectionContext.java:412)
  |   | java.lang.NullPointerException: Cannot invoke "io.questdb.network.IODispatcher.disconnect(io.questdb.network.IOContext, int)" because "this.dispatcher" is null
  |   | 2023-04-08T00:16:14.184271Z C server-main unhandled error [job=io.questdb.cutlass.http.HttpServer$1@4f6f416f, ex=
  |   | 2023-04-08T00:16:14.184116Z I http-server disconnected [ip=255.255.255.255, fd=30, src=queue]
  |   | 2023-04-08T00:16:14.183182Z I http-server scheduling disconnect [fd=30, reason=14]
  |   | 2023-04-08T00:16:14.183061Z I i.q.c.h.HttpConnectionContext failed query result cannot be delivered. Kicked out [fd=30, error=not enough lines [table=my_table]]
  |   | 2023-04-08T00:16:14.182992Z I i.q.c.t.TextDelimiterScanner not enough lines [table=my_table]
  |   | 2023-04-08T00:16:14.182862Z I i.q.c.t.TextLoader configured [table=`my_table`, overwrite=false, durable=false, atomicity=2, partitionBy=YEAR, timestamp=ts, timestampFormat=null]
  |   | 2023-04-08T00:16:14.182586Z I http-server connected [ip=10.2.14.108, fd=30]
```

### Environment

```markdown
- **QuestDB version**: 7.0.1
- **OS**:
- **Browser**:
```

**Comment by rahul0x00** [comment]
The stack trace shows that the NPE occurred when the IO dispatcher was attempting to disconnect a client. The error also mentions that the "result cannot be delivered" because there were not enough lines in the table, indicating that the import failed.

Based on this information, it's likely that the NPE was caused by an issue with the HTTP connection context, possibly due to a misconfiguration or a problem with the way the connection was handled. 

#### Possible Steps to resolve this:
  
        1.Check the configuration: Verify that the CSV import configuration is correct.Make sure that the configuration matches the CSV file being imported.
 
        2.Check the CSV file: Verify that the CSV file being imported is valid and contains the expected data. Make sure that the file is not empty and that the column headers match the expected schema.

        3.Check the network connection: Verify that the HTTP connection is stable and that there are no issues with the network. Check the server logs to see if there are any network errors or timeouts.
   
If the above steps doesn't resolve it,there might be logic errors or null references that could be causing the NPE
