### ISSUE TITLE
SELECT with to_timezone and SAMPLE BY returns wrong result

### ISSUE THREAD

**Issue by tolap22** [questdb/questdb#3178]
### Describe the bug

If you use the sample database in demo.questdb.io and issue the following query:

`Select timestamp as time, avg(windSpeed) from weather
where timestamp between '2010-01-01 00:00' and '2010-01-01 03:00';`

you get 8 rows as result.

Now let's use the SAMPLE BY to get value every 30m:

`Select timestamp as time, avg(windSpeed)
from weather
where timestamp between '2010-01-01 00:00' and '2010-01-01 03:00' SAMPLE BY 30m FILL(NULL);`

you get 7 rows at times: 00:00, 00:30, 01:00, 01:30, 02:00, 02:30, 03:00

Now suppose we want to work in a different time zone (Rome which is +1 for instance), we issue the following modified query:

`Select to_timezone(timestamp, 'Europe/Rome') as time, avg(windSpeed)
from weather
where to_timezone(timestamp, 'Europe/Rome') between '2010-01-01 00:00' and '2010-01-01 03:00' SAMPLE BY 30m FILL(NULL);`

suddenly rows returned are 16 and the times are totally confusing: 01:00, 01:51, 02:36, 02:51, 01:00, 01:51 etc etc 

### To reproduce

1. go to demo.questdb.io
2. issue query `Select to_timezone(timestamp, 'Europe/Rome') as time, avg(windSpeed) from weather where to_timezone(timestamp, 'Europe/Rome') between '2010-01-01 00:00' and '2010-01-01 03:00' SAMPLE BY 30m FILL(NULL);`
3. result is not every 30m and result's rows count is wrong

### Expected Behavior

the result count should be the same as without the to_timezone and the results should be spaced every 30m and ordered by time.

### Environment

```markdown
- **QuestDB version**: 7.1
- **OS**: the one used in demo.questdb.io
- **Browser**: any browser probably (checked on Chrome Version 112.0.5615.50 (Official Build) (64-bit))
```

**Comment by bziobrowski** [comment]
Non-aggregate expressions in SAMPLE BY select list are treated as keys, so in  :
```sql
Select to_timezone(timestamp, 'Europe/Rome') as time, avg(windSpeed) from weather where to_timezone(timestamp, 'Europe/Rome') between '2010-01-01 00:00' and '2010-01-01 03:00' SAMPLE BY 30m FILL(NULL);
```
questdb returns results for each timestamp range AND distinct `to_timezone(timestamp, 'Europe/Rome')` result . 

Please have a look at "Local timezone output" on https://questdb.io/docs/reference/sql/sample-by/ :
```
SELECT to_timezone(ts, 'PST') ts, count
FROM (SELECT ts, count()
      FROM sensors SAMPLE BY 2h
      ALIGN TO CALENDAR TIME ZONE 'PST')
```
