### ISSUE TITLE
Backup database should store the table names registry and recover from it

### ISSUE THREAD

**Issue by marregui** [questdb/questdb#3179]
The `BACKUP DATABASE` command should also store tables.d which contains information required to rebuild the registry on restore.

The `BACKUP TABLE` commane should also store directory (and content) for table folder `txn_seq`.

**Comment by bluestreak01** [comment]
@ideoma does this mean that backup is broken for WAL tables ?

**Comment by marregui** [comment]
being addressed in https://github.com/questdb/questdb/pull/3183 

missing partition by WEEK, there seems to be a bug for calculating partition path.
