### ISSUE TITLE
Queries timing out with Rust's sqlx

### ISSUE THREAD

**Issue by badrbouslikhin** [questdb/questdb#3204]
### Describe the bug

When using Rust sqlx v0.6.2, I am able to connect to a QuestDB database but unable to perform any query. I get the `Error: PoolTimedOut` on the client's side and no explicit error on QuestDB's log.

### To reproduce

```rust
use sqlx::postgres::PgPoolOptions;

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    let pool = PgPoolOptions::new()
        .max_connections(1)
        .connect("postgres://admin:quest@myquestdb.com:8812/qdb")
        .await?;

    sqlx::query("SELECT 150");
    .execute(&pool)
    .await?;

    Ok(())
}
```

With the following dependencies:
```
[dependencies]
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres"] }
tokio = { version = "1", features = ["full"] }
```

### Expected Behavior

Get a row with an int of value 150.

### Environment

```markdown
- **QuestDB version**: 7.1.1 (self-hosted) running in Docker.
- **OS**: macOS 13.2.1 (22D68) on the client side.
- **Browser**: Firefox 112.0 (64-bit).
- **sqlx**: 0.6.2.
```

### Additional context

The issue has been [reproduced](https://questdb.slack.com/archives/C1NFJEER0/p1681734372002929?thread_ts=1681655792.172009&cid=C1NFJEER0) by @jerrinot.

**Comment by strongguy16** [comment]
use sqlx::postgres::PgPoolOptions;

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    let pool = PgPoolOptions::new()
        .max_connections(1)
        .connect("postgres://admin:quest@myquestdb.com:8812/qdb")
        .await?;

    sqlx::query("SELECT 150");
    .execute(&pool);
    .await?;

    Ok(())
}

**Comment by 2anesh** [comment]
- use sqlx::postgres::PgPoolOptions;

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    let pool = PgPoolOptions::new()
        .max_connections(0)
        .connect("postgres://admin:quest@myquestdb.com:8812/qdb")
        .await?;

    sqlx::query("SELECT 150");
    .execute(&Pool)
    .await?;

    Ok(())
}

**Comment by sonukumar00** [comment]
use sqlx::postgres::PgPoolOptions;

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
let pool = PgPoolOptions::new()
.max_connections(1)
.connect("postgres://admin:[quest@myquestdb.com](mailto:quest@myquestdb.com):8812/qdb")
.await?;

sqlx::query("SELECT 150");
.execute(&pool);
.await?;

Ok(())
}

**Comment by 2anesh** [comment]
Thank you
