### ISSUE TITLE
No information if a file being uploaded has been processed already

### ISSUE THREAD

**Issue by AbhishekTemgire** [questdb/questdb#3211]
### Describe the bug

If user tries to upload a file that has been already processed, the process fails (there is a REST /chk request to check the file before uploading), which is as intended, but no feedback is given in the UI.a

### To reproduce

Go to the Import page, a second icon in the navbar
Upload a CSV file.
Try uploading the same file again.

### Environment

```markdown
- **QuestDB version**: 7.0.1
- **OS**: Window 10
- **Browser**: all
```

**Comment by deep867** [comment]
can you assign this to me?

**Comment by ideoma** [comment]
Duplicate #3135
