### ISSUE TITLE
Hyperlinks should open in new tab instead of same Tab when we click on it .

### ISSUE THREAD

**Issue by KartikDhanai** [questdb/questdb#3214]
### Is your feature request related to a problem?

I experienced difficulty as when I do back sometimes all changes are not saved .

### Describe the solution you'd like.

Try to make this feature in website where every hyperlink open in new tab.

### Describe alternatives you've considered.

Try to make this feature in website where every hyperlink open in new tab.

**Comment by bluestreak01** [comment]
ok
