### ISSUE TITLE
Timezone Issue

### ISSUE THREAD

**Issue by Sohan064** [questdb/questdb#3218]
### Is your feature request related to a problem?

QuestDB currently does not support time zone conversions, which can cause issues when working with data across different time zones.

### Describe the solution you'd like.

The option is to store timestamps in the database as Unix timestamps (i.e. the number of seconds since January 1, 1970, UTC), which are timezone-independent. This can make it easier to work with timestamps across different time zones, as the Unix timestamp can be converted to the appropriate time zone when querying the data.

**Comment by bziobrowski** [comment]
This is incorrect, QuestDB does support  converting timestamps between time zones . 
Timestamp data type is stored as signed microsecond offset from unix epoch .
Please have a look at :
- https://questdb.io/docs/guides/working-with-timestamps-timezones/
- https://questdb.io/docs/reference/sql/datatypes/
