### ISSUE TITLE
Adding a link

### ISSUE THREAD

**Issue by vishwajeet5** [questdb/questdb#3225]
### Is your feature request related to a problem?

in readme.md there should be a link of account creation after this line
"✨ As a sign of our gratitude, we also send QuestDB swag to our contributors. [Claim your swag here.](https://questdb.io/community)"

### Describe the solution you'd like.

[account creation](https://slack.questdb.io/)

### Additional context.

[account creation](https://slack.questdb.io/)

**Comment by bluestreak01** [comment]
there is no need to join slack to get swag!

**Comment by vishwajeet5** [comment]
its needed 
because in website it asked to complete
the subscription work
