### ISSUE TITLE
Transactions discarded for WAL table when SeqTxn is higher than WriterTxn

### ISSUE THREAD

**Issue by vscvishal** [questdb/questdb#3234]
### Describe the bug

When using a WAL table in QuestDB, if the SeqTxn is higher than the WriterTxn, all transactions are being discarded. This issue occurs when a writer transaction is interrupted, for example due to a server crash, and then a new transaction is started with a higher SeqTxn.

### To reproduce

Create a WAL table in QuestDB with the following schema:
CREATE TABLE my_table (id INT, name STRING) TYPE 'wal'
Insert a few records into the table:
INSERT INTO my_table VALUES (1, 'John'), (2, 'Jane'), (3, 'Bob')
Crash the QuestDB server while a transaction is in progress
Start a new transaction with a higher SeqTxn than the previous transaction:
BEGIN TRANSACTION WITH SEQ_TXN=100
Insert a record into the table:
INSERT INTO my_table VALUES (4, 'Alice')
Commit the transaction:
COMMIT TRANSACTION

### Expected Behavior

The record with id=4 and name='Alice' should be added to the table and visible in subsequent queries.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

This issue does not occur with non-WAL tables.
The issue persists even after restarting the server.
This issue has been observed with both single-node and clustered configurations.

**Comment by bluestreak01** [comment]
`BEGIN TRANSACTION WITH SEQ_TXN=100` is not a supported SQL syntax
