### ISSUE TITLE
Queries timing out with Rust's sqlx

### ISSUE THREAD

**Issue by harsh94607** [questdb/questdb#3241]
### Describe the bug

When using Rust sqlx v0.6.2, I am able to connect to a QuestDB database but unable to perform any query. I get the Error: PoolTimedOut on the client's side and no explicit error on QuestDB's log.

### To reproduce

use sqlx::postgres::PgPoolOptions;

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    let pool = PgPoolOptions::new()
        .max_connections(1)
        .connect("postgres://admin:quest@myquestdb.com:8812/qdb")
        .await?;

    sqlx::query("SELECT 150");
    .execute(&pool)
    .await?;

    Ok(())
}

### Expected Behavior

Get a row with an int of value 150.

### Environment

```markdown
- **QuestDB version**: 7.1.1 (self-hosted) running in Docker.
- **OS**: macOS 13.2.1 (22D68) on the client side.
- **Browser**: Firefox 112.0 (64-bit).
- **sqlx**: 0.6.2.
```

**Comment by bluestreak01** [comment]
please do not create duplicate issues, clone copy of #3204
