### ISSUE TITLE
Queries timing out with Rusy's sqlx

### ISSUE THREAD

**Issue by VanshBhargava** [questdb/questdb#3264]
### Describe the bug

When using Rust sqlx v0.6.2, it seems that you are able to successfully establish a connection to a QuestDB database. However, when attempting to execute queries, you encounter an error message indicating "PoolTimedOut" on the client's side.

### To reproduce

use sqlx::postgres::PgPoolOptions;

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    let pool = PgPoolOptions::new()
        .max_connections(1)
        .connect("postgres://admin:quest@myquestdb.com:8812/qdb")
        .await?;

    sqlx::query("SELECT 150");
    .execute(&pool)
    .await?;

    Ok(())
}

### Expected Behavior

Get a row with an int of value 150.

### Environment

```markdown
- **QuestDB version**: 7.1.1 (self-hosted) running in Docker.
- **OS**: macOS 13.2.1 (22D68) on the client side.
- **Browser**: Firefox 112.0 (64-bit).
- **sqlx**: 0.6.2.
```

**Comment by bluestreak01** [comment]
spam
