### ISSUE TITLE
Adding Semantic Search Engine 

### ISSUE THREAD

**Issue by bhojrajnarwae** [questdb/questdb#3282]
### Is your feature request related to a problem?

It is difficult to search the exact query in the metadata if we consider the QuestDB as a metadata set. 

### Describe the solution you'd like.

If we can add the feature of  Semantic search In QuestDb by Integrating it with OpenAI text embeddings models and upserting the embeddings in QuestDB. It will be easy for the user to search for a particular query in the QuestDB dataset. 
Natural Language Full-Text Searches support in MySQL may help. But you need to have the columns against which you want to perform the search indexed as FULLTEXT, and your database engine must be MyISAM.

By following the query the semantic search can be done in QuestBD using natural language processing:
SELECT * FROM Question WHERE MATCH (QuestionContent) AGAINST ('+semantic +search' IN NATURAL LANGUAGE MODE);

**Comment by ideoma** [comment]
This is far fetched from where we are now.
