### ISSUE TITLE
Same UPDATE query does work in standard table but doesn't in WAL table

### ISSUE THREAD

**Issue by tolap22** [questdb/questdb#3296]
### Describe the bug

Following query:

"UPDATE table SET  metric_name = 'deleted' WHERE metric_name like  'Isl00001Lib0%';"

### To reproduce

1. execute UPDATE table SET  metric_name = 'deleted' WHERE metric_name like  'Isl00001Lib0%';
2. SELECT * from table WHERE metric_name LIKE 'Isl00001Lib0%';
3. the matching row has not changed

### Expected Behavior

the matching rows should be updated

### Environment

```markdown
- **QuestDB version**: 7.1.1
- **OS**: Linux
- **Browser**: Firefox
```

**Comment by bziobrowski** [comment]
Changes made to WAL tables (insert, update, ddl) are asynchronous so there could be a delay between when current command applies changes and when next command can see them . 
I'm working on an sql command that'd allow waiting until WAL is applied to target table .

**Comment by bziobrowski** [comment]
1 hours is too much. Normally it's maybe a few seconds . 

Could you run 
```sql
select * from wal_tables();
```
and check `suspended` column's value for the table ?

**Comment by tolap22** [comment]
all suspended columns are set to "false"

**Comment by ideoma** [comment]
Can you post the steps from creating a table to updating it? Ideally, CREATE, INSERT and then UPDATE statements so that we can reproduce it.

At least please post the CREATE statement if you cannot reproduce it from scratch.

**Comment by bziobrowski** [comment]
@tolap22  Could you share questdb logs  ?

**Comment by tolap22** [comment]
[wal_logs.txt](https://github.com/questdb/questdb/files/11398706/wal_logs.txt)

**Comment by bziobrowski** [comment]
Thanks, I can reproduce now .
