### ISSUE TITLE
 CASE breaks unless the optional ELSE is used

### ISSUE THREAD

**Issue by sonukumar00** [questdb/questdb#3300]
### Describe the bug

According to the docs, CASE can be used with or without an ELSE block. If no ELSE, null will be returned for unmatched conditions.

In practice, when you issue a CASE statement with no ELSE, QuestDB crashes.

### To reproduce

Go to any questdb installation, can be the demo site.

Do this (it will work)

WITH t as (
SELECT rnd_int(1,10,0) as i
  FROM long_sequence(15)
)
select i, 
CASE
  WHEN i % 2 = 0 THEN i
ELSE null  
END  
from t

### Expected Behavior

I would expect ELSE to be optional

### Environment

```markdown
- **QuestDB version**: 7.1.1
- **OS**: OSx and Linux
- **Browser**: Chrome
```

**Comment by bluestreak01** [comment]
really? :)
