### ISSUE TITLE
alter table should be safe to run anytime

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#3306]
### Describe the bug

![image](https://user-images.githubusercontent.com/7276403/236487453-c5aced27-4fd4-43f9-a79f-d3a2090437d3.png)

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by Shivam-Amin** [comment]
Is it a documentation error?
I'm new to this project, can you help to understand the issue?

**Comment by bluestreak01** [comment]
this is fixed, pending documentation update

@amyshwang could you remove the notice, this is fixed in 7.1.3
