### ISSUE TITLE
The data is inserted successfully but the number of queries remains the same

### ISSUE THREAD

**Issue by realjijk** [questdb/questdb#3309]
### Describe the bug

After inserting 600 million pieces of data into a table, if you insert a few more pieces of data, the insertion will be successful, but the number of rows in the table will not change. After restarting, the records will be restored, but the insertion will still be the same. i got some log:

2023-05-09T03:13:30.574777Z I i.q.c.TableUtils locked '/data/questdb-7.1.1-no-jre-bin/.questdb/db/readings~6/wal15.lock' [fd=138]
2023-05-09T03:13:30.579194Z I i.q.c.TableUtils locked '/data/questdb-7.1.1-no-jre-bin/.questdb/db/readings~6/wal15/0.lock' [fd=139]

### Environment

```markdown
- **QuestDB version**: questdb-7.1.1
- **OS**:Centos 8
- **Browser**: Chrome
```

**Comment by ideoma** [comment]
Inserts to WAL table are asynchronous. The data is queriable eventually but not immediately after the insert.

https://questdb.io/docs/concept/write-ahead-log/

To see the progress you can query `select * from wal_tables()`

https://questdb.io/docs/reference/function/meta/#wal_tables

The table is fully caught up when `writerTxn` equals `sequencerTxn`. If there are errors while applying the table will have `suspended` column set as `true`.

Please report if you can reproduce the table to be in `suspended` state or `writerTxn` never catches up with `sequencerTxn` (or at least for many minutes there are no changes in `writerTxn`)

**Comment by ideoma** [comment]
I am closing the issue until you provide more information if the table is `suspended` or errors in logs leading to progress to `writerTxn`

**Comment by realjijk** [comment]
Thanks a lot.
I found the table  reading **suspended**  by using "WAL_TABLE()" ,  checking the log found:
2023-04-25T08:24:07.327633Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=readings~6, error=bulk update failed and will be rolled back, errno=0]
what's the reason of suspending ?
