### ISSUE TITLE
Unexpected error when using `count()`

### ISSUE THREAD

**Issue by YuanchengJiang** [questdb/questdb#3313]
### Describe the bug

I got an unexpected error: `unbalanced (` when executing the following query:

```
select count(distinct column_name) from table_name;
```

Not sure whether it is supported in questdb but the error seems to be unexpected.

### To reproduce

```
select count(distinct event) from telemetry;
```

### Environment

```markdown
- **QuestDB version**: 7.1.1
- **OS**: ubuntu 20.04
- **Browser**:
```

**Comment by puzpuzpuz** [comment]
We have special `count_distinct` function to handle this case:
```sql
select count_distinct(column_name) from table_name;
```

**Comment by bluestreak01** [comment]
wonder if we can add expression rewrite? this is a common question
