### ISSUE TITLE
Table left locked after create as select timed out via REST

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#3318]
### Describe the bug

When using http endpoint to run SQL to create a table as select and query times out, the table remains locked.

### To reproduce

1. Open web console, run long query like

```SQL
CREATE TABLE readings AS  (
SELECT  rnd_long(0, 10000, 0) sensorId,
rnd_double() temp,
timestamp_sequence(to_timestamp('2019-10-17T00:00:00', 'yyyy-MM-ddTHH:mm:ss') ts
FROM long_sequence(1000000000L) 
) timestamp(ts) partition by MONTH
```

2. Let query time out after default 60s
3. Repeat the query

### Environment

```markdown
- **QuestDB version**: 7.1.1
```

**Comment by bluestreak01** [comment]
must be fixed already
