### ISSUE TITLE
`Null` in equality operator

### ISSUE THREAD

**Issue by YuanchengJiang** [questdb/questdb#3358]
### Describe the bug

I am not sure whether questdb follows the SQL standard, which defines the equality operator (=) compares values for equality and returns either true, false, or **NULL if one or both of the values being compared are NULL** 

The result of `select null=null` in questdb is `true`. Not sure if it is a bug or an intended feature.

**Comment by bziobrowski** [comment]
In QuestDB, null is a concrete value and comparison operators are binary, e.g. :

```sql
select null =  null
select null = cast(null as string)
select null = cast(null as symbol)
select null = cast(null as long)
```

return `true`, while 

```sql
select 1 =  null
select '1' = cast(null as string)
select cast('sym' as symbol) = cast(null as symbol)
select 1L = cast(null as long)
```

return `false`
