### ISSUE TITLE
Describe bug  in the code .

### ISSUE THREAD

**Issue by Madhuryabarche10** [questdb/questdb#3394]
### Is your feature request related to a problem?

Problem:
You are tasked with retrieving the total sales amount for each product from the "Sales" table. However, there seems to be a bug in the SQL query, and it's not producing the correct results. Identify and fix the bug in the query.

Table: Sales
+------------+---------+-------+
| Product_ID | Date | Sales |
+------------+---------+-------+
| 1 | 2023-01 | 100 |
| 2 | 2023-01 | 150 |
| 1 | 2023-02 | 200 |
| 2 | 2023-02 | 250 |
+------------+---------+-------+

code  with bug is given below-----

SELECT Product_ID, SUM(Sales) AS Total_Sales
FROM Sales
GROUP BY Product_ID
ORDER BY Date DESC;

**Comment by iam-roshanj** [comment]
Please assign me this problem.
