### ISSUE TITLE
Repeating chunk of lines in UI

### ISSUE THREAD

**Issue by lejmr** [questdb/questdb#3400]
### Describe the bug

When I do `select *`, it seems the result is cycling every approx 60lines. Interestingly when I do `select timestmap` this problem is not occurring. 

<img width="1959" alt="image" src="https://github.com/questdb/questdb/assets/337103/00f166fb-20fd-41c1-b20a-b6f8cb070724">
a few scrolls later:
<img width="1959" alt="image" src="https://github.com/questdb/questdb/assets/337103/a678e731-e10f-4fd1-a03c-99114798e742">

### Environment

```markdown
- **QuestDB version**: 7.1.2
- **OS**: Windows and Mac
- **Browser**: Chrome, Safari
```

**Comment by ideoma** [comment]
Thanks for reporting it.

The screenshot does not match to the bug you reporting, the query there is not  `select * ...` but a select of a single column. Also, I cannot spot a repeating pattern in the screenshot. 

Can you please highlight what is the problem on the screenshot?

**Comment by lejmr** [comment]
On the demo it can not be reproduced, but the unzomming leads to the same artifact.
