### ISSUE TITLE
extend the docker-entry script to allow passing additional JVM flags

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3401]
### Is your feature request related to a problem?

QuestDB [docker entry script](https://github.com/questdb/questdb/blob/7.1.3/core/docker-entrypoint.sh) keeps Java heap config default and relies on ergonomics. 

Users can pass arguments for the JVM, but this overwrites all default arguments. 
So I want to set e.g. `Xmx` then I also have to set the DATADIR and module path, logging config, etc. 

Example: `docker run questdb/questdb -Xmx5g -m io.questdb/io.questdb.ServerMain -d /var/lib/questdb`

### Describe the solution you'd like.

It would be nice to have a way to prepend additional JVM flags without having to explicitly include all the default arguments. So something like `docker run -e JVM_PREPEND="-Xmx5g" questdb/questdb` could work. 

### Additional context.

This could be also useful for enabling the verbose GC log and other JVM toggles. 
QuestDB is very conservative with Java heap allocations, so most of the time it's not needed. but it would be still nice to have some convenience for situations when it is needed.

**Comment by rajdeep-mondal-hub** [comment]
Hi, can you please assign me this issue? I would like to work on it.

**Comment by puzpuzpuz** [comment]
> Hi, can you please assign me this issue? I would like to work on it.

@rajdeep-mondal-hub done. Look forward to your contribution 👍

**Comment by rajdeep-mondal-hub** [comment]
> > Hi, can you please assign me this issue? I would like to work on it.
> 
> @rajdeep-mondal-hub done. Look forward to your contribution 👍

I have opened a PR. please kindly review and approve.

**Comment by puzpuzpuz** [comment]
@mariusgheorghies could you review the PR? https://github.com/questdb/questdb/pull/3403

**Comment by yifanstefanwang** [comment]
Hi @puzpuzpuz / @bluestreak01
I went ahead and worked on this since I haven't seen active contribution to this otherwise.
Could you assign this issue to me? And please review #3567.
Thank you!

**Comment by puzpuzpuz** [comment]
@yifanstefanwang sure thing. Thanks for picking up this issue!
