### ISSUE TITLE
Add support for geospatial datatypes

### ISSUE THREAD

**Issue by aahmed-se** [questdb/questdb#343]
Support primitives like

- Point
- LineString
- CircularString
- CompoundCurve
- Polygon
- CurvePolygon
- MultiPoint
- MultiLineString
- MultiPolygon

**Comment by igor-suhorukov** [comment]
[h2gis](https://github.com/orbisgis/h2gis) may be helpful to work with spatial data in java/QuestDB functions. It is open source and mature java implementation of geo functions

**Comment by bsmth** [comment]
I will close this issue for the time being - even though all of the requested types are not fully implemented, broadly speaking geospatial support has been added with the addition of `geohash` types as of 6.0.5 - https://questdb.io/blog/2021/09/13/release-6-0-5
