### ISSUE TITLE
Add an option to specify dir mode for detached partitions

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3456]
### Is your feature request related to a problem?

Currently, directories with detached partitions use the same dir mode as directories with live partition data. The mode is configurable via the `cairo.mkdir.mode` property. See the usage of the `mkDirMode` field and its origin here: https://github.com/questdb/questdb/blob/1a3b31f00aade4bd4645b5df319a06abfc4d86b8/core/src/main/java/io/questdb/cairo/TableWriter.java#L1032-L1053

It would be nice to be able to specify a different mode for detached directories similarly how you can use `cairo.sql.backup.mkdir.mode` to set the mode for backup directories.

**Comment by huuji** [comment]
hi, this looks interesting - i can give this a go but might need some guidance. Hope thats ok!

**Comment by marregui** [comment]
@hui-jie-lim go for it! completion will be rewarded with a T-Shirt

**Comment by debanjanc01** [comment]
Hi @marregui , Is this still open? I'd like to take it up in that case.

**Comment by hui-jie-lim** [comment]
go ahead then, I was planning on working on this but it will take me sometime. I think you might be able to complete it faster

**Comment by marregui** [comment]
@debanjanc01 by all means, thank you.
@hui-jie-lim sounds awesome, thank you!

**Comment by debanjanc01** [comment]
Hey @marregui , I've raised the PR [#3818 ](https://github.com/questdb/questdb/pull/3818) against this. Let me know what you think.
