### ISSUE TITLE
Import REST API endpoint requires maxUncommittedRows query parameter to be set to issue intermediate commits

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#3480]
### Describe the bug

https://github.com/questdb/questdb/blob/80034d5f1e6bc0c2fdec2bbd022482f27f93d846/core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java#L196-L200

Here, the `maxUncommittedRows` variable is `-1` by default and set to another value only if a query parameter with the same name is set. This may lead to OOM when importing a large CSV file.

To fix that, we should initialize the variable with table's `maxUncommittedRows` metadata or the default value.

### Environment

```markdown
- **QuestDB version**: 7.2
- **OS**:
- **Browser**:
```

**Comment by tanbirali** [comment]
```java
public void setMaxUncommittedRows(int maxUncommittedRows) {
        this.maxUncommittedRows = maxUncommittedRows;
    }
``` 
Does this function not do the above mentioned thing?
