### ISSUE TITLE
Add a login page using java

### ISSUE THREAD

**Issue by Zedoman** [questdb/questdb#3513]
### Is your feature request related to a problem?

Add a login page using java

### Describe the solution you'd like.

a login page using java servlet.

**Comment by Zedoman** [comment]
Will be using Java as backend and jsp css as front-end to make a login pg.

**Comment by nilerudra** [comment]
Do you want database connectivity as well, if yes please provide me the details of database.

**Comment by Zedoman** [comment]
Yes I want first I have to create if u say yes then I can sent the details.

**Comment by Zedoman** [comment]
so can i work on it?

**Comment by bziobrowski** [comment]
Http authentication and authorization are available in enterprise version only . 
Is community version you could protect web console with e.g. [nginx](https://questdb.io/blog/2022/08/05/setting-basic-auth-nginx/)
