### ISSUE TITLE
Support PG JDBC driver queries for  SHOW TABLES/COLUMNS ...

### ISSUE THREAD

**Issue by patrickSpaceSurfer** [questdb/questdb#354]
You should at least support query emitted by following methods of PG JDBC driver:
```
org.postgresql.jdbc.PgDatabaseMetaData#getTables
org.postgresql.jdbc.PgDatabaseMetaData#getColumns
org.postgresql.jdbc.PgDatabaseMetaData#getSchemas // may be you should return 'public' schema as QuestDB doesn't support schema
org.postgresql.jdbc.PgDatabaseMetaData#getCatalogs // and default catalog/database name
```
It will helps QuestDB to support plenty of existing JDBC / postgresql clients and tools.

Please also implement [pg_catalog.pg_description](https://www.postgresql.org/docs/current/catalog-pg-description.html) as it used under the hood in PgDatabaseMetaData queries. It is create foundation for https://github.com/questdb/questdb/issues/194

Please implement this feature in the same way as [H2Console](http://www.h2database.com/html/quickstart.html) works with db metadata

This code should help to check metadata support:
```
//mvn dependency: com.h2database:h2:1.4.200
DbContents dbContents = new DbContents();
dbContents.readContents(jdbcConnectionUrl, connection);
```

psql also should work with implemented metadata.

Also nice to have support of following clients:
https://en.wikipedia.org/wiki/SQuirreL_SQL_Client
https://www.jetbrains.com/help/idea/relational-databases.html
https://www.dbvis.com

Also please mind that exist more standard way to support DB metadata https://en.wikipedia.org/wiki/Information_schema (but it is optional feature):
`SELECT COLUMN_NAME, ORDINAL_POSITION, COLUMN_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?
`

See also: https://www.postgresql.org/docs/current/catalogs.html

_Originally posted by @igor-suhorukov in https://github.com/questdb/questdb/issues/293#issuecomment-629608970_

**Comment by bluestreak01** [comment]
show tables, e.g. \d is already on master
