### ISSUE TITLE
support influx line protocol via http endpoint

### ISSUE THREAD

**Issue by ttys3** [questdb/questdb#3543]
### Is your feature request related to a problem?

I do not know why questdb implemented the ILP protocol on tcp. not on http.

currently none of the questdb ILP client sdk is thread safe.

like https://github.com/questdb/go-questdb-client
or https://github.com/questdb/c-questdb-client

because it use a shared buffer  to send data via tcp steam to the server.

no concurrent call to the send method is alowed currently.

and if the connection is broken, it even can not auto connect

### Describe the solution you'd like.

implement the ILP via http endpoint. just like a influxdb 2.x  server.

so users can use exists influxdb client sdk to insert data.

the core team should spend time on core db engine dev. 
not invent a new protocol based on tcp but it currently works
not as better as the http version ILP like influxdb does.

on the other side,  use http is more stable and simpler. users can use exists influxdb client sdk, or even write their own.

### Describe alternatives you've considered.

improve the tcp protocol and make it more usable.

improve all client sdk and make it thread safe. 

### Additional context.

related issue:

https://github.com/questdb/go-questdb-client/pull/18#discussion_r1246229904

https://github.com/questdb/go-questdb-client/issues/9

https://github.com/questdb/go-questdb-client/issues/11

https://github.com/questdb/go-questdb-client/issues/10

https://github.com/questdb/c-questdb-client/blob/ad3776efb057d09a86a83e15c0f39ae40d75485b/doc/CONSIDERATIONS.md?plain=1#L5

**Comment by puzpuzpuz** [comment]
v3 ships HTTP sender, so Go client now supports ILP/HTTP.
