### ISSUE TITLE
Give Support Error when connecting DB with Django 

### ISSUE THREAD

**Issue by tabatabaei** [questdb/questdb#3550]
### Describe the bug

I want to connect  Django 4.3.2 to QuestDB 7.2 with using  psycopg2 (2.9.3 ) Driver and get blow error:

django/db/backends/base/base.py", line 214, in check_database_version_supported
    raise NotSupportedError(
django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.3).

I guess you PostgreSQL core of QuestDB should be upgraded

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
QuestDB version: 7.2
OS: mint 21.1
```

**Comment by bziobrowski** [comment]
QuestDB isn't a variant or extension of PostgreSQL so there's no "PostgreSQL core".
11.3 is arbitrary version returned by the implementation.

I think it should be possible to try things out with older version of Django.
