### ISSUE TITLE
Attempt to insert via /exp should return an error

### ISSUE THREAD

**Issue by davidgs** [questdb/questdb#359]
**Describe the bug**
If you attempt to run an `insert` against the `/exp` API endpoint, no data is inserted (because it's the wrong endpoint) but a `200: OK` status is still returned.

**To Reproduce**
1. Go to 'http://localhost:9000/exp?query='
3. Run this SQL 'insert into `dbName` (field1, field2, field3) values (1, 2, 3)'
4. returns `200:OK` but no data is inserted

**Expected behavior**
Some `400` error would be good.

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: [e.g. 4.2]

**Additional context**

Attempts to insert via the wrong endpoint should return an error.

**Comment by HeZean** [comment]
Yep, returning `400` is more reasonable and helps user to clearly find out something wrong happened.

For existing users, they may ignore this "feature?", but new users may find it easier to check the exceptions from the returning value.

If it's needed, I'd like to work on it 😄
