### ISSUE TITLE
How to implement the removal of adjacent data with the same coordinates when querying coordinate data within a certain time range

### ISSUE THREAD

**Issue by feipengcheng** [questdb/questdb#3598]
### Is your feature request related to a problem?

How to implement the removal of adjacent data with the same coordinates when querying coordinate data within a certain time range

**Comment by feipengcheng** [comment]
> Please share schema, query and explain what you want to do a bit more . Is it about deleting data or removing a part of query results ?

![QQ截图20230728090639](https://github.com/questdb/questdb/assets/31195280/86118c60-d438-48e7-9fed-5ec904a57011)

**Comment by feipengcheng** [comment]
how to write sql like  'select * from table where userId=721 and ts>'2023-07-05 00:00:00 and .......''

**Comment by bziobrowski** [comment]
You can remove logical duplicates with group by, e.g. 
```sql
select userId, lat, lon, ...
from table 
where userId=721 
    and ts>'2023-07-05 00:00:00 
    and ...
group by userId, lat, lon;
```

**Comment by feipengcheng** [comment]
> 

no no no ,If the userId, lat, lon is same, but not consecutive according with ‘order by ts’, it still needs to be preserved even if the userId, lat, lon is same

**Comment by feipengcheng** [comment]
> You can remove logical duplicates with group by, e.g.
> 
> ```sql
> select userId, lat, lon, ...
> from table 
> where userId=721 
>     and ts>'2023-07-05 00:00:00 
>     and ...
> group by userId, lat, lon;
> ```

In other words, it means that if a person remains stationary and generates GPS data, the duplicated data needs to be removed.

**Comment by bziobrowski** [comment]
If timestamps per userId are unique you could try the following :

```sql
create table tt (
  userId symbol, 
  lat double,
  lon double,
  ts timestamp
) timestamp(ts);

insert into tt values 
( 'A', 0,0, '2023-07-31T08:00:00.000000Z' ), 
( 'A', 0,0, '2023-07-31T09:00:00.000000Z' ), 
( 'A', 0,1, '2023-07-31T10:00:00.000000Z' ) ;
selecT * from tt ;

select current.*
from (select * from tt where ts > '2023-07-05 00:00:00' and userId='A') current 
lt join tt previous on current.userId = previous.userId
where current.lat != previous.lat or current.lon != previous.lon
order by current.ts;

userId	lat	lon	ts
A	0.0	0.0	2023-07-31T08:00:00.000000Z
A	0.0	1.0	2023-07-31T10:00:00.000000Z
```

**Comment by bziobrowski** [comment]
Please reopen if it doesn't solve your issue . 
By the way - [QuestDB slack channel](https://slack.questdb.io/) is a better place to ask this kind of questions.
