### ISSUE TITLE
Bug fix for NullPointerException when querying empty table

### ISSUE THREAD

**Issue by HammadNazir048** [questdb/questdb#3601]
### Describe the bug

QuestDB currently throws a NullPointerException when querying an empty table. This bug fix adds a check to ensure that the table is not empty before trying to query it.

### To reproduce

Create a new QuestDB instance.
Create an empty table.
Try to query the table.

### Expected Behavior

The query should succeed.

### Environment

```markdown
QuestDB version: 6.0.9
OS: Ubuntu 20.04
Browser: Firefox 93.0 (64-bit)
```

### Additional context

The bug was caused by a typo in the code that was used to query empty tables. The typo caused the code to try to access a column that did not exist. The fix for the bug was to correct the typo and add a check to ensure that the table is not empty before trying to query it.

**Comment by bziobrowski** [comment]
Please re-test on latest QuestDB version .

**Comment by bziobrowski** [comment]
This issue is not a "bug fix", mentions very old and unsupported version and can't be reproduced in latest version.
