### ISSUE TITLE
UI table explorer add button behaviour

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#366]
**Is your feature request related to a problem? Please describe.**
The new table explorer offers an add button to directly add table and column names to a query in the editor. However, when clicking, a comma is added to the left of the table or column name in question. Most of the time, this comma is unnecessary and results in the user having to manually deleting it.

**Describe the solution you'd like**
A simple solution would be not to add commas when clicking on the ADD button. Alternatively, the comma could be added depending on context. For example if either
- The word to the left of the cursor is a column name
- The word to the left of the cursor is in a list of keywords (for example this list would contain 'end' but not 'select' or 'where')
- The next non-blank character to the left of the cursor is a closing bracket `)`

In a similar way, context could be used to determine whether to add a `space` on either side of the recently added column/table name. If the cursor is right next to non-blank text, a space should be added, but not otherwise.

**Describe alternatives you've considered**
Right now I find it more practical to explore columns but type them manually.

**Additional context**
Here is the button in question
![table-explorer](https://user-images.githubusercontent.com/52114895/83921995-80ad2880-a777-11ea-8bc1-93b09a54e527.png)

This would add the following to the SQL query, regardless of context.
`, windGust`
However the comma may actually break the syntax. Therefore, clicking the add button should either add `windGust` to the query (no comma), or take the context into account to decide on whether a comma should be added or not.

**Comment by mpsq** [comment]
TODO:

- [x] clicking the add button will add object name to the query (no comma!)
- [ ] parse the current query to decide on whether a comma should be added or not
