### ISSUE TITLE
Bug when exporting CSV with escaped double quotes

### ISSUE THREAD

**Issue by javier** [questdb/questdb#3719]
### Describe the bug

I exported the contents of one table via `/exp` endpoint and was surprised to see I couldn't import it via the `/imp` endpoint. After debugging for a bit it seems the issue is when exporting data. Apparently when `\"` is found in a String column, the generated CSV is not valid. I tried parsing the exported file with the Python `csv` library and it got confused at exactly the same point where the QuestDB `/imp` endpoint was starting to get errors.

### To reproduce

I had some data ingested in a table, and on exporting I had a big file. I am attaching also the full file, but I isolated the first lines where the issue was happening doing a `head -n 1011` and the first occurrence of the problem is happening at the second to last line you can see on this reduced file [gitlog2.csv](https://github.com/questdb/questdb/files/12540923/gitlog2.csv) file.

I am importing doing this:

```
CREATE TABLE IF NOT EXISTS gitlog (
    committed_datetime TIMESTAMP,
    repo SYMBOL,
    author_name SYMBOL,
    summary STRING,
    size INT,
    insertions INT,
    deletions INT,
    lines INT,
    files INT
    ) timestamp (committed_datetime)
    PARTITION BY MONTH WAL
    DEDUP UPSERT KEYS(committed_datetime, repo, author_name);
```

And then loading the file via:

```
curl -F schema='[{"name":"committed_datetime", "type": "TIMESTAMP", "pattern": "yyyy-MM-ddTHH:mm:ss.SSSUUUZ"}]' -F data=@gitlog2.csv "http://localhost:9000/imp?timestamp=committed_datetime&name=gitlog&delimiter=,"
```

If I remove the offending `\"` from the file, it loads with no errors (and then in my much longer full export file [gitlog.csv](https://github.com/questdb/questdb/files/12540965/gitlog.csv) it breaks again in the next occurrence a few lines further away)

### Expected Behavior

A file I can export I should be able to import. Also, an exported file should have no problems when read using other tools, like Python `csv` libraries

### Environment

```markdown
- **QuestDB version**: 7.1.3
- **OS**: Mac
- **Browser**: not relevant
```

**Comment by jerrinot** [comment]
related to: https://github.com/questdb/questdb/issues/1716

**Comment by javier** [comment]
hey @jerrinot . I am not sure it is the same root cause. In my case it was the export that was producing an incorrect CSV. The resulting CSV was failing not on import, but also using 3rd party tools, so it seems the problem this time was on the `exp` endpoint. The original thread seems to imply the problem is on the `imp` endpoint? Maybe we do have issues on both sides?

**Comment by ZachsCoffee** [comment]
I can help to solve this bug. I found where the problem is in the code.
Also, the @javier has right about the escape isn't correct (escape with `\`), the [RFC](https://www.rfc-editor.org/rfc/rfc4180) for the CSV says that the correct way to escape a double quote is with another double quote. 

>    7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:
       "aaa","b""bb","ccc"
