### ISSUE TITLE
Explain in the JSON format produces trailing commas

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3720]
### Describe the bug

```sql
explain (format json) select * from long_sequence(1);
```
produces this output:
```json
  {
    "Plan": {
        "Node Type": "long_sequence",
        "count":  1",
    }
  }
```

JSON does not allow trailing commas. Chances are some(most?) parsers will tolerate it, but the [grammar](https://www.rfc-editor.org/rfc/rfc8259#section-5) does not allow it. (unlike Javascript) 

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by AbhishekTiwari23** [comment]
Hi, is this bug still open? I am looking for some good-first issues.
Thanks
