### ISSUE TITLE
Explain in the JSON format produces unmatched double-quotes 

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3721]
### Describe the bug

While creating https://github.com/questdb/questdb/issues/3720 I noticed that besides trailing commas there is another problem: unmatched double-quotes.

Reproducer:
```sql
explain (format json) select * from long_sequence(1);
```

Result:
```json
  {
    "Plan": {
        "Node Type": "long_sequence",
        "count":  1",
    }
  }
```

Notice how the count attribute does not have opening double-quotes. Chances are it's related to the attribute type. 

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by techrajdeep** [comment]
Hi @marregui ,Please let me know if this issue is still open

**Comment by hennyboiszz** [comment]
Going to be looking into this, 

my guess it that has something to do with the need to deal with the "always there timestamp" when it interacts with Dedup

**Comment by marregui** [comment]
hi it is open. There is a PR https://github.com/questdb/questdb/pull/3804 that solves a similar issue, so this one should be quite straightforward. 
I suppose @techrajdeep and @hennyboiszz could either work together in a single PR, or independently each on their own. Eitherway mergeable solutions get perks!

Thank you!!

**Comment by hennyboiszz** [comment]
> hi it is open. There is a PR #3804 that solves a similar issue, so this one should be quite straightforward. I suppose @techrajdeep and @hennyboiszz could either work together in a single PR, or independently each on their own. Eitherway mergeable solutions get perks!
> 
> Thank you!!

Saw that loooks solved, going to move onto another like dense _rank() or another analytical function.

also @hennessydylan is me just different device aswell

**Comment by biosfood** [comment]
#3804 just solved a related issue. There still are excessive double quotes after a numeric type if a string type has been inserted before it.

My PR #3756 should solve this issue when eventually merged
