### ISSUE TITLE
Bug with GROUP BY

### ISSUE THREAD

**Issue by ceyssens** [questdb/questdb#3750]
### Describe the bug

Queries with a GROUP BY statement do not behave as expected.

I have tested two cases with GROUP BY as describe in "To reproduce".

IMPORTANT!
This scenario works as expected in version 7.0.1, but started to fails from version 7.1 upwards.

### To reproduce

create table if not exists test(id uuid);
insert into test(id) select rnd_uuid4() from long_sequence(3);

-- the query returns the expected result on the first execution, but returns no records on subsequent executions
-- modifying the SQL string by adding a whitespace somewhere, returns the records again the first time and fails again
-- subsequent times
select  id
from    test
group by id
limit   10;

-----------------------

create table if not exists test(id int);
insert into test(id) select rnd_int() from long_sequence(3);

--- grouping on an integer field doesn't even return a result on the first execution
select  id
from    test
group by id;

### Expected Behavior

Receive the expected result every time

### Environment

```markdown
- **QuestDB version**: 7.3.2 (Docker)
- **OS**: Ubuntu 22.04.3 LTS in WSL2 on Windows 10 21H2
- **Browser**: Chrome Version 116.0.5845.188 (Official Build) (64-bit)
```

### Additional context

I suppose QuestDB computes a hash of the string representation of the SQL query and performs a cache lookup that returns an empty resultset while the data exists (at least in the table storage).

**Comment by ideoma** [comment]
Are you using postgres protocol to run the queries?

**Comment by ceyssens** [comment]
yes, I use postgres protocol
