### ISSUE TITLE
FILL keyword not filling for each interval of the SAMPLE BY

### ISSUE THREAD

**Issue by tolap22** [questdb/questdb#3764]
### Describe the bug

We have two charts representing the same phenomenon populated by two different queries, the results of the two queries need to have the same number of rows so that data in the two charts show as temporally aligned.
The dataset in the database however may have missing values so we started using the SAMPLE BY and the FILL keywords of QuestDB to create two separate results with the same number of columns.

The two queries are as follows:
```sql
SELECT to_timezone(`timestamp`, 'Europe/Rome') AS `timestamp`, `metric_name`, `val` AS `double_value` 
FROM 
( 
  SELECT `timestamp`, `metric_name`, avg(`double_value`) AS `val` 
  FROM 'trends_table' 
  WHERE (`metric_name` = 'State23') 
   AND `timestamp` BETWEEN '2023-09-20 06:00:00' AND '2023-09-20 08:00:00' 
  SAMPLE BY 1m FILL(0)
);
```

The above result however is not 120 rows (2 hours sampled each minute)!
We realized instead that the default behaviour of FILL is to add the missing rows in between the first existing value in the database and the last one: the minutes preceding and following the last value in the database are not filled, the above query in our case return 103 and 115 rows depending on when the first and last value are inserted in the database.

I don't know if it is a desired behaviour (in that case it's a very strange meaning for the FILL keyword) or if it is a bug.

Hope I've been clear enough

### To reproduce

Create following schema:

CREATE TABLE 'trends_table' (
  metric_name SYMBOL capacity 256 CACHE,
  double_value DOUBLE,
  quality LONG,
  timestamp TIMESTAMP
) timestamp (timestamp) PARTITION BY MONTH;

fill with random values the range '2023-09-20 06:00:00' and '2023-09-20 08:00:00' with the first value at 06:10:00 and the last value at 07:40:00 for example.

Run the following query:

SELECT to_timezone(`timestamp`, 'Europe/Rome') AS `timestamp`, `metric_name`, `val` AS `double_value` FROM ( SELECT `timestamp`, `metric_name`, avg(`double_value`) AS `val` FROM 'trends_table' WHERE (`metric_name` = 'State23') AND `timestamp` BETWEEN '2023-09-20 06:00:00' AND '2023-09-20 08:00:00' SAMPLE BY 1m FILL(0));

the result will not be 120 rows but a smaller number!

### Expected Behavior

The FILL keyword with a SAMPLE BY 1m should return 120 rows

### Environment

```markdown
- **QuestDB version**: 7.2.1
- **OS**: Linux
- **Browser**: Independent
```

**Comment by bziobrowski** [comment]
Please have a look at:
-  https://questdb.io/docs/reference/sql/sample-by/#sample-calculation and
- https://questdb.io/docs/reference/sql/sample-by/#align-to-calendar
SAMPLE BY FILL adds missing data between first and last designated timestamp interval only .

**Comment by Arrryyyy** [comment]
Can we have fill function in materizlied view, i tried using like this but it threw an error 

 ```
CREATE MATERIALIZED VIEW IF NOT EXISTS MV_REPLAY 
    WITH BASE positions 
    REFRESH EVERY 1m AS 

SELECT
        timestamp,
        id,
        type,
        FIRST(x) AS x,
        FIRST(y) AS y,
        FIRST(speed) AS speed,
        FIRST(heading) AS heading

    FROM positions
    SAMPLE BY 500T FILL(NULL)
```
