### ISSUE TITLE
ROW_NUMBER() is affected by WHERE clause outside of subquery

### ISSUE THREAD

**Issue by vladidobro** [questdb/questdb#3799]
### Describe the bug

ROW_NUMBER inside a subquery is affected by WHERE clause outside of subquery.

### To reproduce

`SELECT * FROM
    (SELECT *, ROW_NUMBER() OVER (PARTITION BY a ORDER BY b) r
    FROM 
        (SELECT 1 a, 2 b, 4 c UNION SELECT 1, 3, 5) o
    ) ra
WHERE ra.r=1
AND c=5`
results in a,b,c,r = 1,3,5,1.

Removing the 'AND c=5' line results in a,b,c,r = 1,2,4,1 correctly

### Expected Behavior

the same query in SQL Server results in 0 rows

### Environment

```markdown
- **QuestDB version**: 7.3.1
- **OS**:
- **Browser**: Brave 1.58.131

I tested it only in UI, the QuestDB is run in the cloud and I don't know the deployment details
```

**Comment by techrajdeep** [comment]
Hi @vladidobro @puzpuzpuz ,Please let me know if this issue is still open

**Comment by puzpuzpuz** [comment]
@techrajdeep yes, to the best of my knowledge, no one has started working on it.

**Comment by techrajdeep** [comment]
Thanks @puzpuzpuz , could you please assign it to me

**Comment by puzpuzpuz** [comment]
@techrajdeep done. Look forward to your upcoming contribution!
