### ISSUE TITLE
QuestDB container image should use ParallelOld GC

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3814]
### Describe the bug

Our [container image](https://github.com/questdb/questdb/blob/daa41aa8e493c7fd3259e5f292353775bceb037a/core/docker-entrypoint.sh#L50) does not set any GC and relies on defaults for both heap sizing and GC selection. Newer JDKs default to G1. This makes the image different from other distributions which explicitly set the [ParallelOld GC](https://github.com/jerrinot/questdb/blob/aff842735898757c22472b0a83b95bab6fba89f6/core/src/main/bin/questdb.sh#L181). 

We should make Docker images to use the ParallelOld too. For the sake of consistency and also the ParallelOld algo will likely result in higher throughput. 

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by debanjanc01** [comment]
Hey @jerrinot , adding the arg to the [entry point](https://github.com/questdb/questdb/blob/daa41aa8e493c7fd3259e5f292353775bceb037a/core/docker-entrypoint.sh#L50) should solve this. 

I've raised a PR for it.

**Comment by jerrinot** [comment]
fixed by #3819
many thanks to @debanjanc01!
