### ISSUE TITLE
Add Further Aggregate Functions

### ISSUE THREAD

**Issue by superichmann** [questdb/questdb#3826]
### Is your feature request related to a problem?

Hiii I saw you added some more agg functions, here are some more I would love to see

### Describe the solution you'd like.

covariance [COVAR_POP](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/COVAR_POP.html),[COVAR_SAMP](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/COVAR_SAMP.html)
correlation [CORR](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CORR.html),[CORR*](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CORR_A.html)

### Describe alternatives you've considered.

move to oracle ;) jk QDB FOREVER!

**Comment by superichmann** [comment]
Thanks so much for implementing this!

One maybe issue: Infinity or -Infinity values are treated as null values are not incorporated into the final score.

**Comment by superichmann** [comment]
Current workaround fix implementation prolongs the query time (multiple corr calls) from 3 seconds to 12 :|
only fix implementation I have found is
`POWER(corr(COALESCE(nullif(nullif((COLNAME)::string,'Infinity'),'-Infinity')::double,999999999999999.0),TARGETCOL),2)` 12 seconds
`POWER(corr(COLNAME,TARGETCOL),2)` 3 seconds

maybe we can do something? ;] @puzpuzpuz

**Comment by puzpuzpuz** [comment]
> One maybe issue: Infinity or -Infinity values are treated as null values are not incorporated into the final score.

@superichmann what would you suggest as the expected behavior for infinity values?

**Comment by superichmann** [comment]
@puzpuzpuz mmm I am not a math guy but maybe just set the infinite (999999999999999.0) or -infinite (-999999999999999.0) double value in the corr formula which will in turn affect the final corr result.

For me this would be the best ;]
