### ISSUE TITLE
Server hangs on SQL query with expression including many random function calls

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#3840]
### Describe the bug

Create the following python script (`random.py`):
```python
#!/usr/bin/env python3

import sys

N = int(sys.argv[1])


exp = ""
for i in range(N):
    exp += "(rnd_uuid4()::int) + "

exp += "1"

assert exp.count("(") == exp.count(")")
print(exp)
```

Run QDB and then this psql command:
```bash
PGPASSWORD=quest psql -h localhost -U admin -p 8812 qdb -c "select $(python3 ~/tmp/postgres/data/random.py 50) as x"
```

For smaller values of N the above command is fine. Yet, at some point the psql client and the server both cannot be ctrl-c-ed anymore and I have to `kill -9` the server process.

Reported by @eatonphil

### Environment

```markdown
- **QuestDB version**: 7.3.3
- **OS**:
- **Browser**:
```

**Comment by SsjRaz** [comment]
Hello! After looking over this, and trying to find different solutions, I realized that once I put a breakpoint in the Rnd.java folder on the "long l1 = s0" line. The program struggles to load when adding the 2nd random number only, while it runs within a few milliseconds on the first and every run after 2.

**Comment by puzpuzpuz** [comment]
@SsjRaz sorry, I'm not sure I understand your point. Could you elaborate on more details?
