### ISSUE TITLE
Confusing InfluxDB Table/Column Naming Restrictions

### ISSUE THREAD

**Issue by ConstableBrew** [questdb/questdb#3845]
### What would you like to add or change?

https://questdb.io/docs/reference/api/ilp/overview/#name-restrictions

The following section is inconsistent and confusing. 

```
Table and column names must not contain any of the forbidden characters:

,a,b,!,^,[,\n,\r,?,,,:,",',\,/,\\,\0,),(,+,-,*,~,.,$ and %.

Additionally, table name must not start or end with the . character. At any location, the column name must not contain . and -.
```

- The first character in the list appears to be... nothing?
- Are the characters "a" and "b" really forbidden?!
- We have used "[" (and "]") in column names without issue.
- Why the reiteration of the prohibition on "." and "-" at any location when the first sentence states that the column names must not contain those characters?

**Comment by puzpuzpuz** [comment]
Hello,

Thanks for reporting this issue. The docs indeed don't look correct. While we're fixing them, you may refer to our client docs for the correct list, e.g. Go client's docs: https://pkg.go.dev/github.com/questdb/go-questdb-client/v2#LineSender.Table

cc @goodroot

**Comment by ritikverma2000** [comment]
Hi @puzpuzpuz I would like to work on this issue can you pls assign this issue to me.

**Comment by puzpuzpuz** [comment]
@ritikverma2000 unfortunately we [had to make](https://questdb.io/blog/making-our-website-source-private/) our website's source code private recently, so only QuestDB team members will be able to pick up this one.

We plan to move docs source code back to open source in future, but it may take some time for this to happen.

**Comment by ritikverma2000** [comment]
Okay @puzpuzpuz np.

**Comment by goodroot** [comment]
Fixed! https://questdb.io/docs/reference/api/ilp/overview/#name-restrictions

Thanks for the report @ConstableBrew
