### ISSUE TITLE
JSON processor returns ddl:OK even for non DDL queries

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3858]
### Describe the bug

When you execute e.g. INSERT via the REST query interface then QuestDB server still returns `{"ddl":"OK"}` in the response body. That's unexpected, INSERT is not part of DDL. 

The culprit seems to be inside `JsonQueryProcessor` where [`sendConfirmation()`](https://github.com/questdb/questdb/blob/30cd2b204557517cb677009c2079c8db46484839/core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java#L367-L379) has the DDL:OK JSON hard-coded and/or is called from more places than it should. 

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by vss96** [comment]
Some of the Compiled Queries seem to have separate confirmation methods, so I was thinking of having something separate for insert like `sendInsertConfirmation`.

**Comment by jerrinot** [comment]
@vss96 yes, that makes sense

**Comment by siddharth0815** [comment]
Hi @jerrinot I have raised this PR: https://github.com/questdb/questdb/pull/4472
for the issue, kindly have a look

**Comment by siddharth0815** [comment]
@jerrinot gentle reminder to review the PR
