### ISSUE TITLE
Question about data design 

### ISSUE THREAD

**Issue by mehrdad2000** [questdb/questdb#3867]
Hi
Which design of table work faster in questdb?

name family age sex job height weight id1 id2 id3

or 

name family age sex job height weight Id1
name family age sex job height weight Id2
name family age sex job height weight Id3

Any idea?
Thanks

**Comment by jerrinot** [comment]
Hello @mehrdad2000, please next time use [StackOverflow](https://stackoverflow.com/questions/tagged/questdb) or [QuestDB slack](https://slack.questdb.io/) for asking question. 
GitHub issues are not meant to be a support forum. See the description of various channels at https://github.com/questdb/questdb/issues/new/choose

to answer you question: it depends. what are you trying to model? what are the Id1-id3 attributes? does every person(?) has all three attributes? if so then go for the first version.
