### ISSUE TITLE
Telegraf plugin for QuestDB Influx Line Protocol Authentication

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3868]
### Is your feature request related to a problem?

I'd like to feed data from Telegraf to QuestDB over ILP. This currently works only when ILP does not have any authentication configured.

I'd like to use the plugin together with ILP authentication. This likely requires a custom Telegraf plugin, it should not be too difficult to implement one.

**Comment by puzpuzpuz** [comment]
Considering that Telegraf is written in Go, this part of our Golang ILP client may be useful for contributors: https://github.com/questdb/go-questdb-client/blob/e8d780ab25694db95f0925ac84966b4472949f1d/sender.go#L168-L237

**Comment by jerrinot** [comment]
@puzpuzpuz I could not find a way to write an auth plugin for Telegraf. I see Telegraf output plugins tend to handle authentication on their own. At the same time, I don't think it makes sense to add QuestDB-specific authentication into a generic Telegraf Socket Write output plugin. Thus I think the best course of action is to contribute a QuestDB-specific output plugin to the Telegraf project. I could be either based on the current socket plugin with QuestDB auth slapped on. Or - better(?) - it could internally use our go client.

**Comment by puzpuzpuz** [comment]
A fork of the socket plugin makes sense to me. I don't think the plugin parses messages, so using the client would require doing that.

**Comment by jerrinot** [comment]
I sent a PR to Telegraf: https://github.com/influxdata/telegraf/pull/14158

**Comment by badrbouslikhin** [comment]
Hey @jerrinot, any news on the Telegraf PR? Appreciate any updates you can share. Thanks a lot!

**Comment by jerrinot** [comment]
hello @badrbouslikhin, we are trying something slightly different. It's not released yet, but here is a little teaser: If you start the latest QuestDB snapshot (either build it yourself from source or use the [nightly container image](https://hub.docker.com/layers/questdb/questdb/nightly/images/sha256-4d9bd6a5f81b85deb1885c52687149d7da62437e452002fec27c2ec4026e78f5?context=explore ) then it works with Telegraf InfluxDB plugin! Including authentication, proper error reporting etc.

**Comment by badrbouslikhin** [comment]
@jerrinot do you have a documentation on how to set the token and the bucket name?
Is it available for QuestDB CE?

**Comment by jerrinot** [comment]
https://questdb.io/docs/third-party-tools/telegraf/ now shows how to use the ILP over HTTP with Telegraf: https://questdb.io/docs/third-party-tools/telegraf/



Bucket name is irrelevant with QuestDB. For now, authentication works with QuestDB Cloud and QuestDB Enterprise only. We might add some basic form of auth to QuestDB Open Source too.
