### ISSUE TITLE
SQL syntax error reported as a critical error

### ISSUE THREAD

**Issue by eugenels** [questdb/questdb#3893]
### Describe the bug

2023-10-26T15:02:27.722568Z C i.q.c.h.p.JsonQueryProcessorState [224] error [msg=`Duplicate column [name=timestamp]`, errno=-100, q=`SELECT avg(column0), column1 timestamp FROM table 
  WHERE timestamp >= '2023-08-22T09:40:00.000000Z' AND timestamp <= '2023-08-22T09:45:00.000000Z' 
  AND column1 IN ('CODE')
  SAMPLE BY 15s FILL(PREV) ALIGN TO CALENDAR
`]

### To reproduce

```sql 
create table test as (select 'sym', 'str', x, 'a', timestamp_sequence('2023-07-20', 1000000) timestamp from long_sequence(200)) timestamp(timestamp);
select min(x), sym timestamp from test sample by 15s;
```
_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bziobrowski** [comment]
While maybe not entirely critical this isn't a syntax- but an error sql code generator that can't insert an internal timestamp column required by sample by.
