### ISSUE TITLE
QuestDB stops listening to ports after a short while

### ISSUE THREAD

**Issue by x-gnn** [questdb/questdb#3904]
### Describe the bug

I have problems running QuestDB on macOS installed with Homebrew. Everything seems fine but a few seconds after restart all QuestDB listening ports will be closed. There are no message in the log / stdout and the process keeps running.

The ports will be opened for listening after start:

```
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
java    10424  gnn   98u  IPv4 0x8fed7be36c0007dd      0t0  TCP *:9000 (LISTEN)
java    10424  gnn  102u  IPv4 0x8fed7be36bff719d      0t0  TCP *:8812 (LISTEN)
java    10424  gnn  104u  IPv4 0x8fed7be36a250b5d      0t0  TCP *:9009 (LISTEN)
```

But after a short while they will be closed magically without any message:

```
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
java    10424  gnn   98u  IPv4 0x8fed7be36c0007dd      0t0  TCP *:9000 (CLOSED)
java    10424  gnn  102u  IPv4 0x8fed7be36bff719d      0t0  TCP *:8812 (CLOSED)
java    10424  gnn  104u  IPv4 0x8fed7be36a250b5d      0t0  TCP *:9009 (CLOSED)
```

So no new connections are possible (e.g. web console). I have also tried to deactivate macOS integrated firewall but that makes no difference.

The curios thing is that the process seems to be running normal:
```
brew services info questdb
questdb (homebrew.mxcl.questdb)
Running: ✔
Loaded: ✔
Schedulable: ✘
User: gnn
PID: 11010
```

```
questdb status -d /usr/local/var/questdb -f

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                        www.questdb.io

PID: 11029
```

```
  UID   PID  PPID   C STIME   TTY           TIME CMD
  501 11029 11010   0 10:30am ??         0:23.50 /usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/bin/java -DQuestDB-Runtime-66535 -ea -Dnoebug -XX:ErrorFile=/usr/local/var/questdb/db/hs_err_pid+%p.log -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:+UseParallelGC -XX:-MaxFDLimit -p /usr/local/Cellar/questdb/7.3.3/libexec/questdb.jar -m io.questdb/io.questdb.ServerMain -d /usr/local/var/questdb -f -n
```

### To reproduce

1. Install QuestDB: `brew install questdb`
2. Start QuestDB: `brew services start questdb` (NOTE: Same if I start the QuestDB directly by `questdb start -d /usr/local/var/questdb -f`)
3. Watch open ports: `lsof -nP -i tcp:9000,9009,8812`

### Expected Behavior

QuestDB remains listening on ports 9000, 9009 and 8812 until stopped.

### Environment

```markdown
- **QuestDB version**: 7.3.3
- **OS**: macOS Ventura 13.6 (Intel Mac)
- **Browser**: Firefox 119.0 (64-Bit), Safari Version 17.0
```

### Additional context

[stdout-2023-11-01T10-30-20.txt](https://github.com/questdb/questdb/files/13225560/stdout-2023-11-01T10-30-20.txt)

**Comment by x-gnn** [comment]
Sure, here is it. Thanks for investigation.
[stdout-2023-11-01T11-49-42.txt](https://github.com/questdb/questdb/files/13226102/stdout-2023-11-01T11-49-42.txt)

**Comment by jerrinot** [comment]
Thanks for the experiment. I don't see anything suspicious i nthe lost. In the past we had some issues with tcp keep-alive on MacOS - the behaviur was the same as you are observing. It's a long shot, but let's try to disable in. 

In `questdb.sh` (on my system it's in `/opt/homebrew/opt/questdb/libexec/questdb.sh`) there is this part:
```    JAVA_OPTS="
    -D$QDB_PROCESS_LABEL
    -ea -Dnoebug
    -XX:ErrorFile=${QDB_ROOT}/db/hs_err_pid+%p.log
    -XX:+UnlockExperimentalVMOptions
    -XX:+AlwaysPreTouch
    -XX:+UseParallelGC
    "
```
You can disable TCP keep-alive by adding this property: `-Dquestdb.unsupported.tcp.keepalive.seconds=0` 
So please change the 3rd line to look look like this:
```
    JAVA_OPTS="
    -D$QDB_PROCESS_LABEL
    -ea -Dnoebug -Dquestdb.unsupported.tcp.keepalive.seconds=0
    -XX:ErrorFile=${QDB_ROOT}/db/hs_err_pid+%p.log
    -XX:+UnlockExperimentalVMOptions
    -XX:+AlwaysPreTouch
    -XX:+UseParallelGC
    "
```
And again, restart the server.

**Comment by ideoma** [comment]
Do you see ports being closed without any connections being made? There is a limit of connections per port, once the limit is reached the port is released from listening.

**Comment by x-gnn** [comment]
I have tried both: Without any and with one connection to the web console. Same behaviour for both. But what I observed is that an existing connection (reuse HTTP connection in the browser) still works after stop listening for port 9000 on server side. But after a short while it will be closed too. So the server seems to be running but does not accept any new connection.

**Comment by ideoma** [comment]
I saw this, this is a bug in the release. The fix will be released soon

https://github.com/questdb/questdb/pull/3830

Sorry for the experience. You can try the docker nightly build, it should be fixed there.

**Comment by x-gnn** [comment]
Seems the `-Dquestdb.unsupported.tcp.keepalive.seconds=0`solves the problem for now. Thanks @jerrinot.

**Comment by jerrinot** [comment]
@x-gnn thanks for reporting back! The fix is already included in the latest codebase and it'll be shipped in the next QuestDB release. I'm closing this issue for now.
