### ISSUE TITLE
SIGSEV maxInt_AVX2 with insert into <table> select max(id) + 1, ... from <table>

### ISSUE THREAD

**Issue by ChristianHeckl** [questdb/questdb#3905]
### Describe the bug

Hi there,

First of all, great work with QuestDB :+1:  I am really impressed with the performance.

Unfortunately, I encounter a (90%) reproducible SIGSEV when running the following algorithm in a tight loop with many entities. 
. I try to insert hierarchical entities with an emulation of an autoincrement id column. (Code abbreviated)

The crash happens repeatedly at entity counter 5120. When the crash does not happen, corrupted ids after 5120 are present in the table.

```python
import psycopg2

connection = psycopg2.connect(...)
cursor = connection.cursor()

def create_if_not_exists(cursor, entity):
    run = entity.parent
    while run and run.database_id is None:
        create_if_not_exists(run)    
        run = run.parent
    
    parent_id = entity.parent.database_id if run.parent else None

    while entity.database_id is None:
        cursor.execute("""select id from "table" where name = %s and parent_id = %s""", (entity.name, parent_id))
        exists = cursor.fetchone()
        if exists is None:
            cursor.execute("""insert into "table" (id, name, parent_id) select max(id) + 1, %s, %s  from "table" """, (entity.name, parent_id))
        else:
            entity.database_id = exists[0]
```

```
#  SIGSEGV (0xb) at pc=0x00007f8c787cdd80, pid=1, tid=45
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.7.7.1 (17.0.7+7) (build 17.0.7+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (17.0.7+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
# Problematic frame:
# C  [libquestdb4990927995383399878.so+0x75d80]  maxInt_AVX2(int*, long)+0x40
#
# Core dump will be written. Default location: /var/lib/questdb/core
#
# An error report file with more information is saved as:
# /var/lib/questdb/db/hs_err_pid+1.log
Compiled method (n/a)  174872 3842     n 0       io.questdb.std.Vect::maxInt (native)
 total in heap  [0x00007f8c9cc8e310,0x00007f8c9cc8e688] = 888
 relocation     [0x00007f8c9cc8e470,0x00007f8c9cc8e4a0] = 48
 main code      [0x00007f8c9cc8e4a0,0x00007f8c9cc8e680] = 480
 oops           [0x00007f8c9cc8e680,0x00007f8c9cc8e688] = 8
Compiled method (n/a)  174874 3842     n 0       io.questdb.std.Vect::maxInt (native)
 total in heap  [0x00007f8c9cc8e310,0x00007f8c9cc8e688] = 888
 relocation     [0x00007f8c9cc8e470,0x00007f8c9cc8e4a0] = 48
 main code      [0x00007f8c9cc8e4a0,0x00007f8c9cc8e680] = 480
 oops           [0x00007f8c9cc8e680,0x00007f8c9cc8e688] = 8
```

Let me know if you need anything else.

Best regards and keep up the good work,

Christian

### To reproduce

Run the above python code.

### Expected Behavior

Entites are written to the database with consecutive ids. No crash happens.

### Environment

```markdown
- **QuestDB version**:7.3.3
- **OS**: Ubuntu 22.04
- **Browser**: Firefox
- **Architecture**: linux/amd64 [AVX2,8, 64 bits, 12 processors]
```

### Additional context

[hs_err_pid+1.log](https://github.com/questdb/questdb/files/13226170/hs_err_pid%2B1.log)

**Comment by ideoma** [comment]
Thanks for reporting the bug. Can you please share the CREATE statement for the table?
Ideally if you can share the initial data to run the script from that would be great.

**Comment by ChristianHeckl** [comment]
```sql
CREATE TABLE buggy_table (
    id INT, # would really like to use SERIAL here
    name STRING,
    parent_id INT
)
```

To make the "max(id) + 1" emulation work, the table has a default entry (0, "unknown", NULL) inserted, because max(NULL) +1 == NULL.

Can't share the original data, but let me see, if I can anonymize it for you.

**Comment by ChristianHeckl** [comment]
[repro.zip](https://github.com/questdb/questdb/files/13237110/repro.zip)
Please find the repro case attached. Python 3.8 should do fine.

Let me know if you need anything else.
