### ISSUE TITLE
Add stddev_pop to documentation

### ISSUE THREAD

**Issue by MoellJ** [questdb/questdb#3911]
### What would you like to add or change?

https://questdb.io/docs/reference/function/aggregation describes some aggregation functions such as `stddev_samp`, but doesn't describe `stddev_pop`. This should be added to the documentation.

Maybe other aggregation functions are missing as well.

**Comment by goodroot** [comment]
This has been addressed.

Thanks for report @MoellJ !

https://questdb.io/docs/reference/function/aggregation/#stddev_pop
