### ISSUE TITLE
CREATE TABLE as SELECT and INSERT as SELECT with batching

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb#3931]
**Background**
The command `CREATE TABLE target AS (SELECT ... FROM source) TIMESTAMP(ts) PARTITION BY ...` copies all rows from the source table to the target table in a single commit.

When the target table is assigned a designated timestamp while the source table either lacks one or uses a different column, QuestDB sorts all rows in memory, posing a risk of OutOfMemory errors.

**Proposed Solution**
We should implement batching, committing after every X number of rows. Although batching would reduce atomicity, it would significantly lower the risk of OOM. I propose making it the default behavior: one could opt for the old behavior, but with full awareness of the implications.

The precise syntax remains to be determined.

**Alternative Implementation**
An alternative would be to use disk-spilling during the row sorting process. While this would preserve atomicity, it would likely be detrimental to performance and add complexity to both implementation and maintenance. I believe sacrificing some atomicity represents a better compromise for most scenarios.

**Risks**
1. Smaller batches might degrade performance due to increased occurrences of O3 partition merges.
2. Reduced atomicity is a breaking change and may break existing workflows.

**Similar Features**
The `INSERT FROM table` command already supports batching. For example: `INSERT BATCH 100 INTO tab2 SELECT * FROM tab`.

**Workaround**
As an interim solution until this feature is developed, one could:
1.  Establish the structure of the target table, for example: `CREATE TABLE tab2 AS (SELECT * FROM tab WHERE 1<>1) TIMESTAMP(ts) PARTITION BY year;`
2. Fill it using INSERT with batching, such as: `INSERT BATCH 10000 INTO tab2 SELECT * FROM tab;`

**Comment by puzpuzpuz** [comment]
The same issue is relevant for `INSERT INTO tab SELECT ...` - in case of a large result set, this may lead to huge amount of O3 memory being allocated leading to OOM kills. We should reconsider default behavior for INSERT too.

**Comment by jerrinot** [comment]
@puzpuzpuz INSERT INTO tab SELECT already supports batching: `INSERT BATCH 100 INTO tab2 SELECT * FROM tab` 
It's _just_ not default enabled by default. IMHO it should be. If that's what you are saying then +1 from me:)

**Comment by puzpuzpuz** [comment]
Yes, you're correct. The default behavior of INSERT should be batched. I think it makes sense to track and implement both changes in one go since they lead to the same OOM kill outcome.

**Comment by jerrinot** [comment]
resolved by https://github.com/questdb/questdb/pull/4287
