### ISSUE TITLE
Homebrew installation does not set WAL to be default table storage

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#3947]
### Describe the bug

QuestDB installed using homebrew and running locally with with a server.conf that does not set `cairo.wal.enabled.default` but when tables are created by default they do not show that WAL icon next to them but on this docs page: https://questdb.io/docs/concept/write-ahead-log/#enabling-wal-and-configurations

running QuestDB version 7.3.2

if I set the variable in the `server.conf` then it works (tables default to WAL)

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by Rajakavitha1** [comment]
Hi @ideoma . I install questdb on my Mac locally using homebrew and checked the server.conf file.
I notice that cairo.wal.enabled.default=true is already set.
<img width="1058" alt="Screenshot 2023-11-15 at 10 57 14 AM" src="https://github.com/questdb/questdb/assets/37059749/10be3d3d-4ad0-466f-be50-bcc32cc6971e">

**Comment by ideoma** [comment]
Ok, I think it was connected to the fact that it was not a clean installation but an update from an earlier version. I close this issue. Thanks for taking a look!
