### ISSUE TITLE
Upload csv when edit column to save, always "Column names must be unique"

### ISSUE THREAD

**Issue by sevenjay** [questdb/questdb#3966]
### Describe the bug

always happen in 7.3.4, back to 7.3.3 is fine.
![image](https://github.com/questdb/questdb/assets/1086156/8aae151e-a476-46b0-9751-eb6366f6aad8)

### Environment

```markdown
- **QuestDB version**: 7.3.4
- **OS**: Docker image
- **Browser**: chrome
```

**Comment by insmac** [comment]
Hey @sevenjay, thanks for spotting this one up. We'll look into it shortly.

**Comment by insmac** [comment]
@sevenjay We have identified a root cause for the issue and applied a fix - it will go out in the very next release.
