### ISSUE TITLE
Add JVM flags env var support to questdb.sh

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#3981]
### Is your feature request related to a problem?

It's not possible to set things like `-Xms` or `-Xmx` with `questdb.sh`. In Docker image, we support `JVM_PREPEND` env var for this purpose.

### Describe the solution you'd like.

Add env var for the JVM flags.

### Describe alternatives you've considered.

Modify `questdb.sh` manually.

**Comment by ksankeerth** [comment]
Hi @puzpuzpuz,

I'm new to QuestDB. I'll raise a PR for this.

Thanks,
Sankeerthan

**Comment by puzpuzpuz** [comment]
> Hi @puzpuzpuz,
> 
> I'm new to QuestDB. I'll raise a PR for this.
> 
> Thanks,
> Sankeerthan

Hello,

That would be awesome. 👍
