### ISSUE TITLE
`non-window function called in window context` error if `sum` is used as window function

### ISSUE THREAD

**Issue by rueschm** [questdb/questdb#4036]
### Describe the bug

i have a minimal working query which is:

```
 SELECT
    measure_date,
    avg(hs)
    OVER (
        ROWS BETWEEN 3 PRECEDING AND CURRENT ROW
    ) as a
FROM
    my_table
```

if I change the window function to `sum`

```
 SELECT
    measure_date,
    sum(hs)
    OVER (
        ROWS BETWEEN 3 PRECEDING AND CURRENT ROW
    ) as a
FROM
    my_table
```

i get the following error:  `non-window function called in window context`

The error is the same if executed from the web console or with pgwire.
The error is the same for tables with a designated timestamp or without.
WAL is disabled for the table

### To reproduce

I can not reproduce the error on the Quest Demo DB. A similar query e.g. on trades does work as expected.
So I am a bit lost what could cause this error....

### Environment

```markdown
- **QuestDB version**: 7.3.5
- **OS**: Ubuntu
- **Browser**: Chrome
- **HelmChart**: 0.38.0
```

### Additional context

happy to provide more information.

**Comment by bluestreak01** [comment]
hi @rueschm thank you for the attention to our project, really appreciated! `sum()` (cumulative sum) is impemented but yet to be released. Demo runs 7.3.6-SNAPSHOT. We should cut release on Fri, pls stay tuned :)
