### ISSUE TITLE
ILP over HTTP

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#4052]
New feature to support ILP (network protocol) over HTTP.

## Motivation

We would like to provide QuestDB server compatibility with the existing InfluxDB protocol drivers. User shoud be able to update URL to point their application to QuestDB instead of InfluxDB with zero code changes.

We aim to support the following driver features:
- authentication
- TLS
- reconnect and resend
- auto-deduplication based on tags (for tables created over ILP)
- feedback (errors and transaction acks)
- transaction boundary semantics

## Additional functionality

All QuestDB drivers will be able to support ILP over HTTP

- Python
- C
- C++
- Rust
- NodeJS
- Golang
- Kafka connector
- .NET

## Performance considerations

ILP over HTTP is about 10% slower over low-latency connections. Over high latency connections (100ms) performance of both TCP ILP and HTTP ILP degrades, although HTTP ILP degrades faster.

**Comment by amunra** [comment]
nit: At the moment transactions can't be supported as there's no way of doing these across tables.

A hack here would be to enforce only a single table per batch in the client and resolve the table transaction problem at the single table isolation level. This could even be transparent for auto-batching clients.

.. or we could just drop that goal and document that on a batch's error some rows may still be written.

**Comment by jerrinot** [comment]
fixed by https://github.com/questdb/questdb/pull/4034
