### ISSUE TITLE
WAL table is suspended when non-existent partition drop executed in 7.3.7

### ISSUE THREAD

**Issue by smyshliakov** [questdb/questdb#4060]
### Describe the bug

After upgrading from 7.3.5 to 7.3.7 questdb service stops to write records after making snapshot  

### Environment

```markdown
- **QuestDB version** 7.3.7:
- **OS** Almalinux 9:
- **Browser** Firefox:
```

**Comment by ideoma** [comment]
Thank you for submitting the issue. It would be very helpful if you could fill `To reproduce` part.

**Comment by smyshliakov** [comment]
Here is the script to make a snapshot:

# 
removeDate=$(date -d '2 month ago' '+%Y-%m-%d')
curl -G --data-urlencode "query=snapshot prepare" http://localhost:9000/exec
cp -r /opt/questdb/var /opt/questdb/backups
curl -G --data-urlencode "query=snapshot complete" http://localhost:9000/exec
tar zcf /opt/questdb/backups/${backupDate}.backup.tgz /opt/questdb/backups/*
mv /opt/questdb/backups/*.tgz /opt/backups/storeout
rm -R /opt/questdb/backups/*
#find /opt/questdb/backups/ -type f -mtime +1 -name '*.tgz' -execdir rm -- '{}' +
# remove old stat db records from success table older than 2 months
curl -G --data-urlencode "query=ALTER TABLE success_table DROP PARTITION where timestamp < to_timestamp('${removeDate}', 'yyyy-MM-dd')" http://localhost:9000/exec
# remove old stat db records from failed table older than 2 months
curl -G --data-urlencode "query=ALTER TABLE failed_table DROP PARTITION where timestamp < to_timestamp('${removeDate}', 'yyyy-MM-dd')" http://localhost:9000/exec

after it ran service stops to write records silently (no warn or error messages in logs )

**Comment by ideoma** [comment]
@smyshliakov thank you for the script.

Am I right to assume that during execution of this script, you write data to one of the tables and you do not see any more records when you select the data from the table? Or you writing starts after the script is already executed?

What interface do you use to write to the table? Is it ILP or HTTP REST or PgWire?

How long does it take to copy the data e.g. how much time is between `snapshot prepare` and `snapshot complete` commands?

**Comment by ideoma** [comment]
Thanks, I'll try to reproduce based on this description

**Comment by ideoma** [comment]
@smyshliakov 

I tried to reproduce it and couldn't. At every step of running the bash script the new records written were visible to the queries. I made a snapshot of 45GB and it took dozens of seconds to do the `cp` command.

The only theory of how it could happen I have is that at some point in copying the files the machine ran out of disk space and you could not write any more data. This can be especially true if the snapshot was copied to a separate FIle System and took quite a long time. Between `snapshot prepare` and `snapshot complete` QuestDB does not prune temporary files and overuses disk space so the disk QuestDB runs on could run out of space.

QuestDB log would be helpful to prove or deny this theory. 

Feel free to reopen the issue if you can provide more details.

**Comment by smyshliakov** [comment]
log file with my comments
[questdb_log.txt](https://github.com/questdb/questdb/files/13684163/questdb_log.txt)

**Comment by ideoma** [comment]
Very useful, I see the problem now

```
Dec 15 11:54:56 sim20.uptel.net questdb[341]: 2023-12-15T09:54:56.775424Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=success_table~5, error=error applying SQL to wal table [table=success_table, sql=ALTER TABLE success_table DROP PARTITION where timestamp < to_timestamp('2023-10-15', 'yyyy-MM-dd'), position=47, error=no partitions matched WHERE clause, errno=-1]
```

Indeed this is a breaking change in 7.3.7, dropping non-existent partition did not use to suspend the table

**Comment by ideoma** [comment]
@smyshliakov 

BTW, I found this in your logs

```
2023-12-15T09:50:54.115756Z A server-main fs.file-max limit is too low [limit=4096] (SYSTEM COULD BE UNSTABLE)
2023-12-15T09:50:54.117340Z A server-main vm.max_map_count limit is too low [limit=65530] (SYSTEM COULD BE UNSTABLE)
```

This is an ask for a trouble, please follow guide to extend open file limit

https://questdb.io/docs/deployment/capacity-planning/#os-configuration
