### ISSUE TITLE
nullif not working on double

### ISSUE THREAD

**Issue by superichmann** [questdb/questdb#4062]
### Describe the bug

on demo:
```
SELECT timestamp,
       nullif(amount, 0) as amount_null_if_zero
FROM trades
```

code was taken from [official documentation](https://questdb.io/docs/reference/function/conditional/#nullif)

I guess documentation meant int column but it would be nice if it will also work on double ;]

**Comment by ssharaev** [comment]
Hi, @puzpuzpuz ! I have opened a PR, could you review it?
