### ISSUE TITLE
Questdb not supporting designated timestamp below 1970 

### ISSUE THREAD

**Issue by YassaFareed-SAI** [questdb/questdb#4075]
### To reproduce

When I am creating a table (using another table) by casting the date to designated timestamp field, with designated timestamp column with dates less than 1970:

`CREATE TABLE IF NOT EXISTS gdp AS (SELECT CAST(uuid as UUID) AS id,to_timestamp(date, 'yyyy-MM-dd') AS ts,value,CAST(country as SYMBOL) as country FROM "gdp.csv") timestamp(ts) PARTITION by YEAR DEDUP UPSERT KEYS(ts,country);`

 it gives this error:

`2023-12-19T16:06:50.476662Z E i.q.g.SqlCompilerImpl could not create table [error=
io.questdb.cairo.CairoException: [-1] timestamp before 1970-01-01 is not allowed]`

When I did it again after removing the dates below 1970s, it worked fine!

The [changelog](https://py-questdb-client.readthedocs.io/en/stable/changelog.html#id3) shows that this problem was fixed, but seems like it is not reflected to [docker release](https://github.com/questdb/questdb/releases) 

### QuestDB version:

7.3.7

### OS, in case of Docker specify Docker and the Host OS:

questdb/questdb:7.3.7 ,Ubuntu 22.04.3 LTS

### File System, in case of Docker specify Host File System:

-

### Full Name:

Yassa Fareed

### Affiliation:

Surmount

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by ideoma** [comment]
That's a known limitation, yes QuestDB does not support designated timestamps before the epoch at the moment.

**Comment by YassaFareed-SAI** [comment]
@ideoma Thanks for your response!
I came over this [changelog](https://py-questdb-client.readthedocs.io/en/stable/changelog.html#id3). Is it expected that docker will also get this fix sooner or later?

**Comment by ideoma** [comment]
That changelog is correct, you can now send timestamps before 1970 using the Python client, BUT and it's a big but, QuestDB does not QuestDB does not support timestamps before the epoch in DESIGNATED timestamp column.

So if you have a table with 2 timestamp columns, designated and non-designated you can write values before epoch to non-designated.

See more about designated timestamp in the docs

https://questdb.io/docs/concept/designated-timestamp/

**Comment by YassaFareed-SAI** [comment]
Alright!
Thanks for your help!

**Comment by YassaFareed-SAI** [comment]
closing the issue
