### ISSUE TITLE
 questdb cannot submit transactions synchronously

### ISSUE THREAD

**Issue by bodilove** [questdb/questdb#4076]
### To reproduce

Version is 7.3.3
 The questdb cannot submit transactions synchronously。
how can i solve？

![image](https://github.com/questdb/questdb/assets/26559417/d0a2f67d-912e-4615-85ce-09ae37124fb8)

### QuestDB version:

7.3.3

### OS, in case of Docker specify Docker and the Host OS:

Windows server2019

### File System, in case of Docker specify Host File System:

Windows server2019

### Full Name:

lhb

### Affiliation:

lhb

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

![image](https://github.com/questdb/questdb/assets/26559417/2aa15136-31ed-4538-8b2f-977efc355563)

**Comment by ideoma** [comment]
https://questdb.io/docs/concept/write-ahead-log/#comparison
