### ISSUE TITLE
integer_overflow in binary_search

### ISSUE THREAD

**Issue by pompeiifreckles** [questdb/questdb#4087]
### To reproduce

[`const int64_t mid = (low + high) / 2;`](https://github.com/questdb/questdb/blob/fc23804602485c75bf70f1b247aba8d0d4f0ac65/core/src/main/c/share/util.h#L154) potentially introduces integer overflow.
Write `low + (high - low) / 2` to fix the issue.
Check out [here](https://blog.research.google/2006/06/extra-extra-read-all-about-it-nearly.html) for all possible solutions to this problem

### QuestDB version:

master

### OS, in case of Docker specify Docker and the Host OS:

all

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Siddharth Bhardwaj

### Affiliation:

Dalhousie

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [ ] Yes, I have

**Comment by jerrinot** [comment]
hi @pompeiifreckles, thanks for reporting the issue! 
fancy sending a fix PR? the code already computes `high - low` in each iteration, I guess that could be also be used for overflow-free mid-point finding.

**Comment by pompeiifreckles** [comment]
Sure, would love to send a fix. Can you assign me this issue?

**Comment by jerrinot** [comment]
excellent. the issue is yours!

**Comment by pompeiifreckles** [comment]
hey @jerrinot, the build failed on windows. How do I check out the reason for its failure. I tried building it on my Mac locally and it was built without any issues.

**Comment by pompeiifreckles** [comment]
Hi @jerrinot , I made a PR. Can you take a look.
