### ISSUE TITLE
Support IS NULL and IS NOT NULL operators for string and binary columns in JIT compiler

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#4143]
### Is your feature request related to a problem?

As simple as it sounds. Currently if you write `WHERE str_col IS NOT NULL`, filter won't be JIT compiled as we don't support string columns in JIT compiler. We should add partial string and binary column support (null checks) to the compiler as it's a popular type of filter.

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

**Comment by bluestreak01** [comment]
as a context, `int_col = 10` will go thru JIT path and `str_col is not null` will not. The NULL string is stored as two columns:
1. length prefixed array of utf-16 chars
