### ISSUE TITLE
Suspended WAL: cannot resolve WAL table last partition

### ISSUE THREAD

**Issue by jbsgh** [questdb/questdb#4149]
### To reproduce

QuestDB suspends a table on import:
`2024-01-22T11:16:52.477401Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=mytable~5, error=system error, cannot resolve WAL table last partition [path=/root/.questdb/db/mytable~5], errno=0]`

Steps to reproduce:

Remove /root/.questdb/ with exception of conf/. See modified server.con in section "additional context"
Start QuestDB

Create table:
```
drop table 'mytable';
CREATE TABLE IF NOT EXISTS "mytable" ( time TIMESTAMP ) timestamp (time) PARTITION BY DAY WAL DEDUP UPSERT KEYS( time );
```

Import data as ILP: `./mync0.sh` (see section "additional context")

Squash partitions and prepare next import
```
ALTER TABLE "mytable" SQUASH PARTITIONS;CREATE TABLE IF NOT EXISTS "mytable" ( time TIMESTAMP ) timestamp (time) PARTITION BY DAY WAL DEDUP UPSERT KEYS( time );
```
Import data as ILP: `./mync1.sh` (same as mync1.sh; using another data file)

Check logfile for error message.

The issue seems to be timing related. Calling just nc without a loop with delay does not trigger the error.
The issue is not related to the filesystem. I've tried ext4 and ZFS with compression enabled.

### QuestDB version:

7.3.9

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 22.04

### File System, in case of Docker specify Host File System:

ext4, ZFS with LZ4

### Full Name:

Jan Bartels

### Affiliation:

Siempelkamp

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

netcat a file with delay: ([scripts.tar.gz](https://github.com/questdb/questdb/files/14009451/scripts.tar.gz))
```
$ cat mync0.sh 
#!/bin/bash
while read -r line ; do 
  echo "$line"
  sleep 0.001
done < "mytable.0.data.txt" | nc -q 0 127.0.0.1 9009
```
I'll provide you with a download link for the data files via slack. The tgz file is about 90 MiB.

Altered configuration:
```
root@tuxi:~/.questdb/conf# diff server.conf server.conf~
545d544
< line.tcp.msg.buffer.size=524288

```

Log: [questdb.log.tar.gz](https://github.com/questdb/questdb/files/14009368/questdb.log.tar.gz)
See line 7491 for message:
`2024-01-22T11:16:52.477401Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=mytable~5, error=system error, cannot resolve WAL table last partition [path=/root/.questdb/db/mytable~5], errno=0]`

**Comment by bluestreak01** [comment]
hi Jan, thank you for the bug report! ZFS is not officially supported system (ZFS itself has issues we need to work around of) but we will run your reproducer on EXT4 asap.

**Comment by jbsgh** [comment]
I'm aware of that fact. Originally, I've tested on ZFS and re-tested it on ext4 for this GH issue.

**Comment by javier** [comment]
> I'm aware of that fact. Originally, I've tested on ZFS and re-tested it on ext4 for this GH issue.

Just a quick comment that if you do need ZFS, we do support it on QuestDB Enterprise, where we had to develop some specific integrations to workaround some issues that could potentially corrupt data
