### ISSUE TITLE
Query intermittently returns null

### ISSUE THREAD

**Issue by Roh-codeur** [questdb/questdb#4159]
### To reproduce

I have a table with cols: ticker, date, ohlcv. if I run the below query, occasionally, it returns nulls for min(date). if I run the query again, it returns valid values, and maybe null again at a later stage. please note, I am updating the table in another process.

`SELECT ticker, min(date), max(date) from mkt_ohlcv order by 1`

### QuestDB version:

7.3.9

### OS, in case of Docker specify Docker and the Host OS:

Mac

### File System, in case of Docker specify Host File System:

Mac

### Full Name:

Roh Codeur

### Affiliation:

personal

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by puzpuzpuz** [comment]
Could you also share table schema? Also, understanding what you were doing when "updating the table in another process" in more detail would help a lot.

**Comment by Roh-codeur** [comment]
sure. I have a process that downloads bulk data from a data provider and updates this table. 

```
CREATE TABLE mkt_ohlcv
(
    date        TIMESTAMP,
    marketState SYMBOL CAPACITY 10,
    isDarkPool  boolean,
    ticker      SYMBOL CAPACITY 10000,
    tickerType  SYMBOL CAPACITY 50,
    exchange    SYMBOL CAPACITY 50,
    dataSource  SYMBOL CAPACITY 50,
    barInterval SYMBOL CAPACITY 10,
    open double,
    high double,
    low double,
    close double,
    adjustedClose double,
    volume double,
    barCount    int,
    timestamp   TIMESTAMP
) TIMESTAMP(date)
PARTITION BY MONTH WAL
DEDUP UPSERT KEYS(date, ticker, tickerType, exchange, dataSource, barInterval);

```

**Comment by puzpuzpuz** [comment]
@Roh-codeur thanks. Would it be possible to share the table with us? If it's a big one or the data is sensitive, we might be fine with a copy of the table with `ticker` + `date` columns only.

**Comment by Roh-codeur** [comment]
yeah sure, I can send you the ticker + date columns. attach to this issue?

**Comment by puzpuzpuz** [comment]
If the file is small enough, yes, that would be great.

**Comment by Roh-codeur** [comment]
sorry, forgot to upload data earlier. Please see attached. I upgraded to the latest version this morning, issue persists
[questdb-query-1711362934847.csv](https://github.com/questdb/questdb/files/14742231/questdb-query-1711362934847.csv)

**Comment by puzpuzpuz** [comment]
@Roh-codeur I'm able to reproduce the issue. As a workaround, could you try rewriting the query as the following: `SELECT upper(ticker), min(date), max(date) from mkt_ohlcv order by 1;` and see if you still get those `null`s? In this form, the query will use a different execution plan and should work correctly.
