### ISSUE TITLE
qdb not automatically sort by timestamp

### ISSUE THREAD

**Issue by superichmann** [questdb/questdb#4196]
### To reproduce

go to demo
`select time,count from pos`
see results

### QuestDB version:

7.3.9

### OS, in case of Docker specify Docker and the Host OS:

.

### File System, in case of Docker specify Host File System:

.

### Full Name:

.

### Affiliation:

.

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by puzpuzpuz** [comment]
Your query is an implicit GROUP BY query. These queries don't assume any order unless specified explicitly in ORDER BY clause.

**Comment by superichmann** [comment]
oh ok, before 7.3.9 it was automatic.
