### ISSUE TITLE
errno=12 on `SELECT max(open_time)...`

### ISSUE THREAD

**Issue by Niqnil** [questdb/questdb#4303]
### To reproduce

I am running QuestDB on minikube on development laptop.
I was trying to verify data after ingesting and got this error in web console: `could not mmap [size=28800, offset=0, fd=261855, memUsed=7301204960, fileLen=28800] SELECT max(open_time) FROM 'binance_1s_ohlcv-btc_usdt'`

Query over a smaller range e.g. `SELECT max(open_time) FROM 'binance_1s_ohlcv-btc_usdt' WHERE open_time >= '2024-01-01' AND open_time < '2025-01-01';` worked.

Is there anything I can do to make `SELECT max(open_time) FROM 'binance_1s_ohlcv-btc_usdt';` work?

```
~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"

~$ cat /proc/sys/vm/max_map_count
262144

~$ ulimit -Sn
1048576

~$ ulimit -Hn
1048576
```

Logs:
```
# top part removed
2024-03-19T07:40:02.128177Z I i.q.c.TableReader open partition /var/lib/questdb/db/binance_1s_ohlcv-btc_usdt~10/2020-08-11T19.1283 [rowCount=3600, partitionNameTxn=1283, transientRowCount=3600, partitionIndex=26175, partitionCount=57500]
2024-03-19T07:40:02.129410Z C i.q.c.h.p.JsonQueryProcessorState [24] error [msg=`could not mmap  [size=28800, offset=0, fd=261855, memUsed=7301204960, fileLen=28800]`, errno=12, q=`SELECT max(open_time) FROM 'binance_1s_ohlcv-btc_usdt'`]
2024-03-19T07:40:02.129524Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=24, lastRequestBytesSent=381, nCompletedRequests=1, totalBytesSent=0]
```

### QuestDB version:

7.3.8b

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 22.04.4

### File System, in case of Docker specify Host File System:

overlay (Docker container)

### Full Name:

Niq Lin

### Affiliation:

NA

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by bluestreak01** [comment]
Might be this: https://questdb.io/docs/deployment/capacity-planning/#max-virtual-memory-areas-limit

There is also this: https://github.com/questdb/questdb/releases/tag/7.3.10

**Comment by Niqnil** [comment]
Thank you! It worked after setting `vm.max_map_count=1048576`. 

By the way, the helm chart is still version 7.3.8b.
```
~$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "questdb" chart repository
...Successfully got an update from the "timescale" chart repository
Update Complete. ⎈Happy Helming!⎈

~$ helm upgrade my-questdb questdb/questdb
Release "my-questdb" has been upgraded. Happy Helming!
NAME: my-questdb
LAST DEPLOYED: Tue Mar 19 18:51:31 2024
NAMESPACE: default
STATUS: deployed
REVISION: 3
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=questdb,app.kubernetes.io/instance=my-questdb" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:9000 to use your application"
  kubectl --namespace default port-forward $POD_NAME 9000:9000

~$ helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
my-questdb      default         3               2024-03-19 18:51:31.595149863 +0800 +08 deployed        questdb-0.39.0  7.3.8b     

~$ helm search repo questdb
NAME            CHART VERSION   APP VERSION     DESCRIPTION                       
questdb/questdb 0.39.0          7.3.8b          Run QuestDB on Kubernetes via Helm
```

**Comment by bluestreak01** [comment]
we will update helm at the next release! thank you for reporting the issue!
