### ISSUE TITLE
COPY command giving error

### ISSUE THREAD

**Issue by delusion8399** [questdb/questdb#4305]
### To reproduce

1. Run copy command using for import schema 
`COPY weather from 'test_file.csv' WITH HEADER true;`
2. Copy schema and partition it by day/hour
3. COPY weather FROM 'test_file.csv' WITH HEADER true TIMESTAMP 'timestamp' FORMAT 'yyyy-MM-ddTHH:mm:ss.SSSUUUZ';
4. Getting below error
![image](https://github.com/questdb/questdb/assets/38590876/2bc487d9-f34b-4d96-ae8c-6b2641c85915)

### QuestDB version:

7.3.9

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 22.04 (docker)

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Shahid

### Affiliation:

Independent

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by ideoma** [comment]
This looks like a lack of kernel support of IO URING. 
What is your Linux kernel version?

**Comment by delusion8399** [comment]
6.2.0-1018-aws

**Comment by delusion8399** [comment]
For anyone having this issue, kindly set docker seccomp:unconfined then run the copy command.
Thanks
