### ISSUE TITLE
Prevent creating huge WAL commits

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#4312]
### Is your feature request related to a problem?

Huge commits (the data size exceeds available RAM) can be written to WAL files but then crash instances with OOM errors in the Table Writer.

### Describe the solution you'd like.

It is better to have a limit of a maximum number of lines allowed to commit in 1 go to WAL so that the commit fails and it propagates to the user rather than crashing the QuestDB instance later on.

There should be a hard limit introduced in configuration (lines and total memory) and committing more lines than this limit should fail with a descriptive error message.

### Describe alternatives you've considered.

Optimise Table Writer to work with commits that don't fit RSS. This is the following step since it needs more engineering time.

### Full Name:

Alex Pelagenko

### Affiliation:

QuestDB

**Comment by siddharth0815** [comment]
@ideoma `processWalBlock()`  function of `TableWriter` expects two params
`rowLo` and `rowHi`, which are row limits for segment being committed, do we need to explore this area and impose some restrictions on rows being committed? need some advice to proceed

**Comment by ideoma** [comment]
This issue is largely solved now after introducing default batching in the insert as select statements. I'm closing it, I apologise I should reviewed it earlier
