### ISSUE TITLE
Inserting data into Questdb has encountered an exception.

### ISSUE THREAD

**Issue by mdaml** [questdb/questdb#4320]
### To reproduce

During the development of a .NET WinForms application, we utilized SqlSugar to interact with the Questdb database. However, we encountered issues with data insertion failures.
The specific description of the problem is as follows:
1.The return value is 1, indicating that the data insertion was successful, but the inserted data cannot be found when querying the database.
2.There are multiple tables in the database, and not all tables are experiencing issues with data insertion; other tables can be inserted normally.
3.Restarting the computer and restarting the QuestDB service cannot solve this problem.
4.Export the data from the table with the insertion exception, delete the table, create a new table, import the data again, and now the table should be able to insert data normally.
Due to the above-mentioned issues, I have lost a significant amount of crucial data. I seek assistance in identifying the root cause of this problem and finding a solution to prevent it from happening again.

### QuestDB version:

7.1.3

### OS, in case of Docker specify Docker and the Host OS:

。

### File System, in case of Docker specify Host File System:

。

### Full Name:

Sun

### Affiliation:

sbt

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by Jhuwievdcsvsklajscwhsusizyzyjd** [comment]
I have this solution I am attaching a file read that

**Comment by ideoma** [comment]
Please upgrade to latest version
