### ISSUE TITLE
Apple Signing Cert

### ISSUE THREAD

**Issue by davidgs** [questdb/questdb#433]
**Is your feature request related to a problem? Please describe.**
Pre-packaged Binary requires a long series of authorizations because it is not digitally signed by Apple

**Describe the solution you'd like**
Application Signing Cert from Apple. 
**Describe alternatives you've considered**
None.
**Additional context**

**Comment by bluestreak01** [comment]
on OSX we should be using "brew" install, which gets around these issues. One outcome is perhaps not to include OSX binary into next release
