### ISSUE TITLE
The "sum 1 billion doubles" result on the front page can be incorrect.

### ISSUE THREAD

**Issue by alexey-milovidov** [questdb/questdb#436]
I have installed QuestDB on my machine to reproduce the claimed results.

I have:
AMD Ryzen 9 3950X 16-Core Processor
64 GiB RAM

QuestDB is installed as the following:
```
$ wget https://github.com/questdb/questdb/releases/download/5.0.0/questdb-5.0.0-bin.tar.gz
$ tar xf questdb-5.0.0-bin.tar.gz
$ sudo apt install openjdk-14-jre
$ export JAVA_HOME=/usr/lib/jvm/java-14-openjdk-amd64

./questdb.sh start

Exception in thread "main" io.questdb.network.NetworkError: [98] could not bind socket
        at io.questdb@5.0.0/io.questdb.std.ThreadLocal.initialValue(ThreadLocal.java:36)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at io.questdb@5.0.0/io.questdb.network.NetworkError.instance(NetworkError.java:46)
        at io.questdb@5.0.0/io.questdb.network.AbstractIODispatcher.<init>(AbstractIODispatcher.java:96)
        at io.questdb@5.0.0/io.questdb.network.IODispatcherLinux.<init>(IODispatcherLinux.java:36)
        at io.questdb@5.0.0/io.questdb.network.IODispatchers.create(IODispatchers.java:41)
        at io.questdb@5.0.0/io.questdb.cutlass.http.HttpServer.<init>(HttpServer.java:72)
        at io.questdb@5.0.0/io.questdb.cutlass.http.HttpServer.create0(HttpServer.java:148)
        at io.questdb@5.0.0/io.questdb.WorkerPoolAwareConfiguration.create(WorkerPoolAwareConfiguration.java:60)
        at io.questdb@5.0.0/io.questdb.cutlass.http.HttpServer.create(HttpServer.java:110)
        at io.questdb@5.0.0/io.questdb.ServerMain.main(ServerMain.java:145)
        
The exception message is not quite handy.

$ questdb status
questdb: command not found

The example in documentation looks wrong.

$ ./questdb.sh status

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                        www.questdb.io

Not running

The link "with the HTTP API" on the web page https://questdb.io/docs/guideBinaries goes to psql.

Looks like it is using the same port as ClickHouse, so it cannot work with default configuration.

http://localhost:9000/

SELECT 1;
-- does not work

SELECT 1 FROM dual;
-- does not work

create table zz as (select rnd_double() d from long_sequence(1000000000));
select sum(d) from zz;
-- when I copy-paste both commands to the web UI, it shows me

[16:47:58] select sum(d) from zztable does not exist [name=zz]

If I execute these commands one by one, it's Ok.

Table creation is quite slow (about ten seconds), but still Ok.

select sum(d) from zz;

Ok, sustained query time after a few runs is about 282 ms.
```

The sustained query time is about 282 ms.

I'm trying to reproduce the same with ClickHouse (master, clang release build):

```
SET max_memory_usage = '20G'
CREATE TABLE zz (x Float64) ENGINE = Memory;
INSERT INTO zz SELECT number FROM numbers_mt(1000000000)
(3.8 seconds)

SELECT sum(x) FROM zz
0.241 sec.
```

The sustained query time is about 240 ms.

Actually there is no much difference and ClickHouse gives slightly better results.
(Or I did not follow the installation steps of QuestDB correctly?)

If I reduce the number of threads to 4 to align with the results from
https://questdb.io/blog/2020/04/02/using-simd-to-aggregate-billions-of-rows-per-second
ClickHouse gives 232 ms (even slightly better).

The "sum int" is executed in 0.121 (ClickHouse) vs. 0.135 (QuestDB, results on AMD Ryzen 3900X from your blog article).
Again, no much difference and ClickHouse is slightly better.

I suspect that the results for ClickHouse in "sum double" benchmark were improved after https://github.com/ClickHouse/ClickHouse/pull/10992

PS. Thank you for the benchmark and for the great product!

**Comment by bluestreak01** [comment]
thank you for the feedback ;)  how many cores does QuestDB use in this test and how many cores does ClickHouse use?

**Comment by bluestreak01** [comment]
UI probably need a bit of an explanation. It runs query under cursor or "selected" query if something is highlighted with mouse cursor.

**Comment by bluestreak01** [comment]
sorry, i should have said that by default QuestDB uses 2 cores for everything. There is setting in server.conf:

```
shared.worker.count=8
```

**Comment by alexey-milovidov** [comment]
Yes, looks like it is using two cores by default.

I checked with the following command:
```
for i in {1..100}; do time curl 'http://localhost:9000/exec?limit=0%2C1000&count=true&src=con&query=select%20sum(d)%20from%20zz%3B&timings=true'; done
```
looking at the `top` in another terminal.

When I set
```
SET max_threads = 2
```
in ClickHouse,

it executes the same query in 0.270 sec.

It is slightly more close to the results of QuestDB.

**Comment by bluestreak01** [comment]
It is possible that code is the same or similar. Is your column nullable by chance. QuestDB sum() skips nulls and will produce null if all values are null.

**Comment by bluestreak01** [comment]
I swear it wasn't intentional but we bind the same socket by default. We only find out when we run clickhouse on the same box as questdb :)

**Comment by alexey-milovidov** [comment]
It is not nullable.
If I change type to nullable:
```
CREATE TABLE zz (x Float64 NULL) ENGINE = Memory;
```

The query execution time changes to 0.271 ms. (basically does not change at all)

**Comment by alexey-milovidov** [comment]
> I swear it wasn't intentional but we bind the same socket by default. We only find out when we run clickhouse on the same box as questdb :)

No problem, the 9000 port is quite popular :)

**Comment by alexey-milovidov** [comment]
Is there any chance the diagram on the front page will be updated to reflect actual results?

**Comment by bluestreak01** [comment]
Of course. The front page reflects performance on c5.metal, with 6 memory channels, rather than 2 on Ryzen. Do you have a new figure for c5.metal?

**Comment by TheTanc** [comment]
We used `MEMORY` because it's the fastest but QuestDB is reading and writing from disk. How would mergetree affect query time for CH?

**Comment by bluestreak01** [comment]
oh,

```sql
SELECT 1
```

works as of 5.0.1. We removed requirement for `FROM` clause.

We also don't have `DUAL`, we have `long_sequence(nRows)` instead

**Comment by alexey-milovidov** [comment]
@TheTanc

If you use MergeTree instead of Memory, the performance is the same (260 ms) but only if you enable uncompressed cache and make sure the thresholds to use uncompressed cache are set correctly.

Like this:
```
clickhouse-benchmark --use_uncompressed_cache 1 --merge_tree_max_rows_to_use_cache 10000000000 --merge_tree_max_bytes_to_use_cache 10000000000000 <<< "SELECT sum(x) FROM zz_mergetree"
```

If you don't enable uncompressed cache, it will slow down to 800 ms due to:
- decompression of data (QuestDB does not support any kind of compresssion);
- checksumming of data (QuestDB does not support checksums?).

**Comment by alexey-milovidov** [comment]
> Do you have a new figure for c5.metal?

I can get access to c5.metal in a few days.

**Comment by alexey-milovidov** [comment]
I have reproduced the results on fresh AWS c5.metal instance.

ClickHouse, version 20.7-testing, default settings:

```
$ clickhouse-client
SET max_memory_usage = '20G';
CREATE TABLE zz (x Nullable(Float64)) ENGINE = Memory;
INSERT INTO zz SELECT number FROM numbers(1000000000);
```

```
$ ./clickhouse benchmark --max_threads 16 <<< "SELECT sum(x) FROM zz"

localhost:9000, queries 2642, QPS: 10.683, RPS: 10682532832.639, MiB/s: 91688.915, result RPS: 10.683, result MiB/s: 0.000.

0.000%          0.076 sec.
10.000%         0.087 sec.
20.000%         0.087 sec.
30.000%         0.088 sec.
40.000%         0.089 sec.
50.000%         0.090 sec.
60.000%         0.093 sec.
70.000%         0.096 sec.
80.000%         0.101 sec.
90.000%         0.105 sec.
95.000%         0.110 sec.
99.000%         0.117 sec.
99.900%         0.122 sec.
99.990%         0.125 sec.
```

The query from frontpage runs in 0.076 sec.

QuestDB:

```
wget https://github.com/questdb/questdb/releases/download/5.0.1/questdb-5.0.1-no-jre-bin.tar.gz
tar xf questdb-5.0.1-no-jre-bin.tar.gz
```

I have to tune default config to change the number of threads from 2 to 16:
```
mcedit ~/.questdb/conf/server.conf
```

```
cd questdb-5.0.1/
./questdb.sh start
```

Create table:
```
time curl 'http://localhost:9000/exec?limit=0%2C1000&count=true&src=con&query=create+table+zz+as+(select+rnd_double()+d+from+long_sequence(1000000000));&timings=true'
```

Run benchmark:
```
for i in {1..1000}; do curl -w '\n%{time_total}\n' 'http://localhost:9000/exec?limit=0%2C1000&count=true&src=con&query=select%20sum(d)%20from%20zz%3B&timings=true'; done
```

(full log attached: [questdb.txt](https://github.com/questdb/questdb/files/4939695/questdb.txt))

We will have two numbers in each invocation:
- server reported time;
- total query processing time with HTTP request and response;

Total time is about 4 ms more than server reported time.

```
$ grep -o -P '^[\d\.]+' questdb.txt | clickhouse-local --structure 'time Float64' --query 'SELECT arrayJoin(quantilesExact(0, .1, .2, .3, .4, .5, .6, .7, .8, .9, .95, .99, .999)(time)) FROM table'
0.078424
0.093347
0.094877
0.095892
0.097019
0.098006
0.099042
0.100059
0.101063
0.102538
0.103845
0.106836
0.109378
```

```
$ grep -o -P '"execute":\d+' questdb.txt | grep -o -P '\d+' | clickhouse-local --structure 'time UInt64' --query 'SELECT arrayJoin(quantilesExact(0, .1, .2, .3, .4, .5, .6, .7, .8, .9, .95, .99, .999)(time / 1000000)) FROM table'
73.94769
88.845119
90.375894
91.419498
92.49556
93.48852
94.541029
95.549761
96.579194
98.054075
99.31027
102.337189
104.852336
```

Results are the following:
- query processing time for QuestDB is almost the same as for ClickHouse;
- minimal server reported time is slightly better (74ms vs 76ms) for QuestDB;
- if you take client-server interaction into account (that is reasonable), the minimal query processing time for QuestDB will be 78ms that is worse than for ClickHouse;
- median query processing time for ClickHouse is better than for QuestDB (90ms vs 93/98ms).

It does not matter whether the data type is nullable or not. Also it does not matter whether we use simple `sum` or `sumKahan`.

We may assume that performance is bounded by memory bandwidth. But actually we scan just about 100 GB/sec, but according to the STREAM benchmark, the server is capable of about 160 GB/sec.

**Comment by bluestreak01** [comment]
Thank you Alexey, this is interesting! c5.metal has two 24-core CPUs. To make result more consistent in our own benchmark we set thread affinity on all 16 threads to make sure data does not have to travel between NUMA zones.

To set affinity on QuestDB:

```
shared.worker.affinity=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
```

That said, we are working on new version of our website, which does not feaure comparison to ClickHouse anymore:

https://v2.questdb.io/

**Comment by dybxin** [comment]
> I have reproduced the results on fresh AWS c5.metal instance.
> 
> ClickHouse, version 20.7-testing, default settings:
> 
> ```
> $ clickhouse-client
> SET max_memory_usage = '20G';
> CREATE TABLE zz (x Nullable(Float64)) ENGINE = Memory;
> INSERT INTO zz SELECT number FROM numbers(1000000000);
> ```
> 
> ```
> $ ./clickhouse benchmark --max_threads 16 <<< "SELECT sum(x) FROM zz"
> 
> localhost:9000, queries 2642, QPS: 10.683, RPS: 10682532832.639, MiB/s: 91688.915, result RPS: 10.683, result MiB/s: 0.000.
> 
> 0.000%          0.076 sec.
> 10.000%         0.087 sec.
> 20.000%         0.087 sec.
> 30.000%         0.088 sec.
> 40.000%         0.089 sec.
> 50.000%         0.090 sec.
> 60.000%         0.093 sec.
> 70.000%         0.096 sec.
> 80.000%         0.101 sec.
> 90.000%         0.105 sec.
> 95.000%         0.110 sec.
> 99.000%         0.117 sec.
> 99.900%         0.122 sec.
> 99.990%         0.125 sec.
> ```
> 
> The query from frontpage runs in 0.076 sec.
> 
> QuestDB:
> 
> ```
> wget https://github.com/questdb/questdb/releases/download/5.0.1/questdb-5.0.1-no-jre-bin.tar.gz
> tar xf questdb-5.0.1-no-jre-bin.tar.gz
> ```
> 
> I have to tune default config to change the number of threads from 2 to 16:
> 
> ```
> mcedit ~/.questdb/conf/server.conf
> ```
> 
> ```
> cd questdb-5.0.1/
> ./questdb.sh start
> ```
> 
> Create table:
> 
> ```
> time curl 'http://localhost:9000/exec?limit=0%2C1000&count=true&src=con&query=create+table+zz+as+(select+rnd_double()+d+from+long_sequence(1000000000));&timings=true'
> ```
> 
> Run benchmark:
> 
> ```
> for i in {1..1000}; do curl -w '\n%{time_total}\n' 'http://localhost:9000/exec?limit=0%2C1000&count=true&src=con&query=select%20sum(d)%20from%20zz%3B&timings=true'; done
> ```
> 
> (full log attached: [questdb.txt](https://github.com/questdb/questdb/files/4939695/questdb.txt))
> 
> We will have two numbers in each invocation:
> 
> * server reported time;
> * total query processing time with HTTP request and response;
> 
> Total time is about 4 ms more than server reported time.
> 
> ```
> $ grep -o -P '^[\d\.]+' questdb.txt | clickhouse-local --structure 'time Float64' --query 'SELECT arrayJoin(quantilesExact(0, .1, .2, .3, .4, .5, .6, .7, .8, .9, .95, .99, .999)(time)) FROM table'
> 0.078424
> 0.093347
> 0.094877
> 0.095892
> 0.097019
> 0.098006
> 0.099042
> 0.100059
> 0.101063
> 0.102538
> 0.103845
> 0.106836
> 0.109378
> ```
> 
> ```
> $ grep -o -P '"execute":\d+' questdb.txt | grep -o -P '\d+' | clickhouse-local --structure 'time UInt64' --query 'SELECT arrayJoin(quantilesExact(0, .1, .2, .3, .4, .5, .6, .7, .8, .9, .95, .99, .999)(time / 1000000)) FROM table'
> 73.94769
> 88.845119
> 90.375894
> 91.419498
> 92.49556
> 93.48852
> 94.541029
> 95.549761
> 96.579194
> 98.054075
> 99.31027
> 102.337189
> 104.852336
> ```
> 
> Results are the following:
> 
> * query processing time for QuestDB is almost the same as for ClickHouse;
> * minimal server reported time is slightly better (74ms vs 76ms) for QuestDB;
> * if you take client-server interaction into account (that is reasonable), the minimal query processing time for QuestDB will be 78ms that is worse than for ClickHouse;
> * median query processing time for ClickHouse is better than for QuestDB (90ms vs 93/98ms).
> 
> It does not matter whether the data type is nullable or not. Also it does not matter whether we use simple `sum` or `sumKahan`.
> 
> We may assume that performance is bounded by memory bandwidth. But actually we scan just about 100 GB/sec, but according to the STREAM benchmark, the server is capable of about 160 GB/sec (if you use default STREAM benchmark, you have to edit the sources and increase array size 100 times to get proper results).

@bluestreak01 @alexey-milovidov what testing tools you used?

**Comment by dybxin** [comment]
what testing tools you used ?
![Screenshot from 2020-09-15 13-18-49](https://user-images.githubusercontent.com/14888437/93168669-061c7d80-f756-11ea-93cd-5e3707e73a3f.png)
