### ISSUE TITLE
修改之后查询报错

### ISSUE THREAD

**Issue by ztengjiao** [questdb/questdb#4393]
### To reproduce

1:使用update语句修改数据
2:修改完成只有使用 select 语句 查询数据 会出现错误org.postgresql.util.PSQLException: ERROR: Invalid column size [column=/mnt/sdc/.questdb/db/qyskhrcy_discern_division/default/operator.i.1002, size=0]

### QuestDB version:

7.1.1

### OS, in case of Docker specify Docker and the Host OS:

CentOS Linux release 7.9.2009 (Core)

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

ztj

### Affiliation:

1315930794@qq.com

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [ ] Yes, I have

### Additional context

or
![1712818910430](https://github.com/questdb/questdb/assets/70182351/0e1b2005-c8cc-4719-968c-70568c3dea25)
![1712818910430](https://github.com/questdb/questdb/assets/70182351/37416fea-d0e5-47b2-99f0-0a2ea8301c91)
g.postgresql.util.PSQLException: ERROR: Invalid column size [column=/mnt/sdc/.questdb/db/qyskhrcy_discern_division/default/operator.i.1002, size=0]
最大打开文件数量已经设置为10w，最大虚拟内存区域限制没有没有调整

**Comment by bluestreak01** [comment]
this is a very old version, please upgrade

**Comment by ztengjiao** [comment]
> 这是一个很旧的版本，请升级
你好，请问一下我需要升级到那个版本；
Hello, could you tell me which version I need to upgrade to；
升级之后还出现这个错误我应该如何修复；
How can I fix this error after upgrading；

**Comment by ztengjiao** [comment]
> 这是一个很旧的版本，请升级

你好，请问我该升级到那个版本；
如果再次出现这个错误我该如何修复

**Comment by ztengjiao** [comment]
你好请问我应该升级到哪一个版本；这一列数据已经损坏我应该如何修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "questdb/questdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [questdb/questdb] 修改之后查询报错 (Issue #4393)





 
this is a very old version, please upgrade
