### ISSUE TITLE
Create special function to calculate trade price given L2 Order Book price/quantity pairs

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#4454]
### Is your feature request related to a problem?

It is not easy to use QuestDB to calculate prices given order book

### Describe the solution you'd like.

New SQL function that accepts parameters

- TradeSize
- Price1, Quantity1
- Price2, Quantity2
 ...
- PriceN, QuatntityN

that will calculate the price of a given trade if it was executed on the order book described by Price1..N, Quantity1..N

```SQL
SELECT L2Price(100, Price1, Quantity1, Price2, Quantity2, Price3, Quantity3)
FROM L2BOOK

SELECT L2Price(100, Price1, Quantity1, Price2, Quantity2, Price3, Quantity3, Price4, Quantity4)
FROM L2BOOK
```

The implementation of the function will be the same as this CASE statement 

```SQL
case
     when Quantity1>=TradeSize then Price1
     when (Quantity1+Quantity2)>=TradeSize then ((Quantity1*Price1)+((TradeSize-Quantity1)*Price2))/TradeSize
     when (Quantity1+Quantity2+Quantity3)>=TradeSize then  ((Quantity1*Price1)+((Quantity2*Price2)+((TradeSize-Quantity1-Quantity2)*Price3)))/TradeSize
     when (Quantity1+Quantity2+Quantity3+Quantity4)>=TradeSize then  ((Quantity1*Price1)+((Quantity2*Price2)+(Quantity3*Price3)+((TradeSize-Quantity1-Quantity2-Quantity3)*Price4)))/TradeSize
     when (Quantity1+Quantity2+Quantity3+Quantity4+Quantity5)>=TradeSize then  ((Quantity1*Price1)+((Quantity2*Price2)+(Quantity3*Price3)+(Quantity4*Price4)+((TradeSize-Quantity1-Quantity2-Quantity3-Quantity4)*Price5)))/TradeSize
else 0
```

### Full Name:

Alex Pelagenko

### Affiliation:

QuestDB

**Comment by sivukhin** [comment]
@ideoma, does `QuestDB` have plans to support some form of UDF (maybe they can be used only internally for such functions like `vwap` / `l2price` etc and only after some time opened to external users)?
