### ISSUE TITLE
Web Console not available after 7.3.7

### ISSUE THREAD

**Issue by juocal** [questdb/questdb#4483]
### To reproduce

1) Go to localhost:9000 to access the Web Console.
2) The Web Console does not load in Browser (same with wget)

### QuestDB version:

7.3.8

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 20.04.6 (Docker)

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Julien

### Affiliation:

Private

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

With the same configuration, it works for all versions below 7.3.8. 
Last working Version is 7.3.7

When switching back between 7.3.7 and 7.3.8, it always works on 7.3.7, but not on 7.3.8

I am running questdb in a docker environment. The available/published ports are the same, with each version.
According to the Release-Notes no configuration regarding the Web Console changed. At least as far as I could find!

**Comment by bluestreak01** [comment]
Hi Julien, affiliation disclosure is required. Help us help you.

**Comment by juocal** [comment]
> Hi Julien, affiliation disclosure is required. Help us help you.

Sorry! This is my personal account. We are using questdb at Fraunhofer in academic research. Thats my affiliation.

**Comment by juocal** [comment]
Additionally to that, I broke the issue/bug down to the point, that disabling "pg.enabled" via the environment variables (QDB_PG_ENABLED: "false"), disables the web console.

When setting QDB_PG_ENABLED = "true", the web console works.

This behavior changed between 7.3.5 and 7.3.8 apparently.

**Comment by juocal** [comment]
Steps do reproduce with minimal setup utilizing docker run command from documentation and setting  `QDB_PG_ENABLED` environment-variable to false:

Web-Console is available:
```
docker run -p 9000:9000   -p 9009:9009   -p 8812:8812   -p 9003:9003 -e QDB_PG_ENABLED='false' --name docker_questdb  questdb/questdb:7.3.7
```

Web-Console is **NOT** available:

```
docker run -p 9000:9000   -p 9009:9009   -p 8812:8812   -p 9003:9003 -e QDB_PG_ENABLED='false' --name docker_questdb  questdb/questdb:7.3.8
```

**Comment by bluestreak01** [comment]
Thank you Julien! That is a great find, we will attempt to reproduce the issue today and update you

**Comment by juocal** [comment]
> Thank you Julien! That is a great find, we will attempt to reproduce the issue today and update you

Great thank you! I am glad I could be of help!
This is not ciritcal and wasn't expecting it to be handled like this :)
I am just curious what lead to this change, as I already checked the commits and couldnt find any obvious changes.

If you need more info/help, let me know!
