### ISSUE TITLE
HTTPS redirect when using FQDN instead of IP

### ISSUE THREAD

**Issue by jsaathof** [questdb/questdb#4498]
### To reproduce

1. Go to http://<fqdn>:9000
2. page is redirected to HTTPS and fails because no certificate is configured

### QuestDB version:

7.4.2

### OS, in case of Docker specify Docker and the Host OS:

OpenSUSE Leap 15.5

### File System, in case of Docker specify Host File System:

btrfs

### Full Name:

Jurriaan Saathof

### Affiliation:

none

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by jerrinot** [comment]
hello @jsaathof, are you sure QuestDB sends the redirect? Isn't your browser being too keen on trying HTTPS on its own? Since I am unaware of QuestDB ever sending a redirect from HTTP to HTTPS.

**Comment by jsaathof** [comment]
It indeed seems to be browser related. However I tested both Safari and Firefox. When using a private window on either of the browsers the URL is not rewritten into a HTTPS URL. But I have not turned on HTTPS only mode in Firefox. Safari does not have this option.

One thing I did find is that QuestDB only supports TLS mode only for the enterprise version. Is there a reason for this?
