### ISSUE TITLE
simdjson support

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#4526]
### Is your feature request related to a problem?

We need SQL function, to create JSON projections from VARCHAR column type.

Lets assume we store JSON in the following tables:

```
create table xyz(json varchar);
```

I would like to be able to create projection as follows:

```sql
select extract_json(json, json_path, cast_as_type, fail_on_error) from xyz
```

- `json` - varchar field
- `json_path` - examples of json path can be taken from https://www.postgresqltutorial.com/postgresql-json-functions/postgresql-json-path/
- `cast_as_type` - our type to CAST json value as
- `fail_on_error` - boolean when `true` function must fail when json path is invalid. When `json` field contains incorrect json or there is error execution jsonpath, the function can throw `CairoException` when `fail_on_error` is true. Otherwise function must return `NULL` in the correct datatype

https://github.com/simdjson/simdjson is a library that alrady supports JSONPath and type casts. We should attempt to integrate with those.

### Full Name:

Vlad Ilyushchenko

### Affiliation:

QuestDB

**Comment by amunra** [comment]
Done, as of https://github.com/questdb/questdb/pull/4633
