### ISSUE TITLE
Alias in GROUP BY clause is not recognized

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#4534]
### To reproduce

This issue is reported by a person who's using QuestDB [Cube.js](https://cube.dev/) driver.

```sql
CREATE TABLE 'dim_apTemperature' (id INT, category STRING, aparent_temperature FLOAT);

CREATE TABLE 'fact_table' (
  id INT,
  date TIMESTAMP,
  fulltime STRING,
  id_OF INT,
  id_companie INT,
  id_location INT,
  id_asset INT,
  energy_power FLOAT,
  energy_power_factor FLOAT,
  data_time TIMESTAMP,
  id_state INT,
  temperature FLOAT,
  radiation FLOAT,
  id_wind_direction INT,
  pressure FLOAT,
  precipitation FLOAT,
  id_precipitation INT,
  wind_intensity FLOAT,
  id_wind_intensity INT,
  humidity FLOAT,
  id_humidity INT,
  dew_point FLOAT,
  cloud_base_height FLOAT,
  id_cloud INT,
  thermal_sensation FLOAT,
  id_aparent_temperature INT,
  ST FLOAT
);
```

Execute the following query:
```sql
SELECT
  "dim_ap_temperature".category "dim_ap_temperature__category",
  timestamp_floor('d', to_timezone("fact_table".data_time, 'UTC')) "fact_table__date_time_day",
  avg("fact_table".radiation) "fact_table__avg_radiation",
  avg("fact_table".energy_power) "fact_table__energy_power"
FROM
  fact_table AS "fact_table"
  LEFT JOIN dim_apTemperature AS "dim_ap_temperature" ON "fact_table".id_aparent_temperature = "dim_ap_temperature".id
GROUP BY
  "dim_ap_temperature__category",
  "fact_table__date_time_day"
ORDER BY
  "fact_table__avg_radiation" DESC
LIMIT
  10000;
```
and get this error:
```
Invalid column: fact_table.data_time
```

If you remove GROUP BY clause completely, the query executes fine.

### QuestDB version:

latest master

### OS, in case of Docker specify Docker and the Host OS:

Linux

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by Anuj-Tewari** [comment]
The error message "Invalid column: fact_table.data_time" suggests that the column data_time doesn't exist in the fact_table.
However, the query uses timestamp_floor('d', to_timezone("fact_table.date_time")) as fact_table_date_time_day in the GROUP BY clause. This indicates that the intended column for grouping is most likely date_time and not data_time.
Here's the corrected query:
SELECT
  "dim_ap_temperature".category "dim_ap_temperature_category",
  timestamp_floor('d', to_timezone("fact_table.date_time")) "fact_table_date_time_day",
  AVG("fact_table.energy_power") "fact_table_avg_energy_power",
  AVG("fact_table.radiation") "fact_table_avg_radiation"
FROM
  AVG("fact_table.energy_power") "fact_table_avg_energy_power",
  fact_table AS "fact_table"
LEFT JOIN
  dim_apTemperature AS "dim_ap_temperature"
ON
  "fact_table.id" = "dim_ap_temperature.id"
GROUP BY
  "dim_ap_temperature_category",
  "fact_table_date_time_day"
ORDER BY
  "fact_table_avg_radiation" DESC
LIMIT
  10000;

This corrected query groups the data by dim_ap_temperature_category and fact_table_date_time_day, which are the intended columns based on the alias definitions.
