### ISSUE TITLE
Update Twitter to X

### ISSUE THREAD

**Issue by iaayushmaan** [questdb/questdb#4605]
### Is your feature request related to a problem?

Enhancements to user experience
- Scroll down to the bottom
![Screenshot 2024-05-28 125830](https://github.com/questdb/questdb/assets/116517217/cfc17f4c-5030-4686-ab49-377373736a67)

### Describe the solution you'd like.

To stay up-to-date with the latest trends, Twitter should be rebranded as X.

### Full Name:

Aayushmaan Tawer

### Affiliation:

Software Developer

**Comment by Monik2002** [comment]
So we just need to rename it as X ? . you can assign me this work

**Comment by Vijaykv5** [comment]
> This part of QuestDB isn't public, so no.

Please add some labels, if it is not up for devs/isn't public.
Else why you make this Opensource?
