### ISSUE TITLE
Support IN operator for numeric columns in JIT compiler

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#4659]
### Is your feature request related to a problem?

The goal is simple: make `CompiledFilterIRSerializer` produce the same output for the following filters:
```sql
WHERE long_col = 42 AND int_col IN (2, 3, 5) AND short_col = 0;
WHERE long_col = 42 AND (int_col =2 OR int_col = 3 OR int_col = 5) AND short_col = 0;
```

`CompiledFilterIRSerializer` is QuestDB's JIT compiler frontend. It takes the filter AST and produces intermediate representation (IR) binary to be processed by the compiler backend (written in C++ with asmjit library).

The corresponding test suite is `CompiledFilterIRSerializerTest`.

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

**Comment by veerraj01** [comment]
WHERE Long_col = 42 AND Int_col IN (2, 3, 5) AND short_col = 0;
WHERE Long_col = 42 AND (Int_col =2 OR int_col = 3 OR int_col = 5) AND short_col = 0;

**Comment by zebs97** [comment]
Hi @puzpuzpuz, I've created a PR with a proposed solution for this issue.

**Comment by puzpuzpuz** [comment]
@zebs97 many thanks! I've left a few comments on the PR.

**Comment by veerraj01** [comment]
WHERE long_col = 42 AND int_col IN (2, 3, 5) AND short_col = 0;
WHERE long_col = 42 AND (int_col =2 OR int_col = 3 OR int_col = 5) AND short_col = 0;
WHERE Long_col = 42 AND (int , var , varchar , int 89)

**Comment by zebs97** [comment]
Hi @puzpuzpuz @bluestreak01, can I mplement JIT for `atimestamp IN <time_range_expression>` as a followup for this?

**Comment by puzpuzpuz** [comment]
> Hi @puzpuzpuz @bluestreak01, can I implement JIT for `atimestamp IN <time_range_expression>` as a followup for this?

@zebs97 that would be awesome! Simple expressions with a single interval would be a great starting point.
