### ISSUE TITLE
bad folder name in archive

### ISSUE THREAD

**Issue by cangencer** [questdb/questdb#468]
When I do `tar zxvf questdb-5.0.1-rt-osx-amd64.tar.gz` it extract itself to ` rt-osx-amd64/` instead of `questdb-5.0.1-rt-osx-amd64` as I would expect.

**Comment by mpsq** [comment]
Reopening - Although this was fixed for the `rt` versions, this is still happening for the `no-jre` version:

```
tar zxvf questdb-5.0.2-no-jre-bin.tar.gz
```

Is extracted to:

```
questdb-5.0.2/
```

Rather than:

```
questdb-5.0.2-no-jre-bin/
```
