### ISSUE TITLE
ZFS on Docker Container

### ISSUE THREAD

**Issue by QuadStingray** [questdb/questdb#4688]
### Is your feature request related to a problem?

You have the Compression Feature (https://questdb.io/docs/guides/compression-zfs/) in Version 8.0 documentation. How can I activate this at Docker? 

### Full Name:

QuadStringray

### Affiliation:

MongoCamp

**Comment by JAGANNADH18** [comment]
Hi @QuadStingray ,

You have to enable this at the block device level: https://docs.docker.com/storage/storagedriver/zfs-driver/

Then create your volumes on this device.

**Comment by QuadStingray** [comment]
Thanks @nwoolmer and @JAGANNADH18. I close this issue.
