### ISSUE TITLE
Limit maximum string length in string_agg aggregate function

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#4729]
### Is your feature request related to a problem?

The function concatenates all met values, so we should introduce a limit behind which the function returns an error. See `LPadFunctionFactory` class as an example.

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

**Comment by sklarsa** [comment]
@puzpuzpuz should we base the limit on available system resources? Seems like setting a single value could be just introducing another footgun for larger, more complex deployments

**Comment by puzpuzpuz** [comment]
We already have a global limit for RSS, so this limit is an additional one.
