### ISSUE TITLE
Add a pricing midpoint function

### ISSUE THREAD

**Issue by nwoolmer** [questdb/questdb#4730]
### Is your feature request related to a problem?

See https://github.com/questdb/questdb/issues/4620

Find the mid of an asking and bidding price i.e

`mid(DD)` = `mid(bid, ask)` = `avg(bid, ask)`

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

**Comment by sidprabaharan** [comment]
Hi! I’m a beginner in open source and would love to work on implementing the `mid(bid, ask)` function. Could you please assign this issue to me?
