### ISSUE TITLE
Add a pricing spread function

### ISSUE THREAD

**Issue by nwoolmer** [questdb/questdb#4731]
### Is your feature request related to a problem?

See https://github.com/questdb/questdb/issues/4620

Add a function to calculate the spread betwen asking and bidding prices (i.e difference)

`spread(bid, ask) = ask-bid`

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

**Comment by sklarsa** [comment]
I think this should be `spread(bid, ask) = ask - bid`
