### ISSUE TITLE
Window function on timezone converted data gives wrong result with negative limits

### ISSUE THREAD

**Issue by oz-brg** [questdb/questdb#4748]
### To reproduce

This bug appears when a very specific sequence is requested.

To reproduce, run the below with and without `LIMIT -100` and observe the difference in results.

```sql
WITH EastCoastTime AS (
    SELECT 
        to_timezone(timestamp, 'America/New_York') as timestamp,
        symbol,
        amount
    FROM trades
    WHERE timestamp in '2024-07-01T00:00:00'
)
SELECT timestamp, symbol, amount, sum(amount) OVER (
    PARTITION BY symbol
    ORDER BY timestamp
    RANGE UNBOUNDED PRECEDING
) as cumulative_amount
FROM EastCoastTime
```

When no negative limits are provided, the cumulative sum is correct, however if a negative limit is provided, it appears to apply the window function over additional rows outside the range/partition the window should be calculated on.

This bug only appears when the window function is applied to a timezone converted timestamp and only if the limit specified is negative.

### QuestDB version:

8.0.1

### OS, in case of Docker specify Docker and the Host OS:

Public demo instance

### File System, in case of Docker specify Host File System:

Public demo instance

### Full Name:

Oliver Zhu

### Affiliation:

BRG

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by jerrinot** [comment]
hello @oz-brg,

thank you for reporting this issue. I can confirm it's a bug. 

Before a proper fix is released you can workaround it by marking the `timestamp` column as a designed timestamp:
```sql
WITH EastCoastTime AS (
    (SELECT 
        to_timezone(timestamp, 'America/New_York') as timestamp,
        symbol,
        amount
    FROM trades
    WHERE timestamp in '2024-07-01T00:00:00') timestamp(timestamp) -- <-- INSTRUCTS QDB TO TREAT TIMESTAMP AS A DESIGNATED TIMESTAMP
)
SELECT timestamp, symbol, amount, sum(amount) OVER (
    PARTITION BY symbol
    ORDER BY timestamp
    RANGE UNBOUNDED PRECEDING
) as cumulative_amount
FROM EastCoastTime
limit -5;
```

**Comment by oz-brg** [comment]
Thanks for providing the workaround. It looks like this trick also works for the other timezone related bug I reported here: https://github.com/questdb/questdb/issues/4678

**Comment by jerrinot** [comment]
@oz-brg np at all. 

Marking the timestamp as a designated timestamp should also make the query faster. As a general rule, if you have a synthetic timestamp column—as you do in this case—and you are certain that the result data are ordered by this column, then marking this column as a designated timestamp can make some queries faster, sometimes much faster. When the query engine knows how the data are ordered, it can often choose a better plan.
