### ISSUE TITLE
LIKE implementation

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#476]
QuestDB implements regex string match with the operators `~=` and `!~`. However, `LIKE` is not implemented.

**Describe the solution you'd like**
Implement `LIKE` such that 
`column LIKE pattern` becomes `~=(column, pattern)`
`NOT column LIKE pattern` becomes `!~(column, pattern)`

**Comment by mick2004** [comment]
@TheTanc  : I would like to work on this , Can I ?

**Comment by TheTanc** [comment]
Thanks a lot for offering @mick2004 . Of course! Feel free to have a go and let us know if you need any help.

**Comment by mick2004** [comment]
@TheTanc  My understanding is that we need to write new function class derived from FunctionFactory and using ~= from within the new class.Let me know if that approach/understanding is correct ?

**Comment by bluestreak01** [comment]
Hey Mick, I would suggest to start with a static function that would match CharSequence instance to LIKE pattern, e.g.

```java
public static boolean match(CharSequence value, LIKE) {
...
}
```

I would come up with an efficient algorithm first, then benchmark  and optimise it.

The very last thing is to make this static function into something QuestDB SQL can invoke. That's the easy part.

**Comment by mick2004** [comment]
@bluestreak01  @TheTanc  Is there a yammer group for this project ? I have some questions.I have implemented the changes for this task (I can see changes working via web UI) but my test case is not able to invoke my new class.Is there some registration somewhere for new classes to be invoked from test.I have already put an entry in OperatorExpression.java and module-info.java.

I am trying below from my testcase class:

try (RecordCursorFactory factory = compiler.compile("select * from x where name like 'XJ'",sqlExecutionContext).getRecordCursorFactory())

**Comment by TheTanc** [comment]
No yammer group I'm afraid, but you can find us on [slack](https://questdb.slack.com)
