### ISSUE TITLE
Slow performance of non-exact matching on Symbol columns

### ISSUE THREAD

**Issue by oz-brg** [questdb/questdb#4775]
### To reproduce

Attempting to filter a Symbol column with non-exact filters like regex, like, or ilike currently does not use the column index and executes very slowly.

Running the below on the public demo instance:
```sql
SELECT timestamp, symbol FROM trades WHERE symbol ~ '^BTC-.+$' AND timestamp in '2024';
```
The execution time is about 2s. This scales pretty much linearly if we looked at more records.

Running the equivalent with an exact match:
```sql
SELECT timestamp, symbol FROM trades WHERE symbol IN ('BTC-USD', 'BTC-USDT') AND timestamp in '2024';
```
returns the results in ~250ms

However, even if we try to guide the calculation by first finding the unique symbols that satisfy the regex, the optimizer appears to re-write the query to scan the full table.

```sql
SELECT timestamp, symbol FROM trades WHERE symbol IN (
    SELECT symbol FROM (
        SELECT symbol FROM trades GROUP BY symbol
        )
    WHERE symbol ~ '^BTC-.+$'
) AND timestamp IN '2024';
```
This runs even slower than the original query and actually times out on the demo instance.

Looking at the query plan, it appears that the statement has been optimized to remove the first unique symbol selection and is instead running the regex filter across the full table.
![image](https://github.com/user-attachments/assets/af426bed-aa81-4f5b-8da5-1e2164bda0c0)

### QuestDB version:

8.0.1

### OS, in case of Docker specify Docker and the Host OS:

Public demo instance

### File System, in case of Docker specify Host File System:

Public demo instance

### Full Name:

Oliver Zhu

### Affiliation:

BRG

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by bluestreak01** [comment]
thanks for the bug report, this is on our immediate roadmap to fix.
