### ISSUE TITLE
Query takes time

### ISSUE THREAD

**Issue by janetthecoder** [questdb/questdb#482]
**Wrote a simple query took 35sec to execute**
I'm assuming this query is correct:
SELECT * FROM trips where pickup_latitude=-73.997484;

This query took 35 seconds to execute. As shown in the screenshot.

**To Reproduce**
1. Go to 'http://demo.questdb.io'
2. Run this SQL 'SELECT * FROM trips where pickup_latitude=-73.997484;'
4. See time taken to execute

**Expected behavior**
less than 1 second to execute.

**Screenshots**
Attached

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

<img width="1263" alt="Screen Shot 2020-07-03 at 6 27 07 AM" src="https://user-images.githubusercontent.com/17319377/86421464-c833bf80-bcf7-11ea-820a-994ed777d268.png">

**Comment by bluestreak01** [comment]
thank you, we are aware of this, filter expressions are not optimal yet and it is on our road map to make execution concurrent and SIMD-accelerated
