### ISSUE TITLE
Automatic recovery for suspended (WAL) tables on start-up

### ISSUE THREAD

**Issue by newskooler** [questdb/questdb#4829]
### Is your feature request related to a problem?

When data is streamed to a table 24/7 and there is a power outage (or similar issue), upon resume of the server many (if not all) WAL tables are suspended due to corrupt data (I guess).

At this stage, the user needs to go an manually perform an `ALTER TABLE my_table RESUME WAL from txn 1231` 
Any corrupted transaction will not enter into the table, so the table will keep being suspended, unless this transaction is skipped. There is a lot of manual work or a separate script which the user needs to write in order to get the table back up and running.

It will be nice to have a feature where the user can say:
- i want each table to be auto resumed
- i want it to try and add any txn from WAL but skip the corrupted ones

### Describe the solution you'd like.

Manually resume the table 
or
manually resume WAL from the last transaction (essentially skipping all of them and discarding them)
or 
going one by one in the pending transaction until the table is fully caught up and resumed

### Describe alternatives you've considered.

Nothing else beyond what I wrote.

Either way I do not understand why a table will be suspended at all. Surely the user wants all possible good data from WAL to go into the table and the table to be back up and running. This can be automated, so the need for suspension at all is something I do not get why it exists and why it awaits user choice and intervention, since the rational choice (it seems) is always the same. 
I may be missing something.

### Full Name:

Stelian Nenkov

### Affiliation:

WA

**Comment by siddharth0815** [comment]
@newskooler @nwoolmer is this issue picked already? I would like to work on it
It would be great if you could provide me with the following info
- Which classes to explore for starters
- Any easy way to replicate this scenario on my local machine?

**Comment by jerrinot** [comment]
Some additional thoughts/ideas: When starting QuestDB, during the recovery process, it could check if the next transaction can be applied. If not, it could provide hints on what to do, for example, linking to https://questdb.io/docs/reference/sql/alter-table-resume-wal/.

Alternatively, there could be syntax like `ALTER TABLE <table> RESUME WAL FROM TRANSACTION AUTO;` or `ALTER TABLE <table> RESUME WAL FORCE`, where QuestDB would skip all transactions that cannot be applied. Obviously, this is a drastic option, but in practice, users would likely need to skip the problematic transactions manually anyway.

**Comment by matt-kubica** [comment]
Is there any progress on that? Lack of this feature stops me from being able to effectivelu use questdb for my appliance. 

I want to deploy questdb in an environment with occassional power outages. I performed some test deployments and it seems that my tables get suspended from time to time because corrupted txn. For my appliance it's not a huge deal that some data get lost, however it's troublesome if I need to constantly monitor if table haven't had suspended and manually perform some actions to resume them.

I was thinking about performing some automation around that, however, being able to controll that with configuration in questdb would be more welcomed.

If nobody is currently working on that, maybe I'd give it a try.

**Comment by siddharth0815** [comment]
Hi @matt-kubica , I am working on this issue, will try to wrap it ASAP

**Comment by matt-kubica** [comment]
Thanks for confirmation @siddharth0815, looking forward to that!

@newskooler would you mind sharing your solution? I need to solve this problem before QDB gets it natively, it would save me some time if I use yours :)

**Comment by siddharth0815** [comment]
@nwoolmer, thanks for clarifications, 
  I am following the approach told by you
Couple of questions around it

1. `_txn` file is decoded in some format, how to corrupt data inside it
2. I json serialised the file and found it contains information about txn offsets, partitions etc, what data should I change in that so that a particular txn can be eligible for **being skipped**

**Comment by siddharth0815** [comment]
@newskooler can you share zip of any broken table for testing, I'll import in my local to replicate this case

**Comment by matt-kubica** [comment]
@siddharth0815 I have couple of tables that got suspended because corrupted txn. I've compressed whole `/var/lib/questdb`. Hope it will help you. 
[questdb.zip](https://github.com/user-attachments/files/17034244/questdb.zip)

**Comment by puzpuzpuz** [comment]
Closed by #4513 and shipped in v8.0.0.

**Comment by matt-kubica** [comment]
I wouldn't say that #4513 solves an issue that is described above. AFAIU #4513 is about making an attempt to resume suspended WAL tables on service startup, however, this issue is more about being able to resume table while skipping problematic/corrupted transactions.

I opt for reopening this issue as I believe it's not solved yet.

**Comment by puzpuzpuz** [comment]
> I wouldn't say that #4513 solves an issue that is described above. AFAIU #4513 is about making an attempt to resume suspended WAL tables on service startup, however, this issue is more about being able to resume table while skipping problematic/corrupted transactions.
> 
> I opt for reopening this issue as I believe it's not solved yet.

Makes sense. I got misled by the PR title. Changed it to "Automatic recovery for suspended (WAL) tables on start-up". This has to be an opt-in feature, not the default behavior as otherwise data corruption may go unnoticed by users.

**Comment by matt-kubica** [comment]
@ideoma thanks on elaborating a bit more on that. I'll definetely check out sync durability mode, probaby it will work better for my appliance.

**Comment by antst** [comment]
Looked at referenced issues. it i not like "unstable hardware". Any, literally ANY hardware can hit once in a while power issue. There are almost no datacenters which are fully safe from "man on excavator" :)
And once you have hundreds of tables to recover manually, it is a pain :) and in such situation, strategy is very simple, indeed, just look for txn from which you can recover, incrementing by one(right now I do this monkey job manually). Having some sort of mechanism, maybe not automatic, but one which can be triggered manually  - would be nice.

**Comment by antst** [comment]
I was also thinking about writing script ))))
But thought that if I ever get to this point again, then will do.
Thanks anyway, will snatch it for future )

**Comment by razuro** [comment]
Hi @matt-kubica, thanks for sharing the script! In the end, did the sync durability mode helps for your case?

Just sharing my context, I'm deploying QDB for a customer, remotely, and if it needs to be restarted manually (skip txn etc) everytime there's an outage that causes corrupted transactions, it's not very convenient unfortunately.

**Comment by matt-kubica** [comment]
@razuro since I've enabled durability mode I've never had the issue with corrupted txns again, despite several power outages.

**Comment by antst** [comment]
How bad durability mode affect performance/CPU load in real life?

**Comment by matt-kubica** [comment]
I haven't noticed any performance drop, but I wouldn't consider my usage heavy - occasional queries and ingestion every 10 seconds, also the volume of my databases is not extra huge.

But to answer this question one would need to run some performance tests
