### ISSUE TITLE
LATEST BY is not mentioned in SQL reference

### ISSUE THREAD

**Issue by rukmarr** [questdb/questdb#490]
There are currently three places in the documentation where LATEST BY is mentioned:
* https://questdb.io/docs/sqlExtensions
  This section describes expression but doesn't explain how to use it 
* https://questdb.io/docs/sqlExecutionOrder
  Is a brief mention
* https://questdb.io/docs/crudOperations
  The UPDATE section for some reason describes how to use LATEST BY in SELECT queries. More than that, examples are using shorthand **table** instead of **SELECT \* FROM table**, it doesn't make understanding them easier.

Docs would be much easier to read and understand if SELECT reference included LATEST BY

**Comment by TheTanc** [comment]
Thanks for the feedback. 
We are working on an overhaul of the SQL documentation which:
- Includes a dedicated page documenting the `LATEST BY` clause.
- Briefly introduces `LATEST BY` in the `SELECT` documentation (which will itself be completely overhauled and simplified) and points to the dedicated `SAMPLE BY` documentation page.

The same will be done for other extensions such as `SAMPLE BY` or `TIMESTAMP`. It should all be rolled out in the next few days. 

Thanks for pointing out that the shorthand expression of `select *` might make it harder to understand for new users. I will update the examples.

FYI, here is where the draft LATEST BY page stands so far (forgive the formatting, pdf exports are terrible).
[LATEST BY _ QuestDB.pdf](https://github.com/questdb/questdb/files/4884900/LATEST.BY._.QuestDB.pdf)

**Comment by rukmarr** [comment]
Thanks a lot for your help!

**Comment by bluestreak01** [comment]
https://questdb.io/docs/reference/sql/latest-by/
