### ISSUE TITLE
Flaky TextLoaderTest.testBrokenUtf8Header()

### ISSUE THREAD

**Issue by glasstiger** [questdb/questdb#4901]
### To reproduce

Intermittent failure on linux-x64-zfs CI.

Full log:
[253.txt.zip](https://github.com/user-attachments/files/16784779/253.txt.zip)

### QuestDB version:

8.1.0

### OS, in case of Docker specify Docker and the Host OS:

linux

### File System, in case of Docker specify Host File System:

zfs

### Full Name:

Imre

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by bluestreak01** [comment]
https://github.com/questdb/questdb/issues/4823
