### ISSUE TITLE
Data Sharding and Multi-Primary Support

### ISSUE THREAD

**Issue by tarun-t** [questdb/questdb#4957]
### Current Situation
QuestDB currently supports table partitioning within a single instance and allows for read replicas, but does not have built-in support for data sharding across multiple nodes or multi-primary setups.

### Feature Request
1. Data Sharding: 
   - Implement native support for data sharding across multiple nodes.
   - Ability to automatically distribute data across shards based on configurable criteria (e.g., time ranges, custom shard keys).
   - Support for cross-shard querying.

2. Multi-Primary Support:
   - Enable write operations on multiple nodes simultaneously.
   - Implement conflict resolution mechanisms for concurrent writes.

### Use Case
These features would be particularly beneficial for users dealing with large datasets, allowing for better distribution of data and write operations across multiple nodes without the need for full data replication on each node.

### Questions
1. Is data sharding across multiple nodes on the roadmap for QuestDB?
2. Are there plans to implement multi-primary support in future releases?
3. If these features are planned, is there an estimated timeline for their implementation?
4. Is this supported on the enterprise version?

### Additional Context
These features would significantly enhance QuestDB's ability to handle extremely large datasets and high write loads, making it more competitive in the big data and high-performance time-series database market.

Thank you for considering this feature request.

### Full Name:

Tarun Thammisetty

### Affiliation:

Open Futures Group

**Comment by ideoma** [comment]
We have both suggestions covered in the roadmap, I'm closing this issue
