### ISSUE TITLE
Alter table non WAL to WAL does not show in UI until QDB is restarted

### ISSUE THREAD

**Issue by newskooler** [questdb/questdb#4973]
### To reproduce

1. Create a Non-WAL table in UI
2. Change table to WAL table with ALTER TABLE
3. See that in the UI it does not show to be WAL
4. Reset QDB and check the UI. Now it shows to be WAL

### QuestDB version:

8.0.1

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 22.04.4 LTS

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

SN

### Affiliation:

WQ

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [x] Yes, I have

**Comment by glasstiger** [comment]
Hi @newskooler , this works as expected.
Table conversion happens after a restart only.
Please, see docs:
https://questdb.io/docs/reference/sql/alter-table-set-type/#description
