### ISSUE TITLE
Own/Native JDBC Driver

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#501]
**Is your feature request related to a problem? Please describe.**
When writing `DriverManager.getConnection("jdbc:postgresql://localhost:9120/qdb", properties);` I always have a doubt if this is the most efficient way to use QuestDB through JDBC.

**Describe the solution you'd like**
I would be happier if QuestDB has its own JDBC driver which is extensively fine-tuned for:
- low overhead, 
- zero GC and 
- speed.

**Describe alternatives you've considered**
Continue with the current driver. Unfortunately, need a JDBC driver in this context.

**Comment by bluestreak01** [comment]
JDBC driver cannot be zero gc by day ya design. The API expects string instances everywhere to begin with.

We are definitely not going to write our own JDBC driver. There is an issue for our own client - server protocol already and this is the route we will be taking
