### ISSUE TITLE
Log in DB File Format so they are Queryable in the DB

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#502]
**Is your feature request related to a problem? Please describe.**
Logs are not accessible through the DB as tables.

**Describe the solution you'd like**
Store logs in the DB format so they can be queried in the DB. Also, enhance log format to make it easily queriable.

Also, expose the logging framework, as a drop-in replacement for current popular loggers and metrics frameworks, to the application so they also save logs and metrics in the DB such they can be queried.

**Comment by bluestreak01** [comment]
Hey Sirinath, do you have any other feedback on our logging framework?

**Comment by sirinath** [comment]
- Also the ability to store the logs in a central DB. If the remote connection fails, catch locally and synch when the remove DB comes online. 
- current JDBC connection through PG client does not cut it for high-performance low overhead remote logging
- If logs are to be stored in the DB itself, don't convert to string, directly serialise objects for speed. On reading, if needed the client can construct the string. See: https://github.com/OpenHFT/Chronicle-Logger
- Have annotations like `logged(level = ..., message = "Ba ba ba", table = "...", appStart = true, timestamp = true, clazz = true, objID = true, stack = true, funName = true, param = true, result = true, in = true, out = true, state = true, thrown = true)` 
  - `level` - log level
  - `message` - message
  - `table` - table to store the message
  - `appStart` - application startup time to separate different sessions as `objID` will change from session to session
  - `timestamp` - include/exclude timestamp
  - `clazz` - include seriealised class
  - `objID` - identity hash
  - `stack` - seriealised stack
  - `funName` - include function name
  - `param` - function parameters
  - `result` - return value
  - `in` - IO inputs
  - `out` - IO outputs
  - `state` - local variable state
  - `thrown` - serialised uncaught exceptions
  - the default table name will be something like `$className` for the class which will have object creation and static initiliser logs and session timestamp, `$className$functionsName$param1Type$param2Type` for functions, `$className$functionsName$param1Type$param2Type$IO` & `$className$IO` for IO logs and `$className$functionsName$param1Type$param2Type$State` & `$className$State`. The table headers will have parameter names in addition to the above columns. If a table is specified the table column names will determine what is logged. This will be configured one at start up. The IO tables will log IO inputs and IO outputs separately as a function evocation can have many inputs and outputs. The state tables will have local state and state changes.
- In the DB configuration there should be a way to configure:
  - how many rows to keep OR
  - how many session to keep OR
  - how long to keep row
  - this will not be limited to logging
- Replay logs
  - ability to do time travelling debugging
  - ability to set the application to last know state after crash from logs
    - IO will be mocked when replaying and restoring state

**Comment by bsmth** [comment]
I'm going to close this due to inactivity for the moment. Thank you!
