### ISSUE TITLE
Avoid multiple SQL function compilations when preparing a parallel filter/GROUP BY query

### ISSUE THREAD

**Issue by puzpuzpuz** [questdb/questdb#5025]
### Is your feature request related to a problem?

Currently, when compiling a parallel filter/GROUP BY query we're compiling SQL functions from AST multiple times, once per the owner query thread and each shared worker thread. We could speed up the query compilation by compiling the functions only once and then cloning the functions per worker. This needs a new `deepClone()` method on the `Function` interface and proper implementations in all functions.

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

**Comment by puzpuzpuz** [comment]
@kafka1991 this one assumes a lot of code changes, so it's not the best choice for the first contribution. I suggest picking up one of `Good first issue` issues instead of this one:
https://github.com/questdb/questdb/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22

**Comment by kafka1991** [comment]
> @kafka1991 this one assumes a lot of code changes, so it's not the best choice for the first contribution. I suggest picking up one of `Good first issue` issues instead of this one: https://github.com/questdb/questdb/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22

May I start at `GroupByFunction`:
```
    private @Nullable ObjList<ObjList<GroupByFunction>> compileWorkerGroupByFunctionsConditionally(
            SqlExecutionContext executionContext,
            QueryModel model,
            @NotNull ObjList<GroupByFunction> groupByFunctions,
            int workerCount,
            RecordMetadata metadata
    ) throws SqlException {
        boolean threadSafe = true;
        for (int i = 0, n = groupByFunctions.size(); i < n; i++) {
            if (!groupByFunctions.getQuick(i).isThreadSafe()) {
                threadSafe = false;
                break;
            }
        }
        if (!threadSafe) {
            ObjList<ObjList<GroupByFunction>> allWorkerGroupByFunctions = new ObjList<>();
            for (int i = 0; i < workerCount; i++) {
                ObjList<GroupByFunction> workerGroupByFunctions = new ObjList<>(groupByFunctions.size());
                allWorkerGroupByFunctions.extendAndSet(i, workerGroupByFunctions);
                GroupByUtils.prepareWorkerGroupByFunctions(
                        model,
                        metadata,
                        functionParser,
                        executionContext,
                        groupByFunctions,
                        workerGroupByFunctions
                );
            }
            return allWorkerGroupByFunctions;
        }
        return null;
    }
```

In `compileWorkerGroupByFunctionsConditionally`, if has at least one `GroupByFunctions` is not thread safe, all `GroupByFunctions` need to recompile. We can enhance here by:
- `GroupByFunctions` that  threadSafe need not recompile/deepClone, which can be "shared" between different workers;
- `GroupByFunctions` that  not threadSafe need implement deepClone, but only need clone fields with conflict thread access, this means most of fields in GroupByFunctions objects can be shared(need not clone), like filed`arg` in `SumDoubleGroupByFunction` 
- This means `DeepClone` of `GroupByFunction` is not a common real clone function , May be its name  is DeepCloneIfNeed()
- The fields in `GroupByFunction` need be shared between different objects's  lifeCycle should controlled by the owner query thread(clear())
- Find Every `GroupByFunction` not threadSafe fileds, clone it in `deepClone()`


Am I understand right ?

BTW, The `Good first issue` seems has been exhausted and every has its owner -.-

**Comment by kafka1991** [comment]
> The problem is that a `GroupByFunction` may wrap a number of non-group by functions as its arguments and, when a `deepClone()` happens, it needs to clone them as well. So, due to that all `Function`s have to support `deepClone()`.

In my humble option,  non-group by functions seems has no inner-state, which mean is thread-safe access, may  the `GroupByFunction`'s  non-group by functions arg need not clone(Shared between different `GroupByFunction` objects by reference/pointer)?

**Comment by puzpuzpuz** [comment]
Many non-group by functions have runtime state which makes them non-thread safe. E.g. if the query has `first(concat(str_col, 'foobar'))` as an aggregate, the `ConcatFunction` function will have a `StringSink` to accumulate the concatenated strings.

**Comment by kafka1991** [comment]
> Many non-group by functions have runtime state which makes them non-thread safe. E.g. if the query has `first(concat(str_col, 'foobar'))` as an aggregate, the `ConcatFunction` function will have a `StringSink` to accumulate the concatenated strings.

OK，I checked  the `StrFunction` and most of are not thread-safe to reuse alloc memory.
So here `deepCloneIfNeed` can implement as:
- if `isThreadSafe()` return true, return `this` as pointer;
- if `isThreadSafe()` return false, only clone necessary fields that not thread-safe.

Is it ok to implement by this way?
Can i work on this issue?

**Comment by puzpuzpuz** [comment]
> Is it ok to implement by this way?
> Can i work on this issue?

I'd prefer cloning the functions unconditionally since this is less error-prone: it matches the current behavior when we recompile each function. As for working on the issue, sure please go ahead!

**Comment by kafka1991** [comment]
> Thanks for the thoughtful approach and have fun with the contribution! Don't hesitate to ask any questions here or on our public [Slack](https://slack.questdb.io/).

I hava two possible options to implement `deepClone` for base classes for `Function`:
1. Roughly implemet  `deepClone` method for every base class.
Example:
```
    private static class Func extends AbstractCastToStrFunction {
        ......
             @overide
             public Function deepClone() {
                    return new Func();
             }
        ......
    }
```
- Pros: Low runtime cost compare to opition 2
- Cons: A large amount of repetitive code, need implement `deepClone()` from every add function in the future.

2. Provide a default `deepClone()` method in interface/abstractClass which Use reflection to eliminate repetitive code.
Example:
```
    @Override
    default Function deepClone() {
        try {
            Class<? extends UnaryFunction> unaryFunctionClass = this.getClass();
            Constructor<? extends UnaryFunction> unaryFunctionClassCons =
                    unaryFunctionClass.getConstructor(Function.class);
            return unaryFunctionClassCons.newInstance(this.getArg().deepClone());
        } catch (NoSuchMethodException | IllegalAccessException |
                 InstantiationException | InvocationTargetException ex) {
            throw new IllegalArgumentException(ex);
        }
    }
```
- Pros: Effectively eliminate repetitive code(of cource also need override for 'special' function base class that not conform to this pattern)
- Cons: A slight runtime performance loss due to use of reflection compare option 1. However, I think the performance loss is acceptable because function.deepClone not happen offen In the whole query/sql execution time.
(I think  the reason of making this trade-off is that Java lacks template-meta programming.)

So, I'd perfer option2 to implement. What do you think about the two options? Or have another good idea?
@puzpuzpuz

**Comment by puzpuzpuz** [comment]
Sorry for the late reply. I'd try to go with option 2, but that might be tricky as signatures of function constructors vary a lot. Alternatively, we could add `newInstance` to UnaryFunction`/`BinaryFunction/... and have each class effectively expose its "constructor" (with a unified interface) though this function. Then in `UnaryFunction` the `deepClone()` impl would be simple:
```java
    default void deepClone() {
        return newInstance(getArg().deepClone());
    }
```

**Comment by kafka1991** [comment]
> Sorry for the late reply. I'd try to go with option 2, but that might be tricky as signatures of function constructors vary a lot. Alternatively, we could add `newInstance` to UnaryFunction`/`BinaryFunction/... and have each class effectively expose its "constructor" (with a unified interface) though this function. Then in `UnaryFunction` the `deepClone()` impl would be simple:
> 
> ```java
>     default void deepClone() {
>         return newInstance(getArg().deepClone());
>     }
> ```

Thanks for your good idea. Everything is fine util tricky  `CursorFunction`, which stand by a `subquery` or `system function` or `storage scan rows abstract`. The  `CursorFunction` 'contain' a RecordCursorFactory that hard to implement `deepClone`, nor `CursorFunction` also thread-safe. The siuation seems very difficult to handle. Can `GroupByFunction` has `CursorFunction` as its warpper function?

**Comment by puzpuzpuz** [comment]
ATM `CursorFunction` can be used only in `IN (<symbol sub-query>)` and `IN (<timestamp sub-query>)` expressions in WHERE clause. So, it doesn't need implementing `deepClone()`, but instead can throw an exception.

**Comment by puzpuzpuz** [comment]
Closing this one, at least for now, as SQL compilation appears to be on-par or very close to reflection-based code.
