### ISSUE TITLE
Connection to superset failed

### ISSUE THREAD

**Issue by Kiwami-Zhang** [questdb/questdb#5129]
### To reproduce

1.I installed superset according to the requirements on the official website and executed
`pip install 'questdb-connect==1.0.12'`
2.Create a new database connection in superset and enter`questdb://admin:quest@host.docker.internal:9000/qdb`
3.In the Docker container of Questdb, you can see `http server connected`,but the superset shows _Connection failed, please check your connection settings._

### QuestDB version:

8.1.4

### OS, in case of Docker specify Docker and the Host OS:

windows(Docker)

### File System, in case of Docker specify Host File System:

NTFS

### Full Name:

Xinhai Zhang

### Affiliation:

NEFU

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by jerrinot** [comment]
hi @Kiwami-Zhang,
thanks for reportig this issue. Can you try it with port 8812 instead of 9000? `questdb-connect` uses the Postgres Wire Protocol to talk to QuestDB server. The default port for Postgres protocol in QuestDB is 8812, not 9000. Port 9000 is for HTTP.
