### ISSUE TITLE
Separate HTTP settings for ILP over HTTP

### ISSUE THREAD

**Issue by ntippman** [questdb/questdb#5130]
### Is your feature request related to a problem?

Currently, ILP over HTTP relies on the general HTTP server settings for authentication and configuration. This setup limits flexibility by requiring the same credentials for both the web console and ILP clients. Additionally, it restricts the ability to make the web console read-only while still allowing ILP/HTTP to insert data.

### Describe the solution you'd like.

I would like to provide users with read-only access to the web console, either without authentication or with distinct credentials, while still allowing authenticated data insertion via ILP/HTTP. To achieve this, I propose the following changes:

1. **Override Read-Only Settings for ILP**:
The configuration option `line.http.enabled` should not be affected by the `http.security.readonly` setting. This will ensure that even if the web console is set to read-only, ILP/HTTP can still be used for data insertion.

2. **Separate Credentials for ILP Over HTTP**:
Introduce a separate set of credentials specifically for ILP over HTTP. This would allow differentiated access levels, enabling more granular security management for users of the web console versus ILP clients.

### Describe alternatives you've considered.

While ILP TCP token authentication is available, many users prefer to handle ILP via HTTP for simplicity and accessibility. This proposed change would make ILP over HTTP more usable in multi-user environments where different access levels are essential.

### Full Name:

Nico Tippmann

### Affiliation:

MEGWARE GmbH

**Comment by bluestreak01** [comment]
Enterprise version with full access control layer solves this problem fully.

**Comment by bluestreak01** [comment]
https://questdb.io/docs/operations/rbac/

**Comment by bluestreak01** [comment]
https://questdb.io/docs/operations/rbac/

There are fine grained permissions that can separate access to JSON and ILP endpoints.

**Comment by tris0laris** [comment]
Hi @ntippman thanks for coming to us with this proposed approach. QuestDB Enterprise would be a solution to this problem, is this something you'd like to discuss with our team? You can drop us a message on slack (slack@questdb.io) and we can take it from there. thank you
