### ISSUE TITLE
Add quoted spread

### ISSUE THREAD

**Issue by alexandrebrilhante** [questdb/questdb#5155]
### Is your feature request related to a problem?

Find the quoted spread:

`(spread / mid) * 100`

where `spread` and `mid` are defined as:

`spread = ask - bid`

`mid = (ask + bid) / 2.0`

### Describe the solution you'd like.

`QuotedPriceFunctionFactory` would need to be implemented re-using the `spread` and `mid` functions in `FinanceUtils`. I can submit a PR.

### Full Name:

Alexandre Brilhante

### Affiliation:

BMO Capital Markets

**Comment by bluestreak01** [comment]
that looks like a "relative spread" and can be calculated as follows:

```
SELECT
    timestamp,
    symbol,
    ask_price,
    bid_price,
    (ask_price - bid_price) AS quoted_spread,
    ((ask_price - bid_price) / ((ask_price + bid_price) / 2)) * 100 AS relative_spread_percentage
FROM
    market_quotes;
```

Assuming `bid` and `ask` are stored as columns of the same record. Why would we need a function for what looks like a relatively simple maths?

**Comment by alexandrebrilhante** [comment]
> https://questdb.io/docs/reference/function/finance/#spread_bps
> 
> Divide this by 100.

Looks like it, thanks.
