### ISSUE TITLE
Slack: Contact the workspace administrator for an invitation

### ISSUE THREAD

**Issue by djrobby** [questdb/questdb#525]
Unable to join your **public** Slack channel (attached GIF). It keeps stating to "**Contact the workspace administrator for an invitation**". Please provide detailed instructions on your site on "How To" join your Slack channel. I also see others experiencing the same (attached).

![SS_20200729_8](https://user-images.githubusercontent.com/22199/88825964-31dba800-d196-11ea-93bf-5e11f738e116.jpg)

![20200405-001](https://user-images.githubusercontent.com/22199/88826762-2046d000-d197-11ea-9ef1-ff50af72133f.gif)

**Comment by mpsq** [comment]
Can you try with that link instead:
https://questdb.slack.com/join/shared_invite/enQtNzk4Nzg4Mjc2MTE2LTEzZThjMzliMjUzMTBmYzVjYWNmM2UyNWJmNDdkMDYyZmE0ZDliZTQxN2EzNzk5MDE3Zjc1ZmJiZmFiZTIwMGY#/
?

**Comment by bluestreak01** [comment]
this should be fixed
