### ISSUE TITLE
Add Prometheus metrics endpoint

### ISSUE THREAD

**Issue by dgl** [questdb/questdb#532]
**Is your feature request related to a problem? Please describe.**

It would be useful to know if QuestDB is misbehaving and how it is performing.

**Describe the solution you'd like**

A common way to do this is with Prometheus metrics, providing a /metrics endpoint with various counters would be helpful (HTTP requests, SQL execution count, exceptions, errors), potentially histograms of execution times as well as some gauges (e.g. current number of running queries, open FDs, open TCP connections).

**Describe alternatives you've considered**

Providing a SQL command to get stats and then writing an exporter would be an option (maybe useful to have a stats command anyway), however built-in support would be good (and very common for cloud native tools).

**Comment by bygui86** [comment]
Hi guys, any news about this?
Prometheus metrics has become a must in every cloud-native environment ;)

**Comment by bsmth** [comment]
Hi @dgl and @bygui86, basic support has been added in https://github.com/questdb/questdb/pull/905 and details for usage are covered in https://questdb.io/blog/2021/07/16/release-6-0-4#prometheus-metrics

We're now in a position to improve this functionality but we need to know which counters and gauges to add. David's suggestions are as follows:

__Counters:__
* HTTP requests
* SQL execution count
* Exceptions / errors

__Gauges:__
* Number of running queries
* Open FDs
* Open TCP connections

Is there anything else useful I can add to this list?

**Comment by bygui86** [comment]
@bsmth Thanks a lot for the effort!

As I'm using Cassandra, PostgreSQL and MongoDB extensively, I will take some idea there. Give me some time to put down a list.

**Comment by bygui86** [comment]
@bsmth meanwhile, when do you plan to release Prometheus metrics?

**Comment by bsmth** [comment]
@bygui86 it's available as of release 6.0.4, but there is only one counter added as MVP - this is why we're looking for feedback on what's most important to add next. There's instructions for trying it out in this blog post:

https://questdb.io/blog/2021/07/16/release-6-0-4#prometheus-metrics

**Comment by dgl** [comment]
Mostly what I said originally, but in particular as this is using a custom client implementation there's some metrics that the standard client libraries implement which it would be good to see with the same names and behaviours (as then it's possible to have generic dashboards / alerts), see e.g. https://github.com/prometheus/client_java/blob/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java

**Comment by puzpuzpuz** [comment]
Closing this one since Prometheus endpoint was added. Feel free to create separate GH issues around potential enhancements.
