### ISSUE TITLE
SAMPLE BY does not seem to work

### ISSUE THREAD

**Issue by MBaert** [questdb/questdb#537]
**Describe the bug**
SAMPLE BY functionality returns 'base query does not provide dedicated TIMESTAMP column'

**To Reproduce**
Follow the example on https://questdb.io/docs/reference/sql/sample-by/
Does not work even with the example 'trips.csv' file
eg. SELECT pickupDatetime, count()
FROM trips.csv
SAMPLE BY 1h;

**Expected behavior**
Expected to have a successful query.

**Screenshots**
![image](https://user-images.githubusercontent.com/5864255/89634546-de5c0f00-d8a5-11ea-8d94-b26f558535a4.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by bluestreak01** [comment]
`sample by` is expecting table to have data in chronological order and also have nominated timestamp column. E.g. the column with timestamp values. If you know that your data is indeed ordered by timestamp at source, you can assign timestamp dynamically:

```sql
select pickupDatetime, count()
from (trips.csv timestamp(pickupDatetime))
sample by 1h
```

could you try that?

**Comment by MBaert** [comment]
Awesome, that works! So I basically still have to tell which timestamp-type column I want to be THE timestamp column of that table. This is what is meant in https://questdb.io/docs/concept/designated-timestamp I guess. Thanks.

Issue can be closed.

**Comment by bluestreak01** [comment]
great, thank you!
