### ISSUE TITLE
Not fail on table with dot on query 'Drop table'

### ISSUE THREAD

**Issue by danyanya** [questdb/questdb#559]
**Describe the bug**
I imported csv file. It's created table with dot name (clients.csv as example). Also have table with name 'clients'.
Query 'select * from clients.csv;' -> **Fail** (as expected)
Query 'drop table clients.csv' -> **Good** (drops another table with name 'clients') 

**To Reproduce**
1. Import CSV document (name.csv)
2. Create a table with name 'name' (with CREATE TABLE name) 
3. Run this SQL 'DROP TABLE name.csv'
4. Don't see any error, but see dropped table 'name'

**Expected behavior**
**Fail** as 'select * from name.csv' (without quotes)

**Environment (please complete the following information):**
 - OS: Linux, Docker
 - Browser: Chrome
 - Version: questdb/questdb:5.0.2

**Comment by bluestreak01** [comment]
thanks Daniil, this is should be an easy fix
