### ISSUE TITLE
Does it support multiple indexes, if not, are there other similar things

### ISSUE THREAD

**Issue by dybxin** [questdb/questdb#590]
Hi :

> Does it support multiple indexes like SQL `CREATE INDEX`, if not, are there other similar things.

Thanks a lot,
dybxin

**Comment by bluestreak01** [comment]
this is what we have on indexes:

https://questdb.io/docs/concept/indexes/

**Comment by thatkit** [comment]
You can `ALTER TABLE `command to add more indexes, but for now all of them must be of type `symbol`.
https://questdb.com/docs/reference/sql/alter-table-alter-column-add-index/
