### ISSUE TITLE
SQL for bulk insert

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#593]
support syntax for insert of multiple rows at once:

```sql
INSERT INTO table_name (column_list)
VALUES
    (value_list_1),
    (value_list_2),
    ...
    (value_list_n);
```

## Unknowns

Investigate if PostgreSQL supports bind variables in statement like that.

## Implementation

It is very likely this insert will need to be executed _without_ creating intermediate model. The existing QuestDb's implementation of Insert is also deficient and this is an opportunity to prove it.

## Considerations

- insert should convert constant types similarly to how BindVariableService does. In that it should be possible to insert `null` into primitive types, such as `int`, `long` etc. It should also be possible to insert  constant `int` into `short` and `byte` column, numeric value into `char` column etc.

- The implementation should be efficient and performant for frequent execution of insert statements

- The implementation must not generate grabage

**Comment by dybxin** [comment]
@bluestreak01  How many data can be inserted at one time,and what server configuration required? thanks a lot !

**Comment by bluestreak01** [comment]
We will get to implementing this insert soon. Have you considered using https://questdb.io/docs/api/influxdb-line-protocol ?

**Comment by dybxin** [comment]
thanks a lot, current, i will not consider using it !

**Comment by bluestreak01** [comment]
fixed in https://github.com/questdb/questdb/pull/1603

**Comment by morganchristiansson** [comment]
Awesome!

But the documentation makes no mention of this yet... https://questdb.io/docs/reference/sql/insert/

**Comment by Shivansh-Mittal** [comment]
Can I insert json file data in my questdb table from C# ?

**Comment by jerrinot** [comment]
hi @Shivansh-Mittal you parse the JSON file in C# and then use a Postgres client to connect to QuestDB and use SQL bulk update as [documented here](https://questdb.io/docs/reference/sql/insert#examples)
