### ISSUE TITLE
batch insert data error arrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dybxin** [questdb/questdb#599]
**Describe the bug**
` java
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 16
	at io.questdb.std.ObjList.getQuick(ObjList.java:117)
	at io.questdb.griffin.engine.functions.rnd.RndStringListFunctionFactory$Func.getStr(RndStringListFunctionFactory.java:87)
	at io.questdb.cairo.sql.VirtualRecord.getStr(VirtualRecord.java:119)
	at io.questdb.griffin.rowcopier/0x000000080020e840.copy(Unknown Source)
	at io.questdb.griffin.SqlCompiler.copyUnordered(SqlCompiler.java:1331)
	at io.questdb.griffin.SqlCompiler.insertAsSelect(SqlCompiler.java:1663)
	at io.questdb.griffin.SqlCompiler.executeWithRetries(SqlCompiler.java:1459)
	at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1239)
	at io.questdb.griffin.SqlCompiler.compile(SqlCompiler.java:710)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:1414)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:976)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:304)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:79)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:69)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:151)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:82)
	at io.questdb.mp.Worker.run(Worker.java:107)
`
**Additional context**

sql = `
		INSERT INTO orders
			SELECT
				x uid, --increasing integer
				rnd_long(1, 100000000, 0) rider_id,
				rnd_long(1, 10000000, 0) taxi_id,
				rnd_long(1, 10000000, 0) driver_id,
				rnd_timestamp(to_timestamp('2017', 'yyyy'), to_timestamp('2018', 'yyyy'), 0)start_time,
				rnd_timestamp(to_timestamp('2019', 'yyyy'), to_timestamp('2020', 'yyyy'), 0) end_time,
				rnd_str('alipay', 'wechatpay', 'cashpay') payment_type,
				rnd_double() fare,
				rnd_str('xxxxx', 'xxxxxx', 'xxxxx') start_location,
				rnd_str('xxxxx', 'xxxxx', 'xxxxx') end_location
			FROM long_sequence(10000000) x
		;
	`

c := time.Tick(5 * time.Second)
    for next := range c {
	fmt.Printf("%v \n", next)
	_, err = db.Exec(sql)

	if err != nil {
		fmt.Println(err)
	}
   }

**Comment by bluestreak01** [comment]
may I ask what version of QuestDB are you using? 

```
RndStringListFunctionFactory.java:87
```

![image](https://user-images.githubusercontent.com/7276403/93072981-1b23de80-f67a-11ea-8b10-51d0faf2593a.png)

then

![image](https://user-images.githubusercontent.com/7276403/93073037-30990880-f67a-11ea-8699-514f96fa6f68.png)

I struggle to see how can you can `-2`

**Comment by dybxin** [comment]
> I struggle to see how can you can

thank you! however i can't get the version.
[i used golang guides](https://questdb.io/docs/tutorial/go)

**Comment by dybxin** [comment]
> may I ask what version of QuestDB are you using?
> 
> ```
> RndStringListFunctionFactory.java:87
> ```
> 
> ![image](https://user-images.githubusercontent.com/7276403/93072981-1b23de80-f67a-11ea-8b10-51d0faf2593a.png)
> 
> then
> 
> ![image](https://user-images.githubusercontent.com/7276403/93073037-30990880-f67a-11ea-8699-514f96fa6f68.png)
> 
> I struggle to see how can you can `-2`

thank you! i used latest docker image,
docker run -p 9000:9000  \
    -p 8812:8812 \
    -p 9009:9009 \
    -v /data/questdb/server.conf:/root/.questdb/conf/server.conf  \
    -v /data/questdb/data:/root/.questdb/db \
    --cpus=4 --cpuset-cpus="0-3" -m 16G --memory-reservation 16G \
    questdb/questdb`
`

**Comment by mpsq** [comment]
What is the result of `docker images | grep questdb`?

**Comment by dybxin** [comment]
> docker images | grep questdb

![Screenshot from 2020-09-14 18-44-47](https://user-images.githubusercontent.com/14888437/93076770-6c53c280-f6ba-11ea-911e-c9813cac63c3.png)

**Comment by bluestreak01** [comment]
Thanks for providing all this info. Do you mind providing table structure for `orders` please?

**Comment by dybxin** [comment]
> Thanks for providing all this info. Do you mind providing table structure for `orders` please?

![Screenshot from 2020-09-14 18-54-12](https://user-images.githubusercontent.com/14888437/93077693-c608bc80-f6bb-11ea-9623-c3a3f859801a.png)

**Comment by bluestreak01** [comment]
I cannot reproduce  :(

```shell
docker run -p 9000:9000 questdb/questdb
```

```sql
create table orders (
uid long,
rider_id long,
taxi_id long,
driver_id long,
start_time timestamp,
end_time timestamp,
payment_type string,
fare double,
start_location string,
end_location string
);

INSERT INTO orders SELECT x uid, --increasing integer 
rnd_long(1, 100000000, 0) rider_id, 
rnd_long(1, 10000000, 0) taxi_id, 
rnd_long(1, 10000000, 0) driver_id, 
rnd_timestamp(to_timestamp('2017', 'yyyy'), to_timestamp('2018', 'yyyy'), 0)start_time, 
rnd_timestamp(to_timestamp('2019', 'yyyy'), to_timestamp('2020', 'yyyy'), 0) end_time, 
rnd_str('alipay', 'wechatpay', 'cashpay') payment_type, 
rnd_double() fare, 
rnd_str('xxxxx', 'xxxxxx', 'xxxxx') start_location, 
rnd_str('xxxxx', 'xxxxx', 'xxxxx') end_location 
FROM long_sequence(10000000) x ;
```

Can you?

**Comment by dybxin** [comment]
> reproduce

Do you use  `time.Tick(5 * time.Second)` to repeat insert?

**Comment by bluestreak01** [comment]
yeah, this is the code i used:

```golang
package main

import (
    "database/sql"
    "fmt"
    "time"
    _ "github.com/lib/pq"
)

func main() {

    db, err := sql.Open("postgres", "host=localhost port=8812 user=admin password=quest dbname=qdb sslmode=disable")
    if err != nil {
        panic(err)
    }
    defer db.Close()

    fmt.Println("Successfully connected!")

    sql := "INSERT INTO orders SELECT x uid, rnd_long(1, 100000000, 0) rider_id, rnd_long(1, 10000000, 0) taxi_id, rnd_long(1, 10000000, 0) driver_id, rnd_timestamp(to_timestamp('2017', 'yyyy'), to_timestamp('2018', 'yyyy'), 0)start_time, rnd_timestamp(to_timestamp('2019', 'yyyy'), to_timestamp('2020', 'yyyy'), 0) end_time, rnd_str('alipay', 'wechatpay', 'cashpay') payment_type, rnd_double() fare, rnd_str('xxxxx', 'xxxxxx', 'xxxxx') start_location, rnd_str('xxxxx', 'xxxxx', 'xxxxx') end_location FROM long_sequence(10000000) x";

    c := time.Tick(5 * time.Second)
    for next := range c {
       fmt.Printf("%v \n", next)
       _, err = db.Exec(sql)
       
       if err != nil {
	fmt.Println(err)
       }
    }
}
```


```shell
C:\Users\Vlad\dev\questdb\tmp>go run main.go                                                                                                                                                                                                                                                                                                                                                                                            Successfully connected!
2020-09-14 13:06:14.293201 +0100 BST m=+5.002999001
2020-09-14 13:06:19.2922416 +0100 BST m=+10.002039601
2020-09-14 13:06:24.2937568 +0100 BST m=+15.003554801
2020-09-14 13:06:29.293817 +0100 BST m=+20.003615001
2020-09-14 13:06:34.2923304 +0100 BST m=+25.002128401
2020-09-14 13:06:39.2928813 +0100 BST m=+30.002679301
```

**Comment by dybxin** [comment]
> yeah, this is the code i used:
> 
> ```go
> package main
> 
> import (
>     "database/sql"
>     "fmt"
>     "time"
>     _ "github.com/lib/pq"
> )
> 
> func main() {
> 
>     db, err := sql.Open("postgres", "host=localhost port=8812 user=admin password=quest dbname=qdb sslmode=disable")
>     if err != nil {
>         panic(err)
>     }
>     defer db.Close()
> 
>     fmt.Println("Successfully connected!")
> 
>     sql := "INSERT INTO orders SELECT x uid, rnd_long(1, 100000000, 0) rider_id, rnd_long(1, 10000000, 0) taxi_id, rnd_long(1, 10000000, 0) driver_id, rnd_timestamp(to_timestamp('2017', 'yyyy'), to_timestamp('2018', 'yyyy'), 0)start_time, rnd_timestamp(to_timestamp('2019', 'yyyy'), to_timestamp('2020', 'yyyy'), 0) end_time, rnd_str('alipay', 'wechatpay', 'cashpay') payment_type, rnd_double() fare, rnd_str('xxxxx', 'xxxxxx', 'xxxxx') start_location, rnd_str('xxxxx', 'xxxxx', 'xxxxx') end_location FROM long_sequence(10000000) x";
> 
>     c := time.Tick(5 * time.Second)
>     for next := range c {
>        fmt.Printf("%v \n", next)
>        _, err = db.Exec(sql)
>        
>        if err != nil {
> 	fmt.Println(err)
>        }
>     }
> }
> ```
> 
> ```shell
> C:\Users\Vlad\dev\questdb\tmp>go run main.go                                                                                                                                                                                                                                                                                                                                                                                            Successfully connected!
> 2020-09-14 13:06:14.293201 +0100 BST m=+5.002999001
> 2020-09-14 13:06:19.2922416 +0100 BST m=+10.002039601
> 2020-09-14 13:06:24.2937568 +0100 BST m=+15.003554801
> 2020-09-14 13:06:29.293817 +0100 BST m=+20.003615001
> 2020-09-14 13:06:34.2923304 +0100 BST m=+25.002128401
> 2020-09-14 13:06:39.2928813 +0100 BST m=+30.002679301
> ```

@bluestreak01 Thanks for your reply, if recurrent i will provide more info !

**Comment by bluestreak01** [comment]
thanks 👍
