### ISSUE TITLE
inner join query time is too long 

### ISSUE THREAD

**Issue by dybxin** [questdb/questdb#600]
**Describe the bug**
i use orders table have 1 billion data, and rdiers table have 1 million data. then, execute the following sql statement
`select * from orders inner join riders on orders.rider_id = riders.uid;`
i hope get the results quickly, however very time consuming

**Comment by patrickSpaceSurfer** [comment]
Can you provide the table structure for both your tables. You can get the structure with the SQL

```show columns from orders;```

**Comment by dybxin** [comment]
> show columns from orders;

![Screenshot from 2020-09-14 18-20-55](https://user-images.githubusercontent.com/14888437/93074562-21847b80-f6b7-11ea-8644-6551c39cca9e.png)
![Screenshot from 2020-09-14 18-21-14](https://user-images.githubusercontent.com/14888437/93074575-29442000-f6b7-11ea-96e8-f6f8912c3bf5.png)

**Comment by patrickSpaceSurfer** [comment]
For the order table, you have two timestamp field types, start_time and end_time. Which one is the designated timestamp? Your query will be speeded up by selecting a time range for your designated time stamp. So if your designated timestamp is start_time a query like

```select * from orders inner join riders on orders.rider_id = riders.uid WHERE start_time >= '2020-01-01' AND start_time <= '2020-01-05';```

Should be fast

**Comment by patrickSpaceSurfer** [comment]
You can also trying increasing the size of the internal data structures used to resolve the join, in your configuration (server.conf) you can add:

```cairo.sql.map.page.size=33554432```
```cairo.sql.hash.join.light.value.page.size=33554432```

**Comment by dybxin** [comment]
> You can also trying increasing the size of the internal data structures used to resolve the join, in your configuration (server.conf) you can add:
> 
> `cairo.sql.map.page.size=33554432`
> `cairo.sql.hash.join.light.value.page.size=33554432`

@patrickSpaceSurfer Thanks for your reply, I will try and let you know !

**Comment by dybxin** [comment]
@patrickSpaceSurfer  if i have created the order table, and  contains  timestamp field types, however i not use `start_time` or `end_time` as designated timestamp, [timestamp](https://questdb.io/docs/reference/function/timestamp/), the two solutions of the document did not meet my needs, what should i do that add timestap(start_time).

**Comment by patrickSpaceSurfer** [comment]
> > You can also trying increasing the size of the internal data structures used to resolve the join, in your configuration (server.conf) you can add:
> > `cairo.sql.map.page.size=33554432`
> > `cairo.sql.hash.join.light.value.page.size=33554432`
> 
> @patrickSpaceSurfer Thanks for your reply, I will try and let you know ! otherwise, `33554432` on the basis of ?

The join is implemented with a hash table in memory, the hash table will resize if its not big enough, resizing can be slow. The size of the table (and results in memory) is based on the data set size of the riders table. I created a riders table with 1 million entries and tried the join, the logging shows me that the hash table needs to resize unilt its 32M big when I tried your join. So really these things are trial and error, but the logging should tell you whats happening.

**Comment by patrickSpaceSurfer** [comment]
> @patrickSpaceSurfer if i have created the order table, and contains timestamp field types, however i not use `start_time` or `end_time` as designated timestamp, [the two solutions of the document did not meet my needs](https://questdb.io/docs/reference/function/timestamp/), what should i do that add timestap(start_time).

I am afraid there is no way at the moment to add a designated timestamp to an already existing table. You will need to create a new table with a designated timestamp and re-instert all the data. You need to select your designated timestamp column such that any inserts are in timestamp order, so you can only insert new data if the designated timestamp is the same or more than the last row in the table (We are working on out of order inserts, so in the future this will not be an issue).

**Comment by dybxin** [comment]
@patrickSpaceSurfer thanks a lot !

**Comment by bluestreak01** [comment]
I apologise for delayed suggestion, but better late than never :+1:


Joins are performed in order of their appearance in the SQL. If you rewite SQL to be:

```sql
select * from riders inner join orders on orders.rider_id = riders.uid;
```

It should run much faster

**Comment by dybxin** [comment]
thanks a lot !
