### ISSUE TITLE
Group by time period (x minutes/hours/days etc)

### ISSUE THREAD

**Issue by AxelRHD** [questdb/questdb#607]
Is it possible to group values by a special time period (like average on hour or day)?

If not, it would be a great feature.

**Comment by bluestreak01** [comment]
we have introduced a SQL extension to do that, hopefully simple enough to use:

```sql
select avg(x) from tab sample by 1h
```

more here: https://questdb.io/docs/reference/sql/sample-by/

**Comment by AxelRHD** [comment]
Exactly what I was looking for. Thank you for the very fast response. I have to confess, that I didn't read the documentation enough carefully.
