### ISSUE TITLE
Add query parameter to specify file name on `/exp` REST endpoint

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#682]
## Background
The `/exp` endpoint is used by the Web Console for exporting the current query results as a .CSV file. When using the 'export as CSV' button, the following call is made behind the scenes:

* __path:__ `/exp`
* __query param:__ `query={current query}`

The response headers for this request defaults to `questdb-query-{timestamp}.csv`, for example:

```http
Content-Disposition: attachment; filename="questdb-query-1607071793458.csv"
```

## Desired behaviour
It would be convenient to be able to specify a new filename via query parameters to this endpoint, for example:

```http
exp?query=select%20*%20from%20table&filename=my_exported_data
```

* __path:__ `/exp`
* __query params:__
  * `query=select * from table`
  * `filename=my_exported_data`

### Response
The browser should prompt the user to download `my_exported_data.csv`, the response header should look like the following

```http
Content-Disposition: attachment; filename="my_exported_data.csv"
```

**Comment by bsmth** [comment]
Backend handling of this is closed in #830 thanks to @siddheshlatkar 🎉 
Follow-up for UI components tbd
