### ISSUE TITLE
Support for displaying server and UI versions from Web Console

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb#718]
## Background 
If there are multiple versions of QuestDB installed, it can be the case that the Web Console is running a different release version than the QuestDB server or an older version may be cached in the browser. This can lead to compatibility/interoperability issues with supported features.

## Feature Description
Software versions of the currently-running installations should be easily accessible to the user from the UI through a debug element or otherwise in the Web Console. This should help the user identify the following:

* Current server version
* Current Web Console version
* __bonus:__ git hash of the build for finer details to pinpoint underlying code

Support for this will speed up troubleshooting when trying to diagnose UI issues.

**Comment by ideoma** [comment]
hey @bsmth, it looks like it's done, there is a button to copy it to clipboard

**Comment by bsmth** [comment]
Thanks @ideoma , resolving this one 👍🏻
