### ISSUE TITLE
Javadoc?

### ISSUE THREAD

**Issue by nu11ptr** [questdb/questdb#727]
Looking to possibly use this as an embedded DB in a Scala project. So far all I can find for docs is:

https://questdb.io/docs/reference/api/java-embedded

Is there at least a complete Javadoc API hosted somewhere? I can generate my own, but a hosted solution would be helpful, thx

**Comment by bluestreak01** [comment]
sorry, not hosted yet, we will think of something

**Comment by bluestreak01** [comment]
https://javadoc.questdb.io

**Comment by nu11ptr** [comment]
Amazingly quick - thx!
