### ISSUE TITLE
Postgres timestamp function

### ISSUE THREAD

**Issue by jonathanskrz** [questdb/questdb#740]
It seems questdb doesn't support the "timestamp" function.
https://www.postgresql.org/docs/12/functions-datetime.html

**To Reproduce**
insert into "test" ("test_timestamp","test_value") 
values (timestamp with time zone '2020-12-31 15:15:51.663+00:00', '256')

**Expected behavior**
Data being inserted

**Current behavior**
[18:05:05] insert into "test" ("test_timestamp","test_value") 
values (timestamp with time zone '2020-12-31 15:15:51.663+00:00', '256')  ')' expected

**Environment (please complete the following information):**
 - QuestDB 5.0.5

**Comment by jonathanskrz** [comment]
Some additional context : 
In my use case the SQL is generated by JooQ, based on a postgres schema with the test_timestamp field being of type "timestamptz".
With questdb having its own timestamp type, what would be a postgres type I could choose as an equivalent ?

**Comment by bluestreak01** [comment]
hey Jonathan, thanks for reporting the issue. We are hardening PostgreSQL wire support on "master" right now. The latest released version is weaker.

We would support the following insert 

```sql
insert into "test" ("test_timestamp","test_value") values ('2020-12-31 15:15:51.663+00:00', 256)
```

Are you using JOOQ are ORM tool against QuestDB or as a migration tool?
