### ISSUE TITLE
Unable to write using Line with TCP C#

### ISSUE THREAD

**Issue by MalikRizwanBashir** [questdb/questdb#741]
I tried lineprotocol with **NodeJs**, that worked fine!. I don't know maybe, I am doing someting wrong or need to do some configurations, but I can't find in documentation. 
I tried with all encoding types and also tried with different stream writers, BUT not able to write line using **C#**.

I have this code for sending data over **TCP**.

           `DateTime timestamp = DateTime.Now.AddDays(-30);
            var timeSpan = timestamp.Subtract(EpochStart);
            var row = $@"trades,name=test_ilp1 value=12.4 { timestamp.Ticks * 100 }";
            Socket clientSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

            var serverBaseAddress = new Uri("http://127.0.0.1:9009");
            var _udpHostName = serverBaseAddress.Host;

            IPAddress ipAddress = Dns.GetHostEntry(_udpHostName).AddressList[0];
            IPEndPoint ipEndPoint = new IPEndPoint(ipAddress, 9009);
            clientSocket.Connect(ipEndPoint);

            // Sending
            int toSendLen = System.Text.Encoding.ASCII.GetByteCount(row);
            byte[] toSendBytes = System.Text.Encoding.ASCII.GetBytes(row);
            byte[] toSendLenBytes = System.BitConverter.GetBytes(toSendLen);
            clientSocket.Send(toSendLenBytes);
            clientSocket.Send(toSendBytes);

            // Receiving
            byte[] rcvLenBytes = new byte[4];
            clientSocket.Receive(rcvLenBytes);
            int rcvLen = System.BitConverter.ToInt32(rcvLenBytes, 0);
            byte[] rcvBytes = new byte[rcvLen];
            clientSocket.Receive(rcvBytes);
            String rcv = System.Text.Encoding.ASCII.GetString(rcvBytes);

            Console.WriteLine("Client received: " + rcv);

            clientSocket.Close();`

**Actually i am trying to write C# client for Questdb.**
Thanks in advance!
It will be really appreciated. Thanks again

**Comment by TimBo93** [comment]
Hey @MalikRizwanBashir there are multiple issues regarding your code.

At first I want to encourage you to use **TcpClient instead of Socket**. Do you really need the full control of the lowlevel-socket functionality? This is how I would solve the problem.
```csharp
// Usings
using System;
using System.IO;
using System.Net.Sockets;

// Connect
using TcpClient tcpClient = new();
await tcpClient.ConnectAsync("localhost", 9009);
await using var stream = tcpClient.GetStream();
using StreamWriter writer = new(stream)
{
    NewLine = "\n"
};

// Send Data
await writer.WriteLineAsync($"RhineLevel,station=Worms height=164 {DateTimeOffset.Now.ToUnixTimeMilliseconds() * 1_000_000}");

// Close and flush stream
await writer.FlushAsync();
tcpClient.Close();
```

Further you have a bug creating your string 
```csharp
var row = $@"trades,name=test_ilp1 value=12.4 { timestamp.Ticks * 100 }";
```
If you want to use the **@** instead of explicitly concatenating \n then you need to have a line-break inside your code. 
```csharp
var row = $@"trades,name=test_ilp1 value=12.4 { timestamp.Ticks * 100 }
";
```

The next point is that you send the **length of the buffer**. That is something which is not necessary. 

All in all this is your code working for me:
```csharp
using System;
using System.Net;
using System.Net.Sockets;

var timeInNs = DateTimeOffset.Now.ToUnixTimeMilliseconds() * 1_000_000;
var row = $@"trades,name=test_ilp1 value=12.4 { timeInNs }
";
Socket clientSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

var serverBaseAddress = new Uri("http://127.0.0.1:9009");
var _udpHostName = serverBaseAddress.Host;

IPAddress ipAddress = Dns.GetHostEntry(_udpHostName).AddressList[0];
IPEndPoint ipEndPoint = new IPEndPoint(ipAddress, 9009);
clientSocket.Connect(ipEndPoint);

// Sending
byte[] toSendBytes = System.Text.Encoding.ASCII.GetBytes(row);
clientSocket.Send(toSendBytes);
```

**Comment by bluestreak01** [comment]
thanks Tim! Assuming this is resolved
