### ISSUE TITLE
use postgre jdbc driver connect to db with the error wrong user/password

### ISSUE THREAD

**Issue by roycyz** [questdb/questdb#782]
I have downloaded the binaries version and run it.When I was used the  postgre's JDBC driver to link it on port 8812.It reported the error what is the wrong user and password.So how can I set the user and password for it.

**Comment by ideoma** [comment]
https://questdb.io/docs/reference/configuration/

Defaults are
pg.password = quest
pg.user = admin

**Comment by ideoma** [comment]
You can also ask questions on StackOverlow, mark it with QuestDb tag

**Comment by roycyz** [comment]
thanks for helping.
