### ISSUE TITLE
Add functionality to check partitioning strategy of existing table

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb#789]
It would be helpful to be able to determine the following:

* If a table has a partitioning strategy and if not `NONE`
  * Whether the strategy is by `DAY`, `MONTH` or `YEAR`

**Describe the solution you'd like**
* Either the web console should show in the tables view that a table has a partitioning strategy employed and what time interval it's being partitioned
* a query or function could be improved to include this as table metadata

**Existing queries and functions for table metadata:**
* `all_tables()` function - [meta reference](https://questdb.io/docs/reference/function/meta)
* `SHOW TABLES;` - [show reference](https://questdb.io/docs/reference/sql/show)
*  `SHOW COLUMNS FROM TABLE <table_name>` - [SHOW COLUMNS reference](https://questdb.io/docs/reference/sql/show#examples)

**Comment by piotrrzysko** [comment]
I've started working on this 🙂 .
