### ISSUE TITLE
Bound parameters are broken with Go's lib/pq

### ISSUE THREAD

**Issue by tamasd** [questdb/questdb#797]
I can't run an `INSERT` query with Go's lib/pq.

I started `questdb/questdb:5.0.6-linux-amd64` in Docker, then ran the following code (queries are copied from the docs):

```go
package main

import (
	"database/sql"
	"fmt"
	"time"

	_ "github.com/lib/pq"
)

func main() {
	conn, err := sql.Open("postgres", "host=localhost dbname=qdb user=admin password=quest sslmode=disable port=8812")
	checkErr(err)

	_, err = conn.Exec("CREATE TABLE trades (ts TIMESTAMP, date DATE, name STRING, value INT) timestamp(ts);")
	checkErr(err)

	defer func() {
		_, _ = conn.Exec("DROP TABLE trades")
		_ = conn.Close()
	}()

	_, err = conn.Exec("INSERT INTO trades VALUES($1, $2, $3, $4)", time.Now(), time.Now().Round(time.Millisecond), "test insert", 1)
	if err != nil {
		fmt.Println(err)
	}
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}
```

Running the code prints:

```
pq: got 4 parameters but the statement requires 0
```

I did a little debugging, and the problem seems to be that [parameter information is incorrectly returned by QuestDB](https://github.com/lib/pq/blob/master/conn.go#L805), so later [lib/pq refuses to use the parameters](https://github.com/lib/pq/blob/master/conn.go#L1385).

**Comment by bluestreak01** [comment]
hi Tamás, thanks for raising the issue. We should be able to fix it asap. In the mean time "pgx" works. Is that a suitable workaround?

**Comment by bsmth** [comment]
Hi @tamasd, thanks for the issue! It might be worth mentioning that in [pq's README ](https://github.com/lib/pq) there's a note about the project status:

> This package is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using pgx which is actively maintained.

This was one of the reasons we went for using `pgx` in the examples.

**Comment by bsmth** [comment]
@tamasd I had a look at using the `lib/pq` Go library and this is working for me using `Prepare` for two-stage prepared statements:

```go
package main

import (
  "database/sql"
  "log"
  "time"

  _ "github.com/lib/pq"
)

func main() {
  db, err := sql.Open("postgres", "postgresql://admin:quest@localhost:8812/qdb?sslmode=disable")
  if err != nil {
    log.Fatal("Failed to open a DB connection: ", err)
  }
  _, err = db.Query("CREATE TABLE IF NOT EXISTS trades (ts TIMESTAMP, date DATE, name STRING, value INT) timestamp(ts);")
  
  smt, err := db.Prepare("INSERT INTO trades VALUES($1,$2,$3,$4)")
  if err != nil {
    log.Fatalln(err)
  }
  for i := 0; i < 10; i++ {
    _, err = smt.Exec(time.Now().UnixNano() / 1000, time.Now().Round(time.Millisecond), "go prepared statement", i+1)
    if err != nil {
      log.Fatalln(err)
    }
  }
}
```

Declaring a prepared statement:

```go
smt, err := db.Prepare("INSERT INTO trades VALUES($1,$2,$3,$4)")
```

Executing with parameters:

```go
smt.Exec(p1, p2,...)
```

Which auto generates a prepared statement name `1` on the server side.

```
2021-02-15T10:35:44.424406Z I i.q.c.p.PGConnectionContext parse [q=INSERT INTO trades VALUES($1,$2,$3,$4)]
2021-02-15T10:35:44.424815Z I i.q.c.p.PGConnectionContext prepare [name=1]
2021-02-15T10:35:44.425104Z I i.q.c.p.WriterPool >> [table=`trades`, thread=15]
2021-02-15T10:35:44.425164Z I i.q.c.p.WriterPool << [table=`trades`, thread=15]
...
2021-02-15T10:35:44.426867Z I i.q.c.p.PGConnectionContext disconnect [code=-2]
```

Let us know if this is sufficient

**Comment by bsmth** [comment]
I'm going to close this one because of inactivity and that the approach detailed in https://github.com/questdb/questdb/issues/797#issuecomment-779136640 appears to achieve the results requested.

If this issue is not resolved, please feel free to reopen with more details.

Thanks :)
