### ISSUE TITLE
Web Console reports syntax error when some queries succeed

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb#813]
**Describe the bug**
On certain statements that are passing, the console reports an error.

**To Reproduce**
1. Go to Web Console
2. Run SQL `ALTER TABLE table_name RENAME COLUMN x TO y;`
3. See error `',' expected`
4. Run SQL `SELECT * FROM table_name` to see new table schema from step 2

**Expected behavior**
Success notification that the query was executed without any issues

**Environment (please complete the following information):**
 - OS: MacOS 11.2.1
 - Browser: Firefox 85.0.2 (64-bit)
 - QuestDB version: Master - https://github.com/questdb/questdb/commit/02f33951671f4b5b9346aa4ef5252db15d3c387a

__EDIT - Additional context:__

It seems to occur in `ALTER TABLE` queries as the following statement also demonstrates this bug:

```sql
ALTER TABLE 'weather.csv' DROP PARTITION LIST '2010-01-01';
```
Returns the error `',' expected`. The `LIST` keyword does not have syntax highlighting applied, but this may be unrelated.

**Comment by bluestreak01** [comment]
SQL compiler executes drop partition as it parses it. It should do full syntax check first and execute only syntactically correct statment

**Comment by bsmth** [comment]
I believe this is fixed in https://github.com/questdb/questdb/pull/1634
