### ISSUE TITLE
The result of the aggregate function "AVG" query is sometimes ”NULL“

### ISSUE THREAD

**Issue by AllKai** [questdb/questdb#825]
I have a table named sk with the fields of `code` (INT), `name` (SYMBOL)(INDEX), `age` (INT), `avgV` (DOUBLE) and `ts` (TIMESTAMP),totaling 200 million data.

BUG：
when i execute SQL (select name,min(code),avg(age) from sk group by name order by name) in WebConsole,in the returned data, AVG (age) column is sometimes normal and sometimes null.

This problem is what I found today.

**Comment by bluestreak01** [comment]
what version of questdb did you use?

**Comment by AllKai** [comment]
> what version of questdb did you use?

5.0.6.1 for rt-Linux

**Comment by AllKai** [comment]
I just tried again a few times,If all columns of the query are aggregate,then everything is normal, otherwise the above problems will appear

**Comment by AllKai** [comment]
The version started by docker does not have the above problems. At present, I have tested the Linux version and docker version, and Linux will have this problem.

**Comment by bluestreak01** [comment]
this should be fixed
