### ISSUE TITLE
UCASE functions

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#83]
Issue with uppercase. Compiler only recognise functions when fully lowercase.

COUNT(), Count(), coUnt() dont work
count() works

Same for min, max, avg etc...

**Comment by bluestreak01** [comment]
Function names, column name and table names are case sensitive. Good workaround would be to suggest list of possible names whenever function name is miss-spelt and subsequently not resolved by SQL compiler.

**Comment by bluestreak01** [comment]
the plan is to add function name hints in SQL errors, when function is not found. Title this issue doesn't reflect that, hence closing this issue.
