### ISSUE TITLE
All contributors edit

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb#853]
We had some merge conflicts by adding too quickly to our [all contributors megathread](https://github.com/questdb/questdb/issues/252) so this is a temp ticket for adding you guys in one go! 😂 

Thanks again for the contributions!

**Comment by bsmth** [comment]
@all-contributors bot, please add @gabor-boros for tutorial, example 

Thanks for the awesome [tutorial](https://questdb.io/tutorial/2021/01/13/application-uptime-monitoring-with-python-nuxtjs-questdb/) and [example application](https://github.com/gabor-boros/questdb-statuspage) 🔧 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @kovid-r for tutorial, example 

Thanks Kovid for brilliant contributions about [SQL extensions](https://towardsdatascience.com/sql-extensions-for-time-series-data-in-questdb-f6b53acf3213) for time series and how to use [Influx line protocol](https://towardsdatascience.com/schemaless-ingestion-in-questdb-using-influxdb-line-protocol-18850e69b453) 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @TimBo93 for bug, userTesting

Thanks Tim for [filing multiple bug reports](https://github.com/questdb/questdb/issues?q=is%3Aissue+author%3ATimBo93+), and your feedback which greatly helps us improve the stability of the system! 🎉

**Comment by bluestreak01** [comment]
this was replaced with https://github.com/questdb/questdb/issues/868
