### ISSUE TITLE
Implicit casts of e (exponent) notation to DOUBLE / FLOAT

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb#866]
**Is your feature request related to a problem? Please describe.**
I would like to be able to insert values using exponent notation. Currently, this is possible by means of an explicit cast:

```sql
CREATE TABLE example_table (double_num DOUBLE, float_num FLOAT);
INSERT INTO example_table VALUES(cast('1.5e-07' as DOUBLE), cast('1.5e2' as FLOAT));
```

**Describe the solution you'd like**
I would like to be able to pass the following example SQL without issues:

```sql
CREATE TABLE example_table (double_num DOUBLE, float_num FLOAT);
INSERT INTO example_table VALUES(1.5e-07, 1.5e2);
```

This fails on current master with the following error message:

```log
... i.q.c.h.p.JsonQueryProcessorState [23] syntax-error [q=`INSERT INTO example_table VALUES(1.5e-07, 1.5e2);`, at=33, message=`invalid constant: 1.5e`]
```

**Comment by bluestreak01** [comment]
problem can also be reproduced with:

```sql
select 1.8e-1
```

**Comment by bluestreak01** [comment]
fixed
