### ISSUE TITLE
Add contributors additions!

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb#868]
Adding more contributors to the repo!

**Comment by bsmth** [comment]
@all-contributors bot, please add @jaugsburger for significant code contributions and maintenance 

Thanks for being part of the QuestDB journey! 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @TheTanc for management, content and ideas 

Thanks for being part of the QuestDB journey! 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @davidgs for filing bugs and writing great content

Thanks for your contributions and efforts building the community, David! 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @kaishin for coding an example application 

Thank you for the [awesome SwiftNIO client](https://github.com/swift-glide/questdb-nio) using QuestDB! 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @bluestreak01 for everything from code to maintenance and testing!

Thanks for the dedication to keeping QuestDB superpowered! 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @patrickSpaceSurfer for stellar coding 🌟 and continued maintenance and testing additions!

Thanks for the hard work! 🎉

**Comment by bsmth** [comment]
@all-contributors bot, please add @chenrui333 for infra additions 

Thank you for helping our homebrew users get the latest QuestDB versions!

**Comment by tris0laris** [comment]
@all-contributors bot, please add @bsmth for docs and content :books:
Thanks for the contribution!

**Comment by tris0laris** [comment]
@all-contributors bot, please add @lepolac for code contributions and integration to other OSS tools
Thanks for the contribution!

**Comment by tris0laris** [comment]
@all-contributors bot, please add @Ugbot for integration with other systems and product feedback
Thanks for the contribution!

**Comment by tris0laris** [comment]
@all-contributors bot, please add @Ugbot for questions, user testing and participating in talks about QuestDB

**Comment by bsmth** [comment]
@all-contributors bot, please add @Ugbot for questions, user testing and participating in talks about QuestDB!

Thanks Ben!

**Comment by bsmth** [comment]
@all-contributors bot, please add @Ugbot for questions, user testing and participating in talks about QuestDB!
