### ISSUE TITLE
Missing http.min.bind.to in questdb conf

### ISSUE THREAD

**Issue by TimBo93** [questdb/questdb#870]
**Describe the bug**
I would suggest to add the http.min.bind.to in questdb-conf file.
If  one runs two instances of questdb it is mandatory to change the port.

**To Reproduce**
Please look at 
https://github.com/questdb/questdb/blob/f11e29ef60ce8223d38268dd77d0f602f41abba4/core/src/main/resources/io/questdb/site/conf/server.conf

**Expected behavior**
comments like
```
# http.min.enabled=true
# http.min.bind.to=0.0.0.0:9013
```

**Screenshots**

**Environment (please complete the following information):**
- OS: Windows Server 2016

**Additional context**

**Comment by patrickSpaceSurfer** [comment]
The http min service is only needed for monitoring in some setups, it may be an idea to disable this in the default configuration

**Comment by bluestreak01** [comment]
in addition to what Patrick said, http min is used in context where you have load balancer pinging http very often but it isn't necessary to log every LB request. LB could of course monitor main http server, but it would either produce a lot of noise in the log file or, when log is disabled on main http server, lead to difficulty logging real http requests
