### ISSUE TITLE
Designated timestamps cannot be directly compared to epoch microseconds

### ISSUE THREAD

**Issue by patrickSpaceSurfer** [questdb/questdb#874]
Non designated fields of type timestamp can be directly compared to an integer value representing the epoch time in microseconds, thus

`select * from x where ts<1616170125000000`

However, for designated timestamps this does not work, you need to first cast to timestamp, thus

`select * from x where ts<cast(1616170125000000 as timestamp)`

or

`select * from x where cast(ts as timestamp)<1616170125000000`

**Comment by RickyC0626** [comment]
Perhaps parser-level implicit casting from long to timestamp is a viable option, though I'm not sure what potential problems this may cause. Explicit casting would still be available for those who prefer more type safety, but implicit casting would be more readable and quicker to use. I'm willing to give this one a shot.

**Comment by bluestreak01** [comment]
have a look at `WhereClauseParser`, this issue refers to the code, which recognises that designated, ordered timestamp column is being searched against a constant. Right now it picks up specific timestamp constants, but not epoch. It should be relatively easy to add epoch there as well

**Comment by RickyC0626** [comment]
> have a look at `WhereClauseParser`, this issue refers to the code, which recognises that designated, ordered timestamp column is being searched against a constant. Right now it picks up specific timestamp constants, but not epoch. It should be relatively easy to add epoch there as well

Thanks for the additional information, but I'm not exactly sure where in `WhereClauseParser` changes should be made. I did notice that the parse methods used in `IntervalUtils` would only accept the proper timestamp format, and not microsecond longs, so my initial thought was to check if the expression is in microsecond format, and return its value instead of parsing through as we would an ISO 8601 string.

**Comment by Belair34** [comment]
If it's okay, I'd like to use this issue and a few more (which I'll comment on later) for a college hackathon on November 5th. If this is alright with you guys, I'd also appreciate any recommendations for issues that may be suitable for this 4-6 hour event. We expect to solve a few issues that day! If you prefer to communicate further on slack: my name on slack is Michael IZKOOL.

**Comment by bluestreak01** [comment]
yes, sure

**Comment by pswu11** [comment]
Hi @Belair34 excited to hear that! we'll try to mark some more small issues with good first issue label.
