### ISSUE TITLE
QuestDB spam

### ISSUE THREAD

**Issue by techtonik** [questdb/questdb#875]
Few say ago I received this mail from the person who claims to be the CTO of QuestDB.
```
Vlad Ilyushchenko <vlad.ilyushchenko@questdb.tech>

Hey anatoly,


I helped develop an alternative to InfluxDB, which is faster, more reliable, uses standard SQL and supports InfluxDB line protocol. It's an Open Source time series database that should be easy to try out with your existing stack. Here's the GitHub link if you'd like to check it out: https://github.com/questdb/questdb


QuestDB is built from the ground up to be the most performant open source time series database available. Would love to hear what you think!


Thanks,

Vlad / CTO @ QuestDB


If you don't want to hear from me again, please let me know :)
```
The two links provided in the mail - to GitHub and to "let me know" are links trackers. The domain leads to `track.questdb.tech` which is different from https://questdb.io/ that this project uses.

So I want to ask what all of this mean?

**Comment by bluestreak01** [comment]
please reach out to the sender

**Comment by techtonik** [comment]
@bluestreak01 so why are sending these automated mails to people? What is your selection criteria to choose who to send? Why you need trackers on the links to GitHub? And why you don't use the https://questdb.io/ domain for your mail?

**Comment by quantumpacket** [comment]
I highly doubt a spammer is promoting a random project, when it would not benefit them. So Occam's razor is that someone associated with the project is spamming users to promote it. So far @bluestreak01 has closed 2 issues about this that I could find, with no explanation other than to "reach out" to the spammer. Awesome advice! :facepalm:

**Comment by austince** [comment]
From the WHOIS on `questdb.tech`, it appears that @bluestreak01 Vlad has hidden all contactable information but it is clearly registered to QuestDB in London...

# whois.nic.tech

Domain Name: QUESTDB.TECH
Registry Domain ID: D182620599-CNIC
Registrar WHOIS Server: whois.gandi.net
Registrar URL: http://www.gandi.net/
Updated Date: 2021-04-12T19:05:00.0Z
Creation Date: 2020-04-13T17:59:59.0Z
Registry Expiry Date: 2025-04-13T23:59:59.0Z
Registrar: Gandi SAS
Registrar IANA ID: 81
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
**Registrant Organization: QuestDB**
Registrant State/Province:
**Registrant Country: GB**
Registrant Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Admin Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Tech Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Name Server: NS-144-C.GANDI.NET
Name Server: NS-27-B.GANDI.NET
Name Server: NS-0-A.GANDI.NET
DNSSEC: unsigned
Billing Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Registrar Abuse Contact Email: abuse@support.gandi.net
Registrar Abuse Contact Phone: +33.170377661
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2021-04-15T18:34:06.0Z <<<

# whois.gandi.net

Domain Name: questdb.tech
Registry Domain ID: D182620599-CNIC
Registrar WHOIS Server: whois.gandi.net
Registrar URL: http://www.gandi.net
Updated Date: 2021-04-12T21:05:00Z
Creation Date: 2020-04-13T17:59:59Z
Registrar Registration Expiration Date: 2025-04-13T23:59:59Z
Registrar: GANDI SAS
Registrar IANA ID: 81
Registrar Abuse Contact Email: abuse@support.gandi.net
Registrar Abuse Contact Phone: +33.170377661
Reseller: 
Domain Status: clientTransferProhibited http://www.icann.org/epp#clientTransferProhibited
Domain Status: 
Domain Status: 
Domain Status: 
Domain Status: 
Registry Registrant ID: REDACTED FOR PRIVACY
Registrant Name: REDACTED FOR PRIVACY
Registrant Organization: QuestDB
Registrant Street: REDACTED FOR PRIVACY
Registrant City: REDACTED FOR PRIVACY
Registrant State/Province: 
Registrant Postal Code: REDACTED FOR PRIVACY
Registrant Country: GB
Registrant Phone: REDACTED FOR PRIVACY
Registrant Phone Ext:
Registrant Fax: REDACTED FOR PRIVACY
Registrant Fax Ext:
Registrant Email: a14de3e04ed1896bf94b85416974ccaa-18544863@contact.gandi.net
Registry Admin ID: REDACTED FOR PRIVACY
Admin Name: REDACTED FOR PRIVACY
Admin Organization: REDACTED FOR PRIVACY
Admin Street: REDACTED FOR PRIVACY
Admin City: REDACTED FOR PRIVACY
Admin State/Province: REDACTED FOR PRIVACY
Admin Postal Code: REDACTED FOR PRIVACY
Admin Country: REDACTED FOR PRIVACY
Admin Phone: REDACTED FOR PRIVACY
Admin Phone Ext:
Admin Fax: REDACTED FOR PRIVACY
Admin Fax Ext:
Admin Email: a14de3e04ed1896bf94b85416974ccaa-18544863@contact.gandi.net
Registry Tech ID: REDACTED FOR PRIVACY
Tech Name: REDACTED FOR PRIVACY
Tech Organization: REDACTED FOR PRIVACY
Tech Street: REDACTED FOR PRIVACY
Tech City: REDACTED FOR PRIVACY
Tech State/Province: REDACTED FOR PRIVACY
Tech Postal Code: REDACTED FOR PRIVACY
Tech Country: REDACTED FOR PRIVACY
Tech Phone: REDACTED FOR PRIVACY
Tech Phone Ext:
Tech Fax: REDACTED FOR PRIVACY
Tech Fax Ext:
Tech Email: a14de3e04ed1896bf94b85416974ccaa-18544863@contact.gandi.net
Name Server: NS-0-A.GANDI.NET
Name Server: NS-27-B.GANDI.NET
Name Server: NS-144-C.GANDI.NET
Name Server: 
Name Server: 
Name Server: 
Name Server: 
Name Server: 
Name Server: 
Name Server: 
DNSSEC: Unsigned
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/
>>> Last update of WHOIS database: 2021-04-15T18:34:06Z <<<

**Comment by austince** [comment]
The fact that @bluestreak01 seems to be actively hiding his association with this is absurd and abusive behavior.


CC
@mpsq @ideoma @patrickSpaceSurfer @jaugsburger @TheTanc @tris0laris @clickingbuttons @alexprut @bsmth 

Are the other contributors to this project aware of this?

**Comment by techtonik** [comment]
I guess the startup had failed, and now those are the desperate (and crude) attempts from development team to do own marketing, because they run out of money, and would have to abandon the project and join some corporate slavery as code workers.

**Comment by bluestreak01** [comment]
Hi all,
 Thanks for flagging your concerns. Just wanted to address a couple of points here and also apologise.
1. We blocked Techtonik not because of his initial issue but because of personal attacks that goes against our code of conduct. 
2. The domain .tech is ours.
3. Our intent is not to spam people, but rather to get feedback to improve our product. We have never sent more than 1 email. The email was found on your GitHub profile and we thought you'd be interested in a new project in this space.
4. Apologies for the tracking, which we should have been disabling instead.

**Comment by bluestreak01** [comment]
You can also reach out directly if you want to at vlad@questdb.io

**Comment by quantumpacket** [comment]
> 3. Our intent is not to spam people, but rather to get feedback to improve our product. We have never sent more than 1 email. The email was found on your GitHub profile and we thought you'd be interested in a new project in this space.

If you want feedback to improve your product, then why not survey existing users (such as the 3.1K stars)? I don't ever recall interacting with this repository, organization, or product before. If someone who has no established relation to me sends me such an email I consider it spam as it's unsolicited.

**Comment by bluestreak01** [comment]
Hi @quantumpacket, thanks for the feedback and apologies for having left this impression on you. We're taking this feedback seriously, and stopped sending emails to get product feedback last week. We will focus on our existing community instead

**Comment by austince** [comment]
Hey @bluestreak01, thank you for the full picture. I agree with your actions to moderate the conversation in the name of respect. 

On that note, I think your apology, while a good start, leaves some next steps open to how you can improve the situation, given where we are now.

Considering the responses (and issues that have been closed), I would suggest a pinned open issue answering the following topics/ questions:

* Transparency: this was the root issue in this situation
  * How did you get the emails? Was it purchased from a 3rd party or pulled independently by you?
  * Where is the tracked data stored?
* Project governance: this is important to people contributing to open source 
  * Who's decision was it to send these out?
  * On a larger note, how are decisions made in this project?

@quantumpacket, please let me know your thoughts here as well.
