### ISSUE TITLE
Feature Request: Storage Bucket Backup

### ISSUE THREAD

**Issue by Kampe** [questdb/questdb#908]
As a downstream consumer it'd be nice to be able to give QuestDB access to a cloud storage bucket and allow it to publish backups and restore itself if need be.

A configuration path (that can be used by helm etc) to be able to configure backups in Google Storage / S3 compatible object stores

Running postgressql with a kubertnetes operator and running our own spilo containers to facilitate timescaledb deployments.

**Comment by bsmth** [comment]
Thanks for raising this @Kampe, is there a reason why you closed the issue?

**Comment by Kampe** [comment]
I found the article where it's suggested that we use valero to facilitate this 😀

**Comment by DeanWronowski** [comment]
> I found the article where it's suggested that we use valero to facilitate this 😀

Do you a link to the article? If you don't mind sharing.

**Comment by Kampe** [comment]
here ya are! https://questdb.io/tutorial/2021/03/18/questdb-and-prometheus-on-gke-autopilot/#automated-velero-backups
