### ISSUE TITLE
Crud Operations

### ISSUE THREAD

**Issue by dhait** [questdb/questdb#912]
I see no documentation of CRUD operations anywhere in the docs or the website.
Was this feature removed?
How does one modify the value of an item already stored in the database?

**Comment by bluestreak01** [comment]
Hi David, we are not really geared for CRUD like conventional relational database. Current model is append only. We can emulate update while keeping database immutable. Here is some documentation on how to do this: https://questdb.io/docs/reference/sql/latest-by/

**Comment by dhait** [comment]
This would seem to imply that modifying an erroneous data value from a previous date (such as a price correction) is impossible if the date is a timestamp?

**Comment by bluestreak01** [comment]
For now yes. We are releasing something imminently that would enable data editing. Not right away, but does pave the way to

**Comment by bsmth** [comment]
Hi @dhait, I will close this now as your question appears to be answered. If there are further questions, feel free to reopen the ticket with further details.

Thanks for the contribution :)
