### ISSUE TITLE
JDBC return null result

### ISSUE THREAD

**Issue by WLLS253** [questdb/questdb#913]
**Describe the bug**
When I execute the following SQL using the JDBC driver, it returns `null`, the correct result is returned in the web console.

```sql
SELECT *
FROM readings
JOIN(
    SELECT ID sensId, make, city
    FROM sensors)
ON readings.sensorId = sensId;
```

In web console

![Screenshot from 2021-04-19 11-20-11](https://user-images.githubusercontent.com/52878813/115177950-d629c400-a102-11eb-8666-f78a27ded232.png)

In JDBC 
![Screenshot from 2021-04-19 11-19-09](https://user-images.githubusercontent.com/52878813/115177951-d629c400-a102-11eb-98b3-aa924d597f63.png)

The configuration of driver code:

```java
 Properties properties = new Properties();
        properties.setProperty("user", "admin");
        properties.setProperty("password", "quest");
        properties.setProperty("sslmode", "disable");
        String url = "jdbc:postgresql://localhost:" + port + "/qdb";
Class.forName("org.postgresql.Driver");
                connection = DriverManager.getConnection(url, properties);
```

Excecuting code

```java
  var tmpString = "SELECT *\n" +
                    "FROM readings\n" +
                    "JOIN(\n" +
                    "    SELECT ID sensId, make, city\n" +
                    "    FROM sensors)\n" +
                    "ON readings.sensorId = sensId;";
            for (var tmpSubStr: tmpString.split(";")) {
                try {
                    String querySQL = tmpSubStr + ";";
                    System.out.println(querySQL);
                    outputRs(driver.getResultSet(querySQL), System.out);
                }catch (SQLException e){
                    e.printStackTrace();
                }
            }
    public ResultSet getResultSet(String sql) throws SQLException {

        Statement statement = this.connection.createStatement();
        ResultSet resultSet = null;
        boolean hasResultSet = statement.execute(sql);
        if (hasResultSet) {
            resultSet = statement.getResultSet();
            if(resultSet == null) {
                System.out.println("resultSet is NULL");
            }
        }
        return resultSet;
    }

    public static  void outputRs(ResultSet resultSet, PrintStream out) throws SQLException {
        if(resultSet!=null) {
            ResultSetMetaData metaData = resultSet.getMetaData();
            int columnCount = metaData.getColumnCount();
            for(int i = 0; i < columnCount; i++ ){
                out.print(metaData.getColumnLabel(i+1)+" ");
            }
            out.println();
            while (resultSet.next()) {
                for (int i = 1; ; i++) {
                    out.print(resultSet.getString(i));
                    if (i < columnCount) {
                        out.print(", ");
                    } else {
                        out.println();
                        break;
                    }
                }
            }
        }
    }
```

**To Reproduce**
the log of databases
[stdout-2021-04-15T19-36-59.txt](https://github.com/questdb/questdb/files/6333076/stdout-2021-04-15T19-36-59.txt)

**Environment (please complete the following information):**
 - OS: [Linux,  ubuntu 20.04]
 - Browser: [chrome]
 - Version: [5.0.6.1]
-JDBC Postrges 42.2.12

**Comment by ideoma** [comment]
When I run your code on readers, sensors table listed in the QuestDB guide page I get "Java heap space" which is connected to #806 .
If I add LIMIT 1000 at the end of the select it works fine.

What is your java heap space? What is row count of the result set when you select it in Web Console? Does it work if you add LIMIT 1000 to the select?

**Comment by WLLS253** [comment]
Thanks for reply.  In Web Console , we see the count rows  is 79,991,656. When it return null result, there is no java heap space error, and I do not set the maxsize of java heap space .when I add LIMIT 1000,it return results ,and when it set LIMIT 10,000,000  it still result. But  when it set LIMIT 70,000,000, no result is returned and no exception is throwed.

**Comment by piotrrzysko** [comment]
I've prepared the test that probably reproduces the described bug: [link to the branch](https://github.com/piotrrzysko/questdb/commit/da69f464fc7a1066a5e60e2db0464c9b58a7a6cd) (it works the same in version `5.0.6.1` as well as in `6.0.0-SNAPSHOT`). 

It seems there is a problem when the client reads data too slowly:
1. When the number of unsuccessful attempts of sending data to the client is exhausted an exception is thrown [here](https://github.com/questdb/questdb/blob/4775f2f35d4101c35dde20bcc78aca435cbb1754/core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java#L1104).
2. The exception is handled [here](https://github.com/questdb/questdb/blob/4775f2f35d4101c35dde20bcc78aca435cbb1754/core/src/main/java/io/questdb/cutlass/pgwire/PGWireServer.java#L78) and finally, [this method](https://github.com/questdb/questdb/blob/4775f2f35d4101c35dde20bcc78aca435cbb1754/core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java#L318) is called.
3. If sending pending data finally succeeds in [this place](https://github.com/questdb/questdb/blob/4775f2f35d4101c35dde20bcc78aca435cbb1754/core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java#L322), we go [here](https://github.com/questdb/questdb/blob/4775f2f35d4101c35dde20bcc78aca435cbb1754/core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java#L1245) and notify the client that we are ready to process another query, even though the current one is not completed (we successfully sent data from the buffer, but not all produced by the query) - this is why the driver returns `null`.
4. The server gets stuck in an infinite loop logging `PGConnectionContext shift [offset=0, len=0]` (even after the client disconnects).

**Comment by bluestreak01** [comment]
Fixed in master
