### ISSUE TITLE
Stop the Mail spam

### ISSUE THREAD

**Issue by zekroTJA** [questdb/questdb#915]
As issues in #875 as well as in #906, I also received cold spam mails pointing to this project sent from the address `vlad.ilyushchenko@questdb.tech`. Are the team members of this project aware of this spam methods? And can you please stop this? Especially because this practice is [illegal in some countries like Germany](https://www.gesetze-im-internet.de/englisch_uwg/englisch_uwg.html#p0099), where I come from.

And by the way, really friendly and nice community management by blocking people who are actually pissed of by this crude and intruding spam.
![brave_nXeGhyxFzf](https://user-images.githubusercontent.com/16734205/115232071-9ec51280-a116-11eb-8be7-3fb104f5decb.png)

I think, depending on the reactions to this issue, I also will file a report to GitHub related to this issue.

**Comment by bluestreak01** [comment]
Hi, please see my reply in #875

**Comment by zekroTJA** [comment]
Is someone impersonating you? Can you confirm that no one of your team is responsible for sending these mails? And when yes, why would someone randomly send these mails to promote this project including a tracking link?

**Comment by bluestreak01** [comment]
I can confirm that nobody is impersonating me and the email was for getting feedback on our open source project. We’re sorry for the inconvenience. If you want, you can get in touch at vlad@questdb.io

**Comment by zekroTJA** [comment]
But I really don't understand why you say we shall reach out to the sender of the mail, which then is actually you (`vlad.ilyushchenko@questdb.tech`)? I really don't get it ad this seems really odd.

And I mean, this repos is not small at all. >3k Stars is a lot and I guess this repo will have also a heck lot of traffic and contributions when looking at the number of issues and PRs. Why getting more feedback.

But well, thank you for the response and yeah, maybe get some exposure by making some quality content like blog posts or YouTube videos instead of intruding people with random spam mails they did not sign up for.

**Comment by quantumpacket** [comment]
@zekroTJA I had already filed a complaint with GitHub on the 17th due to the sketchy responses or lack thereof in the other opened issues. I have yet to receive a response.

Whoever thought it was a good idea to just send emails to random people for feedback on a product they've never used needs to rethink their PR strategy. Hopefully lesson is learned from the backlash, and we can all move on now. Wish the project and their maintainers the best of luck!

**Comment by bluestreak01** [comment]
Hey @austince

Thanks for the feedback. I wanted to gather feedback on the project from individuals who had taken an interest in time-series data and whose emails are public on GitHub. There was zero intent on any sales/spam. Many people gave great feedback and did not mind a personal outreach - I now understand that this is not the case for everybody, hence based on your feedback I have decided to stop. Decisions made in the project are co-founder led, and we try to gather feedback from the community to inform the roadmap. We've taken steps do delete all tracking that had been stored previously. Would you be keen to share additional advice in private? 

Thanks 
Vlad

**Comment by austince** [comment]
Hi @bluestreak01, thanks for the notes, but no, I think making any of this conversation private is counter-productive. I think you are also missing the point – we are not upset about harmless personal outreach but by the way you went about it. Since you chose to go about it in the way that you did, I believe you must now do a bit more than hand-wave over the situation. 

Please answer the following questions:

    * **How did you get the email addresses? Were they purchased from a 3rd party or pulled independently by you?**
      * "from individuals who had taken an interest in time-series data and whose emails are public on GitHub" – please elaborate
    * **Where is the tracked data stored?**

**Comment by zekroTJA** [comment]
Okay, if this is the case that the addresses were hand-picked, then everything is fine for me, I guess.

The thing is, why I thought this is some kind of arbitrary spam male stuff, because of the tracking link hidden behind the repository URL *(I mean, come on, the repo URL was as is in the mail but it was actually just text with a tracking link behind it)* and also because of the opt-out link.

Don't mind me wrong there, the opt out link is a perfectly fine solution and its nice that you have integrated that, but in first glance this seems like these arbitrary news letter spam mails. I hope you get what I mean there. ^^

And please, as @austince said, be transparent about it and maybe don't respond with `please reach out to the sender` when you actually have the same name as the name in the mail address so that it seems like you are the actual sender of the mails.
