### ISSUE TITLE
How to prevent duplicate entries into database ? is out-of-order policy configurable ?

### ISSUE THREAD

**Issue by Mahaaveer** [questdb/questdb#952]
I am trying out questdb for storing financial data. 
Having designated timestamp allows replication of final two rows in the time series. 
How do i change the out-of-order policy to something that does not allow duplication of records while updating the existing database?

I have attached a picture of tail of the table where duplication can be seen when i try to update the existing database: https://imgur.com/a/K4WVl5B

Also, it would be nice if there are any detailed guides on pandas dataframe to questdb and db to dataframe.

Really appreciate the efforts put into development.

**Comment by bsmth** [comment]
Hi @Mahaaveer 👋🏻  thanks for opening the issue. At the moment there is no constraint on unique timestamps values (also designated), so a table may look like the following:

|ts|val|
|---|---|
|2021-04-29T15:59:20.861080Z|1
|2021-04-29T15:59:20.861080Z|2
|2021-04-29T15:59:20.861080Z|2
|2021-04-29T15:59:20.861080Z|1
|...|...

This might be desirable depending on the use case, but having this user-configurable makes total sense.
Did you have in mind that there's a constraint on unique per key/column or a general rule of having no unique rows over last x seconds or so?

**Comment by bsmth** [comment]
@Mahaaveer I'm going to close this one as it looks like the following issue has the same feature request: https://github.com/questdb/questdb/issues/622

I can add your comment in the other thread so we track this in a single issue

Thanks for your feedback! 👍🏻

**Comment by Mahaaveer** [comment]
Thanks for taking note. constraint unique on index/column. 
Dealing with financial data, one may accidentally end up duplicating existing values while updating  the database and may cause contamination in calculations if not diligent.
