### ISSUE TITLE
Sample by should (also) support calendar time range (vs only rolling time range).

### ISSUE THREAD

**Issue by snenkov** [questdb/questdb#953]
**Is your feature request related to a problem? Please describe.**
My problem is that I have a lot of data (10+ years) with millions of rows per day. This data is not practically digestible without being resampled.

When I do a query such as:
```
SELECT timestamp, last(value) from my_large_table
sample by 1d;
```
I expect it to behave the way `pandas` would behave - get the last value for this calendar day.
Instead (as described in your docs [here](https://questdb.io/docs/reference/sql/sample-by#sample-calculation)) it takes the last value of a rolling 24h window.
 

**Describe the solution you'd like**
I would like for there to be an easy way for me to specify that I want it to be based on calendar days and not 24 window (the same logic extends for hours, minutes, etc.).

**Describe alternatives you've considered**
Alternative 1 (inside QuestDB)
I have not tested this idea yet, but I guess a work-around would be to duplicate the timestamp and drop the minutes (if I want hourly or daily data to be aggregated) and to `samply by` or `group by` that. This is yet to be tested.

Alternative 2 (outside of QuestDB)
I can have a job running which reads - aggregates and saves to a new table. I think this is not really a solution, but it's possible.

**Additional context**
I'd consider this as a bug, but I labelled it as a "New feature" because it's noted in the docs, so it seems that this is the desired behaviour.

I am happy to help in whatever way to make this possible in questdb. It's a central feature for me at least in order to be able to make use of QuestDB properly.

P.S.
I don't know how QDB works inside, but possibly if a DB is partitioned by day, and the user looks for some the last value based on some symbol grouping, the partition may play a role in making the query much faster since the partition too is based on UTC calendar dates (vs the current SAMPLE by not being based on calendar dates, must execute the query slower). My thinking may be wrong here, but in case it's not, I wanted to share.

Related conversation: 
- https://questdb.slack.com/archives/C1NFJEER0/p1620254576297700

**Comment by snenkov** [comment]
@bluestreak01 Is it possible for this to go in the next update (questdb:6.0.0.b3)? : )

**Comment by bluestreak01** [comment]
yep, it is

**Comment by postol** [comment]
great, looking forward to this ... will help our use case too
