### ISSUE TITLE
difference between web console exec time and js sample code exec time

### ISSUE THREAD

**Issue by mohammad-rj** [questdb/questdb#959]
when i run `select * from telemetry` on web console 

it show popup log :
Execute:  453.69μs
Network: 182.55ms
Total: 183ms

then when i test with this js:
var microtime = require('microtime')
var t1 =microtime.now();

const fetch = require("node-fetch")
const qs = require("querystring")
const HOST = "http://localhost:9000"
async function run() {
    try {
        const queryData = {
            query: "SELECT * FROM telemetry;",
        }

        const response = await fetch(`${HOST}/exec?${qs.encode(queryData)}`)
        const json = await response.json()

        // console.log(json)
    } catch (error) {
        // console.log(error)
    }
}
run()

var t2 = microtime.now();
console.log("time exex: ", (t2-t1));

time exex:  35,214

its take 35 ms
is it the fastest way for test ?

**Comment by ideoma** [comment]
As you can see most of the time is spent on network - 182ms vs 0.43ms. Network time can vary between node js and browser and this where you get the difference - 35ms vs 182ms. 

Network time can also vary same request in the same browser even with localhost so perhaps if you keep trying the query in web console you'll see 35ms as well.

**Comment by mohammad-rj** [comment]
i run rhis js script on cli !
it on local and no time will be allocated to the network here

time load module:  24.700
time exec:  11.124

const fetch = require("node-fetch")
const qs = require("querystring")
load module take 24 ms
and exec action take 9 - 15 ms

**Comment by ideoma** [comment]
There is always network cost, even with localhost. The reason is that you have to copy data between 2 processes and it's never instant for big volumes.

Execution time you see in the console is the time between QuestDb receiving the request and sending back first byte of the response. You can only compare with time in the console inclusive of network.
