### ISSUE TITLE
Incorrect LEFT OUTER JOIN results

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#969]
**Describe the bug**
Left outer join returns records as if it's an inner join

**To Reproduce**

```SQL

create table l as
( select x from long_sequence(100) )

create table rr as
( select x + 50 as y from long_sequence(100) )

select x, y
from l left join rr on l.x = rr.y
where y > 0 or y > 10

```

**Expected behavior**
Result is 50 rows while 100 rows expected - all rows from table l and 50-100 rows from table rr.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: [e.g. chrome, safari]
 - Version: master as of 2021-05-05, 0b2bcb385215a95fc74d6825a5251eb1f27133e2

**Comment by bluestreak01** [comment]
when I execute the SQL you provided omitting `where` clause

```sql
select x, y
from l left join rr on l.x = rr.y
```
then first 50 rows look like:

![image](https://user-images.githubusercontent.com/7276403/118295898-480fe600-b4d4-11eb-87cd-5b57dbf0a907.png)

when you apply `y > 0 or y > 10` to first 50 rows the predicate would be `false`, as in `null > 0` is `false`. For that reason only last 50 rows are returned.

I feel SQL execution is correct.

**Comment by ideoma** [comment]
This returns 100 rows

```SQL
select x, y
from l left join rr on l.x = rr.y
where y > 0 ;
```

and this only 50

```SQL
select x, y
from l left join rr on l.x = rr.y
where y > 0 or y > 10
```

You're right, they both should return 50 rows
