### ISSUE TITLE
NULL should be variant type instead of always assuming STRING

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#973]
**Describe the bug**
When you try to insert NULL into table with DOUBLE field error is
inconvertible types: STRING -> DOUBLE [from=NULL, to=testfield]

**Expected behavior**
NULL literal should be automatically converted to the data type in insert, select queries

**Environment (please complete the following information):**
 - Version: 6.0.2

**Comment by bluestreak01** [comment]
This also extends to using `NULL` as constant in `where` clause with `double` and `float` types. For example this works:

```sql
select * from tab where double = NaN
```

but this does not work:

```sql
select * from tab where double = NULL
```

**Comment by marregui** [comment]
I am still working on it, I am aware of some broken tests.
Would the general approach be on the right path?

Thank you in advance.
