### ISSUE TITLE
Support for `timestamp with time zone` type for PG framework compatibility

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb#980]
**Describe the solution you'd like**
I would like the following SQL to be supported:

```sql
cast('2021-04-28 11:58:37.619715+01:00' as timestamp with time zone)
```

**Additional context**
This occurs with queries generated by [JooQ](https://www.jooq.org/)

**Relates to**
https://github.com/questdb/questdb/issues/819#issuecomment-833439590

**Comment by bsmth** [comment]
Looks like a duplicate of https://github.com/questdb/questdb/issues/740

**Comment by bluestreak01** [comment]
duplicate of #740
